/**
 * Module 5 — Advanced Mechanics.
 * Projectile motion, circular motion, work/energy/power, forces in two dimensions, torque,
 * gravitation and orbital motion.
 */
import { acos, asin, DEG, GVar, gVar, sq } from './common';
import { FormulaDef, v } from './types';

const PI = Math.PI;

/** smallest non-negative root of ½a t² + u t − s = 0 */
function timeFromSUA(s: number, u: number, a: number): number {
  if (Math.abs(a) < 1e-15) return u === 0 ? NaN : s / u;
  const disc = u * u + 2 * a * s;
  if (disc < 0) return NaN;
  const r1 = (-u + Math.sqrt(disc)) / a;
  const r2 = (-u - Math.sqrt(disc)) / a;
  const pos = [r1, r2].filter((t) => t > 1e-12).sort((x, y) => x - y);
  return pos.length ? pos[0] : NaN;
}

export const m5Formulas: FormulaDef[] = [
  // ───────────── Kinematics (constant acceleration) ─────────────
  {
    id: 'suvat_v',
    name: 'Velocity–time (constant acceleration)',
    module: 'm5',
    topic: 'projectile',
    equation: 'v = u + at',
    vars: [
      v('v', 'v', 'Final velocity', 'velocity', { signed: true }),
      v('u', 'u', 'Initial velocity', 'velocity', { signed: true }),
      v('a', 'a', 'Acceleration', 'acceleration', { signed: true }),
      v('t', 't', 'Time', 'time', { nonNegative: true }),
    ],
    solve: {
      v: { expr: '#u + #a #t', fn: ({ u, a, t }) => u + a * t },
      u: { expr: '#v - #a #t', fn: ({ v, a, t }) => v - a * t },
      a: { expr: '\\frac{#v - #u}{#t}', fn: ({ v, u, t }) => (v - u) / t },
      t: { expr: '\\frac{#v - #u}{#a}', fn: ({ v, u, a }) => (v - u) / a },
    },
    aliases: ['suvat', 'kinematics', 'equations of motion', 'final velocity', 'v=u+at'],
    when: 'Motion in a straight line with constant acceleration (apply separately to each component of projectile motion).',
    whenNot: 'Not for non-uniform acceleration (e.g. circular motion speed is constant but acceleration direction changes).',
    assumptions: ['Acceleration is constant', 'Choose a positive direction and keep signs consistent'],
    related: ['suvat_s', 'suvat_v2', 'proj_vy'],
    sheet: 'sheet',
    hsc: ['Vertical velocity of a projectile at time t', 'Time for a charged particle to reach a speed in a uniform field'],
    example: { u: 5, a: 9.8, t: 2 },
    priority: 3,
  },
  {
    id: 'suvat_s',
    name: 'Displacement–time (constant acceleration)',
    module: 'm5',
    topic: 'projectile',
    equation: 's = ut + \\tfrac{1}{2}at^2',
    vars: [
      v('s', 's', 'Displacement', 'length', { signed: true }),
      v('u', 'u', 'Initial velocity', 'velocity', { signed: true }),
      v('t', 't', 'Time', 'time', { nonNegative: true }),
      v('a', 'a', 'Acceleration', 'acceleration', { signed: true }),
    ],
    solve: {
      s: { expr: '#u #t + \\tfrac{1}{2} #a #t^2', fn: ({ u, t, a }) => u * t + 0.5 * a * t * t },
      u: { expr: '\\frac{#s - \\tfrac{1}{2} #a #t^2}{#t}', fn: ({ s, a, t }) => (s - 0.5 * a * t * t) / t },
      a: { expr: '\\frac{2(#s - #u #t)}{#t^2}', fn: ({ s, u, t }) => (2 * (s - u * t)) / (t * t) },
      t: { expr: '\\frac{-#u + \\sqrt{#u^2 + 2 #a #s}}{#a}', fn: ({ s, u, a }) => timeFromSUA(s, u, a), note: 'quadratic in t — the smallest positive root is taken' },
    },
    aliases: ['displacement', 's=ut+1/2at^2', 'suvat', 'time of fall', 'distance fallen'],
    when: 'Displacement after time t with constant acceleration; vertical motion of a projectile (a = −g with up positive).',
    whenNot: 'Do not use with a varying acceleration.',
    assumptions: ['Acceleration is constant'],
    related: ['suvat_v', 'suvat_v2', 'proj_sy'],
    sheet: 'sheet',
    hsc: ['Height fallen by a horizontally launched projectile', 'Deflection of a charged particle between parallel plates'],
    example: { u: 0, t: 3, a: 9.8 },
    priority: 3,
  },
  {
    id: 'suvat_v2',
    name: 'Velocity–displacement (constant acceleration)',
    module: 'm5',
    topic: 'projectile',
    equation: 'v^2 = u^2 + 2as',
    vars: [
      v('v', 'v', 'Final velocity (magnitude)', 'velocity', { nonNegative: true }),
      v('u', 'u', 'Initial velocity', 'velocity', { signed: true }),
      v('a', 'a', 'Acceleration', 'acceleration', { signed: true }),
      v('s', 's', 'Displacement', 'length', { signed: true }),
    ],
    solve: {
      v: { expr: '\\sqrt{#u^2 + 2 #a #s}', fn: ({ u, a, s }) => Math.sqrt(u * u + 2 * a * s), note: 'the square root gives the speed; the sign (direction) comes from the context' },
      u: { expr: '\\sqrt{#v^2 - 2 #a #s}', fn: ({ v, a, s }) => Math.sqrt(v * v - 2 * a * s), note: 'magnitude of the initial velocity' },
      a: { expr: '\\frac{#v^2 - #u^2}{2 #s}', fn: ({ v, u, s }) => (v * v - u * u) / (2 * s) },
      s: { expr: '\\frac{#v^2 - #u^2}{2 #a}', fn: ({ v, u, a }) => (v * v - u * u) / (2 * a) },
    },
    aliases: ['v^2=u^2+2as', 'suvat', 'maximum height', 'stopping distance'],
    when: 'Constant-acceleration motion when time is not given or not required.',
    assumptions: ['Acceleration is constant'],
    related: ['suvat_v', 'suvat_s', 'proj_vy2'],
    sheet: 'sheet',
    hsc: ['Maximum height of a vertically launched object', 'Speed gained by a particle accelerated over a distance'],
    example: { u: 0, a: 9.8, s: 20 },
    priority: 3,
  },
  {
    id: 'const_velocity',
    name: 'Uniform (constant) velocity',
    module: 'm5',
    topic: 'projectile',
    alsoIn: ['relativity'],
    equation: 's = vt',
    vars: [
      v('s', 's', 'Distance / displacement', 'length', { nonNegative: true }),
      v('v', 'v', 'Speed', 'velocity', { positive: true }),
      v('t', 't', 'Time', 'time', { positive: true }),
    ],
    solve: {
      s: { expr: '#v #t', fn: ({ v, t }) => v * t },
      v: { expr: '\\frac{#s}{#t}', fn: ({ s, t }) => s / t },
      t: { expr: '\\frac{#s}{#v}', fn: ({ s, v }) => s / v },
    },
    aliases: ['constant speed', 'distance = speed × time', 'muon distance'],
    when: 'Motion with zero acceleration: horizontal projectile motion, distance travelled by a particle (e.g. a muon) in a given frame.',
    whenNot: 'Not when the object accelerates.',
    sheet: 'y11',
    hsc: ['Distance a muon travels in the Earth frame', 'Time for light to travel a distance'],
    example: { v: 20, t: 3 },
    priority: 1,
    chainCost: 1.2,
  },
  // ───────────── Projectile components ─────────────
  {
    id: 'proj_ux',
    name: 'Horizontal component of launch velocity',
    module: 'm5',
    topic: 'projectile',
    equation: 'u_x = u\\cos\\theta',
    vars: [
      v('ux', 'u_x', 'Horizontal component of initial velocity', 'velocity', { signed: true }),
      v('u', 'u', 'Launch speed', 'velocity', { positive: true }),
      v('th', '\\theta', 'Launch angle (above horizontal)', 'angle', { concept: 'thetaL', min: -PI / 2, max: PI / 2 }),
    ],
    solve: {
      ux: { expr: '#u \\cos #th', fn: ({ u, th }) => u * Math.cos(th) },
      u: { expr: '\\frac{#ux}{\\cos #th}', fn: ({ ux, th }) => ux / Math.cos(th) },
      th: { expr: '\\cos^{-1}\\left(\\frac{#ux}{#u}\\right)', fn: ({ ux, u }) => acos(ux / u) },
    },
    aliases: ['resolve velocity', 'horizontal component', 'ux', 'components'],
    when: 'Resolving a launch velocity into its horizontal component (horizontal velocity stays constant, aₓ = 0).',
    related: ['proj_uy', 'proj_sx'],
    sheet: 'derived',
    hsc: ['Resolving the initial velocity of a ball kicked at an angle'],
    example: { u: 20, th: 30 * DEG },
    priority: 4,
  },
  {
    id: 'proj_uy',
    name: 'Vertical component of launch velocity',
    module: 'm5',
    topic: 'projectile',
    equation: 'u_y = u\\sin\\theta',
    vars: [
      v('uy', 'u_y', 'Vertical component of initial velocity', 'velocity', { signed: true }),
      v('u', 'u', 'Launch speed', 'velocity', { positive: true }),
      v('th', '\\theta', 'Launch angle (above horizontal)', 'angle', { concept: 'thetaL', min: -PI / 2, max: PI / 2 }),
    ],
    solve: {
      uy: { expr: '#u \\sin #th', fn: ({ u, th }) => u * Math.sin(th) },
      u: { expr: '\\frac{#uy}{\\sin #th}', fn: ({ uy, th }) => uy / Math.sin(th) },
      th: { expr: '\\sin^{-1}\\left(\\frac{#uy}{#u}\\right)', fn: ({ uy, u }) => asin(uy / u) },
    },
    aliases: ['resolve velocity', 'vertical component', 'uy', 'components'],
    when: 'Resolving a launch velocity into its vertical component (vertical acceleration = −g, up positive).',
    related: ['proj_ux', 'proj_vy'],
    sheet: 'derived',
    hsc: ['Resolving the initial velocity of a projectile'],
    example: { u: 20, th: 30 * DEG },
    priority: 4,
  },
  {
    id: 'proj_sx',
    name: 'Horizontal displacement of a projectile',
    module: 'm5',
    topic: 'projectile',
    equation: 's_x = u_x t',
    vars: [
      v('sx', 's_x', 'Horizontal displacement (range)', 'length', { concept: 'sx', signed: true }),
      v('ux', 'u_x', 'Horizontal velocity', 'velocity', { signed: true }),
      v('t', 't', 'Time of flight', 'time', { nonNegative: true }),
    ],
    solve: {
      sx: { expr: '#ux #t', fn: ({ ux, t }) => ux * t },
      ux: { expr: '\\frac{#sx}{#t}', fn: ({ sx, t }) => sx / t },
      t: { expr: '\\frac{#sx}{#ux}', fn: ({ sx, ux }) => sx / ux },
    },
    aliases: ['range', 'horizontal distance', 'horizontal displacement', 'x = uxt'],
    when: 'Horizontal motion of a projectile: no horizontal force (air resistance ignored), so aₓ = 0 and uₓ is constant.',
    whenNot: 'Not if air resistance is significant.',
    related: ['proj_ux', 'proj_sy'],
    sheet: 'sheet',
    hsc: ['Range of a ball kicked horizontally off a cliff', 'How far a package dropped from a plane travels horizontally'],
    example: { ux: 15, t: 2.5 },
    priority: 4,
  },
  {
    id: 'proj_vx',
    name: 'Horizontal velocity is constant',
    module: 'm5',
    topic: 'projectile',
    equation: 'v_x = u_x',
    vars: [v('vx', 'v_x', 'Horizontal velocity at any time', 'velocity', { signed: true }), v('ux', 'u_x', 'Initial horizontal velocity', 'velocity', { signed: true })],
    solve: { vx: { expr: '#ux', fn: ({ ux }) => ux }, ux: { expr: '#vx', fn: ({ vx }) => vx } },
    aliases: ['horizontal velocity', 'vx'],
    when: 'In projectile motion aₓ = 0, so the horizontal velocity never changes.',
    sheet: 'sheet',
    hsc: ['Velocity of a projectile at impact'],
    example: { ux: 12 },
    priority: 2,
    chainCost: 0.6,
  },
  {
    id: 'proj_vy',
    name: 'Vertical velocity of a projectile',
    module: 'm5',
    topic: 'projectile',
    equation: 'v_y = u_y + a_y t \\quad (a_y = -g)',
    vars: [
      v('vy', 'v_y', 'Vertical velocity (up positive)', 'velocity', { signed: true }),
      v('uy', 'u_y', 'Initial vertical velocity (up positive)', 'velocity', { signed: true }),
      gVar(),
      v('t', 't', 'Time', 'time', { nonNegative: true }),
    ],
    solve: {
      vy: { expr: '#uy - #g #t', fn: ({ uy, g, t }) => uy - g * t },
      uy: { expr: '#vy + #g #t', fn: ({ vy, g, t }) => vy + g * t },
      g: { expr: '\\frac{#uy - #vy}{#t}', fn: ({ uy, vy, t }) => (uy - vy) / t },
      t: { expr: '\\frac{#uy - #vy}{#g}', fn: ({ uy, vy, g }) => (uy - vy) / g },
    },
    aliases: ['vertical velocity', 'vy', 'time to maximum height'],
    when: 'Vertical motion of a projectile, taking up as positive so a_y = −g. At maximum height v_y = 0.',
    related: ['proj_sy', 'proj_vy2'],
    sheet: 'sheet',
    hsc: ['Time to reach maximum height (v_y = 0)', 'Vertical velocity at impact'],
    example: { uy: 10, t: 1.5 },
    priority: 4,
  },
  {
    id: 'proj_sy',
    name: 'Vertical displacement of a projectile',
    module: 'm5',
    topic: 'projectile',
    equation: 's_y = u_y t + \\tfrac{1}{2}a_y t^2 \\quad (a_y = -g)',
    vars: [
      v('sy', 's_y', 'Vertical displacement (up positive)', 'length', { signed: true }),
      v('uy', 'u_y', 'Initial vertical velocity (up positive)', 'velocity', { signed: true }),
      v('t', 't', 'Time', 'time', { nonNegative: true }),
      gVar(),
    ],
    solve: {
      sy: { expr: '#uy #t - \\tfrac{1}{2} #g #t^2', fn: ({ uy, t, g }) => uy * t - 0.5 * g * t * t },
      uy: { expr: '\\frac{#sy + \\tfrac{1}{2} #g #t^2}{#t}', fn: ({ sy, g, t }) => (sy + 0.5 * g * t * t) / t },
      t: { expr: '\\frac{#uy + \\sqrt{#uy^2 - 2 #g #sy}}{#g}', fn: ({ sy, uy, g }) => timeFromSUA(sy, uy, -g), note: 'quadratic in t — if the point is above the launch height it is passed twice (up and down); the earlier time is given' },
      g: { expr: '\\frac{2(#uy #t - #sy)}{#t^2}', fn: ({ sy, uy, t }) => (2 * (uy * t - sy)) / (t * t) },
    },
    aliases: ['vertical displacement', 'height', 'drop', 'sy'],
    when: 'Vertical position of a projectile. A landing point below the launch point has s_y negative (up positive).',
    related: ['proj_vy', 'proj_sx'],
    sheet: 'sheet',
    hsc: ['Time for a projectile launched from a cliff to reach the ground', 'Height of a projectile after t seconds'],
    example: { uy: 10, t: 2.5 },
    priority: 4,
  },
  {
    id: 'proj_vy2',
    name: 'Vertical velocity–displacement',
    module: 'm5',
    topic: 'projectile',
    equation: 'v_y^2 = u_y^2 + 2a_y s_y \\quad (a_y = -g)',
    vars: [
      v('vy', 'v_y', 'Vertical speed', 'velocity', { nonNegative: true }),
      v('uy', 'u_y', 'Initial vertical velocity (up positive)', 'velocity', { signed: true }),
      gVar(),
      v('sy', 's_y', 'Vertical displacement (up positive)', 'length', { signed: true }),
    ],
    solve: {
      vy: { expr: '\\sqrt{#uy^2 - 2 #g #sy}', fn: ({ uy, g, sy }) => Math.sqrt(uy * uy - 2 * g * sy), note: 'magnitude — downward if the projectile is falling' },
      uy: { expr: '\\sqrt{#vy^2 + 2 #g #sy}', fn: ({ vy, g, sy }) => Math.sqrt(vy * vy + 2 * g * sy) },
      sy: { expr: '\\frac{#uy^2 - #vy^2}{2 #g}', fn: ({ uy, vy, g }) => (uy * uy - vy * vy) / (2 * g) },
      g: { expr: '\\frac{#uy^2 - #vy^2}{2 #sy}', fn: ({ uy, vy, sy }) => (uy * uy - vy * vy) / (2 * sy) },
    },
    aliases: ['maximum height', 'vertical speed at impact', 'vy^2'],
    when: 'Vertical motion when time is not needed, e.g. maximum height (v_y = 0 at the top).',
    related: ['proj_hmax'],
    sheet: 'sheet',
    hsc: ['Maximum height of a projectile', 'Vertical speed on hitting the ground'],
    example: { uy: 12, sy: -20 },
    priority: 3,
  },
  {
    id: 'vec_resultant_v',
    name: 'Resultant velocity from components',
    module: 'm5',
    topic: 'projectile',
    equation: 'v = \\sqrt{v_x^2 + v_y^2}',
    vars: [
      v('v', 'v', 'Speed (magnitude of velocity)', 'velocity', { nonNegative: true }),
      v('vx', 'v_x', 'Horizontal velocity', 'velocity', { signed: true }),
      v('vy', 'v_y', 'Vertical velocity', 'velocity', { signed: true }),
    ],
    solve: {
      v: { expr: '\\sqrt{#vx^2 + #vy^2}', fn: ({ vx, vy }) => Math.hypot(vx, vy) },
      vx: { expr: '\\sqrt{#v^2 - #vy^2}', fn: ({ v, vy }) => Math.sqrt(v * v - vy * vy) },
      vy: { expr: '\\sqrt{#v^2 - #vx^2}', fn: ({ v, vx }) => Math.sqrt(v * v - vx * vx), note: 'magnitude — decide up/down from the context' },
    },
    aliases: ['resultant velocity', 'impact velocity', 'final velocity of projectile', 'pythagoras'],
    when: 'Combining perpendicular velocity components into a speed (e.g. impact velocity of a projectile).',
    related: ['vec_dir_v'],
    sheet: 'derived',
    hsc: ['Velocity of a projectile on hitting the ground'],
    example: { vx: 15, vy: 20 },
    priority: 3,
  },
  {
    id: 'vec_dir_v',
    name: 'Direction of velocity',
    module: 'm5',
    topic: 'projectile',
    equation: '\\theta = \\tan^{-1}\\left(\\frac{v_y}{v_x}\\right)',
    vars: [
      v('th', '\\theta', 'Angle of velocity to the horizontal', 'angle', { concept: 'thetaV', min: -PI / 2, max: PI / 2 }),
      v('vy', 'v_y', 'Vertical velocity', 'velocity', { signed: true }),
      v('vx', 'v_x', 'Horizontal velocity', 'velocity', { positive: true }),
    ],
    solve: {
      th: { expr: '\\tan^{-1}\\left(\\frac{#vy}{#vx}\\right)', fn: ({ vy, vx }) => Math.atan(vy / vx), note: 'negative angle = below the horizontal' },
      vy: { expr: '#vx \\tan #th', fn: ({ vx, th }) => vx * Math.tan(th) },
      vx: { expr: '\\frac{#vy}{\\tan #th}', fn: ({ vy, th }) => vy / Math.tan(th) },
    },
    aliases: ['direction', 'angle of impact', 'angle below horizontal'],
    when: 'Direction of a velocity (or any vector) from its horizontal and vertical components.',
    sheet: 'derived',
    hsc: ['Angle at which a projectile hits the ground'],
    example: { vy: -20, vx: 15 },
    priority: 2,
  },
  {
    id: 'proj_tflight',
    name: 'Time of flight (level ground)',
    module: 'm5',
    topic: 'projectile',
    equation: 't = \\frac{2u\\sin\\theta}{g}',
    vars: [
      v('t', 't', 'Time of flight', 'time', { concept: 'tFlight', positive: true }),
      v('u', 'u', 'Launch speed', 'velocity', { positive: true }),
      v('th', '\\theta', 'Launch angle', 'angle', { concept: 'thetaL', min: 0, max: PI / 2 }),
      gVar(),
    ],
    solve: {
      t: { expr: '\\frac{2 #u \\sin #th}{#g}', fn: ({ u, th, g }) => (2 * u * Math.sin(th)) / g },
      u: { expr: '\\frac{#g #t}{2 \\sin #th}', fn: ({ t, th, g }) => (g * t) / (2 * Math.sin(th)) },
      th: { expr: '\\sin^{-1}\\left(\\frac{#g #t}{2 #u}\\right)', fn: ({ t, u, g }) => asin((g * t) / (2 * u)) },
      g: { expr: '\\frac{2 #u \\sin #th}{#t}', fn: ({ t, u, th }) => (2 * u * Math.sin(th)) / t },
    },
    aliases: ['time of flight', 'flight time', 'how long in the air'],
    when: 'Projectile launched and landing at the same height (s_y = 0).',
    whenNot: 'Not when launch and landing heights differ — use s_y = u_y t − ½gt² instead.',
    derivation: ['s_y = u_y t - \\tfrac{1}{2}gt^2 = 0', '\\Rightarrow t = \\frac{2u_y}{g} = \\frac{2u\\sin\\theta}{g}'],
    sheet: 'derived',
    hsc: ['Time a golf ball is in the air on level ground'],
    example: { u: 25, th: 40 * DEG },
    priority: 2,
    chainCost: 1.1,
    unlessKnown: ['sy'],
  },
  {
    id: 'proj_range',
    name: 'Range (level ground)',
    module: 'm5',
    topic: 'projectile',
    equation: 'R = \\frac{u^2\\sin 2\\theta}{g}',
    vars: [
      v('R', 'R', 'Horizontal range', 'length', { concept: 'sx', positive: true }),
      v('u', 'u', 'Launch speed', 'velocity', { positive: true }),
      v('th', '\\theta', 'Launch angle', 'angle', { concept: 'thetaL', min: 0, max: PI / 2 }),
      gVar(),
    ],
    solve: {
      R: { expr: '\\frac{#u^2 \\sin(2 #th)}{#g}', fn: ({ u, th, g }) => (u * u * Math.sin(2 * th)) / g },
      u: { expr: '\\sqrt{\\frac{#g #R}{\\sin(2 #th)}}', fn: ({ R, th, g }) => Math.sqrt((g * R) / Math.sin(2 * th)) },
      th: { expr: '\\tfrac{1}{2}\\sin^{-1}\\left(\\frac{#g #R}{#u^2}\\right)', fn: ({ R, u, g }) => 0.5 * asin((g * R) / (u * u)), note: 'the complementary angle (90° − θ) gives the same range' },
      g: { expr: '\\frac{#u^2 \\sin(2 #th)}{#R}', fn: ({ R, u, th }) => (u * u * Math.sin(2 * th)) / R },
    },
    aliases: ['range', 'maximum range', 'horizontal range', 'range equation'],
    when: 'Projectile landing at its launch height, no air resistance. Maximum range at θ = 45°.',
    whenNot: 'Not for launch from a cliff/height.',
    derivation: ['R = u_x t = u\\cos\\theta \\cdot \\frac{2u\\sin\\theta}{g} = \\frac{u^2 \\sin 2\\theta}{g}'],
    sheet: 'derived',
    hsc: ['Range of a projectile on level ground', 'Launch speed for a given range'],
    example: { u: 25, th: 40 * DEG },
    priority: 2,
    chainCost: 1.1,
    unlessKnown: ['sy'],
  },
  {
    id: 'proj_hmax',
    name: 'Maximum height of a projectile',
    module: 'm5',
    topic: 'projectile',
    equation: 'H = \\frac{u^2\\sin^2\\theta}{2g}',
    vars: [
      v('H', 'H', 'Maximum height above launch point', 'length', { concept: 'H', nonNegative: true }),
      v('u', 'u', 'Launch speed', 'velocity', { positive: true }),
      v('th', '\\theta', 'Launch angle', 'angle', { concept: 'thetaL', min: 0, max: PI / 2 }),
      gVar(),
    ],
    solve: {
      H: { expr: '\\frac{#u^2 \\sin^2 #th}{2 #g}', fn: ({ u, th, g }) => sq(u * Math.sin(th)) / (2 * g) },
      u: { expr: '\\frac{\\sqrt{2 #g #H}}{\\sin #th}', fn: ({ H, th, g }) => Math.sqrt(2 * g * H) / Math.sin(th) },
      th: { expr: '\\sin^{-1}\\left(\\frac{\\sqrt{2 #g #H}}{#u}\\right)', fn: ({ H, u, g }) => asin(Math.sqrt(2 * g * H) / u) },
      g: { expr: '\\frac{#u^2 \\sin^2 #th}{2 #H}', fn: ({ H, u, th }) => sq(u * Math.sin(th)) / (2 * H) },
    },
    aliases: ['maximum height', 'max height', 'peak height', 'highest point'],
    when: 'Highest point of a projectile, where v_y = 0.',
    derivation: ['0 = u_y^2 - 2gH \\Rightarrow H = \\frac{u_y^2}{2g}'],
    sheet: 'derived',
    hsc: ['Maximum height reached by a ball'],
    example: { u: 25, th: 40 * DEG },
    priority: 2,
    chainCost: 1.1,
  },
  {
    id: 'proj_tpeak',
    name: 'Time to maximum height',
    module: 'm5',
    topic: 'projectile',
    equation: 't_{peak} = \\frac{u\\sin\\theta}{g}',
    vars: [
      v('tp', 't_{peak}', 'Time to maximum height', 'time', { concept: 'tPeak', nonNegative: true }),
      v('u', 'u', 'Launch speed', 'velocity', { positive: true }),
      v('th', '\\theta', 'Launch angle', 'angle', { concept: 'thetaL', min: 0, max: PI / 2 }),
      gVar(),
    ],
    solve: {
      tp: { expr: '\\frac{#u \\sin #th}{#g}', fn: ({ u, th, g }) => (u * Math.sin(th)) / g },
      u: { expr: '\\frac{#g #tp}{\\sin #th}', fn: ({ tp, th, g }) => (g * tp) / Math.sin(th) },
      th: { expr: '\\sin^{-1}\\left(\\frac{#g #tp}{#u}\\right)', fn: ({ tp, u, g }) => asin((g * tp) / u) },
      g: { expr: '\\frac{#u \\sin #th}{#tp}', fn: ({ tp, u, th }) => (u * Math.sin(th)) / tp },
    },
    aliases: ['time to top', 'time to reach maximum height', 'time to peak'],
    when: 'Time for the vertical velocity to fall to zero (v_y = u_y − gt = 0).',
    sheet: 'derived',
    hsc: ['Time taken to reach the highest point'],
    example: { u: 25, th: 40 * DEG },
    priority: 1,
    chainCost: 1.1,
  },
  {
    id: 'proj_fall_time',
    name: 'Time to fall from a height (horizontal launch)',
    module: 'm5',
    topic: 'projectile',
    equation: 't = \\sqrt{\\frac{2h}{g}}',
    vars: [
      v('t', 't', 'Time of fall', 'time', { concept: 'tFlight', positive: true }),
      v('h', 'h', 'Height fallen', 'length', { concept: 'hDrop', positive: true }),
      gVar(),
    ],
    solve: {
      t: { expr: '\\sqrt{\\frac{2 #h}{#g}}', fn: ({ h, g }) => Math.sqrt((2 * h) / g) },
      h: { expr: '\\tfrac{1}{2} #g #t^2', fn: ({ t, g }) => 0.5 * g * t * t },
      g: { expr: '\\frac{2 #h}{#t^2}', fn: ({ h, t }) => (2 * h) / (t * t) },
    },
    aliases: ['horizontally launched', 'rolls off a table', 'off a cliff', 'dropped', 'fall time'],
    when: 'An object launched horizontally (u_y = 0) or dropped from rest falls a height h.',
    whenNot: 'Not if the launch has a vertical component.',
    derivation: ['s_y = u_y t - \\tfrac{1}{2}gt^2, \\; u_y = 0,\\; s_y = -h', '\\Rightarrow t = \\sqrt{2h/g}'],
    sheet: 'derived',
    hsc: ['Ball rolling off a table', 'Stone thrown horizontally from a cliff'],
    example: { h: 20 },
    priority: 2,
    chainCost: 1,
  },
  // ───────────── Newton's laws, energy, power ─────────────
  {
    id: 'newton2',
    name: "Newton's second law",
    module: 'm5',
    topic: 'forces',
    alsoIn: ['particles'],
    equation: '\\Sigma F = ma',
    vars: [v('F', 'F', 'Net force', 'force', { signed: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), v('a', 'a', 'Acceleration', 'acceleration', { signed: true })],
    solve: {
      F: { expr: '#m #a', fn: ({ m, a }) => m * a },
      m: { expr: '\\frac{#F}{#a}', fn: ({ F, a }) => F / a },
      a: { expr: '\\frac{#F}{#m}', fn: ({ F, m }) => F / m },
    },
    aliases: ['newton', 'F=ma', 'net force', 'acceleration from force', 'resultant force'],
    when: 'Linking the net (resultant) force on an object to its acceleration — e.g. a = F/m for a charged particle in a field.',
    whenNot: 'F must be the NET force, not just one of several forces.',
    related: ['circ_Fc', 'efield_force', 'mag_force_q'],
    sheet: 'sheet',
    hsc: ['Acceleration of a proton in a magnetic field (a = qvB/m)', 'Acceleration of an electron between charged plates'],
    example: { m: 2, a: 3 },
    priority: 5,
  },
  {
    id: 'weight',
    name: 'Weight force',
    module: 'm5',
    topic: 'gravitation',
    alsoIn: ['forces'],
    equation: 'F_g = mg',
    vars: [v('W', 'F_g', 'Weight (gravitational force)', 'force', { concept: 'Wt', nonNegative: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), gVar()],
    solve: {
      W: { expr: '#m #g', fn: ({ m, g }) => m * g },
      m: { expr: '\\frac{#W}{#g}', fn: ({ W, g }) => W / g },
      g: { expr: '\\frac{#W}{#m}', fn: ({ W, m }) => W / m },
    },
    aliases: ['weight', 'mg', 'gravitational force near surface'],
    when: 'Weight of a mass in a gravitational field of strength g (g = 9.8 N kg⁻¹ at Earth’s surface).',
    sheet: 'derived',
    hsc: ['Weight of an astronaut on another planet', 'Millikan oil drop: weight balanced by electric force'],
    example: { m: 70 },
    priority: 4,
  },
  {
    id: 'kinetic',
    name: 'Kinetic energy',
    module: 'm5',
    topic: 'forces',
    alsoIn: ['particles'],
    equation: 'K = \\tfrac{1}{2}mv^2',
    vars: [v('K', 'K', 'Kinetic energy', 'energy', { nonNegative: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), v('v', 'v', 'Speed', 'velocity', { nonNegative: true })],
    solve: {
      K: { expr: '\\tfrac{1}{2} #m #v^2', fn: ({ m, v }) => 0.5 * m * v * v },
      m: { expr: '\\frac{2 #K}{#v^2}', fn: ({ K, v }) => (2 * K) / (v * v) },
      v: { expr: '\\sqrt{\\frac{2 #K}{#m}}', fn: ({ K, m }) => Math.sqrt((2 * K) / m) },
    },
    aliases: ['kinetic energy', 'KE', 'Ek', '1/2mv^2'],
    when: 'Energy of motion (non-relativistic, v ≪ c).',
    whenNot: 'Not valid near the speed of light.',
    checks: ({ v }) => (v > 0.1 * 3e8 ? [{ level: 'warning', message: 'v > 0.1c — the classical ½mv² is inaccurate at relativistic speeds.' }] : []),
    sheet: 'sheet',
    hsc: ['Speed of an electron from its kinetic energy', 'Kinetic energy of a satellite'],
    example: { m: 9.109e-31, v: 2e6 },
    priority: 4,
  },
  {
    id: 'grav_pe_near',
    name: 'Change in gravitational potential energy (near surface)',
    module: 'm5',
    topic: 'forces',
    equation: '\\Delta U = mg\\Delta h',
    vars: [v('dU', '\\Delta U', 'Change in potential energy', 'energy', { signed: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), gVar(), v('dh', '\\Delta h', 'Change in height', 'length', { signed: true, concept: 'dh' })],
    solve: {
      dU: { expr: '#m #g #dh', fn: ({ m, g, dh }) => m * g * dh },
      m: { expr: '\\frac{#dU}{#g #dh}', fn: ({ dU, g, dh }) => dU / (g * dh) },
      g: { expr: '\\frac{#dU}{#m #dh}', fn: ({ dU, m, dh }) => dU / (m * dh) },
      dh: { expr: '\\frac{#dU}{#m #g}', fn: ({ dU, m, g }) => dU / (m * g) },
    },
    aliases: ['potential energy', 'GPE', 'mgh'],
    when: 'Small height changes near a planet’s surface where g is constant.',
    whenNot: 'Not for large changes in radius (orbits) — use U = −GMm/r.',
    sheet: 'sheet',
    hsc: ['Energy to lift an object', 'Projectile energy conservation'],
    example: { m: 2, dh: 5 },
    priority: 3,
  },
  {
    id: 'work',
    name: 'Work done by a force',
    module: 'm5',
    topic: 'forces',
    alsoIn: ['circular'],
    equation: 'W = F_{\\parallel}s = Fs\\cos\\theta',
    vars: [
      v('W', 'W', 'Work done', 'energy', { concept: 'Wk', signed: true }),
      v('F', 'F', 'Force', 'force', { positive: true }),
      v('s', 's', 'Displacement', 'length', { nonNegative: true }),
      v('th', '\\theta', 'Angle between force and displacement', 'angle', { concept: 'thetaFs', min: 0, max: PI }),
    ],
    solve: {
      W: { expr: '#F #s \\cos #th', fn: ({ F, s, th }) => F * s * Math.cos(th) },
      F: { expr: '\\frac{#W}{#s \\cos #th}', fn: ({ W, s, th }) => W / (s * Math.cos(th)) },
      s: { expr: '\\frac{#W}{#F \\cos #th}', fn: ({ W, F, th }) => W / (F * Math.cos(th)) },
      th: { expr: '\\cos^{-1}\\left(\\frac{#W}{#F #s}\\right)', fn: ({ W, F, s }) => acos(W / (F * s)) },
    },
    aliases: ['work', 'work done', 'Fs cos theta'],
    when: 'Energy transferred by a force. In uniform circular motion the centripetal force does no work (θ = 90°).',
    sheet: 'sheet',
    hsc: ['Work done by the centripetal force (zero)', 'Work done pulling an object at an angle'],
    example: { F: 50, s: 10, th: 30 * DEG },
    priority: 2,
  },
  {
    id: 'power_fv',
    name: 'Power from force and velocity',
    module: 'm5',
    topic: 'forces',
    equation: 'P = F_{\\parallel}v = Fv\\cos\\theta',
    vars: [
      v('P', 'P', 'Power', 'power', { signed: true }),
      v('F', 'F', 'Force', 'force', { positive: true }),
      v('v', 'v', 'Velocity', 'velocity', { nonNegative: true }),
      v('th', '\\theta', 'Angle between force and velocity', 'angle', { concept: 'thetaFs', min: 0, max: PI }),
    ],
    solve: {
      P: { expr: '#F #v \\cos #th', fn: ({ F, v, th }) => F * v * Math.cos(th) },
      F: { expr: '\\frac{#P}{#v \\cos #th}', fn: ({ P, v, th }) => P / (v * Math.cos(th)) },
      v: { expr: '\\frac{#P}{#F \\cos #th}', fn: ({ P, F, th }) => P / (F * Math.cos(th)) },
      th: { expr: '\\cos^{-1}\\left(\\frac{#P}{#F #v}\\right)', fn: ({ P, F, v }) => acos(P / (F * v)) },
    },
    aliases: ['power', 'Fv'],
    when: 'Rate of doing work by a force on an object moving at velocity v.',
    sheet: 'sheet',
    hsc: ['Power of a motor lifting a load at constant speed'],
    example: { F: 500, v: 3, th: 0 },
    priority: 2,
  },
  {
    id: 'power_et',
    name: 'Power as rate of energy transfer',
    module: 'm5',
    topic: 'forces',
    alsoIn: ['nuclear', 'quantumLight', 'stars'],
    equation: 'P = \\frac{\\Delta E}{\\Delta t}',
    vars: [v('P', 'P', 'Power', 'power', { positive: true }), v('E', '\\Delta E', 'Energy transferred', 'energy', { positive: true }), v('t', '\\Delta t', 'Time interval', 'time', { positive: true })],
    solve: {
      P: { expr: '\\frac{#E}{#t}', fn: ({ E, t }) => E / t },
      E: { expr: '#P #t', fn: ({ P, t }) => P * t },
      t: { expr: '\\frac{#E}{#P}', fn: ({ E, P }) => E / P },
    },
    aliases: ['power', 'energy per second', 'rate of energy', 'luminosity'],
    when: 'Any rate of energy transfer: electrical, radiated (luminosity), nuclear reactor output.',
    sheet: 'sheet',
    hsc: ['Mass lost per second by the Sun (with E = mc²)', 'Energy output of a reactor over a time'],
    example: { E: 3600, t: 60 },
    priority: 2,
  },
  // ───────────── Forces in two dimensions ─────────────
  {
    id: 'force_x',
    name: 'Horizontal (x) component of a force',
    module: 'm5',
    topic: 'forces',
    equation: 'F_x = F\\cos\\theta',
    vars: [v('Fx', 'F_x', 'x-component', 'force', { signed: true }), v('F', 'F', 'Force magnitude', 'force', { positive: true }), v('th', '\\theta', 'Angle to the x-axis', 'angle', { concept: 'thetaF' })],
    solve: {
      Fx: { expr: '#F \\cos #th', fn: ({ F, th }) => F * Math.cos(th) },
      F: { expr: '\\frac{#Fx}{\\cos #th}', fn: ({ Fx, th }) => Fx / Math.cos(th) },
      th: { expr: '\\cos^{-1}\\left(\\frac{#Fx}{#F}\\right)', fn: ({ Fx, F }) => acos(Fx / F) },
    },
    aliases: ['resolve force', 'x component', 'horizontal component', 'components'],
    when: 'Resolving a force (or any vector) into perpendicular components.',
    sheet: 'derived',
    hsc: ['Components of a tension at an angle'],
    example: { F: 100, th: 30 * DEG },
    priority: 2,
  },
  {
    id: 'force_y',
    name: 'Vertical (y) component of a force',
    module: 'm5',
    topic: 'forces',
    equation: 'F_y = F\\sin\\theta',
    vars: [v('Fy', 'F_y', 'y-component', 'force', { signed: true }), v('F', 'F', 'Force magnitude', 'force', { positive: true }), v('th', '\\theta', 'Angle to the x-axis', 'angle', { concept: 'thetaF' })],
    solve: {
      Fy: { expr: '#F \\sin #th', fn: ({ F, th }) => F * Math.sin(th) },
      F: { expr: '\\frac{#Fy}{\\sin #th}', fn: ({ Fy, th }) => Fy / Math.sin(th) },
      th: { expr: '\\sin^{-1}\\left(\\frac{#Fy}{#F}\\right)', fn: ({ Fy, F }) => asin(Fy / F) },
    },
    aliases: ['resolve force', 'y component', 'vertical component', 'components'],
    when: 'Resolving a force into perpendicular components.',
    sheet: 'derived',
    hsc: ['Vertical component of a pull at an angle'],
    example: { F: 100, th: 30 * DEG },
    priority: 2,
  },
  {
    id: 'force_resultant',
    name: 'Resultant of perpendicular components',
    module: 'm5',
    topic: 'forces',
    equation: 'F = \\sqrt{F_x^2 + F_y^2}',
    vars: [v('F', 'F', 'Resultant magnitude', 'force', { nonNegative: true }), v('Fx', 'F_x', 'x-component', 'force', { signed: true }), v('Fy', 'F_y', 'y-component', 'force', { signed: true })],
    solve: {
      F: { expr: '\\sqrt{#Fx^2 + #Fy^2}', fn: ({ Fx, Fy }) => Math.hypot(Fx, Fy) },
      Fx: { expr: '\\sqrt{#F^2 - #Fy^2}', fn: ({ F, Fy }) => Math.sqrt(F * F - Fy * Fy) },
      Fy: { expr: '\\sqrt{#F^2 - #Fx^2}', fn: ({ F, Fx }) => Math.sqrt(F * F - Fx * Fx) },
    },
    aliases: ['resultant force', 'net force', 'pythagoras', 'magnitude'],
    when: 'Magnitude of a vector from its perpendicular components.',
    sheet: 'derived',
    hsc: ['Resultant of two perpendicular forces'],
    example: { Fx: 30, Fy: 40 },
    priority: 2,
  },
  {
    id: 'force_direction',
    name: 'Direction of a resultant force',
    module: 'm5',
    topic: 'forces',
    equation: '\\theta = \\tan^{-1}\\left(\\frac{F_y}{F_x}\\right)',
    vars: [v('th', '\\theta', 'Direction (angle to x-axis)', 'angle', { concept: 'thetaF' }), v('Fy', 'F_y', 'y-component', 'force', { signed: true }), v('Fx', 'F_x', 'x-component', 'force', { signed: true, nonZero: true })],
    solve: {
      th: { expr: '\\tan^{-1}\\left(\\frac{#Fy}{#Fx}\\right)', fn: ({ Fy, Fx }) => Math.atan2(Fy, Fx), note: 'quadrant chosen from the signs of the components' },
      Fy: { expr: '#Fx \\tan #th', fn: ({ Fx, th }) => Fx * Math.tan(th) },
      Fx: { expr: '\\frac{#Fy}{\\tan #th}', fn: ({ Fy, th }) => Fy / Math.tan(th) },
    },
    aliases: ['direction', 'angle of resultant', 'bearing'],
    when: 'Direction of a resultant vector from its components.',
    sheet: 'derived',
    hsc: ['Direction of the net force'],
    example: { Fy: 40, Fx: 30 },
    priority: 1,
  },
  {
    id: 'incline_components',
    name: 'Weight components on an incline',
    module: 'm5',
    topic: 'forces',
    equation: 'F_{\\parallel} = mg\\sin\\theta',
    vars: [v('Fp', 'F_{\\parallel}', 'Component of weight down the slope', 'force', { concept: 'Fpar', nonNegative: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), gVar(), v('th', '\\theta', 'Angle of incline', 'angle', { concept: 'thetaBank', min: 0, max: PI / 2 })],
    solve: {
      Fp: { expr: '#m #g \\sin #th', fn: ({ m, g, th }) => m * g * Math.sin(th) },
      m: { expr: '\\frac{#Fp}{#g \\sin #th}', fn: ({ Fp, g, th }) => Fp / (g * Math.sin(th)) },
      g: { expr: '\\frac{#Fp}{#m \\sin #th}', fn: ({ Fp, m, th }) => Fp / (m * Math.sin(th)) },
      th: { expr: '\\sin^{-1}\\left(\\frac{#Fp}{#m #g}\\right)', fn: ({ Fp, m, g }) => asin(Fp / (m * g)) },
    },
    aliases: ['inclined plane', 'slope', 'component down the slope'],
    when: 'Resolving weight parallel to a slope (the perpendicular component is mg cos θ).',
    sheet: 'derived',
    hsc: ['Force needed to hold an object on a ramp'],
    example: { m: 10, th: 30 * DEG },
    priority: 1,
  },
  // ───────────── Torque ─────────────
  {
    id: 'torque',
    name: 'Torque',
    module: 'm5',
    topic: 'torque',
    equation: '\\tau = r_{\\perp}F = rF\\sin\\theta',
    vars: [
      v('tau', '\\tau', 'Torque', 'torque', { signed: true }),
      v('r', 'r', 'Distance from pivot to point of application', 'length', { concept: 'rArm', positive: true }),
      v('F', 'F', 'Force', 'force', { positive: true }),
      v('th', '\\theta', 'Angle between r and F', 'angle', { concept: 'thetaT', min: 0, max: PI }),
    ],
    solve: {
      tau: { expr: '#r #F \\sin #th', fn: ({ r, F, th }) => r * F * Math.sin(th) },
      r: { expr: '\\frac{#tau}{#F \\sin #th}', fn: ({ tau, F, th }) => tau / (F * Math.sin(th)) },
      F: { expr: '\\frac{#tau}{#r \\sin #th}', fn: ({ tau, r, th }) => tau / (r * Math.sin(th)) },
      th: { expr: '\\sin^{-1}\\left(\\frac{#tau}{#r #F}\\right)', fn: ({ tau, r, F }) => asin(tau / (r * F)), note: '180° − θ gives the same torque' },
    },
    aliases: ['torque', 'moment', 'turning effect', 'spanner', 'rF sin theta', 'lever'],
    when: 'Turning effect of a force about a pivot. θ is the angle between the position vector r (pivot → force) and F. Maximum when F ⟂ r.',
    whenNot: 'r must be measured from the pivot/axis of rotation.',
    related: ['torque_perp', 'moments_balance', 'motor_torque'],
    sheet: 'sheet',
    hsc: ['Torque applied by a spanner at an angle', 'Force needed on a door handle'],
    example: { r: 0.3, F: 40, th: 60 * DEG },
    priority: 4,
  },
  {
    id: 'torque_perp',
    name: 'Torque using perpendicular distance',
    module: 'm5',
    topic: 'torque',
    equation: '\\tau = r_{\\perp}F',
    vars: [v('tau', '\\tau', 'Torque', 'torque', { signed: true }), v('rp', 'r_{\\perp}', 'Perpendicular distance from pivot to the line of action', 'length', { concept: 'rPerp', positive: true }), v('F', 'F', 'Force', 'force', { positive: true })],
    solve: {
      tau: { expr: '#rp #F', fn: ({ rp, F }) => rp * F },
      rp: { expr: '\\frac{#tau}{#F}', fn: ({ tau, F }) => tau / F },
      F: { expr: '\\frac{#tau}{#rp}', fn: ({ tau, rp }) => tau / rp },
    },
    aliases: ['torque', 'moment', 'perpendicular distance', 'lever arm'],
    when: 'When the perpendicular distance from the pivot to the force’s line of action is known (r⊥ = r sin θ).',
    sheet: 'sheet',
    hsc: ['Torque on a seesaw or lever'],
    example: { rp: 0.5, F: 20 },
    priority: 3,
  },
  {
    id: 'moments_balance',
    name: 'Rotational equilibrium (two forces)',
    module: 'm5',
    topic: 'torque',
    equation: 'F_1 r_1 = F_2 r_2',
    vars: [
      v('F1', 'F_1', 'Force 1 (e.g. clockwise)', 'force', { positive: true }),
      v('r1', 'r_1', 'Perpendicular distance of force 1', 'length', { concept: 'rArm1', positive: true }),
      v('F2', 'F_2', 'Force 2 (e.g. anticlockwise)', 'force', { positive: true }),
      v('r2', 'r_2', 'Perpendicular distance of force 2', 'length', { concept: 'rArm2', positive: true }),
    ],
    solve: {
      F1: { expr: '\\frac{#F2 #r2}{#r1}', fn: ({ F2, r1, r2 }) => (F2 * r2) / r1 },
      r1: { expr: '\\frac{#F2 #r2}{#F1}', fn: ({ F1, F2, r2 }) => (F2 * r2) / F1 },
      F2: { expr: '\\frac{#F1 #r1}{#r2}', fn: ({ F1, r1, r2 }) => (F1 * r1) / r2 },
      r2: { expr: '\\frac{#F1 #r1}{#F2}', fn: ({ F1, r1, F2 }) => (F1 * r1) / F2 },
    },
    aliases: ['equilibrium', 'principle of moments', 'seesaw', 'balance', 'clockwise equals anticlockwise'],
    when: 'An object in rotational equilibrium: Στ = 0, so clockwise torque = anticlockwise torque. For more forces use the Torque tool.',
    derivation: ['\\Sigma\\tau = 0 \\Rightarrow \\tau_{cw} = \\tau_{acw}'],
    sheet: 'derived',
    hsc: ['Where to sit on a seesaw to balance it', 'Force a bicep must exert'],
    example: { r1: 1.5, F2: 400, r2: 1.2 },
    priority: 2,
  },
  // ───────────── Uniform circular motion ─────────────
  {
    id: 'circ_v',
    name: 'Orbital / circular speed',
    module: 'm5',
    topic: 'circular',
    alsoIn: ['orbital'],
    equation: 'v = \\frac{2\\pi r}{T}',
    vars: [v('v', 'v', 'Speed', 'velocity', { positive: true }), v('r', 'r', 'Radius', 'length', { positive: true }), v('T', 'T', 'Period', 'time', { positive: true })],
    solve: {
      v: { expr: '\\frac{2\\pi #r}{#T}', fn: ({ r, T }) => (2 * PI * r) / T },
      r: { expr: '\\frac{#v #T}{2\\pi}', fn: ({ v, T }) => (v * T) / (2 * PI) },
      T: { expr: '\\frac{2\\pi #r}{#v}', fn: ({ r, v }) => (2 * PI * r) / v },
    },
    aliases: ['circular speed', 'orbital speed', 'period', 'circumference over period', '2 pi r / T'],
    when: 'Uniform circular motion: one circumference (2πr) per period.',
    sheet: 'sheet',
    hsc: ['Speed of a satellite from its period', 'Period of a car on a circular track'],
    example: { r: 50, T: 12 },
    priority: 4,
  },
  {
    id: 'circ_ac',
    name: 'Centripetal acceleration',
    module: 'm5',
    topic: 'circular',
    equation: 'a_c = \\frac{v^2}{r}',
    vars: [v('a', 'a_c', 'Centripetal acceleration', 'acceleration', { positive: true }), v('v', 'v', 'Speed', 'velocity', { positive: true }), v('r', 'r', 'Radius', 'length', { positive: true })],
    solve: {
      a: { expr: '\\frac{#v^2}{#r}', fn: ({ v, r }) => (v * v) / r },
      v: { expr: '\\sqrt{#a #r}', fn: ({ a, r }) => Math.sqrt(a * r) },
      r: { expr: '\\frac{#v^2}{#a}', fn: ({ v, a }) => (v * v) / a },
    },
    aliases: ['centripetal acceleration', 'ac', 'v^2/r', 'radial acceleration'],
    when: 'Acceleration towards the centre for any object in uniform circular motion.',
    sheet: 'sheet',
    hsc: ['Acceleration of a car around a bend'],
    example: { v: 20, r: 50 },
    priority: 4,
  },
  {
    id: 'circ_ac_T',
    name: 'Centripetal acceleration from period',
    module: 'm5',
    topic: 'circular',
    equation: 'a_c = \\frac{4\\pi^2 r}{T^2}',
    vars: [v('a', 'a_c', 'Centripetal acceleration', 'acceleration', { positive: true }), v('r', 'r', 'Radius', 'length', { positive: true }), v('T', 'T', 'Period', 'time', { positive: true })],
    solve: {
      a: { expr: '\\frac{4\\pi^2 #r}{#T^2}', fn: ({ r, T }) => (4 * PI * PI * r) / (T * T) },
      r: { expr: '\\frac{#a #T^2}{4\\pi^2}', fn: ({ a, T }) => (a * T * T) / (4 * PI * PI) },
      T: { expr: '2\\pi\\sqrt{\\frac{#r}{#a}}', fn: ({ a, r }) => 2 * PI * Math.sqrt(r / a) },
    },
    aliases: ['centripetal acceleration', 'period', '4 pi^2 r / T^2'],
    when: 'Centripetal acceleration when the period is known instead of the speed.',
    derivation: ['a_c = \\frac{v^2}{r},\\; v = \\frac{2\\pi r}{T} \\Rightarrow a_c = \\frac{4\\pi^2 r}{T^2}'],
    sheet: 'derived',
    hsc: ['Acceleration of the Moon in its orbit'],
    example: { r: 50, T: 12 },
    priority: 2,
    chainCost: 1.05,
  },
  {
    id: 'circ_Fc',
    name: 'Centripetal force',
    module: 'm5',
    topic: 'circular',
    alsoIn: ['orbital', 'particles'],
    equation: 'F_c = \\frac{mv^2}{r}',
    vars: [v('F', 'F_c', 'Centripetal (net) force', 'force', { positive: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), v('v', 'v', 'Speed', 'velocity', { positive: true }), v('r', 'r', 'Radius', 'length', { positive: true })],
    solve: {
      F: { expr: '\\frac{#m #v^2}{#r}', fn: ({ m, v, r }) => (m * v * v) / r },
      m: { expr: '\\frac{#F #r}{#v^2}', fn: ({ F, v, r }) => (F * r) / (v * v) },
      v: { expr: '\\sqrt{\\frac{#F #r}{#m}}', fn: ({ F, m, r }) => Math.sqrt((F * r) / m) },
      r: { expr: '\\frac{#m #v^2}{#F}', fn: ({ F, m, v }) => (m * v * v) / F },
    },
    aliases: ['centripetal force', 'mv^2/r', 'net inward force', 'friction on a bend', 'tension in string'],
    when: 'The net inward force needed for uniform circular motion. It is supplied by a real force: friction, tension, gravity, magnetic force, a normal force.',
    whenNot: 'Centripetal force is not an extra force on a free-body diagram.',
    derivation: ['F = ma,\\; a_c = \\frac{v^2}{r} \\Rightarrow F_c = \\frac{mv^2}{r}'],
    sheet: 'derived',
    hsc: ['Friction needed for a car to round a bend', 'Tension in a string for a mass in a horizontal circle'],
    example: { m: 1200, v: 20, r: 50 },
    priority: 4,
  },
  {
    id: 'circ_Fc_T',
    name: 'Centripetal force from period',
    module: 'm5',
    topic: 'circular',
    equation: 'F_c = \\frac{4\\pi^2 mr}{T^2}',
    vars: [v('F', 'F_c', 'Centripetal force', 'force', { positive: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), v('r', 'r', 'Radius', 'length', { positive: true }), v('T', 'T', 'Period', 'time', { positive: true })],
    solve: {
      F: { expr: '\\frac{4\\pi^2 #m #r}{#T^2}', fn: ({ m, r, T }) => (4 * PI * PI * m * r) / (T * T) },
      m: { expr: '\\frac{#F #T^2}{4\\pi^2 #r}', fn: ({ F, r, T }) => (F * T * T) / (4 * PI * PI * r) },
      r: { expr: '\\frac{#F #T^2}{4\\pi^2 #m}', fn: ({ F, m, T }) => (F * T * T) / (4 * PI * PI * m) },
      T: { expr: '2\\pi\\sqrt{\\frac{#m #r}{#F}}', fn: ({ F, m, r }) => 2 * PI * Math.sqrt((m * r) / F) },
    },
    aliases: ['centripetal force', 'period'],
    when: 'Centripetal force when the period (or frequency) is known.',
    derivation: ['F_c = \\frac{mv^2}{r},\\; v = \\frac{2\\pi r}{T}'],
    sheet: 'derived',
    hsc: ['Tension in a string swung with a known period'],
    example: { m: 0.5, r: 1.2, T: 0.8 },
    priority: 2,
    chainCost: 1.05,
  },
  {
    id: 'period_freq',
    name: 'Period and frequency',
    module: 'm5',
    topic: 'circular',
    alsoIn: ['waves'],
    equation: 'T = \\frac{1}{f}',
    vars: [v('T', 'T', 'Period', 'time', { positive: true }), v('f', 'f', 'Frequency', 'frequency', { positive: true })],
    solve: { T: { expr: '\\frac{1}{#f}', fn: ({ f }) => 1 / f }, f: { expr: '\\frac{1}{#T}', fn: ({ T }) => 1 / T } },
    aliases: ['period', 'frequency', 'revolutions per second', 'T=1/f'],
    when: 'Time for one cycle/revolution. Also for waves.',
    sheet: 'derived',
    hsc: ['Period from revolutions per second', 'Period of a wave'],
    example: { f: 5 },
    priority: 3,
  },
  {
    id: 'ang_vel',
    name: 'Angular velocity',
    module: 'm5',
    topic: 'circular',
    equation: '\\omega = \\frac{\\Delta\\theta}{t}',
    vars: [v('w', '\\omega', 'Angular velocity', 'angularVelocity', { concept: 'omega', positive: true }), v('dth', '\\Delta\\theta', 'Angle turned', 'angle', { concept: 'dTheta', positive: true }), v('t', 't', 'Time', 'time', { positive: true })],
    solve: {
      w: { expr: '\\frac{#dth}{#t}', fn: ({ dth, t }) => dth / t },
      dth: { expr: '#w #t', fn: ({ w, t }) => w * t },
      t: { expr: '\\frac{#dth}{#w}', fn: ({ dth, w }) => dth / w },
    },
    aliases: ['angular velocity', 'angular speed', 'omega', 'radians per second'],
    when: 'Rate of change of angle (in radians) for rotation or circular motion.',
    sheet: 'sheet',
    hsc: ['Angular velocity of a wheel or coil'],
    example: { dth: 2 * PI, t: 0.5 },
    priority: 2,
  },
  {
    id: 'ang_vel_T',
    name: 'Angular velocity and period',
    module: 'm5',
    topic: 'circular',
    alsoIn: ['induction'],
    equation: '\\omega = \\frac{2\\pi}{T} = 2\\pi f',
    vars: [v('w', '\\omega', 'Angular velocity', 'angularVelocity', { concept: 'omega', positive: true }), v('T', 'T', 'Period', 'time', { positive: true })],
    solve: { w: { expr: '\\frac{2\\pi}{#T}', fn: ({ T }) => (2 * PI) / T }, T: { expr: '\\frac{2\\pi}{#w}', fn: ({ w }) => (2 * PI) / w } },
    aliases: ['angular velocity', 'omega', 'rpm'],
    when: 'One revolution is 2π rad per period.',
    sheet: 'derived',
    hsc: ['Converting rpm to rad/s'],
    example: { T: 0.5 },
    priority: 2,
  },
  {
    id: 'v_omega_r',
    name: 'Linear and angular speed',
    module: 'm5',
    topic: 'circular',
    equation: 'v = \\omega r',
    vars: [v('v', 'v', 'Linear speed', 'velocity', { positive: true }), v('w', '\\omega', 'Angular velocity', 'angularVelocity', { concept: 'omega', positive: true }), v('r', 'r', 'Radius', 'length', { positive: true })],
    solve: {
      v: { expr: '#w #r', fn: ({ w, r }) => w * r },
      w: { expr: '\\frac{#v}{#r}', fn: ({ v, r }) => v / r },
      r: { expr: '\\frac{#v}{#w}', fn: ({ v, w }) => v / w },
    },
    aliases: ['v = omega r', 'tangential speed', 'angular velocity'],
    when: 'Speed of a point on a rotating object at radius r.',
    sheet: 'derived',
    hsc: ['Speed of the edge of a spinning disc'],
    example: { w: 12, r: 0.3 },
    priority: 2,
  },
  {
    id: 'circ_ac_omega',
    name: 'Centripetal acceleration from angular velocity',
    module: 'm5',
    topic: 'circular',
    equation: 'a_c = \\omega^2 r',
    vars: [v('a', 'a_c', 'Centripetal acceleration', 'acceleration', { positive: true }), v('w', '\\omega', 'Angular velocity', 'angularVelocity', { concept: 'omega', positive: true }), v('r', 'r', 'Radius', 'length', { positive: true })],
    solve: {
      a: { expr: '#w^2 #r', fn: ({ w, r }) => w * w * r },
      w: { expr: '\\sqrt{\\frac{#a}{#r}}', fn: ({ a, r }) => Math.sqrt(a / r) },
      r: { expr: '\\frac{#a}{#w^2}', fn: ({ a, w }) => a / (w * w) },
    },
    aliases: ['omega squared r', 'centripetal acceleration'],
    when: 'Centripetal acceleration from angular velocity (v = ωr in a = v²/r).',
    sheet: 'derived',
    hsc: ['Acceleration in a centrifuge'],
    example: { w: 12, r: 0.3 },
    priority: 1,
    chainCost: 1.1,
  },
  {
    id: 'banked',
    name: 'Banked track / conical pendulum (design speed)',
    module: 'm5',
    topic: 'circular',
    equation: '\\tan\\theta = \\frac{v^2}{rg}',
    vars: [v('th', '\\theta', 'Banking angle (or string angle from vertical)', 'angle', { concept: 'thetaBank', min: 0, max: PI / 2 }), v('v', 'v', 'Speed', 'velocity', { positive: true }), v('r', 'r', 'Radius', 'length', { positive: true }), gVar()],
    solve: {
      th: { expr: '\\tan^{-1}\\left(\\frac{#v^2}{#r #g}\\right)', fn: ({ v, r, g }) => Math.atan((v * v) / (r * g)) },
      v: { expr: '\\sqrt{#r #g \\tan #th}', fn: ({ th, r, g }) => Math.sqrt(r * g * Math.tan(th)) },
      r: { expr: '\\frac{#v^2}{#g \\tan #th}', fn: ({ th, v, g }) => (v * v) / (g * Math.tan(th)) },
      g: { expr: '\\frac{#v^2}{#r \\tan #th}', fn: ({ th, v, r }) => (v * v) / (r * Math.tan(th)) },
    },
    aliases: ['banked track', 'banked curve', 'banking angle', 'design speed', 'conical pendulum', 'mass on a string', 'no friction'],
    when: 'A car on a frictionless banked curve at its design speed: the horizontal component of the normal force provides the centripetal force. Also a conical pendulum (angle of the string from the vertical).',
    whenNot: 'Not if friction contributes to the centripetal force.',
    derivation: ['N\\sin\\theta = \\frac{mv^2}{r},\\quad N\\cos\\theta = mg', '\\Rightarrow \\tan\\theta = \\frac{v^2}{rg}'],
    sheet: 'derived',
    hsc: ['Banking angle for a design speed', 'Speed at which no friction is needed on a banked curve'],
    example: { v: 20, r: 80 },
    priority: 2,
  },
  {
    id: 'flat_curve',
    name: 'Maximum speed on a flat curve (friction)',
    module: 'm5',
    topic: 'circular',
    equation: '\\mu mg = \\frac{mv^2}{r} \\Rightarrow v_{max} = \\sqrt{\\mu rg}',
    vars: [v('v', 'v_{max}', 'Maximum speed', 'velocity', { positive: true }), v('mu', '\\mu', 'Coefficient of friction', 'ratio', { positive: true }), v('r', 'r', 'Radius', 'length', { positive: true }), gVar()],
    solve: {
      v: { expr: '\\sqrt{#mu #r #g}', fn: ({ mu, r, g }) => Math.sqrt(mu * r * g) },
      mu: { expr: '\\frac{#v^2}{#r #g}', fn: ({ v, r, g }) => (v * v) / (r * g) },
      r: { expr: '\\frac{#v^2}{#mu #g}', fn: ({ v, mu, g }) => (v * v) / (mu * g) },
      g: { expr: '\\frac{#v^2}{#mu #r}', fn: ({ v, mu, r }) => (v * v) / (mu * r) },
    },
    aliases: ['friction', 'flat curve', 'unbanked', 'skid', 'coefficient of friction'],
    when: 'A vehicle on a flat (unbanked) curve where static friction alone provides the centripetal force.',
    derivation: ['F_{friction,max} = \\mu N = \\mu mg = \\frac{mv^2}{r}'],
    sheet: 'derived',
    hsc: ['Maximum safe speed around an unbanked corner'],
    example: { mu: 0.6, r: 50 },
    priority: 1,
  },
  {
    id: 'vertical_circle_top',
    name: 'Vertical circle — tension/normal force at the top',
    module: 'm5',
    topic: 'circular',
    equation: 'T + mg = \\frac{mv^2}{r}',
    vars: [v('Tn', 'T', 'Tension (or normal force) at the top', 'force', { concept: 'tension', nonNegative: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), v('v', 'v', 'Speed at the top', 'velocity', { positive: true }), v('r', 'r', 'Radius', 'length', { positive: true }), gVar()],
    solve: {
      Tn: { expr: '\\frac{#m #v^2}{#r} - #m #g', fn: ({ m, v, r, g }) => (m * v * v) / r - m * g },
      m: { expr: '\\frac{#Tn}{#v^2 / #r - #g}', fn: ({ Tn, v, r, g }) => Tn / ((v * v) / r - g) },
      v: { expr: '\\sqrt{\\frac{(#Tn + #m #g) #r}{#m}}', fn: ({ Tn, m, r, g }) => Math.sqrt(((Tn + m * g) * r) / m) },
      r: { expr: '\\frac{#m #v^2}{#Tn + #m #g}', fn: ({ Tn, m, v, g }) => (m * v * v) / (Tn + m * g) },
    },
    aliases: ['vertical circle', 'top of the loop', 'minimum speed at top', 'loop the loop'],
    when: 'At the top of a vertical circle both tension and weight point to the centre. Minimum speed (T = 0): v = √(gr).',
    checks: ({ Tn }) => (Tn < 0 ? [{ level: 'error', message: 'Tension would be negative — the speed is below √(gr), so the object cannot stay on the circular path at the top.' }] : []),
    sheet: 'derived',
    hsc: ['Minimum speed at the top of a loop'],
    example: { m: 0.5, v: 4, r: 1 },
    priority: 1,
    manualOnly: true,
  },
  {
    id: 'vertical_circle_bottom',
    name: 'Vertical circle — tension/normal force at the bottom',
    module: 'm5',
    topic: 'circular',
    equation: 'T - mg = \\frac{mv^2}{r}',
    vars: [v('Tn', 'T', 'Tension (or normal force) at the bottom', 'force', { concept: 'tension', positive: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), v('v', 'v', 'Speed at the bottom', 'velocity', { nonNegative: true }), v('r', 'r', 'Radius', 'length', { positive: true }), gVar()],
    solve: {
      Tn: { expr: '\\frac{#m #v^2}{#r} + #m #g', fn: ({ m, v, r, g }) => (m * v * v) / r + m * g },
      m: { expr: '\\frac{#Tn}{#v^2 / #r + #g}', fn: ({ Tn, v, r, g }) => Tn / ((v * v) / r + g) },
      v: { expr: '\\sqrt{\\frac{(#Tn - #m #g) #r}{#m}}', fn: ({ Tn, m, r, g }) => Math.sqrt(((Tn - m * g) * r) / m) },
      r: { expr: '\\frac{#m #v^2}{#Tn - #m #g}', fn: ({ Tn, m, v, g }) => (m * v * v) / (Tn - m * g) },
    },
    aliases: ['vertical circle', 'bottom of the loop', 'apparent weight', 'swing'],
    when: 'At the bottom of a vertical circle tension acts up (towards the centre) and weight acts down.',
    sheet: 'derived',
    hsc: ['Tension in a pendulum string at the lowest point'],
    example: { m: 0.5, v: 4, r: 1 },
    priority: 1,
    manualOnly: true,
  },
  // ───────────── Gravitation ─────────────
  {
    id: 'grav_force',
    name: "Newton's law of universal gravitation",
    module: 'm5',
    topic: 'gravitation',
    alsoIn: ['orbital'],
    equation: 'F = \\frac{GMm}{r^2}',
    vars: [
      v('F', 'F', 'Gravitational force', 'force', { positive: true }),
      GVar(),
      v('M', 'M', 'Mass of the central body (planet/star)', 'mass', { positive: true }),
      v('m', 'm', 'Mass of the orbiting / second object', 'mass', { positive: true }),
      v('r', 'r', 'Distance between centres', 'length', { positive: true }),
    ],
    solve: {
      F: { expr: '\\frac{#G #M #m}{#r^2}', fn: ({ G, M, m, r }) => (G * M * m) / (r * r) },
      M: { expr: '\\frac{#F #r^2}{#G #m}', fn: ({ F, G, m, r }) => (F * r * r) / (G * m) },
      m: { expr: '\\frac{#F #r^2}{#G #M}', fn: ({ F, G, M, r }) => (F * r * r) / (G * M) },
      r: { expr: '\\sqrt{\\frac{#G #M #m}{#F}}', fn: ({ F, G, M, m }) => Math.sqrt((G * M * m) / F) },
      G: { expr: '\\frac{#F #r^2}{#M #m}', fn: ({ F, M, m, r }) => (F * r * r) / (M * m) },
    },
    aliases: ['gravitational force', 'law of gravitation', 'universal gravitation', 'GMm/r^2', 'inverse square'],
    when: 'Attractive force between two masses. r is measured between CENTRES (r = R_planet + altitude).',
    whenNot: 'Do not use the altitude alone for r.',
    related: ['grav_field', 'orbit_radius_alt', 'orbital_v'],
    sheet: 'sheet',
    hsc: ['Force between the Earth and a satellite', 'Force between the Earth and Moon'],
    example: { M: 6.0e24, m: 1000, r: 7.0e6 },
    priority: 4,
  },
  {
    id: 'grav_field',
    name: 'Gravitational field strength',
    module: 'm5',
    topic: 'gravitation',
    equation: 'g = \\frac{GM}{r^2}',
    vars: [v('g', 'g', 'Gravitational field strength', 'gfield', { positive: true }), GVar(), v('M', 'M', 'Mass of planet/star', 'mass', { positive: true }), v('r', 'r', 'Distance from the centre', 'length', { positive: true })],
    solve: {
      g: { expr: '\\frac{#G #M}{#r^2}', fn: ({ G, M, r }) => (G * M) / (r * r) },
      M: { expr: '\\frac{#g #r^2}{#G}', fn: ({ g, G, r }) => (g * r * r) / G },
      r: { expr: '\\sqrt{\\frac{#G #M}{#g}}', fn: ({ g, G, M }) => Math.sqrt((G * M) / g) },
      G: { expr: '\\frac{#g #r^2}{#M}', fn: ({ g, M, r }) => (g * r * r) / M },
    },
    aliases: ['gravitational field strength', 'acceleration due to gravity', 'g at altitude', 'surface gravity', 'GM/r^2'],
    when: 'Field strength (= free-fall acceleration) at distance r from the centre of a spherical mass.',
    derivation: ['g = \\frac{F}{m} = \\frac{GMm/r^2}{m} = \\frac{GM}{r^2}'],
    sheet: 'sheet',
    hsc: ['g on the surface of Mars', 'g at the altitude of the ISS', 'Mass of a planet from surface gravity'],
    example: { M: 6.0e24, r: 6.371e6 },
    priority: 4,
  },
  {
    id: 'orbit_radius_alt',
    name: 'Orbital radius from altitude',
    module: 'm5',
    topic: 'gravitation',
    alsoIn: ['orbital'],
    equation: 'r = R + h',
    vars: [v('r', 'r', 'Orbital radius (from the centre)', 'length', { positive: true }), v('R', 'R', 'Radius of the planet', 'length', { concept: 'Rp', positive: true }), v('h', 'h', 'Altitude above the surface', 'length', { concept: 'hAlt', nonNegative: true })],
    solve: {
      r: { expr: '#R + #h', fn: ({ R, h }) => R + h },
      R: { expr: '#r - #h', fn: ({ r, h }) => r - h },
      h: { expr: '#r - #R', fn: ({ r, R }) => r - R },
    },
    aliases: ['altitude', 'height above the surface', 'orbital radius', 'distance from centre'],
    when: 'Gravitation formulas need r from the CENTRE of the planet. Add the planet radius to the altitude.',
    sheet: 'exam',
    hsc: ['Satellite at an altitude of 400 km above Earth', 'Altitude of a geostationary satellite'],
    example: { R: 6.371e6, h: 4.0e5 },
    priority: 6,
    chainCost: 0.9,
  },
  {
    id: 'grav_pe',
    name: 'Gravitational potential energy',
    module: 'm5',
    topic: 'gravitation',
    alsoIn: ['orbital'],
    equation: 'U = -\\frac{GMm}{r}',
    vars: [v('U', 'U', 'Gravitational potential energy', 'energy', { concept: 'Ug', max: 0 }), GVar(), v('M', 'M', 'Mass of central body', 'mass', { positive: true }), v('m', 'm', 'Mass of object', 'mass', { positive: true }), v('r', 'r', 'Distance from the centre', 'length', { positive: true })],
    solve: {
      U: { expr: '-\\frac{#G #M #m}{#r}', fn: ({ G, M, m, r }) => -(G * M * m) / r },
      M: { expr: '-\\frac{#U #r}{#G #m}', fn: ({ U, G, m, r }) => -(U * r) / (G * m) },
      m: { expr: '-\\frac{#U #r}{#G #M}', fn: ({ U, G, M, r }) => -(U * r) / (G * M) },
      r: { expr: '-\\frac{#G #M #m}{#U}', fn: ({ U, G, M, m }) => -(G * M * m) / U },
    },
    aliases: ['gravitational potential energy', 'GPE', '-GMm/r', 'potential energy in orbit'],
    when: 'Potential energy relative to zero at infinite separation — always negative. Use for orbits and escape.',
    whenNot: 'For small height changes near the surface ΔU = mgΔh is simpler.',
    sheet: 'sheet',
    hsc: ['Change in GPE when a satellite moves to a higher orbit', 'Energy to launch a satellite'],
    example: { M: 6.0e24, m: 1000, r: 7.0e6 },
    priority: 3,
  },
  {
    id: 'grav_pe_change',
    name: 'Change in GPE between two radii',
    module: 'm5',
    topic: 'orbital',
    alsoIn: ['gravitation'],
    equation: '\\Delta U = GMm\\left(\\frac{1}{r_1} - \\frac{1}{r_2}\\right)',
    vars: [v('dU', '\\Delta U', 'Change in potential energy (r₁ → r₂)', 'energy', { concept: 'dUg', signed: true }), GVar(), v('M', 'M', 'Mass of central body', 'mass', { positive: true }), v('m', 'm', 'Mass of object', 'mass', { positive: true }), v('r1', 'r_1', 'Initial radius', 'length', { concept: 'r1', positive: true }), v('r2', 'r_2', 'Final radius', 'length', { concept: 'r2', positive: true })],
    solve: {
      dU: { expr: '#G #M #m \\left(\\frac{1}{#r1} - \\frac{1}{#r2}\\right)', fn: ({ G, M, m, r1, r2 }) => G * M * m * (1 / r1 - 1 / r2) },
      m: { expr: '\\frac{#dU}{#G #M (1/#r1 - 1/#r2)}', fn: ({ dU, G, M, r1, r2 }) => dU / (G * M * (1 / r1 - 1 / r2)) },
      M: { expr: '\\frac{#dU}{#G #m (1/#r1 - 1/#r2)}', fn: ({ dU, G, m, r1, r2 }) => dU / (G * m * (1 / r1 - 1 / r2)) },
      r2: { expr: '\\left(\\frac{1}{#r1} - \\frac{#dU}{#G #M #m}\\right)^{-1}', fn: ({ dU, G, M, m, r1 }) => 1 / (1 / r1 - dU / (G * M * m)) },
      r1: { expr: '\\left(\\frac{1}{#r2} + \\frac{#dU}{#G #M #m}\\right)^{-1}', fn: ({ dU, G, M, m, r2 }) => 1 / (1 / r2 + dU / (G * M * m)) },
    },
    aliases: ['change in potential energy', 'raise orbit', 'launch from surface', 'work done against gravity'],
    when: 'Energy needed (ΔU > 0) to move a mass from radius r₁ to a larger radius r₂. From the surface, r₁ = R_planet.',
    derivation: ['\\Delta U = U_2 - U_1 = -\\frac{GMm}{r_2} + \\frac{GMm}{r_1}'],
    sheet: 'derived',
    hsc: ['Increase in GPE when lifting a satellite from the surface to orbit'],
    example: { M: 6.0e24, m: 1000, r1: 6.371e6, r2: 7.0e6 },
    priority: 2,
  },
  {
    id: 'escape_v',
    name: 'Escape velocity',
    module: 'm5',
    topic: 'orbital',
    alsoIn: ['gravitation'],
    equation: 'v_{esc} = \\sqrt{\\frac{2GM}{r}}',
    vars: [v('v', 'v_{esc}', 'Escape velocity', 'velocity', { concept: 'vesc', positive: true }), GVar(), v('M', 'M', 'Mass of planet/star', 'mass', { positive: true }), v('r', 'r', 'Distance from the centre', 'length', { positive: true })],
    solve: {
      v: { expr: '\\sqrt{\\frac{2 #G #M}{#r}}', fn: ({ G, M, r }) => Math.sqrt((2 * G * M) / r) },
      M: { expr: '\\frac{#v^2 #r}{2 #G}', fn: ({ v, G, r }) => (v * v * r) / (2 * G) },
      r: { expr: '\\frac{2 #G #M}{#v^2}', fn: ({ v, G, M }) => (2 * G * M) / (v * v) },
    },
    aliases: ['escape velocity', 'escape speed', 'vesc'],
    when: 'Minimum launch speed to escape a gravitational field (K + U = 0), ignoring air resistance.',
    derivation: ['\\tfrac{1}{2}mv^2 - \\frac{GMm}{r} = 0 \\Rightarrow v = \\sqrt{\\frac{2GM}{r}}'],
    sheet: 'sheet',
    hsc: ['Escape velocity from Earth or the Moon'],
    example: { M: 6.0e24, r: 6.371e6 },
    priority: 3,
  },
  // ───────────── Orbital motion ─────────────
  {
    id: 'orbital_v',
    name: 'Orbital velocity',
    module: 'm5',
    topic: 'orbital',
    equation: 'v = \\sqrt{\\frac{GM}{r}}',
    vars: [v('v', 'v', 'Orbital speed', 'velocity', { positive: true }), GVar(), v('M', 'M', 'Mass of central body', 'mass', { positive: true }), v('r', 'r', 'Orbital radius (from centre)', 'length', { positive: true })],
    solve: {
      v: { expr: '\\sqrt{\\frac{#G #M}{#r}}', fn: ({ G, M, r }) => Math.sqrt((G * M) / r) },
      M: { expr: '\\frac{#v^2 #r}{#G}', fn: ({ v, G, r }) => (v * v * r) / G },
      r: { expr: '\\frac{#G #M}{#v^2}', fn: ({ v, G, M }) => (G * M) / (v * v) },
    },
    aliases: ['orbital velocity', 'orbital speed', 'satellite speed', 'sqrt(GM/r)'],
    when: 'Circular orbit: gravity provides the centripetal force. The speed does not depend on the satellite’s mass.',
    derivation: ['\\frac{GMm}{r^2} = \\frac{mv^2}{r}', '\\Rightarrow v = \\sqrt{\\frac{GM}{r}}'],
    sheet: 'derived',
    hsc: ['Speed of a satellite at a given altitude', 'Mass of a planet from a moon’s orbit'],
    example: { M: 6.0e24, r: 7.0e6 },
    priority: 4,
  },
  {
    id: 'kepler3',
    name: "Kepler's third law",
    module: 'm5',
    topic: 'orbital',
    equation: '\\frac{r^3}{T^2} = \\frac{GM}{4\\pi^2}',
    vars: [v('r', 'r', 'Orbital radius', 'length', { positive: true }), v('T', 'T', 'Orbital period', 'time', { positive: true }), GVar(), v('M', 'M', 'Mass of central body', 'mass', { positive: true })],
    solve: {
      r: { expr: '\\sqrt[3]{\\frac{#G #M #T^2}{4\\pi^2}}', fn: ({ T, G, M }) => Math.cbrt((G * M * T * T) / (4 * PI * PI)) },
      T: { expr: '\\sqrt{\\frac{4\\pi^2 #r^3}{#G #M}}', fn: ({ r, G, M }) => Math.sqrt((4 * PI * PI * r ** 3) / (G * M)) },
      M: { expr: '\\frac{4\\pi^2 #r^3}{#G #T^2}', fn: ({ r, T, G }) => (4 * PI * PI * r ** 3) / (G * T * T) },
    },
    aliases: ["kepler's third law", 'kepler', 'law of periods', 'r^3/T^2', 'geostationary', 'period of orbit', 'orbital period'],
    when: 'Relates orbital radius and period for any object orbiting a central mass M (circular orbits).',
    derivation: ['\\frac{GMm}{r^2} = \\frac{4\\pi^2 mr}{T^2} \\Rightarrow \\frac{r^3}{T^2} = \\frac{GM}{4\\pi^2}'],
    sheet: 'sheet',
    hsc: ['Altitude of a geostationary satellite', 'Mass of Jupiter from a moon’s orbit', 'Period of a satellite'],
    example: { T: 86400, M: 6.0e24 },
    priority: 4,
  },
  {
    id: 'kepler_ratio',
    name: "Kepler's third law (comparing two orbits)",
    module: 'm5',
    topic: 'orbital',
    equation: '\\frac{r_1^3}{T_1^2} = \\frac{r_2^3}{T_2^2}',
    vars: [v('r1', 'r_1', 'Radius of orbit 1', 'length', { concept: 'r1', positive: true }), v('T1', 'T_1', 'Period of orbit 1', 'time', { concept: 'T1', positive: true }), v('r2', 'r_2', 'Radius of orbit 2', 'length', { concept: 'r2', positive: true }), v('T2', 'T_2', 'Period of orbit 2', 'time', { concept: 'T2', positive: true })],
    solve: {
      r1: { expr: '#r2 \\left(\\frac{#T1}{#T2}\\right)^{2/3}', fn: ({ T1, r2, T2 }) => r2 * Math.pow(T1 / T2, 2 / 3) },
      T1: { expr: '#T2 \\left(\\frac{#r1}{#r2}\\right)^{3/2}', fn: ({ r1, r2, T2 }) => T2 * Math.pow(r1 / r2, 1.5) },
      r2: { expr: '#r1 \\left(\\frac{#T2}{#T1}\\right)^{2/3}', fn: ({ r1, T1, T2 }) => r1 * Math.pow(T2 / T1, 2 / 3) },
      T2: { expr: '#T1 \\left(\\frac{#r2}{#r1}\\right)^{3/2}', fn: ({ r1, T1, r2 }) => T1 * Math.pow(r2 / r1, 1.5) },
    },
    aliases: ['kepler ratio', 'two satellites', 'two moons', 'two planets', 'compare orbits'],
    when: 'Two objects orbiting the SAME central mass. Units only need to be consistent (e.g. AU and years).',
    whenNot: 'Not for objects orbiting different central bodies.',
    sheet: 'derived',
    hsc: ['Period of a moon from another moon’s orbit', 'Orbital radius of a planet in AU'],
    example: { T1: 1, r2: 1.52, T2: 1.88 },
    priority: 2,
  },
  {
    id: 'orbital_K',
    name: 'Kinetic energy in a circular orbit',
    module: 'm5',
    topic: 'orbital',
    equation: 'K = \\frac{GMm}{2r}',
    vars: [v('K', 'K', 'Kinetic energy', 'energy', { positive: true }), GVar(), v('M', 'M', 'Mass of central body', 'mass', { positive: true }), v('m', 'm', 'Mass of satellite', 'mass', { positive: true }), v('r', 'r', 'Orbital radius', 'length', { positive: true })],
    solve: {
      K: { expr: '\\frac{#G #M #m}{2 #r}', fn: ({ G, M, m, r }) => (G * M * m) / (2 * r) },
      m: { expr: '\\frac{2 #K #r}{#G #M}', fn: ({ K, G, M, r }) => (2 * K * r) / (G * M) },
      M: { expr: '\\frac{2 #K #r}{#G #m}', fn: ({ K, G, m, r }) => (2 * K * r) / (G * m) },
      r: { expr: '\\frac{#G #M #m}{2 #K}', fn: ({ K, G, M, m }) => (G * M * m) / (2 * K) },
    },
    aliases: ['orbital kinetic energy', 'kinetic energy of satellite'],
    when: 'Kinetic energy of a satellite in a circular orbit (half the magnitude of U).',
    derivation: ['v^2 = \\frac{GM}{r} \\Rightarrow K = \\tfrac{1}{2}mv^2 = \\frac{GMm}{2r}'],
    sheet: 'derived',
    hsc: ['Kinetic energy of a satellite at a given altitude'],
    example: { M: 6.0e24, m: 1000, r: 7.0e6 },
    priority: 2,
    chainCost: 1.2,
  },
  {
    id: 'orbital_E',
    name: 'Total energy in a circular orbit',
    module: 'm5',
    topic: 'orbital',
    equation: 'E = K + U = -\\frac{GMm}{2r}',
    vars: [v('E', 'E', 'Total mechanical energy', 'energy', { concept: 'Eorb', max: 0 }), GVar(), v('M', 'M', 'Mass of central body', 'mass', { positive: true }), v('m', 'm', 'Mass of satellite', 'mass', { positive: true }), v('r', 'r', 'Orbital radius', 'length', { positive: true })],
    solve: {
      E: { expr: '-\\frac{#G #M #m}{2 #r}', fn: ({ G, M, m, r }) => -(G * M * m) / (2 * r) },
      m: { expr: '-\\frac{2 #E #r}{#G #M}', fn: ({ E, G, M, r }) => -(2 * E * r) / (G * M) },
      M: { expr: '-\\frac{2 #E #r}{#G #m}', fn: ({ E, G, m, r }) => -(2 * E * r) / (G * m) },
      r: { expr: '-\\frac{#G #M #m}{2 #E}', fn: ({ E, G, M, m }) => -(G * M * m) / (2 * E) },
    },
    aliases: ['total energy', 'orbital energy', 'mechanical energy', 'bound orbit'],
    when: 'Total energy of a satellite in a circular orbit. Negative because the satellite is bound.',
    derivation: ['E = \\frac{GMm}{2r} - \\frac{GMm}{r} = -\\frac{GMm}{2r}'],
    sheet: 'derived',
    hsc: ['Energy needed to move a satellite to a higher orbit (ΔE)'],
    example: { M: 6.0e24, m: 1000, r: 7.0e6 },
    priority: 2,
  },
  {
    id: 'orbit_change_E',
    name: 'Energy to change circular orbits',
    module: 'm5',
    topic: 'orbital',
    equation: '\\Delta E = \\frac{GMm}{2}\\left(\\frac{1}{r_1} - \\frac{1}{r_2}\\right)',
    vars: [v('dE', '\\Delta E', 'Energy required (r₁ → r₂)', 'energy', { concept: 'dEorb', signed: true }), GVar(), v('M', 'M', 'Mass of central body', 'mass', { positive: true }), v('m', 'm', 'Mass of satellite', 'mass', { positive: true }), v('r1', 'r_1', 'Initial orbital radius', 'length', { concept: 'r1', positive: true }), v('r2', 'r_2', 'Final orbital radius', 'length', { concept: 'r2', positive: true })],
    solve: {
      dE: { expr: '\\frac{#G #M #m}{2}\\left(\\frac{1}{#r1} - \\frac{1}{#r2}\\right)', fn: ({ G, M, m, r1, r2 }) => ((G * M * m) / 2) * (1 / r1 - 1 / r2) },
      m: { expr: '\\frac{2 #dE}{#G #M (1/#r1 - 1/#r2)}', fn: ({ dE, G, M, r1, r2 }) => (2 * dE) / (G * M * (1 / r1 - 1 / r2)) },
      M: { expr: '\\frac{2 #dE}{#G #m (1/#r1 - 1/#r2)}', fn: ({ dE, G, m, r1, r2 }) => (2 * dE) / (G * m * (1 / r1 - 1 / r2)) },
      r2: { expr: '\\left(\\frac{1}{#r1} - \\frac{2 #dE}{#G #M #m}\\right)^{-1}', fn: ({ dE, G, M, m, r1 }) => 1 / (1 / r1 - (2 * dE) / (G * M * m)) },
      r1: { expr: '\\left(\\frac{1}{#r2} + \\frac{2 #dE}{#G #M #m}\\right)^{-1}', fn: ({ dE, G, M, m, r2 }) => 1 / (1 / r2 + (2 * dE) / (G * M * m)) },
    },
    aliases: ['change orbit', 'higher orbit', 'transfer orbit energy', 'raise satellite'],
    when: 'Work needed to move a satellite between two circular orbits (difference in total orbital energy).',
    derivation: ['\\Delta E = E_2 - E_1 = -\\frac{GMm}{2r_2} + \\frac{GMm}{2r_1}'],
    sheet: 'derived',
    hsc: ['Energy needed to move a satellite from low Earth orbit to a higher orbit'],
    example: { M: 6.0e24, m: 1000, r1: 6.771e6, r2: 4.22e7 },
    priority: 2,
  },
];
