/**
 * Module 6 — Electromagnetism.
 * Electric fields, charged particles in electric and magnetic fields, the motor effect,
 * electromagnetic induction, generators, transformers and power transmission.
 */
import { asin, acos, DEG, kVar, mu0Var } from './common';
import { FormulaDef, v } from './types';

const PI = Math.PI;
const angleVB = (name = 'Angle between the velocity and the magnetic field') => v('th', '\\theta', name, 'angle', { concept: 'thetaB', min: 0, max: PI });
const angleIB = () => v('th', '\\theta', 'Angle between the conductor (current) and the magnetic field', 'angle', { concept: 'thetaIB', min: 0, max: PI });
const angleN = () => v('th', '\\theta', 'Angle between B and the normal to the coil (area vector)', 'angle', { concept: 'thetaN', min: 0, max: PI });
const qMag = (name = 'Charge (magnitude)') => v('q', 'q', name, 'charge', { positive: true });

export const m6Formulas: FormulaDef[] = [
  // ───────────── Electric fields ─────────────
  {
    id: 'efield_plates',
    name: 'Electric field between parallel plates',
    module: 'm6',
    topic: 'efields',
    equation: 'E = \\frac{V}{d}',
    vars: [v('E', 'E', 'Electric field strength', 'efield', { concept: 'Ef', positive: true }), v('V', 'V', 'Potential difference between plates', 'voltage', { positive: true }), v('d', 'd', 'Plate separation', 'length', { concept: 'dPlate', positive: true })],
    solve: {
      E: { expr: '\\frac{#V}{#d}', fn: ({ V, d }) => V / d },
      V: { expr: '#E #d', fn: ({ E, d }) => E * d },
      d: { expr: '\\frac{#V}{#E}', fn: ({ V, E }) => V / E },
    },
    aliases: ['parallel plates', 'uniform electric field', 'E = V/d', 'field between plates'],
    when: 'Uniform field between two charged parallel plates. The sheet writes E = −V/d; the minus sign means the field points from high to low potential — use magnitudes here.',
    whenNot: 'Not for the (non-uniform) field of a point charge.',
    sheet: 'sheet',
    hsc: ['Field between plates 5 mm apart at 200 V', 'Millikan oil-drop apparatus'],
    example: { V: 200, d: 0.005 },
    priority: 5,
  },
  {
    id: 'efield_force',
    name: 'Force on a charge in an electric field',
    module: 'm6',
    topic: 'efields',
    alsoIn: ['particles'],
    equation: 'F = qE',
    vars: [v('F', 'F', 'Electric force (magnitude)', 'force', { positive: true }), qMag(), v('E', 'E', 'Electric field strength', 'efield', { concept: 'Ef', positive: true })],
    solve: {
      F: { expr: '#q #E', fn: ({ q, E }) => q * E },
      q: { expr: '\\frac{#F}{#E}', fn: ({ F, E }) => F / E },
      E: { expr: '\\frac{#F}{#q}', fn: ({ F, q }) => F / q },
    },
    aliases: ['electric force', 'E = F/q', 'force on charge', 'qE'],
    when: 'Force on a charge in any electric field. Magnitude here; direction: along E for positive charges, opposite E for negative charges (electrons).',
    sheet: 'sheet',
    hsc: ['Force on an electron between plates', 'Field needed to balance an oil drop'],
    example: { q: 1.602e-19, E: 4e4 },
    priority: 5,
  },
  {
    id: 'work_qV',
    name: 'Work done moving a charge through a potential difference',
    module: 'm6',
    topic: 'efields',
    alsoIn: ['particles'],
    equation: 'W = qV',
    vars: [v('W', 'W', 'Work done / energy transferred', 'energyAtomic', { concept: 'Wk', positive: true }), qMag(), v('V', 'V', 'Potential difference', 'voltage', { positive: true })],
    solve: {
      W: { expr: '#q #V', fn: ({ q, V }) => q * V },
      q: { expr: '\\frac{#W}{#V}', fn: ({ W, V }) => W / V },
      V: { expr: '\\frac{#W}{#q}', fn: ({ W, q }) => W / q },
    },
    aliases: ['work done on a charge', 'W = qV', 'electron volt', 'energy gained'],
    when: 'Energy gained (or work done by the field) when a charge moves through potential difference V. 1 eV = energy gained by an electron through 1 V.',
    sheet: 'sheet',
    hsc: ['Kinetic energy gained by an electron accelerated through 2000 V'],
    example: { q: 1.602e-19, V: 2000 },
    priority: 4,
  },
  {
    id: 'work_qEd',
    name: 'Work done by a uniform field',
    module: 'm6',
    topic: 'efields',
    equation: 'W = qEd',
    vars: [v('W', 'W', 'Work done', 'energyAtomic', { concept: 'Wk', positive: true }), qMag(), v('E', 'E', 'Electric field strength', 'efield', { concept: 'Ef', positive: true }), v('d', 'd', 'Distance moved along the field', 'length', { concept: 'dPlate', positive: true })],
    solve: {
      W: { expr: '#q #E #d', fn: ({ q, E, d }) => q * E * d },
      q: { expr: '\\frac{#W}{#E #d}', fn: ({ W, E, d }) => W / (E * d) },
      E: { expr: '\\frac{#W}{#q #d}', fn: ({ W, q, d }) => W / (q * d) },
      d: { expr: '\\frac{#W}{#q #E}', fn: ({ W, q, E }) => W / (q * E) },
    },
    aliases: ['work done', 'W = Fd', 'qEd'],
    when: 'Work done on a charge moving a distance d parallel to a uniform field (W = Fd with F = qE).',
    derivation: ['W = Fd = qEd = qV'],
    sheet: 'derived',
    hsc: ['Work done moving a charge between plates'],
    example: { q: 1.602e-19, E: 5e4, d: 0.01 },
    priority: 2,
    chainCost: 1.1,
  },
  {
    id: 'coulomb',
    name: "Coulomb's law",
    module: 'm6',
    topic: 'efields',
    equation: 'F = \\frac{1}{4\\pi\\varepsilon_0}\\frac{q_1q_2}{r^2}',
    vars: [v('F', 'F', 'Electrostatic force', 'force', { positive: true }), kVar(), v('q1', 'q_1', 'Charge 1 (magnitude)', 'charge', { positive: true }), v('q2', 'q_2', 'Charge 2 (magnitude)', 'charge', { positive: true }), v('r', 'r', 'Separation of the charges', 'length', { positive: true })],
    solve: {
      F: { expr: '\\frac{#k #q1 #q2}{#r^2}', fn: ({ k, q1, q2, r }) => (k * q1 * q2) / (r * r) },
      q1: { expr: '\\frac{#F #r^2}{#k #q2}', fn: ({ F, k, q2, r }) => (F * r * r) / (k * q2) },
      q2: { expr: '\\frac{#F #r^2}{#k #q1}', fn: ({ F, k, q1, r }) => (F * r * r) / (k * q1) },
      r: { expr: '\\sqrt{\\frac{#k #q1 #q2}{#F}}', fn: ({ F, k, q1, q2 }) => Math.sqrt((k * q1 * q2) / F) },
    },
    aliases: ["coulomb's law", 'electrostatic force', 'point charges', 'kq1q2/r^2', 'force between charges'],
    when: 'Force between two point charges. Like charges repel, unlike attract (decide direction separately). k = 1/(4πε₀) = 8.99 × 10⁹ N m² C⁻².',
    sheet: 'sheet',
    hsc: ['Force between two charged spheres', 'Force between a proton and an electron in hydrogen'],
    example: { q1: 2e-6, q2: 3e-6, r: 0.05 },
    priority: 3,
  },
  {
    id: 'efield_point',
    name: 'Electric field of a point charge',
    module: 'm6',
    topic: 'efields',
    equation: 'E = \\frac{1}{4\\pi\\varepsilon_0}\\frac{q}{r^2}',
    vars: [v('E', 'E', 'Electric field strength', 'efield', { concept: 'Ef', positive: true }), kVar(), v('q', 'q', 'Source charge (magnitude)', 'charge', { positive: true }), v('r', 'r', 'Distance from the charge', 'length', { positive: true })],
    solve: {
      E: { expr: '\\frac{#k #q}{#r^2}', fn: ({ k, q, r }) => (k * q) / (r * r) },
      q: { expr: '\\frac{#E #r^2}{#k}', fn: ({ E, k, r }) => (E * r * r) / k },
      r: { expr: '\\sqrt{\\frac{#k #q}{#E}}', fn: ({ E, k, q }) => Math.sqrt((k * q) / E) },
    },
    aliases: ['point charge field', 'field of a charge', 'kq/r^2'],
    when: 'Radial field around a point charge: outward from positive, inward to negative.',
    derivation: ['E = \\frac{F}{q_{test}} = \\frac{kq q_{test}/r^2}{q_{test}} = \\frac{kq}{r^2}'],
    sheet: 'derived',
    hsc: ['Field strength at a distance from a charged sphere'],
    example: { q: 5e-9, r: 0.1 },
    priority: 2,
  },
  // ───────────── Charged particles ─────────────
  {
    id: 'accel_qE',
    name: 'Acceleration of a charge in an electric field',
    module: 'm6',
    topic: 'particles',
    alsoIn: ['efields'],
    equation: 'a = \\frac{qE}{m}',
    vars: [v('a', 'a', 'Acceleration', 'acceleration', { positive: true }), qMag(), v('E', 'E', 'Electric field strength', 'efield', { concept: 'Ef', positive: true }), v('m', 'm', 'Mass of particle', 'mass', { positive: true })],
    solve: {
      a: { expr: '\\frac{#q #E}{#m}', fn: ({ q, E, m }) => (q * E) / m },
      q: { expr: '\\frac{#m #a}{#E}', fn: ({ a, E, m }) => (m * a) / E },
      E: { expr: '\\frac{#m #a}{#q}', fn: ({ a, q, m }) => (m * a) / q },
      m: { expr: '\\frac{#q #E}{#a}', fn: ({ a, q, E }) => (q * E) / a },
    },
    aliases: ['acceleration of electron', 'acceleration of proton', 'qE/m', 'charged particle acceleration'],
    when: 'A charged particle in a uniform electric field (gravity negligible) has constant acceleration — use the kinematics equations for its motion.',
    derivation: ['F = qE,\\quad F = ma \\Rightarrow a = \\frac{qE}{m}'],
    sheet: 'derived',
    hsc: ['Acceleration of an electron between charged plates', 'Deflection of an electron beam (like a projectile)'],
    example: { q: 1.602e-19, E: 1e4, m: 9.109e-31 },
    priority: 3,
  },
  {
    id: 'accel_voltage',
    name: 'Speed of a charge accelerated from rest through V',
    module: 'm6',
    topic: 'particles',
    alsoIn: ['efields', 'quantum'],
    equation: '\\tfrac{1}{2}mv^2 = qV',
    vars: [v('v', 'v', 'Final speed', 'velocity', { positive: true }), qMag(), v('V', 'V', 'Accelerating potential difference', 'voltage', { positive: true }), v('m', 'm', 'Mass of particle', 'mass', { positive: true })],
    solve: {
      v: { expr: '\\sqrt{\\frac{2 #q #V}{#m}}', fn: ({ q, V, m }) => Math.sqrt((2 * q * V) / m) },
      V: { expr: '\\frac{#m #v^2}{2 #q}', fn: ({ v, q, m }) => (m * v * v) / (2 * q) },
      q: { expr: '\\frac{#m #v^2}{2 #V}', fn: ({ v, V, m }) => (m * v * v) / (2 * V) },
      m: { expr: '\\frac{2 #q #V}{#v^2}', fn: ({ v, q, V }) => (2 * q * V) / (v * v) },
    },
    aliases: ['accelerated through', 'electron gun', 'accelerating voltage', 'speed of electron', 'cathode ray tube'],
    when: 'Particle starting from rest, accelerated through potential difference V: all the work qV becomes kinetic energy.',
    whenNot: 'If the particle has an initial speed use ½mv² − ½mu² = qV. Not valid at relativistic speeds.',
    derivation: ['W = qV = \\Delta K = \\tfrac{1}{2}mv^2 - 0'],
    checks: ({ v }) => (v > 3e7 ? [{ level: 'warning', message: 'v > 0.1c — relativistic effects become noticeable; the classical result is approximate.' }] : []),
    sheet: 'derived',
    hsc: ['Speed of an electron from an electron gun', 'Speed of a proton accelerated through 5 kV'],
    example: { q: 1.602e-19, V: 2000, m: 9.109e-31 },
    priority: 4,
  },
  {
    id: 'mag_force_q',
    name: 'Force on a moving charge in a magnetic field',
    module: 'm6',
    topic: 'particles',
    alsoIn: ['bfields'],
    equation: 'F = qv_{\\perp}B = qvB\\sin\\theta',
    vars: [v('F', 'F', 'Magnetic force (magnitude)', 'force', { nonNegative: true }), qMag(), v('v', 'v', 'Speed', 'velocity', { positive: true }), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true }), angleVB()],
    solve: {
      F: { expr: '#q #v #B \\sin #th', fn: ({ q, v, B, th }) => q * v * B * Math.sin(th) },
      q: { expr: '\\frac{#F}{#v #B \\sin #th}', fn: ({ F, v, B, th }) => F / (v * B * Math.sin(th)) },
      v: { expr: '\\frac{#F}{#q #B \\sin #th}', fn: ({ F, q, B, th }) => F / (q * B * Math.sin(th)) },
      B: { expr: '\\frac{#F}{#q #v \\sin #th}', fn: ({ F, q, v, th }) => F / (q * v * Math.sin(th)) },
      th: { expr: '\\sin^{-1}\\left(\\frac{#F}{#q #v #B}\\right)', fn: ({ F, q, v, B }) => asin(F / (q * v * B)), note: '180° − θ gives the same force' },
    },
    aliases: ['magnetic force on a charge', 'qvB', 'lorentz force', 'force on electron', 'force on proton', 'moving charge'],
    when: 'Force on a charged particle moving through a magnetic field. θ is the angle between v and B (θ = 90° when perpendicular). Direction by the right-hand rule; reversed for negative charges.',
    whenNot: 'No force if the charge is stationary or moves parallel to B.',
    related: ['mag_radius', 'mag_accel'],
    sheet: 'sheet',
    hsc: ['Force on a proton moving perpendicular to a 3.00 T field', 'Force on an electron in a cathode-ray tube'],
    example: { q: 1.602e-19, v: 1200, B: 3.0, th: 90 * DEG },
    priority: 5,
  },
  {
    id: 'mag_accel',
    name: 'Acceleration of a charge in a magnetic field',
    module: 'm6',
    topic: 'particles',
    equation: 'a = \\frac{qvB\\sin\\theta}{m}',
    vars: [v('a', 'a', 'Acceleration', 'acceleration', { nonNegative: true }), qMag(), v('v', 'v', 'Speed', 'velocity', { positive: true }), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true }), angleVB(), v('m', 'm', 'Mass', 'mass', { positive: true })],
    solve: {
      a: { expr: '\\frac{#q #v #B \\sin #th}{#m}', fn: ({ q, v, B, th, m }) => (q * v * B * Math.sin(th)) / m },
      q: { expr: '\\frac{#m #a}{#v #B \\sin #th}', fn: ({ a, v, B, th, m }) => (m * a) / (v * B * Math.sin(th)) },
      v: { expr: '\\frac{#m #a}{#q #B \\sin #th}', fn: ({ a, q, B, th, m }) => (m * a) / (q * B * Math.sin(th)) },
      B: { expr: '\\frac{#m #a}{#q #v \\sin #th}', fn: ({ a, q, v, th, m }) => (m * a) / (q * v * Math.sin(th)) },
      m: { expr: '\\frac{#q #v #B \\sin #th}{#a}', fn: ({ a, q, v, B, th }) => (q * v * B * Math.sin(th)) / a },
      th: { expr: '\\sin^{-1}\\left(\\frac{#m #a}{#q #v #B}\\right)', fn: ({ a, q, v, B, m }) => asin((m * a) / (q * v * B)) },
    },
    aliases: ['acceleration in magnetic field', 'qvB/m'],
    when: 'Acceleration (always perpendicular to v, i.e. centripetal) of a charge in a magnetic field.',
    derivation: ['F = qvB\\sin\\theta,\\quad F = ma \\Rightarrow a = \\frac{qvB\\sin\\theta}{m}'],
    sheet: 'derived',
    hsc: ['Acceleration of a proton entering a magnetic field perpendicular to it'],
    example: { q: 1.602e-19, v: 1200, B: 3.0, th: 90 * DEG, m: 1.673e-27 },
    priority: 3,
    chainCost: 1.5,
  },
  {
    id: 'mag_radius',
    name: 'Radius of a charged particle’s circular path',
    module: 'm6',
    topic: 'particles',
    alsoIn: ['atomic'],
    equation: 'r = \\frac{mv}{qB}',
    vars: [v('r', 'r', 'Radius of path', 'length', { positive: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), v('v', 'v', 'Speed (perpendicular to B)', 'velocity', { positive: true }), qMag(), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true })],
    solve: {
      r: { expr: '\\frac{#m #v}{#q #B}', fn: ({ m, v, q, B }) => (m * v) / (q * B) },
      m: { expr: '\\frac{#q #B #r}{#v}', fn: ({ r, v, q, B }) => (q * B * r) / v },
      v: { expr: '\\frac{#q #B #r}{#m}', fn: ({ r, m, q, B }) => (q * B * r) / m },
      q: { expr: '\\frac{#m #v}{#B #r}', fn: ({ r, m, v, B }) => (m * v) / (B * r) },
      B: { expr: '\\frac{#m #v}{#q #r}', fn: ({ r, m, v, q }) => (m * v) / (q * r) },
    },
    aliases: ['radius of path', 'circular path', 'mass spectrometer', 'mv/qB', 'radius of curvature', 'cyclotron'],
    when: 'Charged particle moving perpendicular to a uniform magnetic field: the magnetic force provides the centripetal force. Use the MAGNITUDE of q; the sign of q only sets which way it curves.',
    derivation: ['qvB = \\frac{mv^2}{r}', '\\Rightarrow r = \\frac{mv}{qB}'],
    sheet: 'derived',
    hsc: ['Radius of an electron’s path in a magnetic field', 'Mass of an ion in a mass spectrometer', 'Thomson’s charge-to-mass experiment'],
    example: { m: 9.109e-31, v: 2e6, q: 1.602e-19, B: 0.01 },
    priority: 4,
  },
  {
    id: 'mag_period',
    name: 'Period of circular motion in a magnetic field',
    module: 'm6',
    topic: 'particles',
    equation: 'T = \\frac{2\\pi m}{qB}',
    vars: [v('T', 'T', 'Period', 'time', { positive: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), qMag(), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true })],
    solve: {
      T: { expr: '\\frac{2\\pi #m}{#q #B}', fn: ({ m, q, B }) => (2 * PI * m) / (q * B) },
      m: { expr: '\\frac{#q #B #T}{2\\pi}', fn: ({ T, q, B }) => (q * B * T) / (2 * PI) },
      q: { expr: '\\frac{2\\pi #m}{#B #T}', fn: ({ T, m, B }) => (2 * PI * m) / (B * T) },
      B: { expr: '\\frac{2\\pi #m}{#q #T}', fn: ({ T, m, q }) => (2 * PI * m) / (q * T) },
    },
    aliases: ['cyclotron period', 'period in magnetic field', 'time for one revolution'],
    when: 'Time for one orbit of a charged particle in a uniform magnetic field (independent of speed).',
    derivation: ['T = \\frac{2\\pi r}{v},\\; r = \\frac{mv}{qB} \\Rightarrow T = \\frac{2\\pi m}{qB}'],
    sheet: 'derived',
    hsc: ['Time for a proton to complete a semicircle'],
    example: { m: 1.673e-27, q: 1.602e-19, B: 0.5 },
    priority: 2,
  },
  {
    id: 'velocity_selector',
    name: 'Velocity selector (crossed E and B fields)',
    module: 'm6',
    topic: 'particles',
    alsoIn: ['atomic'],
    equation: 'qE = qvB \\Rightarrow v = \\frac{E}{B}',
    vars: [v('v', 'v', 'Speed that passes undeflected', 'velocity', { positive: true }), v('E', 'E', 'Electric field strength', 'efield', { concept: 'Ef', positive: true }), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true })],
    solve: {
      v: { expr: '\\frac{#E}{#B}', fn: ({ E, B }) => E / B },
      E: { expr: '#v #B', fn: ({ v, B }) => v * B },
      B: { expr: '\\frac{#E}{#v}', fn: ({ v, E }) => E / v },
    },
    aliases: ['velocity selector', 'undeflected', 'crossed fields', 'thomson', 'balanced forces', 'E/B'],
    when: 'Perpendicular E and B fields: particles with v = E/B feel equal and opposite forces and pass straight through (Thomson’s experiment).',
    derivation: ['F_E = F_B \\Rightarrow qE = qvB \\Rightarrow v = \\frac{E}{B}'],
    sheet: 'derived',
    hsc: ['Thomson’s measurement of cathode-ray speed', 'Mass spectrometer velocity selector'],
    example: { E: 2e4, B: 0.01 },
    priority: 3,
    contextOnly: ['particles', 'atomic'],
  },
  {
    id: 'thomson_qm',
    name: 'Charge-to-mass ratio (Thomson)',
    module: 'm6',
    topic: 'particles',
    alsoIn: ['atomic'],
    equation: '\\frac{q}{m} = \\frac{v}{Br} = \\frac{E}{B^2 r}',
    vars: [v('qm', '\\frac{q}{m}', 'Charge-to-mass ratio', 'chargeToMass', { positive: true }), v('E', 'E', 'Electric field (velocity selector)', 'efield', { concept: 'Ef', positive: true }), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true }), v('r', 'r', 'Radius of path', 'length', { positive: true })],
    solve: {
      qm: { expr: '\\frac{#E}{#B^2 #r}', fn: ({ E, B, r }) => E / (B * B * r) },
      E: { expr: '#qm #B^2 #r', fn: ({ qm, B, r }) => qm * B * B * r },
      B: { expr: '\\sqrt{\\frac{#E}{#qm #r}}', fn: ({ qm, E, r }) => Math.sqrt(E / (qm * r)) },
      r: { expr: '\\frac{#E}{#qm #B^2}', fn: ({ qm, E, B }) => E / (qm * B * B) },
    },
    aliases: ['charge to mass ratio', 'e/m', 'q/m', 'thomson experiment'],
    when: 'Thomson’s method: speed from a velocity selector (v = E/B), then radius in the B field alone (r = mv/qB).',
    derivation: ['v = \\frac{E}{B},\\quad r = \\frac{mv}{qB} \\Rightarrow \\frac{q}{m} = \\frac{E}{B^2 r}'],
    sheet: 'derived',
    hsc: ['Thomson’s determination of e/m for cathode rays'],
    example: { E: 2e4, B: 0.01, r: 0.0114 },
    priority: 2,
  },
  {
    id: 'qm_from_v',
    name: 'Charge-to-mass ratio from speed and radius',
    module: 'm6',
    topic: 'particles',
    alsoIn: ['atomic'],
    equation: '\\frac{q}{m} = \\frac{v}{Br}',
    vars: [v('qm', '\\frac{q}{m}', 'Charge-to-mass ratio', 'chargeToMass', { positive: true }), v('v', 'v', 'Speed', 'velocity', { positive: true }), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true }), v('r', 'r', 'Radius', 'length', { positive: true })],
    solve: {
      qm: { expr: '\\frac{#v}{#B #r}', fn: ({ v, B, r }) => v / (B * r) },
      v: { expr: '#qm #B #r', fn: ({ qm, B, r }) => qm * B * r },
      B: { expr: '\\frac{#v}{#qm #r}', fn: ({ qm, v, r }) => v / (qm * r) },
      r: { expr: '\\frac{#v}{#qm #B}', fn: ({ qm, v, B }) => v / (qm * B) },
    },
    aliases: ['q/m', 'charge to mass'],
    when: 'From r = mv/(qB).',
    sheet: 'derived',
    hsc: ['e/m of cathode rays'],
    example: { v: 2e6, B: 0.01, r: 1.137e-3 },
    priority: 1,
  },
  // ───────────── Motor effect / magnetic fields ─────────────
  {
    id: 'force_wire',
    name: 'Force on a current-carrying conductor',
    module: 'm6',
    topic: 'motor',
    alsoIn: ['bfields'],
    equation: 'F = lI_{\\perp}B = lIB\\sin\\theta',
    vars: [v('F', 'F', 'Force on conductor', 'force', { nonNegative: true }), v('l', 'l', 'Length of conductor in the field', 'length', { concept: 'lw', positive: true }), v('I', 'I', 'Current', 'current', { positive: true }), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true }), angleIB()],
    solve: {
      F: { expr: '#l #I #B \\sin #th', fn: ({ l, I, B, th }) => l * I * B * Math.sin(th) },
      l: { expr: '\\frac{#F}{#I #B \\sin #th}', fn: ({ F, I, B, th }) => F / (I * B * Math.sin(th)) },
      I: { expr: '\\frac{#F}{#l #B \\sin #th}', fn: ({ F, l, B, th }) => F / (l * B * Math.sin(th)) },
      B: { expr: '\\frac{#F}{#l #I \\sin #th}', fn: ({ F, l, I, th }) => F / (l * I * Math.sin(th)) },
      th: { expr: '\\sin^{-1}\\left(\\frac{#F}{#l #I #B}\\right)', fn: ({ F, l, I, B }) => asin(F / (l * I * B)) },
    },
    aliases: ['motor effect', 'BIL', 'force on wire', 'current carrying conductor', 'lIB sin theta'],
    when: 'Force on a straight conductor carrying current I in a field B. θ is between the conductor (current direction) and B. Direction: right-hand palm rule with conventional current.',
    whenNot: 'No force when the conductor is parallel to B.',
    sheet: 'sheet',
    hsc: ['Force on a wire in a motor', 'Current balance'],
    example: { l: 0.2, I: 5, B: 0.4, th: 90 * DEG },
    priority: 5,
  },
  {
    id: 'parallel_wires',
    name: 'Force between parallel current-carrying wires',
    module: 'm6',
    topic: 'motor',
    alsoIn: ['bfields'],
    equation: '\\frac{F}{l} = \\frac{\\mu_0 I_1 I_2}{2\\pi r}',
    vars: [v('Fl', '\\frac{F}{l}', 'Force per unit length', 'forcePerLength', { positive: true }), mu0Var(), v('I1', 'I_1', 'Current in wire 1', 'current', { positive: true }), v('I2', 'I_2', 'Current in wire 2', 'current', { positive: true }), v('r', 'r', 'Separation of the wires', 'length', { concept: 'rWire', positive: true })],
    solve: {
      Fl: { expr: '\\frac{#mu0 #I1 #I2}{2\\pi #r}', fn: ({ mu0, I1, I2, r }) => (mu0 * I1 * I2) / (2 * PI * r) },
      I1: { expr: '\\frac{2\\pi #r #Fl}{#mu0 #I2}', fn: ({ Fl, mu0, I2, r }) => (2 * PI * r * Fl) / (mu0 * I2) },
      I2: { expr: '\\frac{2\\pi #r #Fl}{#mu0 #I1}', fn: ({ Fl, mu0, I1, r }) => (2 * PI * r * Fl) / (mu0 * I1) },
      r: { expr: '\\frac{#mu0 #I1 #I2}{2\\pi #Fl}', fn: ({ Fl, mu0, I1, I2 }) => (mu0 * I1 * I2) / (2 * PI * Fl) },
    },
    aliases: ['parallel wires', 'parallel conductors', 'ampere', 'force per unit length', 'mu0 I1 I2 / 2 pi r'],
    when: 'Two long parallel conductors: currents in the same direction attract, opposite directions repel. Multiply by l for the total force.',
    sheet: 'sheet',
    hsc: ['Force per metre between two power cables', 'Definition of the ampere'],
    example: { I1: 10, I2: 5, r: 0.02 },
    priority: 4,
  },
  {
    id: 'parallel_wires_total',
    name: 'Total force between parallel wires',
    module: 'm6',
    topic: 'motor',
    equation: 'F = \\frac{\\mu_0 I_1 I_2 l}{2\\pi r}',
    vars: [v('F', 'F', 'Force on length l', 'force', { positive: true }), mu0Var(), v('I1', 'I_1', 'Current 1', 'current', { positive: true }), v('I2', 'I_2', 'Current 2', 'current', { positive: true }), v('l', 'l', 'Length of wires', 'length', { concept: 'lw', positive: true }), v('r', 'r', 'Separation', 'length', { concept: 'rWire', positive: true })],
    solve: {
      F: { expr: '\\frac{#mu0 #I1 #I2 #l}{2\\pi #r}', fn: ({ mu0, I1, I2, l, r }) => (mu0 * I1 * I2 * l) / (2 * PI * r) },
      I1: { expr: '\\frac{2\\pi #r #F}{#mu0 #I2 #l}', fn: ({ F, mu0, I2, l, r }) => (2 * PI * r * F) / (mu0 * I2 * l) },
      I2: { expr: '\\frac{2\\pi #r #F}{#mu0 #I1 #l}', fn: ({ F, mu0, I1, l, r }) => (2 * PI * r * F) / (mu0 * I1 * l) },
      l: { expr: '\\frac{2\\pi #r #F}{#mu0 #I1 #I2}', fn: ({ F, mu0, I1, I2, r }) => (2 * PI * r * F) / (mu0 * I1 * I2) },
      r: { expr: '\\frac{#mu0 #I1 #I2 #l}{2\\pi #F}', fn: ({ F, mu0, I1, I2, l }) => (mu0 * I1 * I2 * l) / (2 * PI * F) },
    },
    aliases: ['parallel wires', 'total force'],
    when: 'Total force on a length l of two parallel conductors.',
    sheet: 'derived',
    hsc: ['Force on 3.0 m of two parallel wires'],
    example: { I1: 10, I2: 5, l: 3, r: 0.02 },
    priority: 2,
  },
  {
    id: 'b_wire',
    name: 'Magnetic field around a long straight wire',
    module: 'm6',
    topic: 'bfields',
    equation: 'B = \\frac{\\mu_0 I}{2\\pi r}',
    vars: [v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true }), mu0Var(), v('I', 'I', 'Current', 'current', { positive: true }), v('r', 'r', 'Distance from the wire', 'length', { concept: 'rWire', positive: true })],
    solve: {
      B: { expr: '\\frac{#mu0 #I}{2\\pi #r}', fn: ({ mu0, I, r }) => (mu0 * I) / (2 * PI * r) },
      I: { expr: '\\frac{2\\pi #r #B}{#mu0}', fn: ({ B, mu0, r }) => (2 * PI * r * B) / mu0 },
      r: { expr: '\\frac{#mu0 #I}{2\\pi #B}', fn: ({ B, mu0, I }) => (mu0 * I) / (2 * PI * B) },
    },
    aliases: ['field of a wire', 'straight conductor', 'right hand grip', 'mu0 I / 2 pi r'],
    when: 'Field circling a long straight current (right-hand grip rule). Year 11 sheet relationship used in Module 6 questions.',
    sheet: 'y11',
    hsc: ['Field 5 cm from a wire carrying 10 A'],
    example: { I: 10, r: 0.05 },
    priority: 3,
  },
  {
    id: 'b_solenoid',
    name: 'Magnetic field inside a solenoid',
    module: 'm6',
    topic: 'bfields',
    equation: 'B = \\frac{\\mu_0 NI}{L}',
    vars: [v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true }), mu0Var(), v('N', 'N', 'Number of turns', 'count', { concept: 'N', positive: true }), v('I', 'I', 'Current', 'current', { positive: true }), v('L', 'L', 'Length of solenoid', 'length', { concept: 'Lsol', positive: true })],
    solve: {
      B: { expr: '\\frac{#mu0 #N #I}{#L}', fn: ({ mu0, N, I, L }) => (mu0 * N * I) / L },
      N: { expr: '\\frac{#B #L}{#mu0 #I}', fn: ({ B, mu0, I, L }) => (B * L) / (mu0 * I) },
      I: { expr: '\\frac{#B #L}{#mu0 #N}', fn: ({ B, mu0, N, L }) => (B * L) / (mu0 * N) },
      L: { expr: '\\frac{#mu0 #N #I}{#B}', fn: ({ B, mu0, N, I }) => (mu0 * N * I) / B },
    },
    aliases: ['solenoid', 'coil field', 'electromagnet'],
    when: 'Uniform field inside a long solenoid (Year 11 sheet relationship).',
    sheet: 'y11',
    hsc: ['Field inside a solenoid used to induce an emf'],
    example: { N: 500, I: 2, L: 0.25 },
    priority: 2,
  },
  {
    id: 'motor_torque',
    name: 'Torque on a current-carrying coil (DC motor)',
    module: 'm6',
    topic: 'motor',
    alsoIn: ['torque'],
    equation: '\\tau = nIA_{\\perp}B = nIAB\\sin\\theta',
    vars: [v('tau', '\\tau', 'Torque', 'torque', { nonNegative: true }), v('n', 'n', 'Number of turns', 'count', { concept: 'N', positive: true }), v('I', 'I', 'Current', 'current', { positive: true }), v('A', 'A', 'Area of coil', 'area', { positive: true }), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true }), angleN()],
    solve: {
      tau: { expr: '#n #I #A #B \\sin #th', fn: ({ n, I, A, B, th }) => n * I * A * B * Math.sin(th) },
      n: { expr: '\\frac{#tau}{#I #A #B \\sin #th}', fn: ({ tau, I, A, B, th }) => tau / (I * A * B * Math.sin(th)) },
      I: { expr: '\\frac{#tau}{#n #A #B \\sin #th}', fn: ({ tau, n, A, B, th }) => tau / (n * A * B * Math.sin(th)) },
      A: { expr: '\\frac{#tau}{#n #I #B \\sin #th}', fn: ({ tau, n, I, B, th }) => tau / (n * I * B * Math.sin(th)) },
      B: { expr: '\\frac{#tau}{#n #I #A \\sin #th}', fn: ({ tau, n, I, A, th }) => tau / (n * I * A * Math.sin(th)) },
      th: { expr: '\\sin^{-1}\\left(\\frac{#tau}{#n #I #A #B}\\right)', fn: ({ tau, n, I, A, B }) => asin(tau / (n * I * A * B)) },
    },
    aliases: ['motor torque', 'torque on coil', 'DC motor', 'nIAB', 'coil in magnetic field'],
    when: 'Torque on a rectangular coil in a uniform field. θ is between B and the NORMAL to the coil: maximum torque when the plane of the coil is parallel to B (θ = 90°), zero when the plane is perpendicular to B.',
    whenNot: 'If the angle given is between B and the PLANE of the coil, use θ = 90° − (that angle).',
    derivation: ['\\tau = 2 \\times F\\frac{w}{2}\\sin\\theta = (nIlB)w\\sin\\theta = nIAB\\sin\\theta'],
    sheet: 'sheet',
    hsc: ['Maximum torque of a DC motor', 'Torque when the coil has rotated 30°'],
    example: { n: 100, I: 2, A: 0.01, B: 0.5, th: 90 * DEG },
    priority: 4,
  },
  {
    id: 'back_emf',
    name: 'Back emf in a DC motor',
    module: 'm6',
    topic: 'motor',
    equation: 'I = \\frac{V - \\varepsilon_{back}}{R}',
    vars: [v('I', 'I', 'Current in the coil', 'current', { nonNegative: true }), v('V', 'V', 'Supply voltage', 'voltage', { concept: 'Vsupply', positive: true }), v('eb', '\\varepsilon_{back}', 'Back emf', 'voltage', { concept: 'emfBack', nonNegative: true }), v('R', 'R', 'Coil resistance', 'resistance', { positive: true })],
    solve: {
      I: { expr: '\\frac{#V - #eb}{#R}', fn: ({ V, eb, R }) => (V - eb) / R },
      V: { expr: '#I #R + #eb', fn: ({ I, eb, R }) => I * R + eb },
      eb: { expr: '#V - #I #R', fn: ({ I, V, R }) => V - I * R },
      R: { expr: '\\frac{#V - #eb}{#I}', fn: ({ I, V, eb }) => (V - eb) / I },
    },
    aliases: ['back emf', 'counter emf', 'motor current', 'starting current'],
    when: 'A spinning motor coil generates a back emf opposing the supply (Lenz’s law), so the current falls as speed rises. At start-up ε_back = 0.',
    sheet: 'syllabus',
    hsc: ['Current in a motor at full speed vs at start-up'],
    example: { V: 12, eb: 10, R: 2 },
    priority: 2,
  },
  // ───────────── Electromagnetic induction ─────────────
  {
    id: 'flux',
    name: 'Magnetic flux',
    module: 'm6',
    topic: 'induction',
    equation: '\\Phi = B_{\\parallel}A = BA\\cos\\theta',
    vars: [v('Phi', '\\Phi', 'Magnetic flux', 'flux', { signed: true }), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true }), v('A', 'A', 'Area', 'area', { positive: true }), angleN()],
    solve: {
      Phi: { expr: '#B #A \\cos #th', fn: ({ B, A, th }) => B * A * Math.cos(th) },
      B: { expr: '\\frac{#Phi}{#A \\cos #th}', fn: ({ Phi, A, th }) => Phi / (A * Math.cos(th)) },
      A: { expr: '\\frac{#Phi}{#B \\cos #th}', fn: ({ Phi, B, th }) => Phi / (B * Math.cos(th)) },
      th: { expr: '\\cos^{-1}\\left(\\frac{#Phi}{#B #A}\\right)', fn: ({ Phi, B, A }) => acos(Phi / (B * A)) },
    },
    aliases: ['magnetic flux', 'flux', 'BA cos theta', 'weber'],
    when: 'Flux through an area A. θ is between B and the NORMAL to the area: flux is maximum (BA) when the field passes straight through the loop (θ = 0), zero when the field lies in the plane of the loop (θ = 90°).',
    whenNot: 'If the angle is given between B and the PLANE of the loop, use θ = 90° − angle (or Φ = BA sin(angle to plane)).',
    sheet: 'sheet',
    hsc: ['Flux through a coil tilted at 30°', 'Change in flux as a coil rotates'],
    example: { B: 0.5, A: 0.02, th: 0 },
    priority: 5,
  },
  {
    id: 'faraday',
    name: "Faraday's law of induction",
    module: 'm6',
    topic: 'induction',
    equation: '\\varepsilon = -N\\frac{\\Delta\\Phi}{\\Delta t}',
    vars: [v('emf', '\\varepsilon', 'Induced emf (magnitude)', 'voltage', { concept: 'emf', nonNegative: true }), v('N', 'N', 'Number of turns', 'count', { positive: true }), v('dPhi', '\\Delta\\Phi', 'Change in flux (magnitude)', 'flux', { concept: 'dPhi', positive: true }), v('dt', '\\Delta t', 'Time interval', 'time', { positive: true, concept: 't' })],
    solve: {
      emf: { expr: '#N \\frac{#dPhi}{#dt}', fn: ({ N, dPhi, dt }) => (N * dPhi) / dt, note: 'magnitude; the minus sign (Lenz’s law) gives the direction' },
      N: { expr: '\\frac{#emf #dt}{#dPhi}', fn: ({ emf, dPhi, dt }) => (emf * dt) / dPhi },
      dPhi: { expr: '\\frac{#emf #dt}{#N}', fn: ({ emf, N, dt }) => (emf * dt) / N },
      dt: { expr: '\\frac{#N #dPhi}{#emf}', fn: ({ emf, N, dPhi }) => (N * dPhi) / emf },
    },
    aliases: ["faraday's law", 'faraday', 'induced emf', 'electromagnetic induction', 'rate of change of flux', 'lenz'],
    when: 'Average emf induced in a coil of N turns when the flux through it changes by ΔΦ in Δt. The minus sign is Lenz’s law: the induced current opposes the change in flux. It tells you the DIRECTION, not a negative voltage.',
    whenNot: 'ΔΦ = Φ_final − Φ_initial — not just the final flux.',
    sheet: 'sheet',
    hsc: ['Average emf when a magnet is pushed into a coil', 'emf when a coil is rotated a quarter turn', 'emf when B is switched off'],
    example: { N: 200, dPhi: 0.01, dt: 0.05 },
    priority: 5,
  },
  {
    id: 'flux_change',
    name: 'Change in magnetic flux',
    module: 'm6',
    topic: 'induction',
    equation: '\\Delta\\Phi = \\Phi_f - \\Phi_i',
    vars: [v('dPhi', '\\Delta\\Phi', 'Change in flux', 'flux', { concept: 'dPhi', signed: true }), v('Pf', '\\Phi_f', 'Final flux', 'flux', { concept: 'PhiF', signed: true }), v('Pi', '\\Phi_i', 'Initial flux', 'flux', { concept: 'PhiI', signed: true })],
    solve: {
      dPhi: { expr: '#Pf - #Pi', fn: ({ Pf, Pi }) => Pf - Pi },
      Pf: { expr: '#Pi + #dPhi', fn: ({ Pi, dPhi }) => Pi + dPhi },
      Pi: { expr: '#Pf - #dPhi', fn: ({ Pf, dPhi }) => Pf - dPhi },
    },
    aliases: ['change in flux', 'delta phi'],
    when: 'Flux change for Faraday’s law. A change of B, of A or of orientation all change Φ.',
    sheet: 'derived',
    hsc: ['Coil rotated from perpendicular to parallel to the field'],
    example: { Pf: 0, Pi: 0.01 },
    priority: 3,
  },
  {
    id: 'motional_emf',
    name: 'EMF of a conductor moving through a field',
    module: 'm6',
    topic: 'induction',
    equation: '\\varepsilon = lvB',
    vars: [v('emf', '\\varepsilon', 'Induced emf', 'voltage', { concept: 'emf', nonNegative: true }), v('l', 'l', 'Length of conductor', 'length', { concept: 'lw', positive: true }), v('v', 'v', 'Speed (perpendicular to B)', 'velocity', { positive: true }), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true })],
    solve: {
      emf: { expr: '#l #v #B', fn: ({ l, v, B }) => l * v * B },
      l: { expr: '\\frac{#emf}{#v #B}', fn: ({ emf, v, B }) => emf / (v * B) },
      v: { expr: '\\frac{#emf}{#l #B}', fn: ({ emf, l, B }) => emf / (l * B) },
      B: { expr: '\\frac{#emf}{#l #v}', fn: ({ emf, l, v }) => emf / (l * v) },
    },
    aliases: ['moving rod', 'sliding rod', 'rails', 'motional emf', 'Blv', 'wing tip'],
    when: 'A straight conductor moving perpendicular to a uniform field sweeps out area at rate lv, so ε = BΔA/Δt = Blv.',
    derivation: ['\\varepsilon = \\frac{\\Delta\\Phi}{\\Delta t} = \\frac{B\\,\\Delta A}{\\Delta t} = \\frac{B\\,l\\,v\\Delta t}{\\Delta t} = Blv'],
    sheet: 'derived',
    hsc: ['emf across a rod sliding on rails'],
    example: { l: 0.5, v: 4, B: 0.2 },
    priority: 2,
  },
  {
    id: 'induced_current',
    name: 'Induced current (Ohm’s law)',
    module: 'm6',
    topic: 'induction',
    equation: 'I = \\frac{\\varepsilon}{R}',
    vars: [v('I', 'I', 'Induced current', 'current', { nonNegative: true }), v('emf', '\\varepsilon', 'Induced emf', 'voltage', { concept: 'emf', nonNegative: true }), v('R', 'R', 'Resistance of circuit', 'resistance', { positive: true })],
    solve: {
      I: { expr: '\\frac{#emf}{#R}', fn: ({ emf, R }) => emf / R },
      emf: { expr: '#I #R', fn: ({ I, R }) => I * R },
      R: { expr: '\\frac{#emf}{#I}', fn: ({ I, emf }) => emf / I },
    },
    aliases: ['induced current', 'ohm'],
    when: 'Current driven by an induced emf around a circuit of resistance R.',
    sheet: 'y11',
    hsc: ['Current in a coil after a magnet is inserted'],
    example: { emf: 3, R: 6 },
    priority: 2,
  },
  {
    id: 'generator_avg',
    name: 'Generator — average emf over a quarter turn',
    module: 'm6',
    topic: 'induction',
    equation: '\\varepsilon_{avg} = \\frac{NBA}{T/4} = 4NBAf',
    vars: [v('emf', '\\varepsilon_{avg}', 'Average emf (quarter turn)', 'voltage', { concept: 'emf', positive: true }), v('N', 'N', 'Number of turns', 'count', { positive: true }), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true }), v('A', 'A', 'Area of coil', 'area', { positive: true }), v('f', 'f', 'Rotation frequency', 'frequency', { positive: true })],
    solve: {
      emf: { expr: '4 #N #B #A #f', fn: ({ N, B, A, f }) => 4 * N * B * A * f },
      N: { expr: '\\frac{#emf}{4 #B #A #f}', fn: ({ emf, B, A, f }) => emf / (4 * B * A * f) },
      B: { expr: '\\frac{#emf}{4 #N #A #f}', fn: ({ emf, N, A, f }) => emf / (4 * N * A * f) },
      A: { expr: '\\frac{#emf}{4 #N #B #f}', fn: ({ emf, N, B, f }) => emf / (4 * N * B * f) },
      f: { expr: '\\frac{#emf}{4 #N #B #A}', fn: ({ emf, N, B, A }) => emf / (4 * N * B * A) },
    },
    aliases: ['generator', 'AC generator', 'rotating coil', 'alternator', 'average emf'],
    when: 'A coil rotating in a uniform field: the flux changes from BA to 0 in a quarter of a period, so Faraday’s law gives the average emf over that quarter turn.',
    derivation: ['\\Delta\\Phi = BA - 0,\\quad \\Delta t = \\frac{T}{4} = \\frac{1}{4f}', '\\varepsilon_{avg} = N\\frac{\\Delta\\Phi}{\\Delta t} = 4NBAf'],
    sheet: 'derived',
    hsc: ['Average emf of a generator coil rotating at 50 Hz'],
    example: { N: 100, B: 0.2, A: 0.01, f: 50 },
    priority: 2,
    contextOnly: ['induction'],
  },
  {
    id: 'generator_peak',
    name: 'Generator — peak emf',
    module: 'm6',
    topic: 'induction',
    equation: '\\varepsilon_{max} = NBA\\omega',
    vars: [v('emf', '\\varepsilon_{max}', 'Peak emf', 'voltage', { concept: 'emfPeak', positive: true }), v('N', 'N', 'Number of turns', 'count', { positive: true }), v('B', 'B', 'Magnetic field strength', 'bfield', { positive: true }), v('A', 'A', 'Area of coil', 'area', { positive: true }), v('w', '\\omega', 'Angular velocity', 'angularVelocity', { concept: 'omega', positive: true })],
    solve: {
      emf: { expr: '#N #B #A #w', fn: ({ N, B, A, w }) => N * B * A * w },
      N: { expr: '\\frac{#emf}{#B #A #w}', fn: ({ emf, B, A, w }) => emf / (B * A * w) },
      B: { expr: '\\frac{#emf}{#N #A #w}', fn: ({ emf, N, A, w }) => emf / (N * A * w) },
      A: { expr: '\\frac{#emf}{#N #B #w}', fn: ({ emf, N, B, w }) => emf / (N * B * w) },
      w: { expr: '\\frac{#emf}{#N #B #A}', fn: ({ emf, N, B, A }) => emf / (N * B * A) },
    },
    aliases: ['peak emf', 'maximum emf', 'NBA omega'],
    when: 'Maximum instantaneous emf of a rotating coil (when the plane of the coil is parallel to B). Needs calculus to derive — beyond the HSC formula sheet.',
    sheet: 'extension',
    hsc: [],
    example: { N: 100, B: 0.2, A: 0.01, w: 314 },
    priority: 0,
    manualOnly: true,
  },
  // ───────────── Transformers & power transmission ─────────────
  {
    id: 'transformer_v',
    name: 'Transformer turns ratio',
    module: 'm6',
    topic: 'transformers',
    equation: '\\frac{V_p}{V_s} = \\frac{N_p}{N_s}',
    vars: [v('Vs', 'V_s', 'Secondary voltage', 'voltage', { positive: true }), v('Vp', 'V_p', 'Primary voltage', 'voltage', { positive: true }), v('Np', 'N_p', 'Primary turns', 'count', { positive: true }), v('Ns', 'N_s', 'Secondary turns', 'count', { positive: true })],
    solve: {
      Vs: { expr: '#Vp \\frac{#Ns}{#Np}', fn: ({ Vp, Np, Ns }) => (Vp * Ns) / Np },
      Vp: { expr: '#Vs \\frac{#Np}{#Ns}', fn: ({ Vs, Np, Ns }) => (Vs * Np) / Ns },
      Np: { expr: '#Ns \\frac{#Vp}{#Vs}', fn: ({ Vs, Vp, Ns }) => (Ns * Vp) / Vs },
      Ns: { expr: '#Np \\frac{#Vs}{#Vp}', fn: ({ Vs, Vp, Np }) => (Np * Vs) / Vp },
    },
    aliases: ['transformer', 'turns ratio', 'step up', 'step down', 'Vp/Vs'],
    when: 'Ideal transformer (all flux links both coils). Step-up: Ns > Np. Works only with AC (changing flux).',
    sheet: 'sheet',
    hsc: ['Secondary voltage of a step-down transformer', 'Number of turns needed on the secondary'],
    example: { Vp: 240, Np: 1000, Ns: 50 },
    priority: 5,
  },
  {
    id: 'transformer_p',
    name: 'Ideal transformer power',
    module: 'm6',
    topic: 'transformers',
    equation: 'V_pI_p = V_sI_s',
    vars: [v('Is', 'I_s', 'Secondary current', 'current', { positive: true }), v('Vp', 'V_p', 'Primary voltage', 'voltage', { positive: true }), v('Ip', 'I_p', 'Primary current', 'current', { positive: true }), v('Vs', 'V_s', 'Secondary voltage', 'voltage', { positive: true })],
    solve: {
      Is: { expr: '\\frac{#Vp #Ip}{#Vs}', fn: ({ Vp, Ip, Vs }) => (Vp * Ip) / Vs },
      Vp: { expr: '\\frac{#Vs #Is}{#Ip}', fn: ({ Is, Ip, Vs }) => (Vs * Is) / Ip },
      Ip: { expr: '\\frac{#Vs #Is}{#Vp}', fn: ({ Is, Vp, Vs }) => (Vs * Is) / Vp },
      Vs: { expr: '\\frac{#Vp #Ip}{#Is}', fn: ({ Is, Vp, Ip }) => (Vp * Ip) / Is },
    },
    aliases: ['transformer current', 'power in = power out', 'VpIp = VsIs'],
    when: 'Ideal (100 % efficient) transformer: power in = power out, so stepping voltage up steps current down.',
    whenNot: 'Not for a real transformer with stated losses — use the efficiency formula.',
    sheet: 'sheet',
    hsc: ['Primary current drawn by a transformer'],
    example: { Vp: 240, Ip: 0.5, Vs: 12 },
    priority: 4,
  },
  {
    id: 'transformer_i',
    name: 'Transformer current ratio',
    module: 'm6',
    topic: 'transformers',
    equation: '\\frac{I_p}{I_s} = \\frac{N_s}{N_p}',
    vars: [v('Is', 'I_s', 'Secondary current', 'current', { positive: true }), v('Ip', 'I_p', 'Primary current', 'current', { positive: true }), v('Np', 'N_p', 'Primary turns', 'count', { positive: true }), v('Ns', 'N_s', 'Secondary turns', 'count', { positive: true })],
    solve: {
      Is: { expr: '#Ip \\frac{#Np}{#Ns}', fn: ({ Ip, Np, Ns }) => (Ip * Np) / Ns },
      Ip: { expr: '#Is \\frac{#Ns}{#Np}', fn: ({ Is, Np, Ns }) => (Is * Ns) / Np },
      Np: { expr: '#Ns \\frac{#Is}{#Ip}', fn: ({ Is, Ip, Ns }) => (Ns * Is) / Ip },
      Ns: { expr: '#Np \\frac{#Ip}{#Is}', fn: ({ Is, Ip, Np }) => (Np * Ip) / Is },
    },
    aliases: ['current ratio', 'transformer current'],
    when: 'Ideal transformer: combine V_p/V_s = N_p/N_s with V_pI_p = V_sI_s.',
    derivation: ['\\frac{I_p}{I_s} = \\frac{V_s}{V_p} = \\frac{N_s}{N_p}'],
    sheet: 'derived',
    hsc: ['Secondary current from turns and primary current'],
    example: { Ip: 0.5, Np: 1000, Ns: 50 },
    priority: 3,
  },
  {
    id: 'transformer_eff',
    name: 'Transformer efficiency',
    module: 'm6',
    topic: 'transformers',
    equation: '\\eta = \\frac{P_s}{P_p} = \\frac{V_sI_s}{V_pI_p}',
    vars: [v('eta', '\\eta', 'Efficiency', 'percent', { min: 0, max: 1 }), v('Ps', 'P_s', 'Output (secondary) power', 'power', { positive: true }), v('Pp', 'P_p', 'Input (primary) power', 'power', { positive: true })],
    solve: {
      eta: { expr: '\\frac{#Ps}{#Pp}', fn: ({ Ps, Pp }) => Ps / Pp },
      Ps: { expr: '#eta #Pp', fn: ({ eta, Pp }) => eta * Pp },
      Pp: { expr: '\\frac{#Ps}{#eta}', fn: ({ eta, Ps }) => Ps / eta },
    },
    aliases: ['efficiency', 'real transformer', 'energy loss', 'eddy currents'],
    when: 'Real transformers lose energy (eddy currents, resistive heating, flux leakage) so P_s < P_p.',
    checks: ({ eta }) => (eta > 1 ? [{ level: 'error', message: 'Efficiency above 100 % is impossible — output power cannot exceed input power.' }] : []),
    sheet: 'syllabus',
    hsc: ['Efficiency of a transformer from measured primary and secondary values'],
    example: { Ps: 950, Pp: 1000 },
    priority: 3,
  },
  {
    id: 'power_vi',
    name: 'Electrical power',
    module: 'm6',
    topic: 'transformers',
    equation: 'P = VI',
    vars: [v('P', 'P', 'Power', 'power', { positive: true }), v('V', 'V', 'Voltage', 'voltage', { positive: true }), v('I', 'I', 'Current', 'current', { positive: true })],
    solve: {
      P: { expr: '#V #I', fn: ({ V, I }) => V * I },
      V: { expr: '\\frac{#P}{#I}', fn: ({ P, I }) => P / I },
      I: { expr: '\\frac{#P}{#V}', fn: ({ P, V }) => P / V },
    },
    aliases: ['power', 'P = VI', 'transmission current'],
    when: 'Power delivered by a current I at voltage V. For transmission, I = P/V — higher voltage means lower current.',
    sheet: 'y11',
    hsc: ['Current in a transmission line carrying 100 MW at 330 kV'],
    example: { V: 240, I: 5 },
    priority: 3,
  },
  {
    id: 'ohm',
    name: "Ohm's law",
    module: 'm6',
    topic: 'transformers',
    equation: 'V = IR',
    vars: [v('V', 'V', 'Voltage (drop)', 'voltage', { positive: true }), v('I', 'I', 'Current', 'current', { positive: true }), v('R', 'R', 'Resistance', 'resistance', { positive: true })],
    solve: {
      V: { expr: '#I #R', fn: ({ I, R }) => I * R },
      I: { expr: '\\frac{#V}{#R}', fn: ({ V, R }) => V / R },
      R: { expr: '\\frac{#V}{#I}', fn: ({ V, I }) => V / I },
    },
    aliases: ['ohm', 'voltage drop', 'V = IR', 'resistance'],
    when: 'Voltage across a resistance (e.g. the voltage drop along a transmission line).',
    sheet: 'y11',
    hsc: ['Voltage drop across transmission lines'],
    example: { I: 2, R: 6 },
    priority: 2,
  },
  {
    id: 'power_loss',
    name: 'Power loss in a conductor',
    module: 'm6',
    topic: 'transformers',
    equation: 'P_{loss} = I^2R',
    vars: [v('Pl', 'P_{loss}', 'Power lost as heat', 'power', { concept: 'Ploss', nonNegative: true }), v('I', 'I', 'Current', 'current', { positive: true }), v('R', 'R', 'Resistance of the lines', 'resistance', { positive: true })],
    solve: {
      Pl: { expr: '#I^2 #R', fn: ({ I, R }) => I * I * R },
      I: { expr: '\\sqrt{\\frac{#Pl}{#R}}', fn: ({ Pl, R }) => Math.sqrt(Pl / R) },
      R: { expr: '\\frac{#Pl}{#I^2}', fn: ({ Pl, I }) => Pl / (I * I) },
    },
    aliases: ['power loss', 'I^2R', 'transmission loss', 'heating loss'],
    when: 'Resistive heating in transmission lines. Stepping up the voltage lowers I, so losses fall with I².',
    derivation: ['P = VI,\\; V = IR \\Rightarrow P = I^2R'],
    sheet: 'y11',
    hsc: ['Power lost in lines at 11 kV vs 330 kV'],
    example: { I: 300, R: 2 },
    priority: 3,
  },
];
