/**
 * Module 7 — The Nature of Light.
 * Waves and EM radiation, refraction, polarisation (Malus), interference and diffraction,
 * black-body radiation, photons, the photoelectric effect and special relativity.
 */
import { NESA } from '../constants';
import { acos, asin, bVar, belowC, cVar, DEG, eps0Var, hVar, mu0Var, sq } from './common';
import { FormulaDef, v } from './types';

const PI = Math.PI;
const C = NESA.c.value;
const gammaOf = (vv: number, c: number) => 1 / Math.sqrt(1 - (vv * vv) / (c * c));
const vFromGamma = (g: number, c: number) => (g < 1 ? NaN : c * Math.sqrt(1 - 1 / (g * g)));
const relV = () => v('v', 'v', 'Speed of the moving object/frame', 'velocity', { positive: true, ...belowC });

export const m7Formulas: FormulaDef[] = [
  // ───────────── Waves ─────────────
  {
    id: 'wave_eq',
    name: 'Wave equation',
    module: 'm7',
    topic: 'waves',
    equation: 'v = f\\lambda',
    vars: [v('v', 'v', 'Wave speed', 'velocity', { positive: true }), v('f', 'f', 'Frequency', 'frequency', { positive: true }), v('lam', '\\lambda', 'Wavelength', 'wavelength', { concept: 'lambda', positive: true })],
    solve: {
      v: { expr: '#f #lam', fn: ({ f, lam }) => f * lam },
      f: { expr: '\\frac{#v}{#lam}', fn: ({ v, lam }) => v / lam },
      lam: { expr: '\\frac{#v}{#f}', fn: ({ v, f }) => v / f },
    },
    aliases: ['wave equation', 'v = f lambda', 'wave speed', 'sound', 'frequency wavelength'],
    when: 'Any wave (sound, water, light in a medium).',
    sheet: 'sheet',
    hsc: ['Wavelength of a sound wave', 'Speed of light in glass from f and λ'],
    example: { f: 440, lam: 0.773 },
    priority: 3,
    contextOnly: ['waves'],
  },
  {
    id: 'light_eq',
    name: 'Speed of light (EM waves)',
    module: 'm7',
    topic: 'emr',
    alsoIn: ['waves', 'quantumLight'],
    equation: 'c = f\\lambda',
    vars: [v('f', 'f', 'Frequency', 'frequency', { positive: true }), cVar(), v('lam', '\\lambda', 'Wavelength', 'wavelength', { concept: 'lambda', positive: true })],
    solve: {
      f: { expr: '\\frac{#c}{#lam}', fn: ({ c, lam }) => c / lam },
      lam: { expr: '\\frac{#c}{#f}', fn: ({ c, f }) => c / f },
      c: { expr: '#f #lam', fn: ({ f, lam }) => f * lam },
    },
    aliases: ['c = f lambda', 'electromagnetic wave', 'light', 'frequency of light', 'wavelength of light', 'radio', 'x-ray', 'gamma', 'microwave'],
    when: 'All EM radiation in a vacuum (or air) travels at c = 3.00 × 10⁸ m s⁻¹.',
    whenNot: 'In a medium use v = c/n.',
    sheet: 'sheet',
    hsc: ['Frequency of 500 nm light', 'Wavelength of a 100 MHz radio wave'],
    example: { lam: 5e-7 },
    priority: 5,
  },
  {
    id: 'refr_index',
    name: 'Refractive index',
    module: 'm7',
    topic: 'waves',
    equation: 'n = \\frac{c}{v}',
    vars: [v('n', 'n', 'Refractive index', 'ratio', { min: 1 }), cVar(), v('v', 'v', 'Speed of light in the medium', 'velocity', { positive: true, max: C })],
    solve: {
      n: { expr: '\\frac{#c}{#v}', fn: ({ c, v }) => c / v },
      v: { expr: '\\frac{#c}{#n}', fn: ({ c, n }) => c / n },
    },
    aliases: ['refractive index', 'speed of light in glass', 'n = c/v', 'optical density'],
    when: 'Speed of light in a transparent medium. n ≥ 1.',
    sheet: 'sheet',
    hsc: ['Speed of light in water (n = 1.33)'],
    example: { v: 2e8 },
    priority: 4,
  },
  {
    id: 'snell',
    name: "Snell's law",
    module: 'm7',
    topic: 'waves',
    equation: 'n_1\\sin\\theta_1 = n_2\\sin\\theta_2',
    vars: [v('th2', '\\theta_2', 'Angle of refraction (to the normal)', 'angle', { concept: 'theta2', min: 0, max: PI / 2 }), v('n1', 'n_1', 'Refractive index of medium 1', 'ratio', { positive: true }), v('th1', '\\theta_1', 'Angle of incidence (to the normal)', 'angle', { concept: 'theta1', min: 0, max: PI / 2 }), v('n2', 'n_2', 'Refractive index of medium 2', 'ratio', { positive: true })],
    solve: {
      th2: { expr: '\\sin^{-1}\\left(\\frac{#n1 \\sin #th1}{#n2}\\right)', fn: ({ n1, th1, n2 }) => asin((n1 * Math.sin(th1)) / n2), note: 'no solution means total internal reflection' },
      n1: { expr: '\\frac{#n2 \\sin #th2}{\\sin #th1}', fn: ({ th2, th1, n2 }) => (n2 * Math.sin(th2)) / Math.sin(th1) },
      th1: { expr: '\\sin^{-1}\\left(\\frac{#n2 \\sin #th2}{#n1}\\right)', fn: ({ th2, n1, n2 }) => asin((n2 * Math.sin(th2)) / n1) },
      n2: { expr: '\\frac{#n1 \\sin #th1}{\\sin #th2}', fn: ({ th2, n1, th1 }) => (n1 * Math.sin(th1)) / Math.sin(th2) },
    },
    aliases: ["snell's law", 'refraction', 'angle of refraction', 'angle of incidence'],
    when: 'Refraction at a boundary. Angles are measured from the NORMAL. Air: n ≈ 1.00.',
    whenNot: 'If n₁ sin θ₁ / n₂ > 1 there is no refracted ray (total internal reflection).',
    sheet: 'sheet',
    hsc: ['Angle of refraction entering glass', 'Refractive index from measured angles'],
    example: { n1: 1.0, th1: 40 * DEG, n2: 1.5 },
    priority: 4,
  },
  {
    id: 'critical_angle',
    name: 'Critical angle',
    module: 'm7',
    topic: 'waves',
    equation: '\\sin\\theta_c = \\frac{n_2}{n_1}',
    vars: [v('thc', '\\theta_c', 'Critical angle', 'angle', { concept: 'thetaC', min: 0, max: PI / 2 }), v('n2', 'n_2', 'Refractive index of the less dense medium', 'ratio', { positive: true }), v('n1', 'n_1', 'Refractive index of the denser medium', 'ratio', { positive: true })],
    solve: {
      thc: { expr: '\\sin^{-1}\\left(\\frac{#n2}{#n1}\\right)', fn: ({ n2, n1 }) => asin(n2 / n1) },
      n2: { expr: '#n1 \\sin #thc', fn: ({ thc, n1 }) => n1 * Math.sin(thc) },
      n1: { expr: '\\frac{#n2}{\\sin #thc}', fn: ({ thc, n2 }) => n2 / Math.sin(thc) },
    },
    aliases: ['critical angle', 'total internal reflection', 'TIR', 'optical fibre'],
    when: 'Light travelling from a denser (n₁) to a less dense (n₂) medium; θ₂ = 90° in Snell’s law. TIR occurs for incidence angles greater than θc.',
    whenNot: 'No critical angle exists when n₂ ≥ n₁.',
    derivation: ['n_1\\sin\\theta_c = n_2\\sin 90^\\circ \\Rightarrow \\sin\\theta_c = \\frac{n_2}{n_1}'],
    checks: ({ n1, n2 }) => (n2 >= n1 ? [{ level: 'error', message: 'No critical angle: total internal reflection needs light going from a higher to a lower refractive index (n₁ > n₂).' }] : []),
    sheet: 'derived',
    hsc: ['Critical angle of glass–air boundary', 'Optical fibre core/cladding'],
    example: { n2: 1.0, n1: 1.5 },
    priority: 3,
  },
  {
    id: 'lambda_medium',
    name: 'Wavelength in a medium',
    module: 'm7',
    topic: 'waves',
    equation: '\\lambda_n = \\frac{\\lambda}{n}',
    vars: [v('ln', '\\lambda_n', 'Wavelength in the medium', 'wavelength', { concept: 'lambdaN', positive: true }), v('lam', '\\lambda', 'Wavelength in vacuum', 'wavelength', { concept: 'lambda', positive: true }), v('n', 'n', 'Refractive index', 'ratio', { min: 1 })],
    solve: {
      ln: { expr: '\\frac{#lam}{#n}', fn: ({ lam, n }) => lam / n },
      lam: { expr: '#ln #n', fn: ({ ln, n }) => ln * n },
      n: { expr: '\\frac{#lam}{#ln}', fn: ({ ln, lam }) => lam / ln },
    },
    aliases: ['wavelength in glass', 'wavelength in water'],
    when: 'Frequency is unchanged on refraction, so λ shrinks by the factor n.',
    derivation: ['f\\text{ constant},\\; v = \\frac{c}{n} \\Rightarrow \\lambda_n = \\frac{v}{f} = \\frac{\\lambda}{n}'],
    sheet: 'derived',
    hsc: ['Wavelength of laser light inside glass'],
    example: { lam: 6.33e-7, n: 1.5 },
    priority: 1,
  },
  // ───────────── EM radiation & polarisation ─────────────
  {
    id: 'maxwell_c',
    name: 'Maxwell’s prediction of the speed of light',
    module: 'm7',
    topic: 'emr',
    equation: 'c = \\frac{1}{\\sqrt{\\mu_0\\varepsilon_0}}',
    vars: [v('cc', 'c', 'Speed of EM waves', 'velocity', { concept: 'cPred', positive: true }), mu0Var(), eps0Var()],
    solve: {
      cc: { expr: '\\frac{1}{\\sqrt{#mu0 #eps0}}', fn: ({ mu0, eps0 }) => 1 / Math.sqrt(mu0 * eps0) },
      eps0: { expr: '\\frac{1}{#mu0 #cc^2}', fn: ({ cc, mu0 }) => 1 / (mu0 * cc * cc) },
      mu0: { expr: '\\frac{1}{#eps0 #cc^2}', fn: ({ cc, eps0 }) => 1 / (eps0 * cc * cc) },
    },
    aliases: ['maxwell', 'speed of light prediction', 'permittivity permeability', 'electromagnetic wave speed'],
    when: 'Maxwell predicted EM waves travel at 1/√(μ₀ε₀), which matched the measured speed of light — evidence that light is an EM wave.',
    sheet: 'syllabus',
    hsc: ['Show that Maxwell’s prediction gives 3.00 × 10⁸ m s⁻¹'],
    example: {},
    priority: 1,
    manualOnly: true,
  },
  {
    id: 'malus',
    name: "Malus' law (polarisation)",
    module: 'm7',
    topic: 'emr',
    equation: 'I = I_{max}\\cos^2\\theta',
    vars: [v('I', 'I', 'Transmitted intensity', 'intensity', { concept: 'Iint', nonNegative: true }), v('I0', 'I_{max}', 'Intensity of polarised light incident on the analyser', 'intensity', { concept: 'Imax', positive: true }), v('th', '\\theta', 'Angle between polarisation direction and analyser axis', 'angle', { concept: 'thetaPol', min: 0, max: PI })],
    solve: {
      I: { expr: '#I0 \\cos^2 #th', fn: ({ I0, th }) => I0 * sq(Math.cos(th)) },
      I0: { expr: '\\frac{#I}{\\cos^2 #th}', fn: ({ I, th }) => I / sq(Math.cos(th)) },
      th: { expr: '\\cos^{-1}\\sqrt{\\frac{#I}{#I0}}', fn: ({ I, I0 }) => acos(Math.sqrt(I / I0)) },
    },
    aliases: ["malus' law", 'malus', 'polariser', 'polarisation', 'polarization', 'analyser', 'cos squared'],
    when: 'Polarised light through a polarising filter (analyser). Unpolarised light through ONE polariser is halved (I = ½I₀) first.',
    whenNot: 'Do not apply cos²θ to unpolarised light.',
    checks: ({ I, I0 }) => (I > I0 * (1 + 1e-9) ? [{ level: 'error', message: 'Transmitted intensity cannot exceed the incident intensity.' }] : []),
    sheet: 'sheet',
    hsc: ['Intensity through two polarisers at 30°', 'Angle between polarisers for 25 % transmission'],
    example: { I0: 100, th: 30 * DEG },
    priority: 4,
  },
  {
    id: 'unpolarised',
    name: 'Unpolarised light through a polariser',
    module: 'm7',
    topic: 'emr',
    equation: 'I_{max} = \\tfrac{1}{2}I_0',
    vars: [v('Im', 'I_{max}', 'Intensity after the first polariser (now polarised)', 'intensity', { concept: 'Imax', positive: true }), v('I0', 'I_0', 'Intensity of the unpolarised light', 'intensity', { concept: 'I0unpol', positive: true })],
    solve: { Im: { expr: '\\tfrac{1}{2} #I0', fn: ({ I0 }) => I0 / 2 }, I0: { expr: '2 #Im', fn: ({ Im }) => 2 * Im } },
    aliases: ['unpolarised', 'unpolarized', 'first polariser', 'half the intensity'],
    when: 'Unpolarised light contains all orientations; a polariser transmits the average of cos²θ, i.e. half the intensity. The transmitted light is then polarised along the filter axis.',
    whenNot: 'Only for UNPOLARISED light. For already-polarised light use Malus’ law.',
    sheet: 'syllabus',
    hsc: ['Intensity after two polarisers when unpolarised light is incident on the first'],
    example: { I0: 100 },
    priority: 3,
    contextOnly: ['emr'],
  },
  {
    id: 'inverse_square',
    name: 'Inverse square law for intensity',
    module: 'm7',
    topic: 'emr',
    alsoIn: ['stars'],
    equation: 'I_1r_1^2 = I_2r_2^2',
    vars: [v('I2', 'I_2', 'Intensity at distance r₂', 'intensity', { concept: 'Iint2', positive: true }), v('I1', 'I_1', 'Intensity at distance r₁', 'intensity', { concept: 'Iint1', positive: true }), v('r1', 'r_1', 'Distance 1', 'length', { concept: 'dI1', positive: true }), v('r2', 'r_2', 'Distance 2', 'length', { concept: 'dI2', positive: true })],
    solve: {
      I2: { expr: '#I1 \\frac{#r1^2}{#r2^2}', fn: ({ I1, r1, r2 }) => (I1 * r1 * r1) / (r2 * r2) },
      I1: { expr: '#I2 \\frac{#r2^2}{#r1^2}', fn: ({ I2, r1, r2 }) => (I2 * r2 * r2) / (r1 * r1) },
      r1: { expr: '#r2 \\sqrt{\\frac{#I2}{#I1}}', fn: ({ I2, I1, r2 }) => r2 * Math.sqrt(I2 / I1) },
      r2: { expr: '#r1 \\sqrt{\\frac{#I1}{#I2}}', fn: ({ I2, I1, r1 }) => r1 * Math.sqrt(I1 / I2) },
    },
    aliases: ['inverse square', 'intensity', 'brightness', 'distance from source'],
    when: 'A point source radiating equally in all directions: intensity ∝ 1/r².',
    sheet: 'y11',
    hsc: ['Intensity of light at twice the distance', 'Brightness of a star'],
    example: { I1: 100, r1: 1, r2: 3 },
    priority: 2,
  },
  // ───────────── Interference & diffraction ─────────────
  {
    id: 'grating',
    name: 'Double slit / diffraction grating (bright fringes)',
    module: 'm7',
    topic: 'interference',
    equation: 'd\\sin\\theta = m\\lambda',
    vars: [v('lam', '\\lambda', 'Wavelength', 'wavelength', { concept: 'lambda', positive: true }), v('d', 'd', 'Slit separation (grating spacing)', 'length', { concept: 'dSlit', positive: true }), v('th', '\\theta', 'Angle of the maximum from the central axis', 'angle', { concept: 'thetaM', min: 0, max: PI / 2 }), v('m', 'm', 'Order of the maximum (0, 1, 2 …)', 'count', { concept: 'mOrder', nonNegative: true, integer: true })],
    solve: {
      lam: { expr: '\\frac{#d \\sin #th}{#m}', fn: ({ d, th, m }) => (d * Math.sin(th)) / m },
      d: { expr: '\\frac{#m #lam}{\\sin #th}', fn: ({ lam, th, m }) => (m * lam) / Math.sin(th) },
      th: { expr: '\\sin^{-1}\\left(\\frac{#m #lam}{#d}\\right)', fn: ({ lam, d, m }) => asin((m * lam) / d), note: 'no solution if mλ > d — that order does not exist' },
      m: { expr: '\\frac{#d \\sin #th}{#lam}', fn: ({ lam, d, th }) => (d * Math.sin(th)) / lam },
    },
    aliases: ['diffraction grating', 'double slit', "young's double slit", 'young', 'interference maxima', 'd sin theta = m lambda', 'bright fringes', 'constructive interference', 'order'],
    when: 'Bright fringes (constructive interference): path difference d sinθ = mλ. For a grating d = 1/(lines per metre).',
    whenNot: 'Maximum order: m ≤ d/λ (sinθ ≤ 1).',
    sheet: 'sheet',
    hsc: ['Wavelength from a grating with 600 lines/mm', 'Angle of the second-order maximum'],
    example: { d: 1.667e-6, th: 20 * DEG, m: 1 },
    priority: 5,
  },
  {
    id: 'double_slit_dark',
    name: 'Double slit — dark fringes (minima)',
    module: 'm7',
    topic: 'interference',
    equation: 'd\\sin\\theta = \\left(m + \\tfrac{1}{2}\\right)\\lambda',
    vars: [v('lam', '\\lambda', 'Wavelength', 'wavelength', { concept: 'lambda', positive: true }), v('d', 'd', 'Slit separation', 'length', { concept: 'dSlit', positive: true }), v('th', '\\theta', 'Angle of the minimum', 'angle', { concept: 'thetaM', min: 0, max: PI / 2 }), v('m', 'm', 'Minimum number (0 = first dark fringe)', 'count', { concept: 'mOrder', nonNegative: true, integer: true })],
    solve: {
      lam: { expr: '\\frac{#d \\sin #th}{#m + 0.5}', fn: ({ d, th, m }) => (d * Math.sin(th)) / (m + 0.5) },
      d: { expr: '\\frac{(#m + 0.5) #lam}{\\sin #th}', fn: ({ lam, th, m }) => ((m + 0.5) * lam) / Math.sin(th) },
      th: { expr: '\\sin^{-1}\\left(\\frac{(#m + 0.5) #lam}{#d}\\right)', fn: ({ lam, d, m }) => asin(((m + 0.5) * lam) / d) },
      m: { expr: '\\frac{#d \\sin #th}{#lam} - 0.5', fn: ({ lam, d, th }) => (d * Math.sin(th)) / lam - 0.5 },
    },
    aliases: ['dark fringe', 'destructive interference', 'minimum', 'half wavelength'],
    when: 'Destructive interference: the path difference is an odd number of half wavelengths.',
    sheet: 'derived',
    hsc: ['Angle of the first dark fringe'],
    example: { d: 2e-5, th: 1 * DEG, m: 0 },
    priority: 2,
    manualOnly: true,
  },
  {
    id: 'path_diff',
    name: 'Path difference for constructive interference',
    module: 'm7',
    topic: 'interference',
    equation: '\\Delta = m\\lambda',
    vars: [v('pd', '\\Delta', 'Path difference', 'length', { concept: 'pathDiff', nonNegative: true }), v('m', 'm', 'Order / number of wavelengths', 'ratio', { concept: 'mOrder', nonNegative: true }), v('lam', '\\lambda', 'Wavelength', 'wavelength', { concept: 'lambda', positive: true })],
    solve: {
      pd: { expr: '#m #lam', fn: ({ m, lam }) => m * lam },
      m: { expr: '\\frac{#pd}{#lam}', fn: ({ pd, lam }) => pd / lam, note: 'whole number → bright (constructive); half-integer → dark (destructive)' },
      lam: { expr: '\\frac{#pd}{#m}', fn: ({ pd, m }) => pd / m },
    },
    aliases: ['path difference', 'constructive', 'destructive', 'in phase', 'out of phase'],
    when: 'Two coherent sources: whole-number wavelengths of path difference give constructive interference; (m + ½)λ gives destructive.',
    sheet: 'syllabus',
    hsc: ['Is the point bright or dark given a path difference of 1.5λ?'],
    example: { m: 2, lam: 6e-7 },
    priority: 2,
  },
  {
    id: 'fringe_position',
    name: 'Fringe position on a screen (small angle)',
    module: 'm7',
    topic: 'interference',
    equation: 'y_m = \\frac{m\\lambda L}{d}',
    vars: [v('y', 'y_m', 'Distance of the m-th bright fringe from the centre', 'length', { concept: 'yFringe', nonNegative: true }), v('m', 'm', 'Order', 'count', { concept: 'mOrder', nonNegative: true }), v('lam', '\\lambda', 'Wavelength', 'wavelength', { concept: 'lambda', positive: true }), v('L', 'L', 'Slit-to-screen distance', 'length', { concept: 'Lscreen', positive: true }), v('d', 'd', 'Slit separation', 'length', { concept: 'dSlit', positive: true })],
    solve: {
      y: { expr: '\\frac{#m #lam #L}{#d}', fn: ({ m, lam, L, d }) => (m * lam * L) / d },
      m: { expr: '\\frac{#y #d}{#lam #L}', fn: ({ y, lam, L, d }) => (y * d) / (lam * L) },
      lam: { expr: '\\frac{#y #d}{#m #L}', fn: ({ y, m, L, d }) => (y * d) / (m * L) },
      L: { expr: '\\frac{#y #d}{#m #lam}', fn: ({ y, m, lam, d }) => (y * d) / (m * lam) },
      d: { expr: '\\frac{#m #lam #L}{#y}', fn: ({ y, m, lam, L }) => (m * lam * L) / y },
    },
    aliases: ['fringe position', 'distance from central maximum', 'screen', 'small angle approximation'],
    when: 'Double slit with a distant screen (L ≫ y, θ below about 10°): sinθ ≈ tanθ = y/L.',
    whenNot: 'Not for large angles (e.g. most diffraction gratings) — use d sinθ = mλ with tanθ = y/L.',
    derivation: ['d\\sin\\theta = m\\lambda,\\quad \\sin\\theta \\approx \\tan\\theta = \\frac{y}{L}', '\\Rightarrow y_m = \\frac{m\\lambda L}{d}'],
    checks: ({ y, L }) => (y / L > Math.tan(10 * DEG) ? [{ level: 'warning', message: `The angle is about ${(Math.atan(y / L) / DEG).toFixed(1)}° — too large for the small-angle approximation. Use d sinθ = mλ with tanθ = y/L instead.` }] : []),
    sheet: 'derived',
    hsc: ['Distance between the central and first bright fringe', 'Wavelength from Young’s experiment'],
    example: { m: 1, lam: 6.5e-7, L: 2, d: 2.5e-4 },
    priority: 3,
  },
  {
    id: 'fringe_spacing',
    name: 'Fringe spacing (small angle)',
    module: 'm7',
    topic: 'interference',
    equation: '\\Delta y = \\frac{\\lambda L}{d}',
    vars: [v('dy', '\\Delta y', 'Spacing between adjacent bright fringes', 'length', { concept: 'dyFringe', positive: true }), v('lam', '\\lambda', 'Wavelength', 'wavelength', { concept: 'lambda', positive: true }), v('L', 'L', 'Slit-to-screen distance', 'length', { concept: 'Lscreen', positive: true }), v('d', 'd', 'Slit separation', 'length', { concept: 'dSlit', positive: true })],
    solve: {
      dy: { expr: '\\frac{#lam #L}{#d}', fn: ({ lam, L, d }) => (lam * L) / d },
      lam: { expr: '\\frac{#dy #d}{#L}', fn: ({ dy, L, d }) => (dy * d) / L },
      L: { expr: '\\frac{#dy #d}{#lam}', fn: ({ dy, lam, d }) => (dy * d) / lam },
      d: { expr: '\\frac{#lam #L}{#dy}', fn: ({ dy, lam, L }) => (lam * L) / dy },
    },
    aliases: ['fringe spacing', 'fringe separation', 'distance between fringes', 'young'],
    when: 'Equally spaced fringes in Young’s double slit (small angles).',
    whenNot: 'Not for large angles.',
    checks: ({ dy, L }) => (dy / L > Math.tan(10 * DEG) ? [{ level: 'warning', message: 'Fringe spacing is large compared with L — the small-angle approximation may not hold.' }] : []),
    sheet: 'derived',
    hsc: ['Fringe spacing when the slits are moved closer together'],
    example: { lam: 6.5e-7, L: 2, d: 2.5e-4 },
    priority: 3,
  },
  {
    id: 'fringe_angle',
    name: 'Angle to a fringe from screen geometry',
    module: 'm7',
    topic: 'interference',
    equation: '\\tan\\theta = \\frac{y}{L}',
    vars: [v('th', '\\theta', 'Angle from the central axis', 'angle', { concept: 'thetaM', min: 0, max: PI / 2 }), v('y', 'y', 'Distance on the screen from the central maximum', 'length', { concept: 'yFringe', nonNegative: true }), v('L', 'L', 'Distance from slits/grating to screen', 'length', { concept: 'Lscreen', positive: true })],
    solve: {
      th: { expr: '\\tan^{-1}\\left(\\frac{#y}{#L}\\right)', fn: ({ y, L }) => Math.atan(y / L) },
      y: { expr: '#L \\tan #th', fn: ({ L, th }) => L * Math.tan(th) },
      L: { expr: '\\frac{#y}{\\tan #th}', fn: ({ y, th }) => y / Math.tan(th) },
    },
    aliases: ['angle from screen', 'tan theta = y/L', 'grating screen'],
    when: 'Exact geometry for any angle — use before d sinθ = mλ when the angle is not small.',
    sheet: 'derived',
    hsc: ['Grating with fringes 0.6 m from the centre on a screen 1.5 m away'],
    example: { y: 0.6, L: 1.5 },
    priority: 2,
  },
  {
    id: 'grating_spacing',
    name: 'Grating spacing from lines per unit length',
    module: 'm7',
    topic: 'interference',
    equation: 'd = \\frac{1}{N}',
    vars: [v('d', 'd', 'Grating spacing', 'length', { concept: 'dSlit', positive: true }), v('N', 'N', 'Lines per unit length', 'lineDensity', { concept: 'Nlines', positive: true })],
    solve: { d: { expr: '\\frac{1}{#N}', fn: ({ N }) => 1 / N }, N: { expr: '\\frac{1}{#d}', fn: ({ d }) => 1 / d } },
    aliases: ['lines per mm', 'lines per metre', 'lines per cm', 'grating spacing', 'rulings'],
    when: 'Convert a grating specification to slit spacing: 600 lines/mm → N = 6.00 × 10⁵ lines/m → d = 1.67 × 10⁻⁶ m.',
    sheet: 'derived',
    hsc: ['d for a 300 lines/mm grating'],
    example: { N: 6e5 },
    priority: 5,
    chainCost: 0.8,
  },
  {
    id: 'grating_max_order',
    name: 'Highest observable order',
    module: 'm7',
    topic: 'interference',
    equation: 'm_{max} = \\left\\lfloor \\frac{d}{\\lambda} \\right\\rfloor',
    vars: [v('mmax', 'm_{max}', 'Highest order visible', 'count', { concept: 'mMax', nonNegative: true }), v('d', 'd', 'Grating spacing', 'length', { concept: 'dSlit', positive: true }), v('lam', '\\lambda', 'Wavelength', 'wavelength', { concept: 'lambda', positive: true })],
    solve: {
      mmax: { expr: '\\left\\lfloor \\frac{#d}{#lam} \\right\\rfloor', fn: ({ d, lam }) => Math.floor(d / lam + 1e-9), note: 'sinθ cannot exceed 1, so m ≤ d/λ (round down)' },
    },
    aliases: ['maximum order', 'number of orders', 'highest order', 'how many maxima'],
    when: 'sinθ ≤ 1 in d sinθ = mλ limits the number of orders seen. Total bright fringes = 2m_max + 1.',
    sheet: 'derived',
    hsc: ['How many orders can be seen with a 600 lines/mm grating?'],
    example: { d: 1.667e-6, lam: 5.89e-7 },
    priority: 2,
  },
  // ───────────── Black body / photons ─────────────
  {
    id: 'wien',
    name: "Wien's displacement law",
    module: 'm7',
    topic: 'quantumLight',
    alsoIn: ['stars'],
    equation: '\\lambda_{max} = \\frac{b}{T}',
    vars: [v('lam', '\\lambda_{max}', 'Peak wavelength', 'wavelength', { concept: 'lambdaMax', positive: true }), bVar(), v('T', 'T', 'Absolute temperature', 'temperature', { concept: 'Temp', positive: true })],
    solve: {
      lam: { expr: '\\frac{#b}{#T}', fn: ({ b, T }) => b / T },
      T: { expr: '\\frac{#b}{#lam}', fn: ({ b, lam }) => b / lam },
    },
    aliases: ["wien's law", 'wien', 'black body', 'blackbody', 'peak wavelength', 'surface temperature', 'star temperature', 'lambda max'],
    when: 'Peak wavelength of black-body radiation is inversely proportional to absolute temperature (kelvin). Used for star surface temperatures.',
    whenNot: 'Temperature must be in kelvin (T(K) = T(°C) + 273).',
    sheet: 'sheet',
    hsc: ['Surface temperature of a star peaking at 500 nm', 'Peak wavelength of the Sun'],
    example: { T: 5800 },
    priority: 5,
  },
  {
    id: 'stefan_boltzmann',
    name: 'Stefan–Boltzmann law (luminosity)',
    module: 'm8',
    topic: 'stars',
    equation: 'L = 4\\pi R^2\\sigma T^4',
    vars: [
      v('L', 'L', 'Luminosity (power output)', 'power', { concept: 'P', positive: true }),
      v('R', 'R', 'Radius of the star', 'length', { concept: 'Rstar', positive: true }),
      v('sig', '\\sigma', 'Stefan–Boltzmann constant', 'stefan', { constant: 5.67e-8, constantSource: 'not on the NESA data sheet', positive: true }),
      v('T', 'T', 'Surface temperature', 'temperature', { concept: 'Temp', positive: true }),
    ],
    solve: {
      L: { expr: '4\\pi #R^2 #sig #T^4', fn: ({ R, sig, T }) => 4 * PI * R * R * sig * T ** 4 },
      R: { expr: '\\sqrt{\\frac{#L}{4\\pi #sig #T^4}}', fn: ({ L, sig, T }) => Math.sqrt(L / (4 * PI * sig * T ** 4)) },
      T: { expr: '\\left(\\frac{#L}{4\\pi #R^2 #sig}\\right)^{1/4}', fn: ({ L, R, sig }) => Math.pow(L / (4 * PI * R * R * sig), 0.25) },
    },
    aliases: ['stefan-boltzmann', 'luminosity', 'radius of star'],
    when: 'Total power radiated by a star. NOT on the NESA formula sheet and not required by the syllabus — the syllabus only needs luminosity qualitatively (HR diagram). Provided as an extension.',
    sheet: 'extension',
    hsc: [],
    example: { R: 6.96e8, T: 5778 },
    priority: -1,
    manualOnly: true,
  },
  {
    id: 'photon_energy',
    name: 'Photon energy',
    module: 'm7',
    topic: 'quantumLight',
    alsoIn: ['photoelectric', 'atomic'],
    equation: 'E = hf',
    vars: [v('E', 'E', 'Photon energy', 'energyAtomic', { concept: 'Eph', positive: true }), hVar(), v('f', 'f', 'Frequency', 'frequency', { positive: true })],
    solve: {
      E: { expr: '#h #f', fn: ({ h, f }) => h * f },
      f: { expr: '\\frac{#E}{#h}', fn: ({ E, h }) => E / h },
      h: { expr: '\\frac{#E}{#f}', fn: ({ E, f }) => E / f },
    },
    aliases: ['photon energy', 'E = hf', 'planck', 'quantum', 'energy of a photon'],
    when: 'Energy of one photon (quantum) of EM radiation of frequency f. Also ΔE = hf for an electron transition.',
    sheet: 'sheet',
    hsc: ['Energy of a 500 nm photon', 'Frequency of a photon emitted in a transition', 'Planck’s constant from a Kmax–f graph'],
    example: { f: 6e14 },
    priority: 5,
  },
  {
    id: 'photon_energy_lambda',
    name: 'Photon energy from wavelength',
    module: 'm7',
    topic: 'quantumLight',
    alsoIn: ['photoelectric', 'atomic'],
    equation: 'E = \\frac{hc}{\\lambda}',
    vars: [v('E', 'E', 'Photon energy', 'energyAtomic', { concept: 'Eph', positive: true }), hVar(), cVar(), v('lam', '\\lambda', 'Wavelength', 'wavelength', { concept: 'lambda', positive: true })],
    solve: {
      E: { expr: '\\frac{#h #c}{#lam}', fn: ({ h, c, lam }) => (h * c) / lam },
      lam: { expr: '\\frac{#h #c}{#E}', fn: ({ E, h, c }) => (h * c) / E },
    },
    aliases: ['photon energy', 'hc/lambda', 'energy from wavelength'],
    when: 'Photon energy directly from wavelength (combines E = hf and c = fλ).',
    derivation: ['E = hf,\\quad f = \\frac{c}{\\lambda} \\Rightarrow E = \\frac{hc}{\\lambda}'],
    sheet: 'derived',
    hsc: ['Energy of a photon of wavelength 656 nm', 'Wavelength of a photon from an energy-level transition'],
    example: { lam: 5e-7 },
    priority: 4,
    chainCost: 1.3,
  },
  {
    id: 'photon_momentum',
    name: 'Photon momentum',
    module: 'm7',
    topic: 'quantumLight',
    equation: 'p = \\frac{h}{\\lambda}',
    vars: [v('p', 'p', 'Momentum', 'momentum', { positive: true }), hVar(), v('lam', '\\lambda', 'Wavelength', 'wavelength', { concept: 'lambda', positive: true })],
    solve: {
      p: { expr: '\\frac{#h}{#lam}', fn: ({ h, lam }) => h / lam },
      lam: { expr: '\\frac{#h}{#p}', fn: ({ h, p }) => h / p },
    },
    aliases: ['photon momentum', 'momentum of light', 'radiation pressure'],
    when: 'Momentum of a photon (the de Broglie relation applied to light).',
    sheet: 'derived',
    hsc: ['Momentum of an X-ray photon'],
    example: { lam: 5e-7 },
    priority: 1,
    contextOnly: ['quantumLight'],
  },
  {
    id: 'photon_rate',
    name: 'Number of photons emitted per second',
    module: 'm7',
    topic: 'quantumLight',
    equation: 'n = \\frac{P}{E_{photon}}',
    vars: [v('n', 'n', 'Photons per second', 'rate', { concept: 'photonRate', positive: true }), v('P', 'P', 'Power of the source', 'power', { positive: true }), v('E', 'E_{photon}', 'Energy of one photon', 'energyAtomic', { concept: 'Eph', positive: true })],
    solve: {
      n: { expr: '\\frac{#P}{#E}', fn: ({ P, E }) => P / E },
      P: { expr: '#n #E', fn: ({ n, E }) => n * E },
      E: { expr: '\\frac{#P}{#n}', fn: ({ n, P }) => P / n },
    },
    aliases: ['photons per second', 'number of photons', 'laser power', 'photon flux'],
    when: 'A source of power P emitting photons of energy E: P = (photons per second) × E.',
    derivation: ['P = \\frac{E_{total}}{t} = \\frac{nE_{photon}t}{t}'],
    sheet: 'exam',
    hsc: ['Number of photons per second from a 5 mW laser'],
    example: { P: 5e-3, E: 3.14e-19 },
    priority: 3,
  },
  // ───────────── Photoelectric effect ─────────────
  {
    id: 'photoelectric',
    name: "Einstein's photoelectric equation",
    module: 'm7',
    topic: 'photoelectric',
    equation: 'K_{max} = hf - \\phi',
    vars: [v('K', 'K_{max}', 'Maximum kinetic energy of photoelectrons', 'energyAtomic', { concept: 'Kmax', nonNegative: true }), hVar(), v('f', 'f', 'Frequency of incident light', 'frequency', { positive: true }), v('phi', '\\phi', 'Work function', 'energyAtomic', { concept: 'phi', positive: true })],
    solve: {
      K: { expr: '#h #f - #phi', fn: ({ h, f, phi }) => h * f - phi },
      f: { expr: '\\frac{#K + #phi}{#h}', fn: ({ K, h, phi }) => (K + phi) / h },
      phi: { expr: '#h #f - #K', fn: ({ K, h, f }) => h * f - K },
      h: { expr: '\\frac{#K + #phi}{#f}', fn: ({ K, f, phi }) => (K + phi) / f },
    },
    aliases: ['photoelectric effect', 'einstein', 'work function', 'maximum kinetic energy', 'photoelectrons', 'Kmax = hf - phi'],
    when: 'Light of frequency f ejects electrons from a metal of work function φ. If hf < φ no electrons are emitted, however intense the light.',
    whenNot: 'Kmax cannot be negative — if hf < φ there is no photoemission.',
    checks: ({ K }) => (K < 0 ? [{ level: 'error', message: 'Photon energy is below the work function (hf < φ): no photoelectrons are emitted, so Kmax does not exist.' }] : []),
    sheet: 'sheet',
    hsc: ['Kmax of electrons from sodium illuminated with UV', 'Work function from a Kmax–f graph', 'Threshold frequency'],
    example: { f: 1.0e15, phi: 3.65e-19 },
    priority: 5,
  },
  {
    id: 'photoelectric_lambda',
    name: 'Photoelectric equation (wavelength form)',
    module: 'm7',
    topic: 'photoelectric',
    equation: 'K_{max} = \\frac{hc}{\\lambda} - \\phi',
    vars: [v('K', 'K_{max}', 'Maximum kinetic energy', 'energyAtomic', { concept: 'Kmax', nonNegative: true }), hVar(), cVar(), v('lam', '\\lambda', 'Wavelength of incident light', 'wavelength', { concept: 'lambda', positive: true }), v('phi', '\\phi', 'Work function', 'energyAtomic', { concept: 'phi', positive: true })],
    solve: {
      K: { expr: '\\frac{#h #c}{#lam} - #phi', fn: ({ h, c, lam, phi }) => (h * c) / lam - phi },
      lam: { expr: '\\frac{#h #c}{#K + #phi}', fn: ({ K, h, c, phi }) => (h * c) / (K + phi) },
      phi: { expr: '\\frac{#h #c}{#lam} - #K', fn: ({ K, h, c, lam }) => (h * c) / lam - K },
    },
    aliases: ['photoelectric wavelength', 'work function wavelength'],
    when: 'Photoelectric effect when the wavelength is given.',
    derivation: ['K_{max} = hf - \\phi,\\quad f = \\frac{c}{\\lambda}'],
    checks: ({ K }) => (K < 0 ? [{ level: 'error', message: 'Photon energy is below the work function: no photoelectrons are emitted.' }] : []),
    sheet: 'derived',
    hsc: ['Kmax for 250 nm UV on zinc'],
    example: { lam: 2.5e-7, phi: 6.9e-19 },
    priority: 4,
    chainCost: 1.4,
  },
  {
    id: 'work_function',
    name: 'Work function and threshold frequency',
    module: 'm7',
    topic: 'photoelectric',
    equation: '\\phi = hf_0',
    vars: [v('phi', '\\phi', 'Work function', 'energyAtomic', { concept: 'phi', positive: true }), hVar(), v('f0', 'f_0', 'Threshold frequency', 'frequency', { concept: 'f0', positive: true })],
    solve: {
      phi: { expr: '#h #f0', fn: ({ h, f0 }) => h * f0 },
      f0: { expr: '\\frac{#phi}{#h}', fn: ({ phi, h }) => phi / h },
      h: { expr: '\\frac{#phi}{#f0}', fn: ({ phi, f0 }) => phi / f0 },
    },
    aliases: ['threshold frequency', 'cut-off frequency', 'work function', 'minimum frequency'],
    when: 'At the threshold frequency f₀ the photon energy just equals the work function (Kmax = 0). The x-intercept of a Kmax–f graph.',
    derivation: ['K_{max} = 0 \\Rightarrow hf_0 = \\phi'],
    sheet: 'derived',
    hsc: ['Threshold frequency of a metal', 'Work function from the x-intercept of a Kmax–f graph'],
    example: { f0: 5.5e14 },
    priority: 4,
  },
  {
    id: 'threshold_lambda',
    name: 'Threshold wavelength',
    module: 'm7',
    topic: 'photoelectric',
    equation: '\\lambda_0 = \\frac{c}{f_0} = \\frac{hc}{\\phi}',
    vars: [v('l0', '\\lambda_0', 'Threshold (maximum) wavelength', 'wavelength', { concept: 'lambda0', positive: true }), hVar(), cVar(), v('phi', '\\phi', 'Work function', 'energyAtomic', { concept: 'phi', positive: true })],
    solve: {
      l0: { expr: '\\frac{#h #c}{#phi}', fn: ({ h, c, phi }) => (h * c) / phi },
      phi: { expr: '\\frac{#h #c}{#l0}', fn: ({ h, c, l0 }) => (h * c) / l0 },
    },
    aliases: ['threshold wavelength', 'maximum wavelength', 'cut-off wavelength', 'longest wavelength'],
    when: 'Longest wavelength that can eject photoelectrons.',
    sheet: 'derived',
    hsc: ['Longest wavelength that ejects electrons from potassium'],
    example: { phi: 3.65e-19 },
    priority: 3,
  },
  {
    id: 'threshold_f_lambda',
    name: 'Threshold frequency and wavelength',
    module: 'm7',
    topic: 'photoelectric',
    equation: 'c = f_0\\lambda_0',
    vars: [v('f0', 'f_0', 'Threshold frequency', 'frequency', { concept: 'f0', positive: true }), cVar(), v('l0', '\\lambda_0', 'Threshold wavelength', 'wavelength', { concept: 'lambda0', positive: true })],
    solve: { f0: { expr: '\\frac{#c}{#l0}', fn: ({ c, l0 }) => c / l0 }, l0: { expr: '\\frac{#c}{#f0}', fn: ({ c, f0 }) => c / f0 } },
    aliases: ['threshold frequency', 'threshold wavelength'],
    when: 'Converting between threshold frequency and threshold wavelength.',
    sheet: 'derived',
    hsc: ['Threshold wavelength from the threshold frequency'],
    example: { l0: 5.45e-7 },
    priority: 2,
  },
  {
    id: 'stopping_voltage',
    name: 'Stopping voltage',
    module: 'm7',
    topic: 'photoelectric',
    equation: 'K_{max} = qV_s',
    vars: [v('K', 'K_{max}', 'Maximum kinetic energy', 'energyAtomic', { concept: 'Kmax', nonNegative: true }), v('e', 'e', 'Electron charge (magnitude)', 'charge', { concept: 'eCharge', constant: NESA.e.value, constantSource: 'NESA data sheet', positive: true }), v('Vs', 'V_s', 'Stopping voltage', 'voltage', { concept: 'Vstop', nonNegative: true })],
    solve: {
      K: { expr: '#e #Vs', fn: ({ e, Vs }) => e * Vs },
      Vs: { expr: '\\frac{#K}{#e}', fn: ({ K, e }) => K / e },
    },
    aliases: ['stopping voltage', 'stopping potential', 'cut-off voltage', 'retarding potential'],
    when: 'The reverse potential that just stops the most energetic photoelectrons. Kmax in eV is numerically equal to V_s in volts.',
    sheet: 'derived',
    hsc: ['Stopping voltage for photoelectrons with Kmax = 1.2 eV', 'Kmax from a measured stopping voltage'],
    example: { Vs: 1.5 },
    priority: 4,
  },
  {
    id: 'photoelectron_speed',
    name: 'Maximum speed of photoelectrons',
    module: 'm7',
    topic: 'photoelectric',
    equation: 'K_{max} = \\tfrac{1}{2}m_ev_{max}^2',
    vars: [v('K', 'K_{max}', 'Maximum kinetic energy', 'energyAtomic', { concept: 'Kmax', nonNegative: true }), v('m', 'm_e', 'Electron mass', 'mass', { concept: 'me', constant: NESA.me.value, constantSource: 'NESA data sheet', positive: true }), v('v', 'v_{max}', 'Maximum speed', 'velocity', { nonNegative: true })],
    solve: {
      K: { expr: '\\tfrac{1}{2} #m #v^2', fn: ({ m, v }) => 0.5 * m * v * v },
      v: { expr: '\\sqrt{\\frac{2 #K}{#m}}', fn: ({ K, m }) => Math.sqrt((2 * K) / m) },
    },
    aliases: ['speed of photoelectrons', 'maximum velocity', 'fastest electrons'],
    when: 'Speed of the fastest photoelectrons (non-relativistic).',
    sheet: 'derived',
    hsc: ['Maximum speed of ejected electrons'],
    example: { v: 6e5 },
    priority: 2,
    contextOnly: ['photoelectric'],
  },
  // ───────────── Special relativity ─────────────
  {
    id: 'lorentz',
    name: 'Lorentz factor',
    module: 'm7',
    topic: 'relativity',
    equation: '\\gamma = \\frac{1}{\\sqrt{1 - \\dfrac{v^2}{c^2}}}',
    vars: [v('gam', '\\gamma', 'Lorentz factor', 'ratio', { concept: 'gamma', min: 1 }), relV(), cVar()],
    solve: {
      gam: { expr: '\\frac{1}{\\sqrt{1 - \\frac{#v^2}{#c^2}}}', fn: ({ v, c }) => gammaOf(v, c) },
      v: { expr: '#c \\sqrt{1 - \\frac{1}{#gam^2}}', fn: ({ gam, c }) => vFromGamma(gam, c) },
    },
    aliases: ['lorentz factor', 'gamma', 'relativistic factor'],
    when: 'The factor by which time dilates, lengths contract and momentum increases at speed v. Always ≥ 1.',
    derivation: ['\\text{On the sheet the factor appears as } \\sqrt{1 - v^2/c^2} \\text{ in each formula.}'],
    sheet: 'derived',
    hsc: ['γ for v = 0.80c', 'Speed for which γ = 2'],
    example: { v: 0.8 * C },
    priority: 5,
  },
  {
    id: 'time_dilation',
    name: 'Time dilation',
    module: 'm7',
    topic: 'relativity',
    equation: 't = \\frac{t_0}{\\sqrt{1 - \\dfrac{v^2}{c^2}}}',
    vars: [v('t', 't', 'Dilated time (measured by the observer who sees the clock moving)', 'time', { concept: 'tDil', positive: true }), v('t0', 't_0', 'Proper time (measured in the clock’s own rest frame)', 'time', { concept: 't0', positive: true }), relV(), cVar()],
    solve: {
      t: { expr: '\\frac{#t0}{\\sqrt{1 - \\frac{#v^2}{#c^2}}}', fn: ({ t0, v, c }) => t0 * gammaOf(v, c) },
      t0: { expr: '#t \\sqrt{1 - \\frac{#v^2}{#c^2}}', fn: ({ t, v, c }) => t / gammaOf(v, c) },
      v: { expr: '#c \\sqrt{1 - \\frac{#t0^2}{#t^2}}', fn: ({ t, t0, c }) => (t0 > t ? NaN : c * Math.sqrt(1 - (t0 * t0) / (t * t))) },
    },
    aliases: ['time dilation', 'moving clocks run slow', 'proper time', 'muon lifetime', 'twin paradox', 'dilated'],
    when: 'A clock moving relative to an observer runs slow. PROPER time t₀ is measured by a clock at rest relative to the event (both events at the same place — e.g. a muon’s own lifetime). The observer who sees the clock moving measures the longer time t.',
    whenNot: 'Do not mix up which frame measures the proper time: t is always ≥ t₀.',
    checks: ({ t, t0 }) => (t0 > t * (1 + 1e-9) ? [{ level: 'error', message: 'Proper time cannot be longer than the dilated time (t ≥ t₀).' }] : []),
    sheet: 'sheet',
    hsc: ['Lifetime of a muon measured from Earth', 'Time elapsed on a spacecraft travelling at 0.9c'],
    example: { t0: 2.2e-6, v: 0.995 * C },
    priority: 5,
  },
  {
    id: 'time_dilation_gamma',
    name: 'Time dilation (using γ)',
    module: 'm7',
    topic: 'relativity',
    equation: 't = \\gamma t_0',
    vars: [v('t', 't', 'Dilated time', 'time', { concept: 'tDil', positive: true }), v('gam', '\\gamma', 'Lorentz factor', 'ratio', { concept: 'gamma', min: 1 }), v('t0', 't_0', 'Proper time', 'time', { concept: 't0', positive: true })],
    solve: {
      t: { expr: '#gam #t0', fn: ({ gam, t0 }) => gam * t0 },
      gam: { expr: '\\frac{#t}{#t0}', fn: ({ t, t0 }) => t / t0 },
      t0: { expr: '\\frac{#t}{#gam}', fn: ({ t, gam }) => t / gam },
    },
    aliases: ['time dilation gamma'],
    when: 'Time dilation once γ is known.',
    sheet: 'derived',
    hsc: ['Dilated lifetime given γ'],
    example: { gam: 1.667, t0: 10 },
    priority: 2,
    chainCost: 1.2,
  },
  {
    id: 'length_contraction',
    name: 'Length contraction',
    module: 'm7',
    topic: 'relativity',
    equation: 'l = l_0\\sqrt{1 - \\dfrac{v^2}{c^2}}',
    vars: [v('l', 'l', 'Contracted length (measured by the observer who sees the object moving)', 'length', { concept: 'Lc', positive: true }), v('l0', 'l_0', 'Proper length (measured at rest relative to the object)', 'length', { concept: 'L0', positive: true }), relV(), cVar()],
    solve: {
      l: { expr: '#l0 \\sqrt{1 - \\frac{#v^2}{#c^2}}', fn: ({ l0, v, c }) => l0 / gammaOf(v, c) },
      l0: { expr: '\\frac{#l}{\\sqrt{1 - \\frac{#v^2}{#c^2}}}', fn: ({ l, v, c }) => l * gammaOf(v, c) },
      v: { expr: '#c \\sqrt{1 - \\frac{#l^2}{#l0^2}}', fn: ({ l, l0, c }) => (l > l0 ? NaN : c * Math.sqrt(1 - (l * l) / (l0 * l0))) },
    },
    aliases: ['length contraction', 'contracted length', 'proper length', 'lorentz contraction'],
    when: 'Lengths PARALLEL to the motion are shorter when measured by an observer who sees the object moving. Proper length l₀ is measured in the object’s rest frame (e.g. the atmosphere’s thickness in the Earth frame, the spaceship’s length on board).',
    whenNot: 'Perpendicular dimensions are unchanged.',
    checks: ({ l, l0 }) => (l > l0 * (1 + 1e-9) ? [{ level: 'error', message: 'A contracted length cannot exceed the proper length (l ≤ l₀).' }] : []),
    sheet: 'sheet',
    hsc: ['Thickness of the atmosphere in the muon’s frame', 'Length of a spaceship observed from Earth'],
    example: { l0: 100, v: 0.8 * C },
    priority: 5,
  },
  {
    id: 'rel_momentum',
    name: 'Relativistic momentum',
    module: 'm7',
    topic: 'relativity',
    equation: 'p_v = \\frac{m_0v}{\\sqrt{1 - \\dfrac{v^2}{c^2}}}',
    vars: [v('p', 'p_v', 'Relativistic momentum', 'momentum', { concept: 'p', positive: true }), v('m0', 'm_0', 'Rest mass', 'mass', { concept: 'm', positive: true }), relV(), cVar()],
    solve: {
      p: { expr: '\\frac{#m0 #v}{\\sqrt{1 - \\frac{#v^2}{#c^2}}}', fn: ({ m0, v, c }) => m0 * v * gammaOf(v, c) },
      m0: { expr: '\\frac{#p \\sqrt{1 - #v^2/#c^2}}{#v}', fn: ({ p, v, c }) => p / (v * gammaOf(v, c)) },
      v: { expr: '\\frac{#p}{\\sqrt{#m0^2 + #p^2/#c^2}}', fn: ({ p, m0, c }) => p / Math.sqrt(m0 * m0 + (p * p) / (c * c)) },
    },
    aliases: ['relativistic momentum', 'momentum at high speed', 'p = gamma m v'],
    when: 'Momentum at speeds comparable to c. As v → c, p → ∞, so no massive object can reach c.',
    sheet: 'sheet',
    hsc: ['Momentum of an electron at 0.9c', 'Ratio of relativistic to classical momentum'],
    example: { m0: 9.109e-31, v: 0.9 * C },
    priority: 4,
  },
  {
    id: 'mass_energy',
    name: 'Mass–energy equivalence',
    module: 'm7',
    topic: 'relativity',
    alsoIn: ['nuclear', 'stars'],
    equation: 'E = mc^2',
    vars: [v('E', 'E', 'Energy', 'energy', { positive: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), cVar()],
    solve: {
      E: { expr: '#m #c^2', fn: ({ m, c }) => m * c * c },
      m: { expr: '\\frac{#E}{#c^2}', fn: ({ E, c }) => E / (c * c) },
    },
    aliases: ['E = mc^2', 'mass energy', 'rest energy', 'mass-energy equivalence', 'einstein'],
    when: 'Rest energy of a mass, or mass equivalent of an energy (e.g. mass lost by the Sun per second from its power output).',
    sheet: 'sheet',
    hsc: ['Rest energy of an electron in MeV', 'Mass lost by the Sun each second'],
    example: { m: 1e-3 },
    priority: 4,
  },
  {
    id: 'rel_total_energy',
    name: 'Relativistic total energy',
    module: 'm7',
    topic: 'relativity',
    equation: 'E = \\gamma mc^2',
    vars: [v('E', 'E', 'Total energy', 'energyAtomic', { concept: 'Etot', positive: true }), v('gam', '\\gamma', 'Lorentz factor', 'ratio', { concept: 'gamma', min: 1 }), v('m', 'm', 'Rest mass', 'mass', { positive: true }), cVar()],
    solve: {
      E: { expr: '#gam #m #c^2', fn: ({ gam, m, c }) => gam * m * c * c },
      gam: { expr: '\\frac{#E}{#m #c^2}', fn: ({ E, m, c }) => E / (m * c * c) },
      m: { expr: '\\frac{#E}{#gam #c^2}', fn: ({ E, gam, c }) => E / (gam * c * c) },
    },
    aliases: ['total energy', 'relativistic energy', 'relativistic kinetic energy'],
    when: 'Extension only — not on the NESA formula sheet. Relativistic kinetic energy is K = (γ − 1)mc².',
    sheet: 'extension',
    hsc: [],
    example: { gam: 2, m: 9.109e-31 },
    priority: -1,
    manualOnly: true,
  },
];
