/**
 * Module 8 — From the Universe to the Atom.
 * Expansion of the Universe (Hubble), Millikan and Thomson experiments, Bohr model and
 * hydrogen spectrum, de Broglie matter waves, mass defect and binding energy, nuclear
 * reactions, and radioactive decay.
 */
import { NESA } from '../constants';
import { cVar, eVar, hVar, RVar } from './common';
import { FormulaDef, v } from './types';

const PI = Math.PI;
const LN2 = Math.LN2;
const E1_EV = 13.6;

export const m8Formulas: FormulaDef[] = [
  // ───────────── Stars / cosmology ─────────────
  {
    id: 'hubble',
    name: "Hubble's law",
    module: 'm8',
    topic: 'stars',
    equation: 'v = H_0 D',
    vars: [v('v', 'v', 'Recession velocity', 'velocity', { concept: 'vRec', positive: true }), v('H0', 'H_0', 'Hubble constant', 'hubble', { positive: true }), v('D', 'D', 'Distance to the galaxy', 'astroDistance', { concept: 'Dgal', positive: true })],
    solve: {
      v: { expr: '#H0 #D', fn: ({ H0, D }) => H0 * D },
      H0: { expr: '\\frac{#v}{#D}', fn: ({ v, D }) => v / D },
      D: { expr: '\\frac{#v}{#H0}', fn: ({ v, H0 }) => v / H0 },
    },
    aliases: ["hubble's law", 'hubble', 'recession velocity', 'expanding universe', 'galaxy receding'],
    when: 'Galaxies recede with speed proportional to distance — evidence for the expansion of the Universe. The gradient of a v–D graph is H₀. Units: convert km/s/Mpc to s⁻¹ if needed.',
    sheet: 'syllabus',
    hsc: ['Hubble constant from the gradient of a velocity–distance graph', 'Distance to a galaxy receding at 7000 km/s'],
    example: { H0: 70 * 1000 / 3.086e22, D: 100 * 3.086e22 },
    priority: 3,
  },
  {
    id: 'hubble_age',
    name: 'Age of the Universe (Hubble time)',
    module: 'm8',
    topic: 'stars',
    equation: 't \\approx \\frac{1}{H_0}',
    vars: [v('t', 't', 'Approximate age of the Universe', 'longTime', { concept: 'tAge', positive: true }), v('H0', 'H_0', 'Hubble constant', 'hubble', { positive: true })],
    solve: { t: { expr: '\\frac{1}{#H0}', fn: ({ H0 }) => 1 / H0 }, H0: { expr: '\\frac{1}{#t}', fn: ({ t }) => 1 / t } },
    aliases: ['age of the universe', 'hubble time', '1/H0'],
    when: 'If expansion had been at a constant rate, galaxies now at D would have taken t = D/v = 1/H₀ to get there.',
    derivation: ['t = \\frac{D}{v} = \\frac{D}{H_0 D} = \\frac{1}{H_0}'],
    sheet: 'syllabus',
    hsc: ['Estimate the age of the Universe from H₀'],
    example: { H0: 70 * 1000 / 3.086e22 },
    priority: 2,
  },
  {
    id: 'redshift',
    name: 'Redshift (non-relativistic Doppler)',
    module: 'm8',
    topic: 'stars',
    equation: 'z = \\frac{\\Delta\\lambda}{\\lambda_0} \\approx \\frac{v}{c}',
    vars: [v('v', 'v', 'Recession velocity', 'velocity', { concept: 'vRec', positive: true }), v('dl', '\\Delta\\lambda', 'Shift in wavelength (observed − emitted)', 'wavelength', { concept: 'dLambda', signed: true }), v('l0', '\\lambda_0', 'Emitted (rest) wavelength', 'wavelength', { concept: 'lambdaRest', positive: true }), cVar()],
    solve: {
      v: { expr: '#c \\frac{#dl}{#l0}', fn: ({ c, dl, l0 }) => (c * dl) / l0 },
      dl: { expr: '#l0 \\frac{#v}{#c}', fn: ({ v, l0, c }) => (l0 * v) / c },
      l0: { expr: '#c \\frac{#dl}{#v}', fn: ({ v, dl, c }) => (c * dl) / v },
    },
    aliases: ['redshift', 'blueshift', 'doppler shift', 'spectral shift'],
    when: 'Speed of a galaxy from the shift of its spectral lines (v ≪ c). Extension — the syllabus treats redshift qualitatively and this formula is not on the NESA sheet.',
    checks: ({ v }) => (v > 0.1 * NESA.c.value ? [{ level: 'warning', message: 'v > 0.1c: the approximation z ≈ v/c becomes inaccurate.' }] : []),
    sheet: 'extension',
    hsc: [],
    example: { dl: 2e-9, l0: 6.563e-7 },
    priority: 0,
    contextOnly: ['stars'],
  },
  // ───────────── Atomic: Millikan ─────────────
  {
    id: 'millikan',
    name: 'Millikan oil drop (balanced drop)',
    module: 'm8',
    topic: 'atomic',
    equation: 'qE = mg \\Rightarrow q = \\frac{mgd}{V}',
    vars: [v('q', 'q', 'Charge on the drop', 'charge', { positive: true }), v('m', 'm', 'Mass of the drop', 'mass', { positive: true }), v('g', 'g', 'Gravitational field strength', 'gfield', { constant: NESA.g.value, constantSource: 'NESA data sheet', positive: true }), v('d', 'd', 'Plate separation', 'length', { concept: 'dPlate', positive: true }), v('V', 'V', 'Voltage across plates', 'voltage', { positive: true })],
    solve: {
      q: { expr: '\\frac{#m #g #d}{#V}', fn: ({ m, g, d, V }) => (m * g * d) / V },
      m: { expr: '\\frac{#q #V}{#g #d}', fn: ({ q, g, d, V }) => (q * V) / (g * d) },
      V: { expr: '\\frac{#m #g #d}{#q}', fn: ({ q, m, g, d }) => (m * g * d) / q },
      d: { expr: '\\frac{#q #V}{#m #g}', fn: ({ q, m, g, V }) => (q * V) / (m * g) },
    },
    aliases: ['millikan', 'oil drop', 'suspended drop', 'stationary drop', 'balanced'],
    when: 'A charged drop held stationary between plates: electric force up = weight down.',
    derivation: ['F_E = F_g \\Rightarrow qE = mg,\\quad E = \\frac{V}{d}'],
    sheet: 'derived',
    hsc: ['Charge on an oil drop held stationary', 'Number of excess electrons on the drop'],
    example: { m: 3.2e-15, d: 0.01, V: 980 },
    priority: 4,
  },
  {
    id: 'millikan_E',
    name: 'Balanced charge in a field (qE = mg)',
    module: 'm8',
    topic: 'atomic',
    equation: 'qE = mg',
    vars: [v('q', 'q', 'Charge', 'charge', { positive: true }), v('E', 'E', 'Electric field strength', 'efield', { concept: 'Ef', positive: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), v('g', 'g', 'Gravitational field strength', 'gfield', { constant: NESA.g.value, constantSource: 'NESA data sheet', positive: true })],
    solve: {
      q: { expr: '\\frac{#m #g}{#E}', fn: ({ m, g, E }) => (m * g) / E },
      E: { expr: '\\frac{#m #g}{#q}', fn: ({ m, g, q }) => (m * g) / q },
      m: { expr: '\\frac{#q #E}{#g}', fn: ({ q, E, g }) => (q * E) / g },
    },
    aliases: ['balanced', 'suspended', 'levitate', 'oil drop'],
    when: 'Charged object held stationary by an electric field.',
    sheet: 'derived',
    hsc: ['Field needed to suspend a charged drop'],
    example: { E: 9.8e4, m: 3.2e-15 },
    priority: 3,
    contextOnly: ['atomic'],
  },
  {
    id: 'charge_quant',
    name: 'Charge quantisation',
    module: 'm8',
    topic: 'atomic',
    equation: 'q = ne',
    vars: [v('q', 'q', 'Total charge', 'charge', { positive: true }), v('n', 'n', 'Number of elementary charges (electrons)', 'count', { concept: 'nCharges', positive: true }), eVar()],
    solve: {
      q: { expr: '#n #e', fn: ({ n, e }) => n * e },
      n: { expr: '\\frac{#q}{#e}', fn: ({ q, e }) => q / e, note: 'should be (close to) a whole number' },
    },
    aliases: ['number of electrons', 'excess electrons', 'elementary charge', 'quantised charge'],
    when: 'Every charge is a whole-number multiple of e = 1.602 × 10⁻¹⁹ C (Millikan).',
    sheet: 'syllabus',
    hsc: ['How many excess electrons are on the drop?'],
    example: { n: 3 },
    priority: 2,
  },
  // ───────────── Bohr model & spectra ─────────────
  {
    id: 'bohr_energy',
    name: 'Energy levels of hydrogen (Bohr)',
    module: 'm8',
    topic: 'atomic',
    equation: 'E_n = -\\frac{13.6\\ \\text{eV}}{n^2}',
    vars: [v('En', 'E_n', 'Energy of level n', 'energyAtomic', { concept: 'En', max: 0 }), v('n', 'n', 'Principal quantum number', 'count', { concept: 'nLevel', min: 1, integer: true })],
    solve: {
      En: { expr: '-\\frac{13.6\\ \\text{eV}}{#n^2}', fn: ({ n }) => (-E1_EV * NESA.eV.value) / (n * n) },
      n: { expr: '\\sqrt{\\frac{-13.6\\ \\text{eV}}{#En}}', fn: ({ En }) => Math.sqrt((-E1_EV * NESA.eV.value) / En) },
    },
    aliases: ['energy levels', 'bohr model', 'hydrogen atom', 'ground state', 'ionisation energy', '-13.6 eV'],
    when: 'Bohr model energy of the electron in hydrogen. E = 0 is the ionisation limit; the ground state (n = 1) is −13.6 eV.',
    whenNot: 'Only for hydrogen (one-electron atoms). Use given energy-level diagrams for other atoms.',
    derivation: ['E_n = -\\frac{hcR}{n^2}, \\quad hcR = (6.626\\times10^{-34})(3.00\\times10^{8})(1.097\\times10^{7}) = 2.18\\times10^{-18}\\ \\text{J} = 13.6\\ \\text{eV}'],
    sheet: 'derived',
    hsc: ['Energy of the n = 3 level', 'Ionisation energy of hydrogen from n = 2'],
    example: { n: 2 },
    priority: 3,
  },
  {
    id: 'transition_energy',
    name: 'Photon energy in an electron transition',
    module: 'm8',
    topic: 'atomic',
    equation: '\\Delta E = E_i - E_f = hf',
    vars: [v('E', '\\Delta E', 'Photon energy', 'energyAtomic', { concept: 'Eph', positive: true }), v('Ei', 'E_i', 'Initial (upper) level energy', 'energyAtomic', { concept: 'Ei', signed: true }), v('Ef', 'E_f', 'Final (lower) level energy', 'energyAtomic', { concept: 'Ef_level', signed: true })],
    solve: {
      E: { expr: '#Ei - #Ef', fn: ({ Ei, Ef }) => Ei - Ef, note: 'emission: E_i > E_f; for absorption the photon energy is E_f − E_i' },
      Ei: { expr: '#Ef + #E', fn: ({ E, Ef }) => Ef + E },
      Ef: { expr: '#Ei - #E', fn: ({ E, Ei }) => Ei - E },
    },
    aliases: ['transition', 'energy level diagram', 'emitted photon', 'absorbed photon', 'spectral line', 'emission'],
    when: 'An electron dropping from E_i to E_f emits a photon with energy equal to the difference. Absorption is the reverse.',
    sheet: 'syllabus',
    hsc: ['Wavelength of light emitted from a transition on an energy-level diagram'],
    example: { Ei: -1.51 * 1.602e-19, Ef: -3.4 * 1.602e-19 },
    priority: 3,
  },
  {
    id: 'rydberg',
    name: 'Rydberg equation (hydrogen spectrum)',
    module: 'm8',
    topic: 'atomic',
    equation: '\\frac{1}{\\lambda} = R\\left(\\frac{1}{n_f^2} - \\frac{1}{n_i^2}\\right)',
    vars: [v('lam', '\\lambda', 'Wavelength of the spectral line', 'wavelength', { concept: 'lambda', positive: true }), RVar(), v('nf', 'n_f', 'Final (lower) energy level', 'count', { concept: 'nf', min: 1, integer: true }), v('ni', 'n_i', 'Initial (upper) energy level', 'count', { concept: 'ni', min: 1, integer: true })],
    solve: {
      lam: { expr: '\\left[#Ry\\left(\\frac{1}{#nf^2} - \\frac{1}{#ni^2}\\right)\\right]^{-1}', fn: ({ Ry, nf, ni }) => (ni <= nf ? NaN : 1 / (Ry * (1 / (nf * nf) - 1 / (ni * ni)))) },
      ni: { expr: '\\left(\\frac{1}{#nf^2} - \\frac{1}{#Ry #lam}\\right)^{-1/2}', fn: ({ lam, Ry, nf }) => 1 / Math.sqrt(1 / (nf * nf) - 1 / (Ry * lam)), note: 'should be a whole number greater than n_f' },
      nf: { expr: '\\left(\\frac{1}{#Ry #lam} + \\frac{1}{#ni^2}\\right)^{-1/2}', fn: ({ lam, Ry, ni }) => 1 / Math.sqrt(1 / (Ry * lam) + 1 / (ni * ni)), note: 'should be a whole number less than n_i' },
    },
    aliases: ['rydberg', 'balmer', 'lyman', 'paschen', 'hydrogen spectrum', 'spectral line', 'emission spectrum', 'H-alpha'],
    when: 'Wavelengths of the hydrogen spectrum. Lyman series n_f = 1 (UV), Balmer n_f = 2 (visible), Paschen n_f = 3 (IR).',
    whenNot: 'Hydrogen only. n_i must be greater than n_f.',
    checks: ({ ni, nf }) => (ni <= nf ? [{ level: 'error', message: 'For emission the initial level n_i must be higher than the final level n_f.' }] : Math.abs(ni - Math.round(ni)) > 0.05 || Math.abs(nf - Math.round(nf)) > 0.05 ? [{ level: 'warning', message: 'Quantum numbers should be whole numbers — check the wavelength data.' }] : []),
    sheet: 'sheet',
    hsc: ['Wavelength of the n = 3 → 2 (Hα) line', 'Which transition produces 486 nm light?'],
    example: { nf: 2, ni: 3 },
    priority: 5,
  },
  {
    id: 'bohr_angular',
    name: 'Bohr’s quantisation of angular momentum',
    module: 'm8',
    topic: 'atomic',
    alsoIn: ['quantum'],
    equation: 'mvr = \\frac{nh}{2\\pi}',
    vars: [v('r', 'r', 'Orbit radius', 'length', { positive: true }), v('m', 'm', 'Electron mass', 'mass', { concept: 'me', constant: NESA.me.value, constantSource: 'NESA data sheet', positive: true }), v('v', 'v', 'Electron speed', 'velocity', { positive: true }), v('n', 'n', 'Principal quantum number', 'count', { concept: 'nLevel', min: 1, integer: true }), hVar()],
    solve: {
      r: { expr: '\\frac{#n #h}{2\\pi #m #v}', fn: ({ n, h, m, v }) => (n * h) / (2 * PI * m * v) },
      v: { expr: '\\frac{#n #h}{2\\pi #m #r}', fn: ({ n, h, m, r }) => (n * h) / (2 * PI * m * r) },
      n: { expr: '\\frac{2\\pi #m #v #r}{#h}', fn: ({ h, m, v, r }) => (2 * PI * m * v * r) / h },
    },
    aliases: ['angular momentum', 'bohr postulate', 'quantised orbit', 'nh/2pi'],
    when: 'Bohr’s postulate: allowed orbits have angular momentum in whole multiples of h/2π. Equivalent to fitting whole de Broglie wavelengths around the orbit.',
    sheet: 'syllabus',
    hsc: ['Speed of the electron in the n = 1 orbit of radius 5.29 × 10⁻¹¹ m'],
    example: { v: 2.19e6, n: 1 },
    priority: 2,
  },
  {
    id: 'debroglie_orbit',
    name: 'de Broglie standing waves in an orbit',
    module: 'm8',
    topic: 'quantum',
    equation: '2\\pi r = n\\lambda',
    vars: [v('r', 'r', 'Orbit radius', 'length', { positive: true }), v('n', 'n', 'Number of whole wavelengths (quantum number)', 'count', { concept: 'nLevel', min: 1, integer: true }), v('lam', '\\lambda', 'de Broglie wavelength', 'wavelength', { concept: 'lambda', positive: true })],
    solve: {
      r: { expr: '\\frac{#n #lam}{2\\pi}', fn: ({ n, lam }) => (n * lam) / (2 * PI) },
      lam: { expr: '\\frac{2\\pi #r}{#n}', fn: ({ n, r }) => (2 * PI * r) / n },
      n: { expr: '\\frac{2\\pi #r}{#lam}', fn: ({ lam, r }) => (2 * PI * r) / lam },
    },
    aliases: ['standing wave', 'whole number of wavelengths', 'electron orbit circumference'],
    when: 'de Broglie explained Bohr’s stable orbits: a whole number of electron wavelengths fits the circumference.',
    sheet: 'syllabus',
    hsc: ['de Broglie wavelength of the electron in the n = 2 orbit'],
    example: { n: 1, lam: 3.32e-10 },
    priority: 1,
    contextOnly: ['quantum', 'atomic'],
  },
  // ───────────── de Broglie ─────────────
  {
    id: 'debroglie',
    name: 'de Broglie wavelength',
    module: 'm8',
    topic: 'quantum',
    equation: '\\lambda = \\frac{h}{mv}',
    vars: [v('lam', '\\lambda', 'de Broglie wavelength', 'wavelength', { concept: 'lambda', positive: true }), hVar(), v('m', 'm', 'Mass', 'mass', { positive: true }), v('v', 'v', 'Speed', 'velocity', { positive: true })],
    solve: {
      lam: { expr: '\\frac{#h}{#m #v}', fn: ({ h, m, v }) => h / (m * v) },
      m: { expr: '\\frac{#h}{#lam #v}', fn: ({ h, lam, v }) => h / (lam * v) },
      v: { expr: '\\frac{#h}{#m #lam}', fn: ({ h, m, lam }) => h / (m * lam) },
    },
    aliases: ['de broglie', 'matter wave', 'wavelength of electron', 'wave-particle duality', 'h/mv'],
    when: 'Wavelength of a moving particle. Diffraction is only noticeable when λ is comparable to the gap/atom spacing.',
    whenNot: 'At relativistic speeds use λ = h/p with relativistic momentum.',
    sheet: 'sheet',
    hsc: ['Wavelength of an electron moving at 2 × 10⁶ m/s', 'Why a cricket ball shows no wave behaviour', 'Electron diffraction (Davisson–Germer)'],
    example: { m: 9.109e-31, v: 2e6 },
    priority: 5,
  },
  {
    id: 'debroglie_p',
    name: 'de Broglie wavelength from momentum',
    module: 'm8',
    topic: 'quantum',
    equation: '\\lambda = \\frac{h}{p}',
    vars: [v('lam', '\\lambda', 'de Broglie wavelength', 'wavelength', { concept: 'lambda', positive: true }), hVar(), v('p', 'p', 'Momentum', 'momentum', { positive: true })],
    solve: {
      lam: { expr: '\\frac{#h}{#p}', fn: ({ h, p }) => h / p },
      p: { expr: '\\frac{#h}{#lam}', fn: ({ h, lam }) => h / lam },
    },
    aliases: ['de broglie momentum', 'h/p'],
    when: 'Wavelength from momentum (also valid with relativistic momentum).',
    sheet: 'derived',
    hsc: ['Wavelength of a particle with a given momentum'],
    example: { p: 1.8e-24 },
    priority: 2,
    contextOnly: ['quantum', 'relativity'],
  },
  {
    id: 'momentum',
    name: 'Momentum (classical)',
    module: 'm8',
    topic: 'quantum',
    equation: 'p = mv',
    vars: [v('p', 'p', 'Momentum', 'momentum', { positive: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), v('v', 'v', 'Speed', 'velocity', { positive: true })],
    solve: {
      p: { expr: '#m #v', fn: ({ m, v }) => m * v },
      m: { expr: '\\frac{#p}{#v}', fn: ({ p, v }) => p / v },
      v: { expr: '\\frac{#p}{#m}', fn: ({ p, m }) => p / m },
    },
    aliases: ['momentum', 'p = mv'],
    when: 'Classical momentum (v ≪ c).',
    sheet: 'y11',
    hsc: ['Momentum of an electron (then λ = h/p)'],
    example: { m: 9.109e-31, v: 2e6 },
    priority: 2,
    unlessKnown: ['gamma'],
  },
  {
    id: 'debroglie_V',
    name: 'de Broglie wavelength of a charge accelerated through V',
    module: 'm8',
    topic: 'quantum',
    equation: '\\lambda = \\frac{h}{\\sqrt{2mqV}}',
    vars: [v('lam', '\\lambda', 'de Broglie wavelength', 'wavelength', { concept: 'lambda', positive: true }), hVar(), v('m', 'm', 'Mass of particle', 'mass', { positive: true }), v('q', 'q', 'Charge (magnitude)', 'charge', { positive: true }), v('V', 'V', 'Accelerating potential difference', 'voltage', { positive: true })],
    solve: {
      lam: { expr: '\\frac{#h}{\\sqrt{2 #m #q #V}}', fn: ({ h, m, q, V }) => h / Math.sqrt(2 * m * q * V) },
      V: { expr: '\\frac{#h^2}{2 #m #q #lam^2}', fn: ({ h, m, q, lam }) => (h * h) / (2 * m * q * lam * lam) },
      m: { expr: '\\frac{#h^2}{2 #q #V #lam^2}', fn: ({ h, q, V, lam }) => (h * h) / (2 * q * V * lam * lam) },
      q: { expr: '\\frac{#h^2}{2 #m #V #lam^2}', fn: ({ h, m, V, lam }) => (h * h) / (2 * m * V * lam * lam) },
    },
    aliases: ['electron diffraction', 'accelerated electron wavelength', 'electron microscope'],
    when: 'Particle accelerated from rest through V: qV = p²/2m, so p = √(2mqV).',
    derivation: ['qV = \\tfrac{1}{2}mv^2 = \\frac{p^2}{2m} \\Rightarrow p = \\sqrt{2mqV}', '\\lambda = \\frac{h}{p} = \\frac{h}{\\sqrt{2mqV}}'],
    sheet: 'derived',
    hsc: ['Wavelength of electrons accelerated through 54 V (Davisson–Germer)'],
    example: { m: 9.109e-31, q: 1.602e-19, V: 54 },
    priority: 3,
  },
  {
    id: 'debroglie_K',
    name: 'de Broglie wavelength from kinetic energy',
    module: 'm8',
    topic: 'quantum',
    equation: '\\lambda = \\frac{h}{\\sqrt{2mK}}',
    vars: [v('lam', '\\lambda', 'de Broglie wavelength', 'wavelength', { concept: 'lambda', positive: true }), hVar(), v('m', 'm', 'Mass', 'mass', { positive: true }), v('K', 'K', 'Kinetic energy', 'energyAtomic', { positive: true })],
    solve: {
      lam: { expr: '\\frac{#h}{\\sqrt{2 #m #K}}', fn: ({ h, m, K }) => h / Math.sqrt(2 * m * K) },
      K: { expr: '\\frac{#h^2}{2 #m #lam^2}', fn: ({ h, m, lam }) => (h * h) / (2 * m * lam * lam) },
      m: { expr: '\\frac{#h^2}{2 #K #lam^2}', fn: ({ h, K, lam }) => (h * h) / (2 * K * lam * lam) },
    },
    aliases: ['wavelength from kinetic energy', 'neutron wavelength'],
    when: 'Non-relativistic particle with known kinetic energy.',
    derivation: ['K = \\frac{p^2}{2m} \\Rightarrow p = \\sqrt{2mK}'],
    sheet: 'derived',
    hsc: ['Wavelength of a 100 eV electron'],
    example: { m: 9.109e-31, K: 100 * 1.602e-19 },
    priority: 2,
    chainCost: 1.2,
  },
  // ───────────── Nuclear ─────────────
  {
    id: 'mass_defect_energy',
    name: 'Energy from a mass defect',
    module: 'm8',
    topic: 'nuclear',
    equation: 'E = \\Delta mc^2',
    vars: [v('E', 'E', 'Energy (binding energy / energy released)', 'energyNuclear', { concept: 'Enuc', positive: true }), v('dm', '\\Delta m', 'Mass defect', 'atomicMass', { concept: 'dm', positive: true }), cVar()],
    solve: {
      E: { expr: '#dm #c^2', fn: ({ dm, c }) => dm * c * c },
      dm: { expr: '\\frac{#E}{#c^2}', fn: ({ E, c }) => E / (c * c) },
    },
    aliases: ['mass defect', 'binding energy', 'energy released', 'E = delta m c^2', 'fission energy', 'fusion energy'],
    when: 'Energy equivalent of the mass lost in a nuclear reaction, or the binding energy of a nucleus. Convert Δm to kg first — or use 1 u = 931.5 MeV/c².',
    sheet: 'sheet',
    hsc: ['Binding energy of helium-4', 'Energy released in the fission of U-235', 'Energy released in a fusion reaction'],
    example: { dm: 0.0304 * 1.661e-27 },
    priority: 4,
  },
  {
    id: 'u_to_MeV',
    name: 'Energy from mass defect in atomic mass units',
    module: 'm8',
    topic: 'nuclear',
    equation: 'E\\,(\\text{MeV}) = \\Delta m\\,(\\text{u}) \\times 931.5',
    vars: [v('E', 'E', 'Energy (MeV)', 'energyNuclear', { concept: 'Enuc', positive: true }), v('dm', '\\Delta m', 'Mass defect', 'atomicMass', { concept: 'dm', positive: true, unit: 'u' })],
    solve: {
      E: { expr: '#dm \\times 931.5\\ \\text{MeV/u}', fn: ({ dm }) => (dm / NESA.u.value) * 931.5 * 1e6 * NESA.eV.value },
      dm: { expr: '\\frac{#E}{931.5\\ \\text{MeV/u}}', fn: ({ E }) => (E / (931.5 * 1e6 * NESA.eV.value)) * NESA.u.value },
    },
    aliases: ['931.5 MeV', 'atomic mass unit', 'u to MeV'],
    when: 'Data-sheet shortcut: 1 u = 931.5 MeV/c². Gives MeV directly from a mass defect in u.',
    sheet: 'sheet',
    hsc: ['Energy released when the reactant mass exceeds the product mass by 0.0189 u'],
    example: { dm: 0.0304 * 1.661e-27 },
    priority: 3,
    manualOnly: true,
  },
  {
    id: 'binding_per_nucleon',
    name: 'Binding energy per nucleon',
    module: 'm8',
    topic: 'nuclear',
    equation: '\\frac{E_B}{A}',
    vars: [v('BA', '\\frac{E_B}{A}', 'Binding energy per nucleon', 'energyNuclear', { concept: 'BEperA', positive: true }), v('E', 'E_B', 'Total binding energy', 'energyNuclear', { concept: 'Enuc', positive: true }), v('A', 'A', 'Mass number (nucleons)', 'count', { concept: 'Anuc', min: 1, integer: true })],
    solve: {
      BA: { expr: '\\frac{#E}{#A}', fn: ({ E, A }) => E / A },
      E: { expr: '#BA #A', fn: ({ BA, A }) => BA * A },
      A: { expr: '\\frac{#E}{#BA}', fn: ({ BA, E }) => E / BA },
    },
    aliases: ['binding energy per nucleon', 'stability', 'iron-56', 'curve of binding energy'],
    when: 'Measure of nuclear stability (peaks near Fe-56 ≈ 8.8 MeV). Fusion of light nuclei and fission of heavy nuclei both increase it and release energy.',
    sheet: 'syllabus',
    hsc: ['Binding energy per nucleon of carbon-12'],
    example: { E: 28.3 * 1.602e-13, A: 4 },
    priority: 3,
  },
  {
    id: 'nuclear_count',
    name: 'Number of reactions for a total energy or power',
    module: 'm8',
    topic: 'nuclear',
    equation: 'E_{total} = nE_{reaction}',
    vars: [v('Et', 'E_{total}', 'Total energy', 'energy', { concept: 'E', positive: true }), v('n', 'n', 'Number of reactions/nuclei', 'count', { concept: 'nReact', positive: true }), v('Er', 'E_{reaction}', 'Energy per reaction', 'energyNuclear', { concept: 'Enuc', positive: true })],
    solve: {
      Et: { expr: '#n #Er', fn: ({ n, Er }) => n * Er },
      n: { expr: '\\frac{#Et}{#Er}', fn: ({ Et, Er }) => Et / Er },
      Er: { expr: '\\frac{#Et}{#n}', fn: ({ Et, n }) => Et / n },
    },
    aliases: ['number of fissions', 'fissions per second', 'reactions per second', 'reactor output'],
    when: 'A reactor or star producing total energy from many identical reactions. With power: reactions per second = P / E_reaction.',
    sheet: 'exam',
    hsc: ['Fissions per second in a 1000 MW reactor'],
    example: { n: 1e20, Er: 200 * 1.602e-13 },
    priority: 2,
  },
  {
    id: 'nuclei_in_mass',
    name: 'Number of nuclei in a sample',
    module: 'm8',
    topic: 'nuclear',
    alsoIn: ['radioactivity'],
    equation: 'N = \\frac{m}{m_{atom}}',
    vars: [v('N', 'N', 'Number of nuclei (atoms)', 'count', { concept: 'nReact', positive: true }), v('m', 'm', 'Mass of sample', 'mass', { concept: 'mSample', positive: true }), v('ma', 'm_{atom}', 'Mass of one atom', 'atomicMass', { concept: 'mAtom', positive: true })],
    solve: {
      N: { expr: '\\frac{#m}{#ma}', fn: ({ m, ma }) => m / ma },
      m: { expr: '#N #ma', fn: ({ N, ma }) => N * ma },
      ma: { expr: '\\frac{#m}{#N}', fn: ({ m, N }) => m / N },
    },
    aliases: ['number of atoms', 'number of nuclei', 'atoms in a kilogram'],
    when: 'Number of atoms in a sample from the mass of one atom (atomic mass in u × 1.661 × 10⁻²⁷ kg).',
    sheet: 'derived',
    hsc: ['Energy released by fission of 1.0 kg of U-235'],
    example: { m: 1, ma: 235 * 1.661e-27 },
    priority: 2,
  },
  // ───────────── Radioactivity ─────────────
  {
    id: 'decay_law',
    name: 'Radioactive decay law',
    module: 'm8',
    topic: 'radioactivity',
    equation: 'N_t = N_0e^{-\\lambda t}',
    vars: [v('N', 'N_t', 'Amount remaining (nuclei, mass, activity or %)', 'amount', { concept: 'Nt', nonNegative: true }), v('N0', 'N_0', 'Initial amount (same units as N_t)', 'amount', { concept: 'N0', positive: true }), v('lam', '\\lambda', 'Decay constant', 'decayConst', { concept: 'lambdaD', positive: true }), v('t', 't', 'Time elapsed', 'longTime', { nonNegative: true })],
    solve: {
      N: { expr: '#N0 e^{-#lam #t}', fn: ({ N0, lam, t }) => N0 * Math.exp(-lam * t) },
      N0: { expr: '#N e^{#lam #t}', fn: ({ N, lam, t }) => N * Math.exp(lam * t) },
      lam: { expr: '\\frac{\\ln(#N0 / #N)}{#t}', fn: ({ N, N0, t }) => Math.log(N0 / N) / t },
      t: { expr: '\\frac{\\ln(#N0 / #N)}{#lam}', fn: ({ N, N0, lam }) => Math.log(N0 / N) / lam },
    },
    aliases: ['decay', 'radioactive decay', 'exponential decay', 'N0 e^-lambda t', 'remaining', 'carbon dating', 'undecayed'],
    when: 'Amount of a radioisotope remaining after time t. N can be number of nuclei, mass or activity (all decay the same way) — use the same unit for N and N₀. λ and t must use the same time unit.',
    checks: ({ N, N0 }) => (N > N0 * (1 + 1e-9) ? [{ level: 'error', message: 'The remaining amount cannot exceed the initial amount in radioactive decay.' }] : []),
    sheet: 'sheet',
    hsc: ['Mass remaining after 90 years (t½ = 30 years)', 'Age of a sample by carbon dating', 'Time for activity to fall to 10 %'],
    example: { N0: 120, lam: LN2 / 30, t: 90 },
    priority: 5,
  },
  {
    id: 'decay_const',
    name: 'Decay constant and half-life',
    module: 'm8',
    topic: 'radioactivity',
    equation: '\\lambda = \\frac{\\ln 2}{t_{1/2}}',
    vars: [v('lam', '\\lambda', 'Decay constant', 'decayConst', { concept: 'lambdaD', positive: true }), v('th', 't_{1/2}', 'Half-life', 'longTime', { concept: 'tHalf', positive: true })],
    solve: {
      lam: { expr: '\\frac{\\ln 2}{#th}', fn: ({ th }) => LN2 / th },
      th: { expr: '\\frac{\\ln 2}{#lam}', fn: ({ lam }) => LN2 / lam },
    },
    aliases: ['decay constant', 'half-life', 'half life', 'ln2'],
    when: 'Converting between half-life and decay constant (same time unit in both).',
    sheet: 'sheet',
    hsc: ['Decay constant of iodine-131 (t½ = 8.02 days)'],
    example: { th: 30 },
    priority: 5,
  },
  {
    id: 'half_life_n',
    name: 'Number of half-lives',
    module: 'm8',
    topic: 'radioactivity',
    equation: 'n = \\frac{t}{t_{1/2}}',
    vars: [v('n', 'n', 'Number of half-lives elapsed', 'ratio', { concept: 'nHalf', nonNegative: true }), v('t', 't', 'Time elapsed', 'longTime', { nonNegative: true }), v('th', 't_{1/2}', 'Half-life', 'longTime', { concept: 'tHalf', positive: true })],
    solve: {
      n: { expr: '\\frac{#t}{#th}', fn: ({ t, th }) => t / th },
      t: { expr: '#n #th', fn: ({ n, th }) => n * th },
      th: { expr: '\\frac{#t}{#n}', fn: ({ t, n }) => t / n },
    },
    aliases: ['number of half-lives', 'half lives elapsed'],
    when: 'How many half-lives fit into the elapsed time.',
    sheet: 'derived',
    hsc: ['90 years with a half-life of 30 years = 3 half-lives'],
    example: { t: 90, th: 30 },
    priority: 3,
  },
  {
    id: 'half_life_amount',
    name: 'Amount remaining after n half-lives',
    module: 'm8',
    topic: 'radioactivity',
    equation: 'N = N_0\\left(\\tfrac{1}{2}\\right)^{n}',
    vars: [v('N', 'N', 'Amount remaining', 'amount', { concept: 'Nt', nonNegative: true }), v('N0', 'N_0', 'Initial amount', 'amount', { concept: 'N0', positive: true }), v('n', 'n', 'Number of half-lives', 'ratio', { concept: 'nHalf', nonNegative: true })],
    solve: {
      N: { expr: '#N0 \\left(\\tfrac{1}{2}\\right)^{#n}', fn: ({ N0, n }) => N0 * Math.pow(0.5, n) },
      N0: { expr: '#N \\times 2^{#n}', fn: ({ N, n }) => N * Math.pow(2, n) },
      n: { expr: '\\log_2\\left(\\frac{#N0}{#N}\\right)', fn: ({ N, N0 }) => Math.log2(N0 / N) },
    },
    aliases: ['halving', 'half-life', 'fraction remaining', 'halved'],
    when: 'Each half-life halves the amount — identical to N₀e^(−λt) with n = t/t½.',
    derivation: ['N_0 e^{-\\lambda t} = N_0 e^{-(\\ln 2) t/t_{1/2}} = N_0 \\left(\\tfrac{1}{2}\\right)^{t/t_{1/2}}'],
    checks: ({ N, N0 }) => (N > N0 * (1 + 1e-9) ? [{ level: 'error', message: 'The remaining amount cannot exceed the initial amount.' }] : []),
    sheet: 'derived',
    hsc: ['120 g sample after 3 half-lives → 15 g'],
    example: { N0: 120, n: 3 },
    priority: 4,
    chainCost: 0.9,
  },
  {
    id: 'activity',
    name: 'Activity and number of nuclei',
    module: 'm8',
    topic: 'radioactivity',
    equation: 'A = \\lambda N',
    vars: [v('A', 'A', 'Activity', 'activity', { concept: 'Act', nonNegative: true }), v('lam', '\\lambda', 'Decay constant', 'decayConst', { concept: 'lambdaD', positive: true }), v('N', 'N', 'Number of undecayed nuclei', 'count', { concept: 'Nnuclei', nonNegative: true })],
    solve: {
      A: { expr: '#lam #N', fn: ({ lam, N }) => lam * N },
      lam: { expr: '\\frac{#A}{#N}', fn: ({ A, N }) => A / N },
      N: { expr: '\\frac{#A}{#lam}', fn: ({ A, lam }) => A / lam },
    },
    aliases: ['activity', 'becquerel', 'decays per second', 'count rate'],
    when: 'Decays per second. λ must be in s⁻¹ for A in Bq. Extension: not on the NESA sheet (activity ∝ N is enough for HSC questions).',
    sheet: 'extension',
    hsc: [],
    example: { lam: 1e-3, N: 1e12 },
    priority: 0,
    manualOnly: true,
  },
];

