/**
 * Global concept vocabulary. Formula variables map onto these shared concepts so the
 * chain solver can link formulas (σ from σ = F/A feeds E = σ/ε), and the Smart Solver
 * can map question wording ("elongation", "tensile load", "UTS"…) to variables.
 *
 * `keywords` are lower-case phrases searched for near a number or in "find …" clauses.
 * `symbols` are typed symbols (as in "F = 8 kN"); symbol clashes are resolved by unit dimension.
 */
import type { QuantityId } from './quantities';

export interface Concept {
  id: string;
  name: string;
  latex: string;
  quantity: QuantityId;
  keywords: string[];
  symbols?: string[];
}

const c = (id: string, name: string, latex: string, quantity: QuantityId, keywords: string[], symbols: string[] = []): Concept => ({ id, name, latex, quantity, keywords, symbols });

export const CONCEPTS: Concept[] = [
  // forces
  c('F', 'Force', 'F', 'force', ['force', 'load', 'tension', 'tensile load', 'tensile force', 'compressive load', 'compressive force', 'axial force', 'axial load', 'pull', 'push', 'applied force', 'point load', 'carries', 'subjected to', 'thrust load', 'shear force', 'braking force', 'average force', 'centripetal force'], ['F', 'P']),
  c('Wt', 'Weight', 'W', 'force', ['weight', 'weighs', 'weight force', 'gravitational force'], ['W', 'Fg']),
  c('Rres', 'Resultant force', 'R', 'force', ['resultant', 'resultant force', 'equilibrant', 'magnitude of the resultant'], ['R']),
  c('Fx', 'Horizontal component', 'F_x', 'force', ['horizontal component', 'x component', 'x-component', 'sum of horizontal'], ['Fx']),
  c('Fy', 'Vertical component', 'F_y', 'force', ['vertical component', 'y component', 'y-component', 'sum of vertical'], ['Fy']),
  c('thetaR', 'Direction of resultant', '\\theta', 'angle', ['direction', 'direction of the resultant', 'angle of the resultant']),
  c('theta', 'Angle of force', '\\theta', 'angle', ['angle', 'inclined at', 'at an angle', 'to the horizontal'], ['θ', 'theta']),
  c('m', 'Mass', 'm', 'mass', ['mass', 'kg', 'tonne', 'car of', 'vehicle of', 'aircraft of', 'train of', 'block of', 'crate of', 'loaded mass', 'gross mass'], ['m']),
  c('a', 'Acceleration', 'a', 'acceleration', ['acceleration', 'accelerates', 'deceleration', 'decelerates', 'retardation'], ['a']),
  c('g', 'Gravitational acceleration', 'g', 'acceleration', ['gravitational acceleration', 'acceleration due to gravity', 'gravity'], ['g']),
  c('M', 'Moment / bending moment', 'M', 'moment', ['bending moment', 'moment', 'maximum bending moment', 'turning moment'], ['M', 'BM']),
  c('dist', 'Perpendicular distance', 'd', 'length', ['perpendicular distance', 'lever arm', 'moment arm', 'from the pivot', 'from the support', 'from the fulcrum', 'from the hinge', 'at a distance'], ['d']),
  c('torque', 'Torque', 'T', 'torque', ['torque', 'twisting moment'], ['T', 'τ']),
  c('radius', 'Radius', 'r', 'length', ['radius', 'radius of', 'wheel radius', 'crank', 'spanner length', 'curve of radius'], ['r']),
  // stress & strain
  c('sigma', 'Stress', '\\sigma', 'stress', ['stress', 'tensile stress', 'compressive stress', 'axial stress', 'direct stress', 'normal stress', 'engineering stress'], ['σ', 'sigma']),
  c('sigmaB', 'Bending stress', '\\sigma', 'stress', ['bending stress', 'flexural stress', 'maximum bending stress', 'extreme fibre stress']),
  c('eps', 'Strain', '\\varepsilon', 'ratio', ['strain', 'engineering strain'], ['ε', 'epsilon', 'e']),
  c('dL', 'Change in length', '\\Delta L', 'length', ['extension', 'elongation', 'change in length', 'stretches', 'stretched by', 'extends by', 'extended by', 'deformation', 'compresses by', 'shortens by', 'shortening', 'contraction', 'increase in length', 'decrease in length'], ['ΔL', 'dL', 'x', 'δ']),
  c('L0', 'Original length', 'L', 'length', ['original length', 'gauge length', 'length of', 'long', 'initial length', 'length'], ['L', 'L0', 'Lo']),
  c('Lf', 'Final length', 'L_f', 'length', ['final length', 'length after fracture', 'final gauge length', 'length at fracture']),
  c('youngs', "Young's modulus", 'E', 'modulus', ["young's modulus", 'youngs modulus', 'young’s modulus', 'modulus of elasticity', 'elastic modulus', 'modulus'], ['E', 'Y']),
  c('k', 'Stiffness', 'k', 'stiffness', ['spring constant', 'stiffness', 'spring rate'], ['k']),
  c('FoS', 'Factor of safety', 'FoS', 'ratio', ['factor of safety', 'safety factor', 'fos', 'f.o.s', 'f of s'], ['FoS', 'FOS', 'SF', 'n']),
  c('uts', 'Ultimate tensile strength', '\\sigma_{UTS}', 'stress', ['ultimate tensile strength', 'uts', 'ultimate strength', 'tensile strength', 'ultimate stress', 'breaking stress'], ['UTS']),
  c('sy', 'Yield stress', '\\sigma_y', 'stress', ['yield stress', 'yield strength', 'yield point', 'proof stress', 'elastic limit'], ['σy']),
  c('sw', 'Working (allowable) stress', '\\sigma_w', 'stress', ['working stress', 'allowable stress', 'permissible stress', 'safe stress', 'design stress', 'maximum allowable stress', 'safe working stress']),
  c('Ffail', 'Failure load', 'F_{fail}', 'force', ['breaking load', 'failure load', 'ultimate load', 'load at failure', 'maximum load']),
  c('Fw', 'Working load', 'F_w', 'force', ['working load', 'safe working load', 'swl', 'safe load']),
  c('yNA', 'Distance from neutral axis', 'y', 'length', ['distance from the neutral axis', 'from the neutral axis', 'extreme fibre', 'y max', 'ymax'], ['y']),
  c('Isec', 'Second moment of area', 'I', 'secondMoment', ['second moment of area', 'moment of inertia', 'second moment'], ['I']),
  c('Z', 'Section modulus', 'Z', 'sectionModulus', ['section modulus', 'elastic modulus of section'], ['Z']),
  c('breadth', 'Breadth', 'b', 'length', ['breadth', 'width', 'wide'], ['b']),
  c('depth', 'Depth', 'd', 'length', ['depth', 'deep', 'height of section', 'depth of section', 'water depth', 'below the surface', 'depth of water'], ['d', 'h']),
  c('dia', 'Diameter', 'd', 'length', ['diameter', 'dia', 'diameter of', 'bore'], ['d', 'D', 'Ø', 'ø']),
  c('Dout', 'Outside diameter', 'D', 'length', ['outside diameter', 'outer diameter', 'external diameter', 'od'], ['D', 'Do']),
  c('Din', 'Inside diameter', 'd', 'length', ['inside diameter', 'inner diameter', 'internal diameter', 'id', 'bore of'], ['Di']),
  c('A', 'Area', 'A', 'area', ['area', 'cross-sectional area', 'cross sectional area', 'csa', 'contact area', 'surface area'], ['A', 'CSA']),
  c('tau', 'Shear stress', '\\tau', 'stress', ['shear stress', 'shearing stress'], ['τ', 'tau']),
  c('shearPlanes', 'Number of shear planes', 'n', 'count', ['shear planes']),
  c('pctEl', 'Percentage elongation', '\\%El', 'percent', ['percentage elongation', 'percent elongation', '% elongation', 'ductility']),
  c('pctRA', 'Reduction in area', '\\%RA', 'percent', ['reduction in area', 'reduction of area', 'percentage reduction']),
  c('A0', 'Original area', 'A_0', 'area', ['original area', 'original cross-sectional area', 'initial area']),
  c('Af', 'Final area', 'A_f', 'area', ['final area', 'area at fracture', 'necked area']),
  c('U', 'Strain energy', 'U', 'energy', ['strain energy', 'energy stored']),
  c('resilience', 'Strain energy per volume', 'u', 'energyDensity', ['modulus of resilience', 'resilience']),
  c('span', 'Span / beam length', 'L', 'length', ['span', 'beam length', 'long beam', 'metre beam', 'cantilever length', 'length of the beam', 'overhang'], ['L']),
  c('w', 'UDL intensity', 'w', 'udl', ['uniformly distributed load', 'udl', 'distributed load', 'per metre'], ['w']),
  c('udlTotal', 'Total UDL load', 'W', 'force', ['total distributed load', 'total udl']),
  c('p', 'Pressure', 'P', 'pressure', ['pressure', 'gauge pressure', 'fluid pressure', 'line pressure', 'bearing pressure', 'hydraulic pressure', 'tyre pressure'], ['p', 'P']),
  c('rho', 'Density', '\\rho', 'density', ['density', 'fluid density', 'air density', 'density of'], ['ρ', 'rho']),
  c('vol', 'Volume', 'V', 'volume', ['volume', 'capacity of tank']),
  // transport / mechanics
  c('Ff', 'Friction force', 'F_f', 'force', ['friction', 'frictional force', 'friction force', 'limiting friction', 'frictional resistance', 'force required to slide', 'force to slide', 'force needed to move', 'force required to move', 'force needed to push', 'force to push', 'force required to start'], ['Ff', 'Fr']),
  c('mu', 'Coefficient of friction', '\\mu', 'ratio', ['coefficient of friction', 'coefficient of static friction', 'friction coefficient', 'coefficient'], ['μ', 'mu', 'µ']),
  c('normal', 'Normal reaction', 'N', 'force', ['normal force', 'normal reaction', 'reaction force', 'normal'], ['N', 'Rn']),
  c('phi', 'Angle of friction / repose', '\\phi', 'angle', ['angle of repose', 'angle of friction', 'about to slide', 'starts to slide', 'begins to slide', 'on the point of sliding'], ['φ', 'phi']),
  c('incline', 'Incline angle', '\\theta', 'angle', ['incline', 'inclined', 'slope', 'ramp', 'gradient', 'hill', 'plane at', 'inclined plane'], []),
  c('Fpar', 'Component along slope', 'F_{\\parallel}', 'force', ['component down the slope', 'component along the incline', 'down the slope', 'gradient resistance']),
  c('work', 'Work done', 'W', 'energy', ['work done', 'work', 'work input', 'work output'], ['W']),
  c('energy', 'Energy', 'E', 'energy', ['energy', 'energy used', 'energy consumed', 'energy stored', 'electrical energy', 'kwh'], ['E']),
  c('KE', 'Kinetic energy', 'KE', 'energy', ['kinetic energy', 'ke', 'energy of motion', 'energy dissipated', 'energy absorbed by the brakes'], ['KE', 'Ek']),
  c('PE', 'Potential energy', 'PE', 'energy', ['potential energy', 'gravitational potential energy', 'pe', 'gpe'], ['PE', 'Ep', 'GPE']),
  c('h', 'Height', 'h', 'length', ['height', 'high', 'raised', 'lifted', 'lifts', 'vertical height', 'altitude', 'height lost', 'drops', 'falls', 'climbs', 'elevation'], ['h']),
  c('s', 'Displacement / distance', 's', 'length', ['distance', 'displacement', 'travels', 'moved', 'moves', 'stopping distance', 'braking distance', 'runway', 'over a distance', 'through a distance', 'covers'], ['s', 'd']),
  c('v', 'Velocity / speed', 'v', 'velocity', ['speed', 'velocity', 'travelling at', 'traveling at', 'moving at', 'final velocity', 'final speed', 'airspeed', 'cruising speed', 'at a speed', 'reaches'], ['v']),
  c('u', 'Initial velocity', 'u', 'velocity', ['initial velocity', 'initial speed', 'starting speed', 'from a speed', 'from rest', 'initially travelling'], ['u']),
  c('t', 'Time', 't', 'time', ['time', 'seconds', 'takes', 'in a time', 'duration', 'for', 'minutes', 'hours', 'delay', 'transfer time'], ['t']),
  c('P', 'Power', 'P', 'power', ['power', 'power output', 'power rating', 'rated at', 'power consumed', 'power dissipated', 'wattage'], ['P']),
  c('omega', 'Rotational speed', '\\omega', 'angularVelocity', ['rpm', 'rotational speed', 'angular velocity', 'revolutions per minute', 'rev/min', 'shaft speed', 'engine speed'], ['ω', 'N', 'omega']),
  c('eta', 'Efficiency', '\\eta', 'percent', ['efficiency', 'efficient', 'overall efficiency'], ['η', 'eta']),
  c('Pout', 'Output power', 'P_{out}', 'power', ['output power', 'power output', 'useful power', 'mechanical power output', 'output of', 'delivers', 'received power', 'power received'], ['Pout']),
  c('Pin', 'Input power', 'P_{in}', 'power', ['input power', 'power input', 'power supplied', 'electrical input', 'draws', 'consumes', 'transmitted power', 'launched power'], ['Pin']),
  c('Eout', 'Energy output', 'E_{out}', 'energy', ['useful energy', 'energy output', 'work output', 'useful work']),
  c('Ein', 'Energy input', 'E_{in}', 'energy', ['energy input', 'energy supplied', 'work input']),
  c('Ft', 'Tractive force', 'F_t', 'force', ['tractive force', 'tractive effort', 'driving force', 'engine force']),
  c('Fr', 'Resistance', 'F_r', 'force', ['resistance', 'total resistance to motion', 'rolling resistance', 'resistive force', 'resisting force']),
  c('pm', 'Momentum', 'p', 'momentum', ['momentum']),
  c('MA', 'Mechanical advantage', 'MA', 'ratio', ['mechanical advantage', 'ma', 'force ratio'], ['MA']),
  c('VR', 'Velocity ratio', 'VR', 'ratio', ['velocity ratio', 'vr', 'movement ratio', 'gear ratio', 'speed ratio'], ['VR', 'GR']),
  c('load', 'Load (machine output)', 'L', 'force', ['load', 'raise a load', 'lift a load', 'load of'], ['L']),
  c('effort', 'Effort', 'E', 'force', ['effort', 'effort force', 'input force', 'applied effort'], ['E']),
  c('distE', 'Distance moved by effort', 'd_E', 'length', ['distance moved by the effort', 'effort moves', 'effort distance', 'rope pulled', 'pulled through', 'handle moves']),
  c('distL', 'Distance moved by load', 'd_L', 'length', ['distance moved by the load', 'load moves', 'load distance', 'load is raised', 'load rises']),
  c('effortArm', 'Effort arm', 'a', 'length', ['effort arm', 'effort is applied', 'effort distance from fulcrum']),
  c('loadArm', 'Load arm', 'b', 'length', ['load arm', 'load is placed', 'load distance from fulcrum']),
  c('ropes', 'Supporting rope segments', 'n', 'count', ['supporting ropes', 'rope segments', 'falls of rope', 'ropes supporting']),
  c('Dwheel', 'Wheel diameter', 'D', 'length', ['wheel diameter', 'wheel of diameter', 'drum diameter', 'driven pulley diameter']),
  c('daxle', 'Axle diameter', 'd', 'length', ['axle diameter', 'axle of diameter', 'shaft diameter', 'driver pulley diameter']),
  c('handleR', 'Handle radius', 'R', 'length', ['handle radius', 'handle length', 'tommy bar']),
  c('pitch', 'Screw pitch', 'p', 'length', ['pitch', 'thread pitch', 'lead']),
  c('teethDriven', 'Teeth on driven gear', 'T_{driven}', 'count', ['teeth on the driven', 'driven gear', 'driven gear has', 'output gear']),
  c('teethDriver', 'Teeth on driver gear', 'T_{driver}', 'count', ['teeth on the driver', 'driver gear', 'driving gear', 'input gear', 'pinion']),
  c('speedDriven', 'Driven gear speed', 'N_{driven}', 'angularVelocity', ['output speed', 'driven gear speed', 'speed of the driven']),
  c('speedDriver', 'Driver gear speed', 'N_{driver}', 'angularVelocity', ['input speed', 'driver gear speed', 'speed of the driver', 'motor speed']),
  c('Tout', 'Output torque', 'T_{out}', 'torque', ['output torque', 'torque at the wheels', 'wheel torque']),
  c('Tin', 'Input torque', 'T_{in}', 'torque', ['input torque', 'engine torque', 'motor torque']),
  c('F1', 'Input piston force', 'F_1', 'force', ['input force', 'force on the small piston', 'small piston force', 'master cylinder force', 'pedal force', 'force applied to the small piston', 'effort piston']),
  c('F2', 'Output piston force', 'F_2', 'force', ['output force', 'force on the large piston', 'large piston force', 'slave cylinder force', 'force exerted by the large piston', 'ram force', 'calliper force']),
  c('A1', 'Input piston area', 'A_1', 'area', ['small piston area', 'area of the small piston', 'master cylinder area', 'input piston area']),
  c('A2', 'Output piston area', 'A_2', 'area', ['large piston area', 'area of the large piston', 'slave cylinder area', 'output piston area']),
  c('d1', 'Input piston diameter', 'd_1', 'length', ['small piston diameter', 'diameter of the small piston', 'master cylinder diameter', 'small piston has a diameter', 'input piston diameter', 'small piston of diameter']),
  c('d2', 'Output piston diameter', 'd_2', 'length', ['large piston diameter', 'diameter of the large piston', 'slave cylinder diameter', 'large piston has a diameter', 'output piston diameter', 'large piston of diameter', 'ram diameter']),
  c('s1', 'Input piston travel', 's_1', 'length', ['small piston moves', 'small piston travels', 'distance moved by the small piston']),
  c('s2', 'Output piston travel', 's_2', 'length', ['large piston moves', 'large piston rises', 'distance moved by the large piston']),
  // electricity
  c('V', 'Voltage', 'V', 'voltage', ['voltage', 'potential difference', 'supply', 'battery', 'volts', 'emf', 'voltage drop', 'source'], ['V', 'U']),
  c('I', 'Current', 'I', 'current', ['current', 'amps', 'draws a current', 'current of', 'total current'], ['I', 'i']),
  c('R', 'Resistance', 'R', 'resistance', ['resistance', 'resistor', 'total resistance', 'equivalent resistance', 'effective resistance'], ['R', 'RT', 'Rt']),
  c('R1', 'Resistor 1', 'R_1', 'resistance', [], ['R1']),
  c('R2', 'Resistor 2', 'R_2', 'resistance', [], ['R2']),
  c('Q', 'Charge / capacity', 'Q', 'charge', ['charge', 'capacity', 'battery capacity', 'amp-hour', 'amp hour'], ['Q']),
  c('Vp', 'Primary voltage', 'V_p', 'voltage', ['primary voltage', 'input voltage of the transformer', 'primary']),
  c('Vs', 'Secondary voltage', 'V_s', 'voltage', ['secondary voltage', 'output voltage of the transformer', 'secondary']),
  c('Np', 'Primary turns', 'N_p', 'count', ['primary turns', 'turns on the primary', 'primary coil']),
  c('Ns', 'Secondary turns', 'N_s', 'count', ['secondary turns', 'turns on the secondary', 'secondary coil']),
  c('Ip', 'Primary current', 'I_p', 'current', ['primary current']),
  c('Is', 'Secondary current', 'I_s', 'current', ['secondary current']),
  // aero
  c('Lift', 'Lift', 'L', 'force', ['lift', 'lift force', 'aerodynamic lift'], ['L']),
  c('Drag', 'Drag', 'D', 'force', ['drag', 'drag force', 'aerodynamic drag', 'air resistance'], ['D']),
  c('Th', 'Thrust', 'T', 'force', ['thrust', 'engine thrust', 'propulsive force'], ['T']),
  c('LD', 'Lift-to-drag ratio', 'L/D', 'ratio', ['lift to drag ratio', 'lift-to-drag ratio', 'l/d', 'glide ratio', 'lift/drag']),
  c('glideDist', 'Glide distance', 'x', 'length', ['glide distance', 'horizontal distance', 'how far', 'glides', 'range']),
  c('gamma', 'Glide angle', '\\gamma', 'angle', ['glide angle', 'angle of glide', 'glide path angle', 'angle of descent'], ['γ', 'gamma']),
  c('climbAngle', 'Climb angle', '\\gamma', 'angle', ['climb angle', 'angle of climb', 'climbing at', 'climbs at']),
  c('wingArea', 'Wing area', 'S', 'area', ['wing area', 'planform area', 'wing surface area', 'total wing area', 'frontal area', 'reference area'], ['S']),
  c('CL', 'Lift coefficient', 'C_L', 'ratio', ['lift coefficient', 'coefficient of lift', 'cl'], ['CL', 'Cl']),
  c('CD', 'Drag coefficient', 'C_D', 'ratio', ['drag coefficient', 'coefficient of drag', 'cd'], ['CD', 'Cd']),
  c('q', 'Dynamic pressure', 'q', 'pressure', ['dynamic pressure'], ['q']),
  c('p1', 'Pressure at point 1', 'P_1', 'pressure', ['pressure below', 'lower surface pressure', 'pressure under', 'freestream pressure', 'pressure at point 1']),
  c('p2', 'Pressure at point 2', 'P_2', 'pressure', ['pressure above', 'upper surface pressure', 'pressure over', 'pressure at point 2', 'throat pressure']),
  c('v1', 'Speed at point 1', 'v_1', 'velocity', ['below the wing', 'under the wing', 'lower surface', 'beneath the wing', 'underneath', 'speed at point 1', 'inlet speed']),
  c('v2', 'Speed at point 2', 'v_2', 'velocity', ['over the wing', 'above the wing', 'upper surface', 'over the top', 'across the top', 'speed at point 2', 'throat speed']),
  c('deltaP', 'Pressure difference', '\\Delta P', 'pressure', ['pressure difference', 'difference in pressure', 'pressure differential']),
  c('WL', 'Wing loading', 'WL', 'pressure', ['wing loading']),
  c('wingspan', 'Wingspan', 'b', 'length', ['wingspan', 'wing span', 'span of the wing']),
  c('AR', 'Aspect ratio', 'AR', 'ratio', ['aspect ratio']),
  c('loadFactor', 'Load factor', 'n', 'ratio', ['load factor', 'g loading', 'g-force', 'g force']),
  c('bankAngle', 'Bank angle', '\\phi', 'angle', ['bank angle', 'banked at', 'angle of bank', 'bank of']),
  c('mach', 'Mach number', 'M', 'ratio', ['mach number', 'mach']),
  c('soundSpeed', 'Speed of sound', 'a', 'velocity', ['speed of sound', 'sound travels']),
  c('mdot', 'Mass flow rate', '\\dot{m}', 'massFlow', ['mass flow', 'mass flow rate']),
  c('ve', 'Exhaust velocity', 'v_e', 'velocity', ['exhaust velocity', 'exit velocity', 'jet velocity']),
  c('vi', 'Inlet velocity', 'v_i', 'velocity', ['inlet velocity', 'intake velocity', 'flight speed']),
  // telecom
  c('c', 'Wave / signal speed', 'v', 'velocity', ['speed of light', 'wave speed', 'propagation speed', 'speed of the wave', 'signal speed'], ['c']),
  c('f', 'Frequency', 'f', 'frequency', ['frequency', 'hz', 'broadcasts at', 'transmits at', 'operates at', 'carrier frequency', 'signal frequency'], ['f']),
  c('lambda', 'Wavelength', '\\lambda', 'length', ['wavelength', 'wave length'], ['λ', 'lambda']),
  c('period', 'Period', 'T', 'time', ['period', 'periodic time', 'time for one cycle'], ['T']),
  c('antennaLength', 'Antenna length', 'L', 'length', ['antenna length', 'length of the antenna', 'aerial length', 'dipole length', 'length of a dipole', 'antenna']),
  c('gainDb', 'Gain (dB)', 'G_{dB}', 'decibel', ['gain', 'db gain', 'decibel gain', 'amplification', 'attenuation in db', 'loss in db']),
  c('Vout', 'Output voltage', 'V_{out}', 'voltage', ['output voltage', 'output signal voltage']),
  c('Vin', 'Input voltage', 'V_{in}', 'voltage', ['input voltage', 'input signal voltage']),
  c('lossDb', 'Total loss (dB)', '\\text{Loss}', 'decibel', ['total loss', 'total attenuation', 'loss']),
  c('alpha', 'Attenuation (dB/length)', '\\alpha', 'attenuation', ['attenuation', 'db/km', 'db per km', 'loss per km', 'attenuation coefficient'], ['α', 'alpha']),
  c('linkLength', 'Link length', '\\ell', 'length', ['link length', 'length of the fibre', 'fibre length', 'cable length', 'long fibre', 'km of fibre', 'length of cable']),
  c('theta1', 'Angle of incidence', '\\theta_1', 'angle', ['angle of incidence', 'incident angle', 'incidence', 'enters at'], ['θ1']),
  c('theta2', 'Angle of refraction', '\\theta_2', 'angle', ['angle of refraction', 'refracted angle', 'refraction angle'], ['θ2']),
  c('n1', 'Refractive index 1 (core)', 'n_1', 'ratio', ['core', 'refractive index of the core', 'core refractive index', 'core index', 'refractive index', 'index of refraction'], ['n1', 'n']),
  c('n2', 'Refractive index 2 (cladding)', 'n_2', 'ratio', ['cladding', 'refractive index of the cladding', 'cladding refractive index', 'cladding index'], ['n2']),
  c('thetaC', 'Critical angle', '\\theta_c', 'angle', ['critical angle'], ['θc']),
  c('vMedium', 'Speed of light in medium', 'v', 'velocity', ['speed of light in', 'speed in the fibre', 'speed in the core', 'speed in glass']),
  c('thetaA', 'Acceptance angle', '\\theta_a', 'angle', ['acceptance angle', 'acceptance cone', 'numerical aperture']),
  c('dataSize', 'Data size', 'D', 'data', ['file', 'file size', 'data', 'size of', 'download', 'video']),
  c('bitRate', 'Bit rate', 'R_b', 'dataRate', ['bit rate', 'data rate', 'speed of the connection', 'connection', 'link speed', 'bandwidth of', 'mbps', 'bps']),
  c('fs', 'Sampling frequency', 'f_s', 'frequency', ['sampling frequency', 'sampling rate', 'sample rate', 'sampled at']),
  c('fmax', 'Maximum signal frequency', 'f_{max}', 'frequency', ['highest frequency', 'maximum frequency', 'bandwidth of the signal', 'audio frequency', 'modulating frequency']),
  c('bitsPerSample', 'Bits per sample', 'n', 'count', ['bits per sample', 'bit resolution', '-bit', 'bit adc', 'bit samples']),
  c('channels', 'Channels', 'N_{ch}', 'count', ['channels', 'stereo']),
  c('levels', 'Quantisation levels', 'N', 'count', ['levels', 'quantisation levels', 'quantization levels']),
  c('modIndex', 'Modulation index', 'm', 'percent', ['modulation index', 'modulation depth', 'depth of modulation']),
  c('Vm', 'Message amplitude', 'V_m', 'voltage', ['message amplitude', 'modulating signal amplitude', 'audio amplitude']),
  c('Vc', 'Carrier amplitude', 'V_c', 'voltage', ['carrier amplitude']),
  c('bandwidth', 'Bandwidth', 'BW', 'frequency', ['bandwidth', 'bandwidth required']),
];

const BY_ID = new Map(CONCEPTS.map((x) => [x.id, x]));

export function getConcept(id: string): Concept | undefined {
  return BY_ID.get(id);
}
