/**
 * Aeronautical Engineering: flight forces, lift/drag, Bernoulli, fluid mechanics,
 * aircraft performance ratios. Scope is HSC-level (no compressible/university aerodynamics).
 */
import { FormulaDef, v } from './types';

const AERO = ['aero'] as const;

export const aeroFormulas: FormulaDef[] = [
  {
    id: 'levelLift',
    name: 'Straight & level flight: lift = weight',
    modules: [...AERO],
    topic: 'Flight forces',
    equation: 'L = W',
    vars: [v('Lift', 'L', 'Lift', 'force', { positive: true }), v('Wt', 'W', 'Weight', 'force', { positive: true })],
    solve: {
      Lift: { expr: '#Wt', fn: ({ Wt }) => Wt },
      Wt: { expr: '#Lift', fn: ({ Lift }) => Lift },
    },
    aliases: ['straight and level', 'level flight', 'cruise', 'lift equals weight', 'steady flight'],
    when: 'Unaccelerated straight-and-level flight: vertical forces balance (ΣFy = 0).',
    sheet: 'derived',
    source: 'Aeronautical — flight mechanics',
    hsc: ['Lift required for an aircraft of given mass in cruise'],
    example: { Wt: 50000 },
    contextOnly: ['aero'],
    priority: 2,
  },
  {
    id: 'levelThrust',
    name: 'Straight & level flight: thrust = drag',
    modules: [...AERO],
    topic: 'Flight forces',
    equation: 'T = D',
    vars: [v('Th', 'T', 'Thrust', 'force', { positive: true }), v('Drag', 'D', 'Drag', 'force', { positive: true })],
    solve: {
      Th: { expr: '#Drag', fn: ({ Drag }) => Drag },
      Drag: { expr: '#Th', fn: ({ Th }) => Th },
    },
    aliases: ['thrust equals drag', 'constant speed flight'],
    when: 'Constant airspeed in level flight: horizontal forces balance (ΣFx = 0).',
    sheet: 'derived',
    source: 'Aeronautical — flight mechanics',
    hsc: ['Thrust required in cruise given the L/D ratio'],
    example: { Drag: 3000 },
    contextOnly: ['aero'],
    priority: 2,
  },
  {
    id: 'liftDragRatio',
    name: 'Lift-to-drag ratio',
    modules: [...AERO],
    topic: 'Flight forces',
    equation: '\\frac{L}{D} = \\text{L/D ratio}',
    vars: [
      v('LD', 'L/D', 'Lift-to-drag ratio', 'ratio', { positive: true }),
      v('Lift', 'L', 'Lift', 'force', { positive: true }),
      v('Drag', 'D', 'Drag', 'force', { positive: true }),
    ],
    solve: {
      LD: { expr: '\\frac{#Lift}{#Drag}', fn: ({ Lift, Drag }) => Lift / Drag },
      Lift: { expr: '#LD \\times #Drag', fn: ({ LD, Drag }) => LD * Drag },
      Drag: { expr: '\\frac{#Lift}{#LD}', fn: ({ Lift, LD }) => Lift / LD },
    },
    aliases: ['lift to drag ratio', 'L/D', 'aerodynamic efficiency'],
    when: 'Aerodynamic efficiency of an aircraft; in level flight D = W/(L/D).',
    sheet: 'derived',
    source: 'Aeronautical — flight mechanics',
    hsc: ['Drag (and thrust required) in cruise from L/D', 'Comparing glider performance'],
    example: { Lift: 60000, Drag: 4000 },
    priority: 3,
  },
  {
    id: 'glideRatio',
    name: 'Glide ratio (distance)',
    modules: [...AERO],
    topic: 'Flight forces',
    equation: '\\frac{L}{D} = \\frac{\\text{horizontal distance}}{\\text{height lost}}',
    vars: [
      v('LD', 'L/D', 'Glide ratio (= L/D)', 'ratio', { positive: true }),
      v('gd', 'x', 'Horizontal glide distance', 'length', { concept: 'glideDist', positive: true }),
      v('gh', 'h', 'Height lost', 'length', { concept: 'h', positive: true }),
    ],
    solve: {
      LD: { expr: '\\frac{#gd}{#gh}', fn: ({ gd, gh }) => gd / gh },
      gd: { expr: '#LD \\times #gh', fn: ({ LD, gh }) => LD * gh },
      gh: { expr: '\\frac{#gd}{#LD}', fn: ({ gd, LD }) => gd / LD },
    },
    aliases: ['glide ratio', 'glide distance', 'glider', 'engine failure glide', 'how far can it glide'],
    when: 'Steady unpowered glide: glide ratio equals L/D.',
    sheet: 'derived',
    source: 'Aeronautical — flight mechanics',
    hsc: ['Distance a glider travels from a given altitude'],
    example: { gd: 30000, gh: 1000 },
    priority: 3,
  },
  {
    id: 'glideAngle',
    name: 'Glide angle',
    modules: [...AERO],
    topic: 'Flight forces',
    equation: '\\tan\\gamma = \\frac{D}{L} = \\frac{1}{L/D}',
    vars: [v('gamma', '\\gamma', 'Glide angle (below horizontal)', 'angle', { min: 0, max: Math.PI / 2 }), v('LD', 'L/D', 'Lift-to-drag ratio', 'ratio', { positive: true })],
    solve: {
      gamma: { expr: '\\tan^{-1}\\left(\\frac{1}{#LD}\\right)', fn: ({ LD }) => Math.atan(1 / LD) },
      LD: { expr: '\\frac{1}{\\tan(#gamma)}', fn: ({ gamma }) => 1 / Math.tan(gamma) },
    },
    aliases: ['glide angle', 'glide path angle', 'angle of descent'],
    when: 'In a steady glide the resultant aerodynamic force balances weight; tan γ = D/L.',
    sheet: 'derived',
    source: 'Aeronautical — flight mechanics',
    hsc: ['Glide angle of a sailplane with L/D = 40'],
    example: { LD: 20 },
    priority: 2,
  },
  {
    id: 'climbLift',
    name: 'Climbing flight: lift',
    modules: [...AERO],
    topic: 'Flight forces',
    equation: 'L = W\\cos\\gamma',
    vars: [
      v('Lift', 'L', 'Lift', 'force', { positive: true }),
      v('Wt', 'W', 'Weight', 'force', { positive: true }),
      v('gamma', '\\gamma', 'Climb angle', 'angle', { concept: 'climbAngle', min: 0, max: Math.PI / 2 }),
    ],
    solve: {
      Lift: { expr: '#Wt \\cos(#gamma)', fn: ({ Wt, gamma }) => Wt * Math.cos(gamma) },
      Wt: { expr: '\\frac{#Lift}{\\cos(#gamma)}', fn: ({ Lift, gamma }) => Lift / Math.cos(gamma) },
      gamma: { expr: '\\cos^{-1}\\left(\\frac{#Lift}{#Wt}\\right)', fn: ({ Lift, Wt }) => Math.acos(Lift / Wt) },
    },
    aliases: ['climb', 'climbing', 'climb angle lift'],
    when: 'Steady climb: resolve perpendicular to the flight path.',
    sheet: 'derived',
    source: 'Aeronautical — flight mechanics',
    hsc: ['Lift during a steady climb'],
    example: { Wt: 50000, gamma: (10 * Math.PI) / 180 },
    contextOnly: ['aero'],
    priority: 2,
  },
  {
    id: 'climbThrust',
    name: 'Climbing flight: thrust',
    modules: [...AERO],
    topic: 'Flight forces',
    equation: 'T = D + W\\sin\\gamma',
    vars: [
      v('Th', 'T', 'Thrust', 'force', { positive: true }),
      v('Drag', 'D', 'Drag', 'force', { nonNegative: true }),
      v('Wt', 'W', 'Weight', 'force', { positive: true }),
      v('gamma', '\\gamma', 'Climb angle', 'angle', { concept: 'climbAngle', min: 0, max: Math.PI / 2 }),
    ],
    solve: {
      Th: { expr: '#Drag + #Wt \\sin(#gamma)', fn: ({ Drag, Wt, gamma }) => Drag + Wt * Math.sin(gamma) },
      Drag: { expr: '#Th - #Wt \\sin(#gamma)', fn: ({ Th, Wt, gamma }) => Th - Wt * Math.sin(gamma) },
      Wt: { expr: '\\frac{#Th - #Drag}{\\sin(#gamma)}', fn: ({ Th, Drag, gamma }) => (Th - Drag) / Math.sin(gamma) },
      gamma: { expr: '\\sin^{-1}\\left(\\frac{#Th - #Drag}{#Wt}\\right)', fn: ({ Th, Drag, Wt }) => Math.asin((Th - Drag) / Wt) },
    },
    aliases: ['thrust in climb', 'excess thrust', 'climb thrust'],
    when: 'Steady climb: resolve along the flight path.',
    sheet: 'derived',
    source: 'Aeronautical — flight mechanics',
    hsc: ['Thrust required to climb at a given angle', 'Maximum climb angle from excess thrust'],
    example: { Drag: 4000, Wt: 50000, gamma: (8 * Math.PI) / 180 },
    contextOnly: ['aero'],
    priority: 2,
  },
  {
    id: 'liftEquation',
    name: 'Lift equation',
    modules: [...AERO],
    topic: 'Lift & drag',
    equation: 'L = \\tfrac{1}{2}\\rho v^2 S C_L',
    vars: [
      v('Lift', 'L', 'Lift', 'force'),
      v('rho', '\\rho', 'Air density', 'density', { positive: true }),
      v('v', 'v', 'Airspeed', 'velocity', { positive: true }),
      v('S', 'S', 'Wing (planform) area', 'area', { concept: 'wingArea', positive: true }),
      v('CL', 'C_L', 'Lift coefficient', 'ratio', { warnAbove: 3, warnText: 'C_L above ~3 is beyond even high-lift devices.' }),
    ],
    solve: {
      Lift: { expr: '\\tfrac{1}{2} #rho #v^2 #S #CL', fn: ({ rho, v, S, CL }) => 0.5 * rho * v * v * S * CL },
      rho: { expr: '\\frac{2 #Lift}{#v^2 #S #CL}', fn: ({ Lift, v, S, CL }) => (2 * Lift) / (v * v * S * CL) },
      v: { expr: '\\sqrt{\\frac{2 #Lift}{#rho #S #CL}}', fn: ({ Lift, rho, S, CL }) => Math.sqrt((2 * Lift) / (rho * S * CL)) },
      S: { expr: '\\frac{2 #Lift}{#rho #v^2 #CL}', fn: ({ Lift, rho, v, CL }) => (2 * Lift) / (rho * v * v * CL) },
      CL: { expr: '\\frac{2 #Lift}{#rho #v^2 #S}', fn: ({ Lift, rho, v, S }) => (2 * Lift) / (rho * v * v * S) },
    },
    aliases: ['lift equation', 'lift coefficient', 'CL', 'stall speed', 'take-off speed'],
    when: 'Lift from airspeed, air density, wing area and C_L (angle of attack). Stall speed uses C_L,max.',
    sheet: 'no',
    source: 'Aeronautical — aerodynamics',
    hsc: ['Effect of doubling airspeed on lift (×4)', 'Minimum speed to generate lift equal to weight'],
    example: { rho: 1.225, v: 60, S: 16, CL: 0.5 },
    extension: true,
    priority: 2,
  },
  {
    id: 'dragEquation',
    name: 'Drag equation',
    modules: [...AERO, 'transport'],
    topic: 'Lift & drag',
    equation: 'D = \\tfrac{1}{2}\\rho v^2 A C_D',
    vars: [
      v('Drag', 'D', 'Drag force', 'force'),
      v('rho', '\\rho', 'Fluid (air) density', 'density', { positive: true }),
      v('v', 'v', 'Speed', 'velocity', { positive: true }),
      v('S', 'A', 'Reference area (wing or frontal area)', 'area', { concept: 'wingArea', positive: true }),
      v('CD', 'C_D', 'Drag coefficient', 'ratio', { positive: true }),
    ],
    solve: {
      Drag: { expr: '\\tfrac{1}{2} #rho #v^2 #S #CD', fn: ({ rho, v, S, CD }) => 0.5 * rho * v * v * S * CD },
      rho: { expr: '\\frac{2 #Drag}{#v^2 #S #CD}', fn: ({ Drag, v, S, CD }) => (2 * Drag) / (v * v * S * CD) },
      v: { expr: '\\sqrt{\\frac{2 #Drag}{#rho #S #CD}}', fn: ({ Drag, rho, S, CD }) => Math.sqrt((2 * Drag) / (rho * S * CD)) },
      S: { expr: '\\frac{2 #Drag}{#rho #v^2 #CD}', fn: ({ Drag, rho, v, CD }) => (2 * Drag) / (rho * v * v * CD) },
      CD: { expr: '\\frac{2 #Drag}{#rho #v^2 #S}', fn: ({ Drag, rho, v, S }) => (2 * Drag) / (rho * v * v * S) },
    },
    aliases: ['drag equation', 'drag coefficient', 'CD', 'aerodynamic drag', 'air resistance'],
    when: 'Aerodynamic drag on aircraft or vehicles (drag rises with v²).',
    sheet: 'no',
    source: 'Aeronautical — aerodynamics',
    hsc: ['Drag on a car at highway speed', 'Power to overcome drag (P = Dv)'],
    example: { rho: 1.225, v: 30, S: 2.2, CD: 0.3 },
    extension: true,
    priority: 2,
  },
  {
    id: 'dynamicPressure',
    name: 'Dynamic pressure',
    modules: [...AERO],
    topic: 'Fluid mechanics',
    equation: 'q = \\tfrac{1}{2}\\rho v^2',
    vars: [v('q', 'q', 'Dynamic pressure', 'pressure'), v('rho', '\\rho', 'Fluid density', 'density', { positive: true }), v('v', 'v', 'Flow speed / airspeed', 'velocity', { nonNegative: true })],
    solve: {
      q: { expr: '\\tfrac{1}{2} #rho #v^2', fn: ({ rho, v }) => 0.5 * rho * v * v },
      rho: { expr: '\\frac{2 #q}{#v^2}', fn: ({ q, v }) => (2 * q) / (v * v) },
      v: { expr: '\\sqrt{\\frac{2 #q}{#rho}}', fn: ({ q, rho }) => Math.sqrt((2 * q) / rho) },
    },
    aliases: ['dynamic pressure', 'pitot tube', 'airspeed indicator', 'stagnation pressure difference'],
    when: 'Pressure associated with fluid motion; a pitot-static system measures q to give airspeed.',
    sheet: 'derived',
    source: 'Aeronautical — fluid mechanics',
    hsc: ['Airspeed from a pitot-static pressure difference'],
    example: { rho: 1.225, v: 70 },
    priority: 2,
  },
  {
    id: 'bernoulli',
    name: "Bernoulli's principle (horizontal flow)",
    modules: [...AERO],
    topic: 'Fluid mechanics',
    equation: 'P_1 + \\tfrac{1}{2}\\rho v_1^2 = P_2 + \\tfrac{1}{2}\\rho v_2^2',
    vars: [
      v('p2', 'P_2', 'Static pressure at point 2 (e.g. upper wing surface)', 'pressure'),
      v('p1', 'P_1', 'Static pressure at point 1 (e.g. lower surface / freestream)', 'pressure'),
      v('rho', '\\rho', 'Fluid density', 'density', { positive: true }),
      v('v1', 'v_1', 'Flow speed at point 1', 'velocity', { nonNegative: true }),
      v('v2', 'v_2', 'Flow speed at point 2', 'velocity', { nonNegative: true }),
    ],
    solve: {
      p2: { expr: '#p1 + \\tfrac{1}{2} #rho (#v1^2 - #v2^2)', fn: ({ p1, rho, v1, v2 }) => p1 + 0.5 * rho * (v1 * v1 - v2 * v2) },
      p1: { expr: '#p2 + \\tfrac{1}{2} #rho (#v2^2 - #v1^2)', fn: ({ p2, rho, v1, v2 }) => p2 + 0.5 * rho * (v2 * v2 - v1 * v1) },
      rho: { expr: '\\frac{2 (#p1 - #p2)}{#v2^2 - #v1^2}', fn: ({ p1, p2, v1, v2 }) => (2 * (p1 - p2)) / (v2 * v2 - v1 * v1) },
      v1: { expr: '\\sqrt{#v2^2 - \\frac{2 (#p1 - #p2)}{#rho}}', fn: ({ p1, p2, rho, v2 }) => Math.sqrt(v2 * v2 - (2 * (p1 - p2)) / rho) },
      v2: { expr: '\\sqrt{#v1^2 + \\frac{2 (#p1 - #p2)}{#rho}}', fn: ({ p1, p2, rho, v1 }) => Math.sqrt(v1 * v1 + (2 * (p1 - p2)) / rho) },
    },
    aliases: ["bernoulli's principle", 'bernoulli', 'venturi', 'faster air lower pressure'],
    when: 'Along a streamline, faster flow ⇒ lower static pressure (basis of the pressure explanation of lift).',
    sheet: 'yes',
    source: 'Aeronautical — fluid mechanics',
    hsc: ['Pressure on the upper surface of a wing given airspeeds above and below', 'Venturi pressure drop'],
    example: { p1: 101300, rho: 1.225, v1: 60, v2: 70 },
    priority: 2,
  },
  {
    id: 'bernoulliDp',
    name: 'Pressure difference across a wing (Bernoulli)',
    modules: [...AERO],
    topic: 'Lift & drag',
    equation: '\\Delta P = \\tfrac{1}{2}\\rho (v_{upper}^2 - v_{lower}^2)',
    vars: [
      v('dP', '\\Delta P', 'Pressure difference (lower − upper)', 'pressure', { concept: 'deltaP' }),
      v('rho', '\\rho', 'Air density', 'density', { positive: true }),
      v('vu', 'v_{upper}', 'Airflow speed over upper surface', 'velocity', { concept: 'v2', nonNegative: true }),
      v('vl', 'v_{lower}', 'Airflow speed under lower surface', 'velocity', { concept: 'v1', nonNegative: true }),
    ],
    solve: {
      dP: { expr: '\\tfrac{1}{2} #rho (#vu^2 - #vl^2)', fn: ({ rho, vu, vl }) => 0.5 * rho * (vu * vu - vl * vl) },
      rho: { expr: '\\frac{2 #dP}{#vu^2 - #vl^2}', fn: ({ dP, vu, vl }) => (2 * dP) / (vu * vu - vl * vl) },
      vu: { expr: '\\sqrt{#vl^2 + \\frac{2 #dP}{#rho}}', fn: ({ dP, rho, vl }) => Math.sqrt(vl * vl + (2 * dP) / rho) },
      vl: { expr: '\\sqrt{#vu^2 - \\frac{2 #dP}{#rho}}', fn: ({ dP, rho, vu }) => Math.sqrt(vu * vu - (2 * dP) / rho) },
    },
    aliases: ['pressure difference', 'upper surface velocity', 'lower surface velocity', 'wing pressure'],
    when: 'Pressure difference generated by faster flow over the upper surface.',
    sheet: 'derived',
    source: 'Aeronautical — fluid mechanics',
    hsc: ['Lift on a wing from upper/lower surface airspeeds'],
    example: { rho: 1.225, vu: 75, vl: 65 },
    priority: 3,
  },
  {
    id: 'liftFromDp',
    name: 'Lift from pressure difference',
    modules: [...AERO],
    topic: 'Lift & drag',
    equation: 'L = \\Delta P \\times S',
    vars: [
      v('Lift', 'L', 'Lift', 'force'),
      v('dP', '\\Delta P', 'Average pressure difference', 'pressure', { concept: 'deltaP' }),
      v('S', 'S', 'Wing area', 'area', { concept: 'wingArea', positive: true }),
    ],
    solve: {
      Lift: { expr: '#dP \\times #S', fn: ({ dP, S }) => dP * S },
      dP: { expr: '\\frac{#Lift}{#S}', fn: ({ Lift, S }) => Lift / S },
      S: { expr: '\\frac{#Lift}{#dP}', fn: ({ Lift, dP }) => Lift / dP },
    },
    aliases: ['lift from pressure', 'pressure times area', 'wing area'],
    when: 'Lift equals the pressure difference acting over the wing planform area.',
    sheet: 'derived',
    source: 'Aeronautical — fluid mechanics',
    hsc: ['Lift generated by a wing of given area', 'Required pressure difference for lift = weight'],
    example: { dP: 900, S: 20 },
    priority: 3,
  },
  {
    id: 'continuity',
    name: 'Continuity equation',
    modules: [...AERO],
    topic: 'Fluid mechanics',
    equation: 'A_1 v_1 = A_2 v_2',
    vars: [
      v('v2', 'v_2', 'Speed at section 2', 'velocity', { positive: true }),
      v('A1', 'A_1', 'Area at section 1', 'area', { positive: true }),
      v('v1', 'v_1', 'Speed at section 1', 'velocity', { positive: true }),
      v('A2', 'A_2', 'Area at section 2', 'area', { positive: true }),
    ],
    solve: {
      v2: { expr: '\\frac{#A1 #v1}{#A2}', fn: ({ A1, v1, A2 }) => (A1 * v1) / A2 },
      v1: { expr: '\\frac{#A2 #v2}{#A1}', fn: ({ A2, v2, A1 }) => (A2 * v2) / A1 },
      A1: { expr: '\\frac{#A2 #v2}{#v1}', fn: ({ A2, v2, v1 }) => (A2 * v2) / v1 },
      A2: { expr: '\\frac{#A1 #v1}{#v2}', fn: ({ A1, v1, v2 }) => (A1 * v1) / v2 },
    },
    aliases: ['continuity', 'venturi throat', 'flow rate'],
    when: 'Incompressible flow through a duct/venturi: volume flow rate is constant.',
    sheet: 'no',
    source: 'Aeronautical — fluid mechanics',
    hsc: ['Airspeed in a venturi throat'],
    example: { A1: 0.02, v1: 10, A2: 0.01 },
    extension: true,
    priority: 1,
  },
  {
    id: 'wingLoading',
    name: 'Wing loading',
    modules: [...AERO],
    topic: 'Aircraft performance',
    equation: 'WL = \\frac{W}{S}',
    vars: [v('WL', 'WL', 'Wing loading', 'pressure', { positive: true }), v('Wt', 'W', 'Weight', 'force', { positive: true }), v('S', 'S', 'Wing area', 'area', { concept: 'wingArea', positive: true })],
    solve: {
      WL: { expr: '\\frac{#Wt}{#S}', fn: ({ Wt, S }) => Wt / S },
      Wt: { expr: '#WL \\times #S', fn: ({ WL, S }) => WL * S },
      S: { expr: '\\frac{#Wt}{#WL}', fn: ({ Wt, WL }) => Wt / WL },
    },
    aliases: ['wing loading'],
    when: 'Weight per unit wing area (affects stall speed and gust response). In level flight WL equals the average ΔP.',
    sheet: 'no',
    source: 'Aeronautical — aircraft design',
    hsc: ['Comparing wing loading of a glider and an airliner'],
    example: { Wt: 10000, S: 16 },
    priority: 1,
  },
  {
    id: 'aspectRatio',
    name: 'Aspect ratio',
    modules: [...AERO],
    topic: 'Aircraft performance',
    equation: 'AR = \\frac{b^2}{S}',
    vars: [v('AR', 'AR', 'Aspect ratio', 'ratio', { positive: true }), v('bw', 'b', 'Wingspan', 'length', { concept: 'wingspan', positive: true }), v('S', 'S', 'Wing area', 'area', { concept: 'wingArea', positive: true })],
    solve: {
      AR: { expr: '\\frac{#bw^2}{#S}', fn: ({ bw, S }) => (bw * bw) / S },
      bw: { expr: '\\sqrt{#AR \\times #S}', fn: ({ AR, S }) => Math.sqrt(AR * S) },
      S: { expr: '\\frac{#bw^2}{#AR}', fn: ({ bw, AR }) => (bw * bw) / AR },
    },
    aliases: ['aspect ratio', 'wingspan', 'span squared over area'],
    when: 'Wing slenderness — high AR reduces induced drag (gliders).',
    sheet: 'no',
    source: 'Aeronautical — aircraft design',
    hsc: ['Why gliders have high aspect ratio wings'],
    example: { bw: 15, S: 12 },
    extension: true,
    priority: 1,
  },
  {
    id: 'loadFactor',
    name: 'Load factor',
    modules: [...AERO],
    topic: 'Aircraft performance',
    equation: 'n = \\frac{L}{W}',
    vars: [v('nf', 'n', 'Load factor (g)', 'ratio', { concept: 'loadFactor' }), v('Lift', 'L', 'Lift', 'force'), v('Wt', 'W', 'Weight', 'force', { positive: true })],
    solve: {
      nf: { expr: '\\frac{#Lift}{#Wt}', fn: ({ Lift, Wt }) => Lift / Wt },
      Lift: { expr: '#nf \\times #Wt', fn: ({ nf, Wt }) => nf * Wt },
      Wt: { expr: '\\frac{#Lift}{#nf}', fn: ({ Lift, nf }) => Lift / nf },
    },
    aliases: ['load factor', 'g loading', 'g force on airframe'],
    when: 'Structural loading of the airframe in manoeuvres/gusts relative to 1 g.',
    sheet: 'no',
    source: 'Aeronautical — flight mechanics',
    hsc: ['Wing load during a 2 g pull-up'],
    example: { Lift: 100000, Wt: 50000 },
    extension: true,
    priority: 1,
  },
  {
    id: 'bankedTurn',
    name: 'Load factor in a level banked turn',
    modules: [...AERO],
    topic: 'Aircraft performance',
    equation: 'n = \\frac{1}{\\cos\\phi}',
    vars: [v('nf', 'n', 'Load factor', 'ratio', { concept: 'loadFactor', min: 1 }), v('phi', '\\phi', 'Bank angle', 'angle', { concept: 'bankAngle', min: 0, max: Math.PI / 2 - 1e-6 })],
    solve: {
      nf: { expr: '\\frac{1}{\\cos(#phi)}', fn: ({ phi }) => 1 / Math.cos(phi) },
      phi: { expr: '\\cos^{-1}\\left(\\frac{1}{#nf}\\right)', fn: ({ nf }) => Math.acos(1 / nf) },
    },
    aliases: ['banked turn', 'bank angle', 'turning flight', '60 degree bank'],
    when: 'Lift must increase in a level turn: L = W/cos φ.',
    sheet: 'no',
    source: 'Aeronautical — flight mechanics',
    hsc: ['Lift needed in a 60° banked turn (2 g)'],
    example: { phi: Math.PI / 3 },
    extension: true,
    priority: 1,
  },
  {
    id: 'mach',
    name: 'Mach number',
    modules: [...AERO],
    topic: 'Aircraft performance',
    equation: 'M = \\frac{v}{a}',
    vars: [v('Ma', 'M', 'Mach number', 'ratio', { concept: 'mach', nonNegative: true }), v('v', 'v', 'True airspeed', 'velocity', { nonNegative: true }), v('a', 'a', 'Local speed of sound', 'velocity', { concept: 'soundSpeed', positive: true })],
    solve: {
      Ma: { expr: '\\frac{#v}{#a}', fn: ({ v, a }) => v / a },
      v: { expr: '#Ma \\times #a', fn: ({ Ma, a }) => Ma * a },
      a: { expr: '\\frac{#v}{#Ma}', fn: ({ v, Ma }) => v / Ma },
    },
    aliases: ['mach number', 'speed of sound', 'supersonic', 'transonic'],
    when: 'Speed relative to the speed of sound (≈ 340 m/s at sea level).',
    sheet: 'no',
    source: 'Aeronautical — flight mechanics',
    hsc: ['Mach number of Concorde at cruise'],
    example: { v: 250, a: 340 },
    extension: true,
    priority: 1,
  },
  {
    id: 'jetThrust',
    name: 'Jet / propeller thrust (momentum)',
    modules: [...AERO],
    topic: 'Propulsion',
    equation: 'T = \\dot{m}(v_e - v_i)',
    vars: [
      v('Th', 'T', 'Thrust', 'force'),
      v('mdot', '\\dot{m}', 'Mass flow rate of air/exhaust', 'massFlow', { positive: true }),
      v('ve', 'v_e', 'Exhaust (exit) velocity', 'velocity'),
      v('vi', 'v_i', 'Inlet (flight) velocity', 'velocity'),
    ],
    solve: {
      Th: { expr: '#mdot (#ve - #vi)', fn: ({ mdot, ve, vi }) => mdot * (ve - vi) },
      mdot: { expr: '\\frac{#Th}{#ve - #vi}', fn: ({ Th, ve, vi }) => Th / (ve - vi) },
      ve: { expr: '#vi + \\frac{#Th}{#mdot}', fn: ({ Th, mdot, vi }) => vi + Th / mdot },
      vi: { expr: '#ve - \\frac{#Th}{#mdot}', fn: ({ Th, mdot, ve }) => ve - Th / mdot },
    },
    aliases: ['jet thrust', 'mass flow', 'turbofan', 'newton third law propulsion'],
    when: 'Thrust from accelerating a mass of air (Newton’s 2nd/3rd laws).',
    sheet: 'no',
    source: 'Aeronautical — propulsion',
    hsc: ['Thrust of a jet engine from mass flow and velocity change'],
    example: { mdot: 100, ve: 400, vi: 200 },
    extension: true,
    priority: 0,
  },
];
