/**
 * Civil Structures: stress/strain, material testing, bending, section properties,
 * standard beam results, hydrostatics.
 */
import { FormulaDef, gVar, v } from './types';

const MAT = ['civil', 'transport', 'aero'] as const;

export const civilFormulas: FormulaDef[] = [
  {
    id: 'stress',
    name: 'Engineering stress (axial)',
    modules: [...MAT],
    topic: 'Stress & strain',
    equation: '\\sigma = \\frac{F}{A}',
    vars: [
      v('sigma', '\\sigma', 'Stress (tensile or compressive)', 'stress'),
      v('F', 'F', 'Axial force (tension or compression)', 'force'),
      v('A', 'A', 'Cross-sectional area', 'area', { positive: true }),
    ],
    solve: {
      sigma: { expr: '\\frac{#F}{#A}', fn: ({ F, A }) => F / A },
      F: { expr: '#sigma \\times #A', fn: ({ sigma, A }) => sigma * A },
      A: { expr: '\\frac{#F}{#sigma}', fn: ({ F, sigma }) => F / sigma },
    },
    aliases: ['stress', 'tensile stress', 'compressive stress', 'axial stress', 'normal stress', 'direct stress'],
    when: 'Internal force per unit area in a member under axial tension or compression.',
    sheet: 'yes',
    source: 'Engineering mechanics — stress & strain',
    hsc: ['Stress in a truss member once its force is known', 'Minimum diameter of a tie rod for an allowable stress', 'Stress in a cable of a suspension bridge'],
    example: { F: 8000, A: 200e-6 },
    priority: 6,
  },
  {
    id: 'strain',
    name: 'Engineering strain',
    modules: [...MAT],
    topic: 'Stress & strain',
    equation: '\\varepsilon = \\frac{\\Delta L}{L}',
    vars: [
      v('eps', '\\varepsilon', 'Strain', 'ratio', { warnAbove: 0.5, warnText: 'Strain above 0.5 (50%) is unusually large for an engineering material — check that ΔL and L are in the same units.' }),
      v('dL', '\\Delta L', 'Change in length (extension/compression)', 'length'),
      v('L0', 'L', 'Original length', 'length', { positive: true }),
    ],
    solve: {
      eps: { expr: '\\frac{#dL}{#L0}', fn: ({ dL, L0 }) => dL / L0 },
      dL: { expr: '#eps \\times #L0', fn: ({ eps, L0 }) => eps * L0 },
      L0: { expr: '\\frac{#dL}{#eps}', fn: ({ dL, eps }) => dL / eps },
    },
    aliases: ['strain', 'elongation over length', 'extension per unit length'],
    when: 'Deformation per unit original length.',
    sheet: 'yes',
    source: 'Engineering mechanics — stress & strain',
    hsc: ['Strain in a tensile test specimen', 'Extension of a cable from strain'],
    example: { dL: 0.5e-3, L0: 0.5 },
    priority: 6,
  },
  {
    id: 'youngs',
    name: "Young's modulus (modulus of elasticity)",
    modules: [...MAT],
    topic: 'Stress & strain',
    equation: 'E = \\frac{\\sigma}{\\varepsilon}',
    vars: [
      v('E', 'E', "Young's modulus", 'modulus', { concept: 'youngs', positive: true, warnAbove: 1.3e12, warnBelow: 1e6, warnText: "Young's modulus outside ~1 MPa – 1200 GPa is not a realistic engineering material." }),
      v('sigma', '\\sigma', 'Stress (within the elastic/proportional region)', 'stress'),
      v('eps', '\\varepsilon', 'Strain', 'ratio', { nonZero: true }),
    ],
    solve: {
      E: { expr: '\\frac{#sigma}{#eps}', fn: ({ sigma, eps }) => sigma / eps },
      sigma: { expr: '#E \\times #eps', fn: ({ E, eps }) => E * eps },
      eps: { expr: '\\frac{#sigma}{#E}', fn: ({ sigma, E }) => sigma / E },
    },
    aliases: ["young's modulus", 'modulus of elasticity', 'elastic modulus', 'modulus', 'stiffness of material', 'hooke'],
    when: 'Elastic stiffness of a material; valid only up to the limit of proportionality.',
    sheet: 'yes',
    source: 'Engineering mechanics — stress & strain',
    hsc: ['E from the slope of a stress–strain graph', 'Extension of a steel member given E'],
    example: { sigma: 200e6, eps: 0.001 },
    priority: 6,
  },
  {
    id: 'youngsCombined',
    name: "Young's modulus — combined form (extension)",
    modules: [...MAT],
    topic: 'Stress & strain',
    equation: 'E = \\frac{FL}{A\\Delta L}',
    vars: [
      v('E', 'E', "Young's modulus", 'modulus', { concept: 'youngs', positive: true }),
      v('F', 'F', 'Axial force', 'force'),
      v('L0', 'L', 'Original length', 'length', { positive: true }),
      v('A', 'A', 'Cross-sectional area', 'area', { positive: true }),
      v('dL', '\\Delta L', 'Change in length', 'length', { nonZero: true }),
    ],
    solve: {
      E: { expr: '\\frac{#F #L0}{#A #dL}', fn: ({ F, L0, A, dL }) => (F * L0) / (A * dL) },
      F: { expr: '\\frac{#E #A #dL}{#L0}', fn: ({ E, A, dL, L0 }) => (E * A * dL) / L0 },
      L0: { expr: '\\frac{#E #A #dL}{#F}', fn: ({ E, A, dL, F }) => (E * A * dL) / F },
      A: { expr: '\\frac{#F #L0}{#E #dL}', fn: ({ F, L0, E, dL }) => (F * L0) / (E * dL) },
      dL: { expr: '\\frac{#F #L0}{#A #E}', fn: ({ F, L0, A, E }) => (F * L0) / (A * E) },
    },
    aliases: ['extension of a bar', 'elongation', 'change in length', 'FL/AE', 'deformation'],
    when: 'Extension/compression of a member directly from load, length, area and E (combines σ = F/A, ε = ΔL/L, E = σ/ε).',
    sheet: 'derived',
    source: 'Engineering mechanics — stress & strain',
    hsc: ['Elongation of a steel tie under load', 'Change in length of a bridge cable'],
    example: { F: 10000, L0: 2, A: 100e-6, dL: 1e-3 },
    priority: 1,
    chainCost: 3.5,
  },
  {
    id: 'hooke',
    name: "Hooke's law (spring stiffness)",
    modules: [...MAT],
    topic: 'Stress & strain',
    equation: 'F = kx',
    vars: [
      v('F', 'F', 'Force', 'force'),
      v('k', 'k', 'Stiffness (spring constant)', 'stiffness', { positive: true }),
      v('x', 'x', 'Extension', 'length', { concept: 'dL' }),
    ],
    solve: {
      F: { expr: '#k \\times #x', fn: ({ k, x }) => k * x },
      k: { expr: '\\frac{#F}{#x}', fn: ({ F, x }) => F / x },
      x: { expr: '\\frac{#F}{#k}', fn: ({ F, k }) => F / k },
    },
    aliases: ["hooke's law", 'spring constant', 'spring stiffness', 'suspension spring'],
    when: 'Linear elastic springs and members (load ∝ extension).',
    sheet: 'no',
    source: 'Engineering mechanics — stress & strain',
    hsc: ['Suspension spring compression under load'],
    example: { k: 20000, x: 0.05 },
    priority: 1,
  },
  {
    id: 'fosUts',
    name: 'Factor of safety (ultimate strength)',
    modules: [...MAT],
    topic: 'Factor of safety',
    equation: 'FoS = \\frac{\\sigma_{UTS}}{\\sigma_{w}}',
    vars: [
      v('FoS', 'FoS', 'Factor of safety', 'ratio', { positive: true, warnBelow: 1, warnText: 'A factor of safety below 1 means the member will fail.' }),
      v('uts', '\\sigma_{UTS}', 'Ultimate tensile strength', 'stress', { positive: true }),
      v('sw', '\\sigma_{w}', 'Working (allowable) stress', 'stress', { positive: true }),
    ],
    solve: {
      FoS: { expr: '\\frac{#uts}{#sw}', fn: ({ uts, sw }) => uts / sw },
      uts: { expr: '#FoS \\times #sw', fn: ({ FoS, sw }) => FoS * sw },
      sw: { expr: '\\frac{#uts}{#FoS}', fn: ({ uts, FoS }) => uts / FoS },
    },
    aliases: ['factor of safety', 'FoS', 'FOS', 'safety factor', 'allowable stress', 'working stress', 'UTS', 'ultimate tensile strength'],
    when: 'Relating a material’s ultimate strength to the allowable working stress.',
    sheet: 'yes',
    source: 'Engineering materials — design',
    hsc: ['Allowable stress in a cable given UTS and FoS', 'FoS of a truss member'],
    example: { uts: 400e6, sw: 100e6 },
    priority: 5,
  },
  {
    id: 'fosYield',
    name: 'Factor of safety (yield strength)',
    modules: [...MAT],
    topic: 'Factor of safety',
    equation: 'FoS = \\frac{\\sigma_{y}}{\\sigma_{w}}',
    vars: [
      v('FoS', 'FoS', 'Factor of safety', 'ratio', { positive: true, warnBelow: 1, warnText: 'A factor of safety below 1 means the member will yield.' }),
      v('sy', '\\sigma_{y}', 'Yield stress (or proof stress)', 'stress', { positive: true }),
      v('sw', '\\sigma_{w}', 'Working (allowable) stress', 'stress', { positive: true }),
    ],
    solve: {
      FoS: { expr: '\\frac{#sy}{#sw}', fn: ({ sy, sw }) => sy / sw },
      sy: { expr: '#FoS \\times #sw', fn: ({ FoS, sw }) => FoS * sw },
      sw: { expr: '\\frac{#sy}{#FoS}', fn: ({ sy, FoS }) => sy / FoS },
    },
    aliases: ['factor of safety yield', 'yield stress', 'proof stress', 'yield strength'],
    when: 'Designing so a ductile member stays elastic (FoS against yielding).',
    sheet: 'yes',
    source: 'Engineering materials — design',
    hsc: ['Working stress of a steel member with FoS on yield'],
    example: { sy: 250e6, sw: 100e6 },
    priority: 4,
  },
  {
    id: 'fosLoad',
    name: 'Factor of safety (loads)',
    modules: [...MAT],
    topic: 'Factor of safety',
    equation: 'FoS = \\frac{F_{fail}}{F_{w}}',
    vars: [
      v('FoS', 'FoS', 'Factor of safety', 'ratio', { positive: true }),
      v('Ffail', 'F_{fail}', 'Failure (breaking) load', 'force', { positive: true }),
      v('Fw', 'F_{w}', 'Working (safe) load', 'force', { positive: true }),
    ],
    solve: {
      FoS: { expr: '\\frac{#Ffail}{#Fw}', fn: ({ Ffail, Fw }) => Ffail / Fw },
      Ffail: { expr: '#FoS \\times #Fw', fn: ({ FoS, Fw }) => FoS * Fw },
      Fw: { expr: '\\frac{#Ffail}{#FoS}', fn: ({ Ffail, FoS }) => Ffail / FoS },
    },
    aliases: ['safe working load', 'breaking load', 'failure load'],
    when: 'FoS expressed with loads rather than stresses.',
    sheet: 'derived',
    source: 'Engineering materials — design',
    hsc: ['Safe working load of a lifting cable'],
    example: { Ffail: 60000, Fw: 15000 },
    priority: 3,
  },
  {
    id: 'bending',
    name: 'Bending stress',
    modules: ['civil', 'aero', 'transport'],
    topic: 'Bending',
    equation: '\\sigma = \\frac{My}{I}',
    vars: [
      v('sb', '\\sigma', 'Bending stress (at distance y from the neutral axis)', 'stress', { concept: 'sigmaB' }),
      v('M', 'M', 'Bending moment', 'moment'),
      v('y', 'y', 'Distance from the neutral axis', 'length', { concept: 'yNA', nonNegative: true }),
      v('I', 'I', 'Second moment of area about the neutral axis', 'secondMoment', { concept: 'Isec', positive: true }),
    ],
    solve: {
      sb: { expr: '\\frac{#M #y}{#I}', fn: ({ M, y, I }) => (M * y) / I },
      M: { expr: '\\frac{#sb #I}{#y}', fn: ({ sb, I, y }) => (sb * I) / y },
      y: { expr: '\\frac{#sb #I}{#M}', fn: ({ sb, I, M }) => (sb * I) / M },
      I: { expr: '\\frac{#M #y}{#sb}', fn: ({ M, y, sb }) => (M * y) / sb },
    },
    aliases: ['bending stress', 'flexural stress', 'My/I', 'maximum bending stress', 'extreme fibre stress'],
    when: 'Stress in a beam due to bending — maximum at the extreme fibre (y = y_max).',
    sheet: 'yes',
    source: 'Engineering mechanics — bending',
    hsc: ['Maximum bending stress in a simply supported beam with point loads', 'Bending stress in an aircraft wing spar / cantilever'],
    example: { M: 12000, y: 0.1, I: 8e-5 },
    priority: 6,
  },
  {
    id: 'sectionModulus',
    name: 'Section modulus',
    modules: ['civil', 'aero'],
    topic: 'Bending',
    equation: 'Z = \\frac{I}{y_{max}}',
    vars: [
      v('Z', 'Z', 'Elastic section modulus', 'sectionModulus', { positive: true }),
      v('I', 'I', 'Second moment of area', 'secondMoment', { concept: 'Isec', positive: true }),
      v('y', 'y_{max}', 'Distance from NA to extreme fibre', 'length', { concept: 'yNA', positive: true }),
    ],
    solve: {
      Z: { expr: '\\frac{#I}{#y}', fn: ({ I, y }) => I / y },
      I: { expr: '#Z \\times #y', fn: ({ Z, y }) => Z * y },
      y: { expr: '\\frac{#I}{#Z}', fn: ({ I, Z }) => I / Z },
    },
    aliases: ['section modulus', 'Z'],
    when: 'Combines I and y so that σ_max = M/Z.',
    sheet: 'no',
    source: 'Engineering mechanics — bending',
    hsc: ['Selecting a beam section from tables'],
    example: { I: 8e-5, y: 0.1 },
    priority: 2,
  },
  {
    id: 'bendingZ',
    name: 'Bending stress from section modulus',
    modules: ['civil', 'aero'],
    topic: 'Bending',
    equation: '\\sigma_{max} = \\frac{M}{Z}',
    vars: [
      v('sb', '\\sigma_{max}', 'Maximum bending stress', 'stress', { concept: 'sigmaB' }),
      v('M', 'M', 'Bending moment', 'moment'),
      v('Z', 'Z', 'Section modulus', 'sectionModulus', { positive: true }),
    ],
    solve: {
      sb: { expr: '\\frac{#M}{#Z}', fn: ({ M, Z }) => M / Z },
      M: { expr: '#sb \\times #Z', fn: ({ sb, Z }) => sb * Z },
      Z: { expr: '\\frac{#M}{#sb}', fn: ({ M, sb }) => M / sb },
    },
    aliases: ['M/Z'],
    when: 'Maximum bending stress when the section modulus is given.',
    sheet: 'no',
    source: 'Engineering mechanics — bending',
    hsc: ['Beam selection from section tables'],
    example: { M: 12000, Z: 8e-4 },
    priority: 2,
  },
  {
    id: 'Irect',
    name: 'Second moment of area — rectangle',
    modules: ['civil', 'aero'],
    topic: 'Section properties',
    equation: 'I = \\frac{bd^3}{12}',
    vars: [
      v('I', 'I', 'Second moment of area (about centroidal axis parallel to b)', 'secondMoment', { concept: 'Isec', positive: true }),
      v('b', 'b', 'Breadth (width)', 'length', { concept: 'breadth', positive: true }),
      v('d', 'd', 'Depth (height, perpendicular to the bending axis)', 'length', { concept: 'depth', positive: true }),
    ],
    solve: {
      I: { expr: '\\frac{#b #d^3}{12}', fn: ({ b, d }) => (b * d ** 3) / 12 },
      b: { expr: '\\frac{12 #I}{#d^3}', fn: ({ I, d }) => (12 * I) / d ** 3 },
      d: { expr: '\\sqrt[3]{\\frac{12 #I}{#b}}', fn: ({ I, b }) => Math.cbrt((12 * I) / b) },
    },
    aliases: ['second moment of area rectangle', 'bd^3/12', 'moment of inertia rectangle', 'rectangular beam'],
    when: 'Solid rectangular beam bending about its horizontal centroidal axis. y_max = d/2.',
    sheet: 'no',
    source: 'Engineering mechanics — bending',
    hsc: ['I of a timber joist', 'Why a beam is stronger “on edge” (d cubed)'],
    example: { b: 0.05, d: 0.2 },
    priority: 3,
  },
  {
    id: 'yRect',
    name: 'Extreme fibre distance — symmetric section',
    modules: ['civil', 'aero'],
    topic: 'Section properties',
    equation: 'y_{max} = \\frac{d}{2}',
    vars: [v('y', 'y_{max}', 'Distance from NA to extreme fibre', 'length', { concept: 'yNA', positive: true }), v('d', 'd', 'Overall depth of section', 'length', { concept: 'depth', positive: true })],
    solve: {
      y: { expr: '\\frac{#d}{2}', fn: ({ d }) => d / 2 },
      d: { expr: '2 \\times #y', fn: ({ y }) => 2 * y },
    },
    aliases: ['neutral axis at mid depth', 'y = d/2'],
    when: 'Sections symmetric about the neutral axis (rectangle, circle, I-beam).',
    sheet: 'no',
    source: 'Engineering mechanics — bending',
    hsc: ['y for bending stress of a rectangular beam'],
    example: { d: 0.2 },
    priority: 1,
  },
  {
    id: 'Icircle',
    name: 'Second moment of area — solid circle',
    modules: ['civil', 'aero', 'transport'],
    topic: 'Section properties',
    equation: 'I = \\frac{\\pi D^4}{64}',
    vars: [v('I', 'I', 'Second moment of area', 'secondMoment', { concept: 'Isec', positive: true }), v('D', 'D', 'Diameter', 'length', { concept: 'dia', positive: true })],
    solve: {
      I: { expr: '\\frac{\\pi #D^4}{64}', fn: ({ D }) => (Math.PI * D ** 4) / 64 },
      D: { expr: '\\sqrt[4]{\\frac{64 #I}{\\pi}}', fn: ({ I }) => Math.pow((64 * I) / Math.PI, 0.25) },
    },
    aliases: ['circular section', 'round bar', 'solid shaft', 'πD^4/64'],
    when: 'Round bars, pins and axles in bending. y_max = D/2.',
    sheet: 'no',
    source: 'Engineering mechanics — bending',
    hsc: ['Bending stress in an axle'],
    example: { D: 0.05 },
    priority: 2,
  },
  {
    id: 'Itube',
    name: 'Second moment of area — hollow circle (tube)',
    modules: ['civil', 'aero', 'transport'],
    topic: 'Section properties',
    equation: 'I = \\frac{\\pi (D^4 - d^4)}{64}',
    vars: [
      v('I', 'I', 'Second moment of area', 'secondMoment', { concept: 'Isec', positive: true }),
      v('Do', 'D', 'Outside diameter', 'length', { concept: 'Dout', positive: true }),
      v('Di', 'd', 'Inside diameter', 'length', { concept: 'Din', nonNegative: true }),
    ],
    solve: {
      I: { expr: '\\frac{\\pi (#Do^4 - #Di^4)}{64}', fn: ({ Do, Di }) => (Math.PI * (Do ** 4 - Di ** 4)) / 64 },
      Do: { expr: '\\sqrt[4]{\\frac{64 #I}{\\pi} + #Di^4}', fn: ({ I, Di }) => Math.pow((64 * I) / Math.PI + Di ** 4, 0.25) },
      Di: { expr: '\\sqrt[4]{#Do^4 - \\frac{64 #I}{\\pi}}', fn: ({ I, Do }) => Math.pow(Do ** 4 - (64 * I) / Math.PI, 0.25) },
    },
    aliases: ['hollow tube', 'pipe section', 'hollow shaft', 'tubular'],
    when: 'Tubular members — bicycle frames, aircraft struts, hollow axles.',
    sheet: 'no',
    source: 'Engineering mechanics — bending',
    hsc: ['Bending stress in a tubular bicycle frame'],
    example: { Do: 0.05, Di: 0.04 },
    checks: ({ Do, Di }) => (Di >= Do ? [{ level: 'error', message: 'Inside diameter must be smaller than the outside diameter.' }] : []),
    priority: 2,
  },
  {
    id: 'areaCircle',
    name: 'Area of a circle from diameter',
    modules: ['civil', 'transport', 'aero', 'telecom'],
    topic: 'Section properties',
    equation: 'A = \\frac{\\pi d^2}{4}',
    vars: [v('A', 'A', 'Cross-sectional area', 'area', { positive: true }), v('d', 'd', 'Diameter', 'length', { concept: 'dia', positive: true })],
    solve: {
      A: { expr: '\\frac{\\pi #d^2}{4}', fn: ({ d }) => (Math.PI * d * d) / 4 },
      d: { expr: '\\sqrt{\\frac{4 #A}{\\pi}}', fn: ({ A }) => Math.sqrt((4 * A) / Math.PI) },
    },
    aliases: ['area of circle', 'round bar area', 'rod diameter', 'cable diameter', 'πd²/4'],
    when: 'Area of rods, cables, bolts, pins and pistons from their diameter.',
    sheet: 'no',
    source: 'Mathematics — mensuration',
    hsc: ['Area of a steel rod before calculating stress', 'Minimum diameter of a cable'],
    example: { d: 0.02 },
    priority: 7,
  },
  {
    id: 'areaTube',
    name: 'Area of a hollow circle (tube)',
    modules: ['civil', 'transport', 'aero'],
    topic: 'Section properties',
    equation: 'A = \\frac{\\pi (D^2 - d^2)}{4}',
    vars: [
      v('A', 'A', 'Cross-sectional area', 'area', { positive: true }),
      v('Do', 'D', 'Outside diameter', 'length', { concept: 'Dout', positive: true }),
      v('Di', 'd', 'Inside diameter', 'length', { concept: 'Din', nonNegative: true }),
    ],
    solve: {
      A: { expr: '\\frac{\\pi (#Do^2 - #Di^2)}{4}', fn: ({ Do, Di }) => (Math.PI * (Do * Do - Di * Di)) / 4 },
      Do: { expr: '\\sqrt{\\frac{4 #A}{\\pi} + #Di^2}', fn: ({ A, Di }) => Math.sqrt((4 * A) / Math.PI + Di * Di) },
      Di: { expr: '\\sqrt{#Do^2 - \\frac{4 #A}{\\pi}}', fn: ({ A, Do }) => Math.sqrt(Do * Do - (4 * A) / Math.PI) },
    },
    aliases: ['hollow tube area', 'pipe area', 'annulus'],
    when: 'Area of tubes and hollow columns.',
    sheet: 'no',
    source: 'Mathematics — mensuration',
    hsc: ['Stress in a hollow steel column'],
    example: { Do: 0.1, Di: 0.08 },
    checks: ({ Do, Di }) => (Di >= Do ? [{ level: 'error', message: 'Inside diameter must be smaller than the outside diameter.' }] : []),
    priority: 6,
  },
  {
    id: 'areaRect',
    name: 'Area of a rectangle',
    modules: ['civil', 'transport', 'aero'],
    topic: 'Section properties',
    equation: 'A = bd',
    vars: [
      v('A', 'A', 'Area', 'area', { positive: true }),
      v('b', 'b', 'Breadth', 'length', { concept: 'breadth', positive: true }),
      v('d', 'd', 'Depth', 'length', { concept: 'depth', positive: true }),
    ],
    solve: {
      A: { expr: '#b \\times #d', fn: ({ b, d }) => b * d },
      b: { expr: '\\frac{#A}{#d}', fn: ({ A, d }) => A / d },
      d: { expr: '\\frac{#A}{#b}', fn: ({ A, b }) => A / b },
    },
    aliases: ['rectangular section', 'flat bar', 'area of rectangle'],
    when: 'Area of flat bars and rectangular sections.',
    sheet: 'no',
    source: 'Mathematics — mensuration',
    hsc: ['Stress in a rectangular timber member'],
    example: { b: 0.05, d: 0.1 },
    priority: 6,
  },
  {
    id: 'shear',
    name: 'Shear stress (pins, bolts, rivets)',
    modules: ['civil', 'transport', 'aero'],
    topic: 'Stress & strain',
    equation: '\\tau = \\frac{F}{nA}',
    vars: [
      v('tau', '\\tau', 'Shear stress', 'stress'),
      v('F', 'F', 'Shear force (load)', 'force'),
      v('n', 'n', 'Number of shear planes (1 = single, 2 = double shear)', 'count', { concept: 'shearPlanes', positive: true, integer: true, constant: 1 }),
      v('A', 'A', 'Area of one shear plane', 'area', { positive: true }),
    ],
    solve: {
      tau: { expr: '\\frac{#F}{#n #A}', fn: ({ F, n, A }) => F / (n * A) },
      F: { expr: '#tau #n #A', fn: ({ tau, n, A }) => tau * n * A },
      n: { expr: '\\frac{#F}{#tau #A}', fn: ({ F, tau, A }) => F / (tau * A) },
      A: { expr: '\\frac{#F}{#n #tau}', fn: ({ F, n, tau }) => F / (n * tau) },
    },
    aliases: ['shear stress', 'double shear', 'single shear', 'pin', 'bolt', 'rivet', 'clevis'],
    when: 'Stress in pins, bolts and rivets cut by a shearing force. Double shear doubles the resisting area.',
    sheet: 'derived',
    source: 'Engineering mechanics — stress & strain',
    hsc: ['Shear stress in a truss pin joint in double shear', 'Minimum rivet diameter'],
    example: { F: 20000, n: 2, A: 78.54e-6 },
    priority: 3,
  },
  {
    id: 'pctElong',
    name: 'Percentage elongation (ductility)',
    modules: [...MAT],
    topic: 'Material testing',
    equation: '\\%El = \\frac{L_f - L_0}{L_0} \\times 100\\%',
    vars: [
      v('pctEl', '\\%El', 'Percentage elongation', 'percent'),
      v('Lf', 'L_f', 'Final gauge length (after fracture)', 'length', { positive: true }),
      v('L0', 'L_0', 'Original gauge length', 'length', { positive: true }),
    ],
    solve: {
      pctEl: { expr: '\\frac{#Lf - #L0}{#L0}', fn: ({ Lf, L0 }) => (Lf - L0) / L0 },
      Lf: { expr: '#L0 (1 + #pctEl)', fn: ({ L0, pctEl }) => L0 * (1 + pctEl) },
      L0: { expr: '\\frac{#Lf}{1 + #pctEl}', fn: ({ Lf, pctEl }) => Lf / (1 + pctEl) },
    },
    aliases: ['percentage elongation', 'ductility', 'elongation at break', 'gauge length'],
    when: 'Measure of ductility from a tensile test.',
    sheet: 'no',
    source: 'Engineering materials — testing',
    hsc: ['Ductility of a specimen from gauge lengths before and after testing'],
    example: { Lf: 0.062, L0: 0.05 },
    priority: 2,
  },
  {
    id: 'pctRA',
    name: 'Percentage reduction in area',
    modules: [...MAT],
    topic: 'Material testing',
    equation: '\\%RA = \\frac{A_0 - A_f}{A_0} \\times 100\\%',
    vars: [
      v('pctRA', '\\%RA', 'Reduction in area', 'percent'),
      v('A0', 'A_0', 'Original area', 'area', { positive: true }),
      v('Af', 'A_f', 'Final area at fracture (neck)', 'area', { positive: true }),
    ],
    solve: {
      pctRA: { expr: '\\frac{#A0 - #Af}{#A0}', fn: ({ A0, Af }) => (A0 - Af) / A0 },
      A0: { expr: '\\frac{#Af}{1 - #pctRA}', fn: ({ Af, pctRA }) => Af / (1 - pctRA) },
      Af: { expr: '#A0 (1 - #pctRA)', fn: ({ A0, pctRA }) => A0 * (1 - pctRA) },
    },
    aliases: ['reduction in area', 'necking'],
    when: 'Ductility measure from the necked area of a tensile specimen.',
    sheet: 'no',
    source: 'Engineering materials — testing',
    hsc: ['Reduction of area of a tensile specimen'],
    example: { A0: 78.5e-6, Af: 40e-6 },
    priority: 2,
  },
  {
    id: 'strainEnergy',
    name: 'Elastic strain energy',
    modules: [...MAT],
    topic: 'Material testing',
    equation: 'U = \\tfrac{1}{2} F \\Delta L',
    vars: [v('U', 'U', 'Strain energy stored', 'energy'), v('F', 'F', 'Load (elastic)', 'force'), v('dL', '\\Delta L', 'Extension', 'length')],
    solve: {
      U: { expr: '\\tfrac{1}{2} #F #dL', fn: ({ F, dL }) => 0.5 * F * dL },
      F: { expr: '\\frac{2 #U}{#dL}', fn: ({ U, dL }) => (2 * U) / dL },
      dL: { expr: '\\frac{2 #U}{#F}', fn: ({ U, F }) => (2 * U) / F },
    },
    aliases: ['strain energy', 'area under load-extension graph', 'resilience'],
    when: 'Energy stored elastically = area under the linear load–extension graph.',
    sheet: 'no',
    source: 'Engineering materials — testing',
    hsc: ['Energy absorbed by a member up to the elastic limit'],
    example: { F: 10000, dL: 0.002 },
    extension: true,
    priority: 0,
  },
  {
    id: 'resilience',
    name: 'Modulus of resilience (strain energy per volume)',
    modules: [...MAT],
    topic: 'Material testing',
    equation: 'u = \\tfrac{1}{2}\\sigma\\varepsilon',
    vars: [v('u', 'u', 'Strain energy per unit volume', 'energyDensity', { concept: 'resilience' }), v('sigma', '\\sigma', 'Stress', 'stress'), v('eps', '\\varepsilon', 'Strain', 'ratio')],
    solve: {
      u: { expr: '\\tfrac{1}{2} #sigma #eps', fn: ({ sigma, eps }) => 0.5 * sigma * eps },
      sigma: { expr: '\\frac{2 #u}{#eps}', fn: ({ u, eps }) => (2 * u) / eps },
      eps: { expr: '\\frac{2 #u}{#sigma}', fn: ({ u, sigma }) => (2 * u) / sigma },
    },
    aliases: ['modulus of resilience', 'area under stress-strain', 'toughness elastic region'],
    when: 'Area under the elastic part of a stress–strain graph (toughness is the total area to fracture).',
    sheet: 'no',
    source: 'Engineering materials — testing',
    hsc: ['Comparing toughness from stress–strain graphs'],
    example: { sigma: 250e6, eps: 0.00125 },
    extension: true,
    priority: 0,
  },
  // ——— Standard beam results ———
  {
    id: 'ssCentral',
    name: 'Max bending moment — simply supported, central point load',
    modules: ['civil'],
    topic: 'Beams',
    equation: 'M_{max} = \\frac{FL}{4}',
    vars: [v('M', 'M_{max}', 'Maximum bending moment (at mid-span)', 'moment'), v('F', 'F', 'Central point load', 'force'), v('Ls', 'L', 'Span', 'length', { concept: 'span', positive: true })],
    solve: {
      M: { expr: '\\frac{#F #Ls}{4}', fn: ({ F, Ls }) => (F * Ls) / 4 },
      F: { expr: '\\frac{4 #M}{#Ls}', fn: ({ M, Ls }) => (4 * M) / Ls },
      Ls: { expr: '\\frac{4 #M}{#F}', fn: ({ M, F }) => (4 * M) / F },
    },
    aliases: ['central point load', 'midspan load', 'FL/4'],
    when: 'Quick result for a simply supported beam with one load at mid-span (reactions F/2 each).',
    sheet: 'derived',
    source: 'Engineering mechanics — beams',
    hsc: ['Maximum bending stress in a simply supported beam with a central load'],
    example: { F: 10000, Ls: 4 },
    contextOnly: ['civil', 'aero'],
    priority: 2,
  },
  {
    id: 'ssUdl',
    name: 'Max bending moment — simply supported, full-span UDL',
    modules: ['civil'],
    topic: 'Beams',
    equation: 'M_{max} = \\frac{wL^2}{8}',
    vars: [v('M', 'M_{max}', 'Maximum bending moment (at mid-span)', 'moment'), v('w', 'w', 'Uniformly distributed load', 'udl'), v('Ls', 'L', 'Span', 'length', { concept: 'span', positive: true })],
    solve: {
      M: { expr: '\\frac{#w #Ls^2}{8}', fn: ({ w, Ls }) => (w * Ls * Ls) / 8 },
      w: { expr: '\\frac{8 #M}{#Ls^2}', fn: ({ M, Ls }) => (8 * M) / (Ls * Ls) },
      Ls: { expr: '\\sqrt{\\frac{8 #M}{#w}}', fn: ({ M, w }) => Math.sqrt((8 * M) / w) },
    },
    aliases: ['uniformly distributed load', 'UDL', 'wL^2/8'],
    when: 'Simply supported beam carrying a UDL over the whole span.',
    sheet: 'derived',
    source: 'Engineering mechanics — beams',
    hsc: ['Bending moment in a floor joist under UDL'],
    example: { w: 5000, Ls: 6 },
    contextOnly: ['civil', 'aero'],
    priority: 2,
  },
  {
    id: 'cantPoint',
    name: 'Max bending moment — cantilever, end point load',
    modules: ['civil', 'aero'],
    topic: 'Beams',
    equation: 'M_{max} = FL',
    vars: [v('M', 'M_{max}', 'Maximum bending moment (at the fixed end)', 'moment'), v('F', 'F', 'End point load', 'force'), v('Ls', 'L', 'Cantilever length', 'length', { concept: 'span', positive: true })],
    solve: {
      M: { expr: '#F \\times #Ls', fn: ({ F, Ls }) => F * Ls },
      F: { expr: '\\frac{#M}{#Ls}', fn: ({ M, Ls }) => M / Ls },
      Ls: { expr: '\\frac{#M}{#F}', fn: ({ M, F }) => M / F },
    },
    aliases: ['cantilever', 'fixed end', 'wall bracket'],
    when: 'Cantilever with a single load at the free end.',
    sheet: 'derived',
    source: 'Engineering mechanics — beams',
    hsc: ['Bending stress at the root of a cantilever'],
    example: { F: 2000, Ls: 1.5 },
    contextOnly: ['civil', 'aero'],
    priority: 1,
  },
  {
    id: 'cantUdl',
    name: 'Max bending moment — cantilever, UDL',
    modules: ['civil', 'aero'],
    topic: 'Beams',
    equation: 'M_{max} = \\frac{wL^2}{2}',
    vars: [v('M', 'M_{max}', 'Maximum bending moment (at the fixed end)', 'moment'), v('w', 'w', 'Uniformly distributed load', 'udl'), v('Ls', 'L', 'Cantilever length', 'length', { concept: 'span', positive: true })],
    solve: {
      M: { expr: '\\frac{#w #Ls^2}{2}', fn: ({ w, Ls }) => (w * Ls * Ls) / 2 },
      w: { expr: '\\frac{2 #M}{#Ls^2}', fn: ({ M, Ls }) => (2 * M) / (Ls * Ls) },
      Ls: { expr: '\\sqrt{\\frac{2 #M}{#w}}', fn: ({ M, w }) => Math.sqrt((2 * M) / w) },
    },
    aliases: ['cantilever UDL', 'wing as cantilever'],
    when: 'Cantilever carrying a UDL over its full length (idealised wing, balcony).',
    sheet: 'derived',
    source: 'Engineering mechanics — beams',
    hsc: ['Root bending moment of a wing idealised as a UDL cantilever'],
    example: { w: 3000, Ls: 2 },
    contextOnly: ['civil', 'aero'],
    priority: 1,
  },
  {
    id: 'udlTotal',
    name: 'Total load of a UDL',
    modules: ['civil'],
    topic: 'Beams',
    equation: 'W = wL',
    vars: [v('Wu', 'W', 'Total (resultant) load, acting at the centre of the UDL', 'force', { concept: 'udlTotal' }), v('w', 'w', 'UDL intensity', 'udl'), v('Lu', 'L', 'Length loaded', 'length', { concept: 'span', positive: true })],
    solve: {
      Wu: { expr: '#w \\times #Lu', fn: ({ w, Lu }) => w * Lu },
      w: { expr: '\\frac{#Wu}{#Lu}', fn: ({ Wu, Lu }) => Wu / Lu },
      Lu: { expr: '\\frac{#Wu}{#w}', fn: ({ Wu, w }) => Wu / w },
    },
    aliases: ['total UDL', 'equivalent point load'],
    when: 'Replacing a UDL by an equivalent point load at its centre (for reactions only).',
    sheet: 'derived',
    source: 'Engineering mechanics — beams',
    hsc: ['Support reactions for a beam with a UDL'],
    example: { w: 4000, Lu: 5 },
    priority: 2,
  },
  // ——— Hydrostatics / pressure ———
  {
    id: 'pressure',
    name: 'Pressure',
    modules: ['civil', 'transport', 'aero'],
    topic: 'Pressure & hydraulics',
    equation: 'P = \\frac{F}{A}',
    vars: [v('p', 'P', 'Pressure', 'pressure'), v('F', 'F', 'Force (normal to surface)', 'force'), v('A', 'A', 'Area', 'area', { positive: true })],
    solve: {
      p: { expr: '\\frac{#F}{#A}', fn: ({ F, A }) => F / A },
      F: { expr: '#p \\times #A', fn: ({ p, A }) => p * A },
      A: { expr: '\\frac{#F}{#p}', fn: ({ F, p }) => F / p },
    },
    aliases: ['pressure', 'bearing pressure', 'contact pressure', 'tyre pressure', 'force per area'],
    when: 'Force spread over an area — footings, hydraulic pistons, tyres, cabin pressure on a window.',
    sheet: 'yes',
    source: 'Engineering mechanics — fluid mechanics',
    hsc: ['Bearing pressure under a column footing', 'Force on an aircraft door from cabin pressure difference'],
    example: { F: 50000, A: 0.25 },
    priority: 5,
  },
  {
    id: 'hydrostatic',
    name: 'Hydrostatic pressure',
    modules: ['civil', 'aero', 'transport'],
    topic: 'Pressure & hydraulics',
    equation: 'P = \\rho g h',
    vars: [
      v('p', 'P', 'Gauge pressure at depth', 'pressure'),
      v('rho', '\\rho', 'Fluid density', 'density', { positive: true }),
      gVar(),
      v('h', 'h', 'Depth below the free surface', 'length', { concept: 'depth', nonNegative: true }),
    ],
    solve: {
      p: { expr: '#rho #g #h', fn: ({ rho, g, h }) => rho * g * h },
      rho: { expr: '\\frac{#p}{#g #h}', fn: ({ p, g, h }) => p / (g * h) },
      h: { expr: '\\frac{#p}{#rho #g}', fn: ({ p, rho, g }) => p / (rho * g) },
      g: { expr: '\\frac{#p}{#rho #h}', fn: ({ p, rho, h }) => p / (rho * h) },
    },
    aliases: ['hydrostatic pressure', 'pressure at depth', 'water pressure', 'dam', 'ρgh', 'rho g h', 'head of water'],
    when: 'Pressure in a still fluid increases linearly with depth — dams, tanks, piers, hydraulic lines.',
    sheet: 'yes',
    source: 'Engineering mechanics — fluid mechanics',
    hsc: ['Pressure at the base of a dam wall', 'Pressure on a bridge pier footing'],
    example: { rho: 1000, h: 10 },
    priority: 4,
  },
  {
    id: 'damForce',
    name: 'Resultant hydrostatic force on a vertical wall',
    modules: ['civil'],
    topic: 'Pressure & hydraulics',
    equation: 'F = \\tfrac{1}{2}\\rho g h^2 b',
    vars: [
      v('F', 'F', 'Resultant force (acts h/3 above the base)', 'force'),
      v('rho', '\\rho', 'Fluid density', 'density', { positive: true }),
      gVar(),
      v('h', 'h', 'Depth of water', 'length', { concept: 'depth', positive: true }),
      v('b', 'b', 'Width of wall', 'length', { concept: 'breadth', positive: true }),
    ],
    solve: {
      F: { expr: '\\tfrac{1}{2} #rho #g #h^2 #b', fn: ({ rho, g, h, b }) => 0.5 * rho * g * h * h * b },
      rho: { expr: '\\frac{2 #F}{#g #h^2 #b}', fn: ({ F, g, h, b }) => (2 * F) / (g * h * h * b) },
      h: { expr: '\\sqrt{\\frac{2 #F}{#rho #g #b}}', fn: ({ F, rho, g, b }) => Math.sqrt((2 * F) / (rho * g * b)) },
      b: { expr: '\\frac{2 #F}{#rho #g #h^2}', fn: ({ F, rho, g, h }) => (2 * F) / (rho * g * h * h) },
      g: { expr: '\\frac{2 #F}{#rho #h^2 #b}', fn: ({ F, rho, h, b }) => (2 * F) / (rho * h * h * b) },
    },
    aliases: ['force on dam wall', 'retaining wall', 'triangular pressure distribution'],
    when: 'Total water force on a dam/retaining wall (area of the triangular pressure diagram × width).',
    sheet: 'no',
    source: 'Engineering mechanics — fluid mechanics',
    hsc: ['Overturning moment on a dam wall (F × h/3)'],
    example: { rho: 1000, h: 8, b: 20 },
    extension: true,
    contextOnly: ['civil'],
    priority: 1,
  },
  {
    id: 'density',
    name: 'Density',
    modules: ['civil', 'transport', 'aero'],
    topic: 'Materials',
    equation: '\\rho = \\frac{m}{V}',
    vars: [v('rho', '\\rho', 'Density', 'density', { positive: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), v('V', 'V', 'Volume', 'volume', { concept: 'vol', positive: true })],
    solve: {
      rho: { expr: '\\frac{#m}{#V}', fn: ({ m, V }) => m / V },
      m: { expr: '#rho \\times #V', fn: ({ rho, V }) => rho * V },
      V: { expr: '\\frac{#m}{#rho}', fn: ({ m, rho }) => m / rho },
    },
    aliases: ['density', 'mass per volume', 'self weight'],
    when: 'Mass (and hence self-weight) of a member from its volume; comparing materials (specific strength).',
    sheet: 'no',
    source: 'Engineering materials',
    hsc: ['Self-weight of a concrete beam', 'Comparing aluminium and steel components'],
    example: { m: 7850, V: 1 },
    priority: 2,
  },

  {
    id: 'brinell',
    name: 'Brinell hardness',
    modules: ['civil', 'transport', 'aero'],
    topic: 'Material testing',
    equation: 'HB = \\frac{2F}{\\pi D\\left(D - \\sqrt{D^2 - d^2}\\right)}',
    vars: [
      v('HB', 'HB', 'Brinell hardness number (kgf/mm²)', 'hardnessB', { positive: true }),
      v('F', 'F', 'Test load (e.g. 3000 kgf = 29.42 kN)', 'force', { positive: true }),
      v('D', 'D', 'Ball diameter (usually 10 mm)', 'length', { concept: 'ballDia', positive: true }),
      v('d', 'd', 'Indentation diameter', 'length', { concept: 'indentDia', positive: true }),
    ],
    solve: {
      HB: { expr: '\\frac{2 #F}{\\pi #D (#D - \\sqrt{#D^2 - #d^2})}', fn: ({ F, D, d }) => (2 * F) / (Math.PI * D * (D - Math.sqrt(D * D - d * d))) },
      F: { expr: '\\frac{#HB \\pi #D (#D - \\sqrt{#D^2 - #d^2})}{2}', fn: ({ HB, D, d }) => (HB * Math.PI * D * (D - Math.sqrt(D * D - d * d))) / 2 },
      d: {
        expr: '\\sqrt{#D^2 - \\left(#D - \\frac{2 #F}{\\pi #D #HB}\\right)^2}',
        fn: ({ HB, F, D }) => {
          const k = D - (2 * F) / (Math.PI * D * HB);
          return Math.sqrt(D * D - k * k);
        },
      },
      D: {
        expr: '\\text{solved numerically}',
        fn: ({ HB, F, d }) => {
          // HB decreases with D; bisection on D in (d, 100 d)
          const f = (D: number) => (2 * F) / (Math.PI * D * (D - Math.sqrt(D * D - d * d))) - HB;
          let lo = d * (1 + 1e-9);
          let hi = d * 1000;
          if (f(lo) * f(hi) > 0) return NaN;
          for (let i = 0; i < 200; i++) {
            const mid = (lo + hi) / 2;
            if (f(lo) * f(mid) <= 0) hi = mid;
            else lo = mid;
          }
          return (lo + hi) / 2;
        },
        note: 'no closed form — bisection',
      },
    },
    aliases: ['brinell', 'hardness test', 'HB', 'BHN', 'indentation'],
    when: 'Hardness from a Brinell test (hardened steel ball pressed into the surface). Result in kgf/mm² (HB).',
    sheet: 'no',
    source: 'Engineering materials — testing',
    hsc: ['Hardness of a steel sample from indentation diameter'],
    example: { F: 3000 * 9.80665, D: 0.01, d: 0.004 },
    checks: ({ D, d }) => (d >= D ? [{ level: 'error', message: 'Indentation diameter must be smaller than the ball diameter.' }] : []),
    extension: true,
    priority: 1,
  },
  {
    id: 'vickers',
    name: 'Vickers hardness',
    modules: ['civil', 'transport', 'aero'],
    topic: 'Material testing',
    equation: 'HV = \\frac{1.8544 F}{d^2}',
    vars: [
      v('HV', 'HV', 'Vickers hardness number (kgf/mm²)', 'hardnessV', { positive: true }),
      v('F', 'F', 'Test load', 'force', { positive: true }),
      v('d', 'd', 'Mean diagonal of indentation', 'length', { concept: 'indentDia', positive: true }),
    ],
    solve: {
      HV: { expr: '\\frac{1.8544 #F}{#d^2}', fn: ({ F, d }) => (1.8544 * F) / (d * d) },
      F: { expr: '\\frac{#HV #d^2}{1.8544}', fn: ({ HV, d }) => (HV * d * d) / 1.8544 },
      d: { expr: '\\sqrt{\\frac{1.8544 #F}{#HV}}', fn: ({ F, HV }) => Math.sqrt((1.8544 * F) / HV) },
    },
    aliases: ['vickers', 'diamond pyramid', 'HV', 'micro hardness'],
    when: 'Hardness from a Vickers diamond-pyramid test.',
    sheet: 'no',
    source: 'Engineering materials — testing',
    hsc: ['Vickers hardness of a heat-treated component'],
    example: { F: 30 * 9.80665, d: 0.0005 },
    extension: true,
    priority: 1,
  },
  {
    id: 'impactEnergy',
    name: 'Impact test energy absorbed (Charpy / Izod)',
    modules: ['civil', 'transport', 'aero'],
    topic: 'Material testing',
    equation: 'E = mg(h_1 - h_2)',
    vars: [
      v('E', 'E', 'Energy absorbed by the specimen', 'energy', { concept: 'impactE' }),
      v('m', 'm', 'Pendulum mass', 'mass', { positive: true }),
      gVar(),
      v('h1', 'h_1', 'Release height', 'length'),
      v('h2', 'h_2', 'Rise height after fracture', 'length'),
    ],
    solve: {
      E: { expr: '#m #g (#h1 - #h2)', fn: ({ m, g, h1, h2 }) => m * g * (h1 - h2) },
      m: { expr: '\\frac{#E}{#g (#h1 - #h2)}', fn: ({ E, g, h1, h2 }) => E / (g * (h1 - h2)) },
      g: { expr: '\\frac{#E}{#m (#h1 - #h2)}', fn: ({ E, m, h1, h2 }) => E / (m * (h1 - h2)) },
      h1: { expr: '#h2 + \\frac{#E}{#m #g}', fn: ({ E, m, g, h2 }) => h2 + E / (m * g) },
      h2: { expr: '#h1 - \\frac{#E}{#m #g}', fn: ({ E, m, g, h1 }) => h1 - E / (m * g) },
    },
    aliases: ['charpy', 'izod', 'impact test', 'toughness test', 'pendulum'],
    when: 'Toughness: energy absorbed = loss of pendulum potential energy.',
    sheet: 'no',
    source: 'Engineering materials — testing',
    hsc: ['Energy absorbed in a Charpy test comparing brittle and ductile specimens'],
    example: { m: 20, h1: 1.5, h2: 0.6 },
    checks: ({ h1, h2 }) => (h2 > h1 ? [{ level: 'error', message: 'The pendulum cannot rise higher than its release height.' }] : []),
    extension: true,
    priority: 1,
  },

];
