/**
 * Engineering mechanics shared across modules: forces, moments, Newton's laws,
 * work/energy/power, kinematics, momentum.
 */
import { FormulaDef, gVar, v } from './types';

const ALL = ['civil', 'transport', 'aero', 'telecom'] as const;
const MECH = ['civil', 'transport', 'aero'] as const;
const deg = Math.PI / 180;

export const mechanicsFormulas: FormulaDef[] = [
  {
    id: 'newton2',
    name: "Newton's second law",
    modules: [...MECH],
    topic: 'Forces & motion',
    equation: 'F = ma',
    vars: [
      v('F', 'F', 'Net (resultant) force', 'force'),
      v('m', 'm', 'Mass', 'mass', { positive: true }),
      v('a', 'a', 'Acceleration', 'acceleration'),
    ],
    solve: {
      F: { expr: '#m \\times #a', fn: ({ m, a }) => m * a },
      m: { expr: '\\frac{#F}{#a}', fn: ({ F, a }) => F / a },
      a: { expr: '\\frac{#F}{#m}', fn: ({ F, m }) => F / m },
    },
    aliases: ['newton', 'net force', 'resultant force', 'accelerating force', 'F=ma'],
    when: 'Relating the net force on a body to its acceleration (vehicles accelerating/braking, aircraft take-off).',
    sheet: 'yes',
    source: 'Engineering mechanics — dynamics',
    hsc: ['Braking force on a vehicle from deceleration', 'Thrust required for take-off acceleration'],
    example: { m: 1200, a: 2.5 },
    priority: 5,
  },
  {
    id: 'weight',
    name: 'Weight force',
    modules: [...MECH],
    topic: 'Forces & motion',
    equation: 'W = mg',
    vars: [v('Wt', 'W', 'Weight force', 'force', { nonNegative: true }), v('m', 'm', 'Mass', 'mass', { positive: true }), gVar()],
    solve: {
      Wt: { expr: '#m \\times #g', fn: ({ m, g }) => m * g },
      m: { expr: '\\frac{#Wt}{#g}', fn: ({ Wt, g }) => Wt / g },
      g: { expr: '\\frac{#Wt}{#m}', fn: ({ Wt, m }) => Wt / m },
    },
    aliases: ['weight', 'gravity force', 'self weight', 'mg'],
    when: 'Converting a mass (kg, t) into a force (N) before any force/moment/stress calculation.',
    sheet: 'yes',
    source: 'Engineering mechanics — statics',
    hsc: ['Load of a hanging mass on a cable', 'Aircraft weight in flight force diagrams', 'Vehicle normal force'],
    example: { m: 500 },
    priority: 6,
  },
  {
    id: 'moment',
    name: 'Moment of a force',
    modules: [...MECH],
    topic: 'Moments & equilibrium',
    equation: 'M = Fd',
    vars: [
      v('M', 'M', 'Moment (about a point)', 'moment'),
      v('F', 'F', 'Force', 'force'),
      v('d', 'd', 'Perpendicular distance from the pivot', 'length', { concept: 'dist', positive: true }),
    ],
    solve: {
      M: { expr: '#F \\times #d', fn: ({ F, d }) => F * d },
      F: { expr: '\\frac{#M}{#d}', fn: ({ M, d }) => M / d },
      d: { expr: '\\frac{#M}{#F}', fn: ({ M, F }) => M / F },
    },
    aliases: ['moment', 'turning effect', 'lever arm', 'cantilever end load bending moment'],
    when: 'Turning effect about a point: ΣM = 0 for equilibrium, support reactions, levers, cantilever end-loads (M = FL).',
    sheet: 'yes',
    source: 'Engineering mechanics — statics',
    hsc: ['Support reactions of simply supported beams', 'Maximum bending moment at a cantilever root', 'Tailplane load about aircraft CG'],
    example: { F: 5000, d: 2 },
    priority: 5,
  },
  {
    id: 'torque',
    name: 'Torque',
    modules: ['transport', 'aero'],
    topic: 'Moments & equilibrium',
    equation: 'T = Fr',
    vars: [
      v('T', 'T', 'Torque', 'torque', { concept: 'torque' }),
      v('F', 'F', 'Tangential force', 'force'),
      v('r', 'r', 'Radius (lever arm)', 'length', { positive: true, concept: 'radius' }),
    ],
    solve: {
      T: { expr: '#F \\times #r', fn: ({ F, r }) => F * r },
      F: { expr: '\\frac{#T}{#r}', fn: ({ T, r }) => T / r },
      r: { expr: '\\frac{#T}{#F}', fn: ({ T, F }) => T / F },
    },
    aliases: ['torque', 'twisting moment', 'wheel torque', 'spanner'],
    when: 'Twisting effect of a force on a shaft, wheel, spanner or crank.',
    sheet: 'derived',
    source: 'Engineering mechanics — statics',
    hsc: ['Tractive force at the tyre from axle torque', 'Torque applied with a wheel brace'],
    example: { F: 200, r: 0.35 },
  },
  {
    id: 'forceX',
    name: 'Horizontal component of a force',
    modules: [...MECH],
    topic: 'Force resolution',
    equation: 'F_x = F\\cos\\theta',
    vars: [
      v('Fx', 'F_x', 'Horizontal component', 'force'),
      v('F', 'F', 'Force magnitude', 'force', { positive: true }),
      v('theta', '\\theta', 'Angle from horizontal', 'angle', { min: -2 * Math.PI, max: 2 * Math.PI }),
    ],
    solve: {
      Fx: { expr: '#F \\cos(#theta)', fn: ({ F, theta }) => F * Math.cos(theta) },
      F: { expr: '\\frac{#Fx}{\\cos(#theta)}', fn: ({ Fx, theta }) => Fx / Math.cos(theta) },
      theta: { expr: '\\cos^{-1}\\left(\\frac{#Fx}{#F}\\right)', fn: ({ Fx, F }) => Math.acos(Fx / F), note: 'principal value (0°–180°)' },
    },
    aliases: ['horizontal component', 'x component', 'resolve horizontally'],
    when: 'Resolving an inclined force into horizontal/vertical components.',
    sheet: 'derived',
    source: 'Engineering mechanics — statics',
    hsc: ['Components of cable tension', 'Horizontal component of towing force'],
    example: { F: 1000, theta: 30 * deg },
    priority: 3,
  },
  {
    id: 'forceY',
    name: 'Vertical component of a force',
    modules: [...MECH],
    topic: 'Force resolution',
    equation: 'F_y = F\\sin\\theta',
    vars: [
      v('Fy', 'F_y', 'Vertical component', 'force'),
      v('F', 'F', 'Force magnitude', 'force', { positive: true }),
      v('theta', '\\theta', 'Angle from horizontal', 'angle', { min: -2 * Math.PI, max: 2 * Math.PI }),
    ],
    solve: {
      Fy: { expr: '#F \\sin(#theta)', fn: ({ F, theta }) => F * Math.sin(theta) },
      F: { expr: '\\frac{#Fy}{\\sin(#theta)}', fn: ({ Fy, theta }) => Fy / Math.sin(theta) },
      theta: { expr: '\\sin^{-1}\\left(\\frac{#Fy}{#F}\\right)', fn: ({ Fy, F }) => Math.asin(Fy / F), note: 'principal value (−90° to 90°)' },
    },
    aliases: ['vertical component', 'y component', 'resolve vertically'],
    when: 'Resolving an inclined force into horizontal/vertical components.',
    sheet: 'derived',
    source: 'Engineering mechanics — statics',
    hsc: ['Vertical component of a cable supporting a sign'],
    example: { F: 1000, theta: 30 * deg },
    priority: 3,
  },
  {
    id: 'resultant',
    name: 'Resultant of perpendicular components',
    modules: [...MECH],
    topic: 'Force resolution',
    equation: 'R = \\sqrt{F_x^2 + F_y^2}',
    vars: [
      v('R', 'R', 'Resultant force', 'force', { concept: 'Rres', nonNegative: true }),
      v('Fx', 'F_x', 'Sum of horizontal components (ΣFx)', 'force'),
      v('Fy', 'F_y', 'Sum of vertical components (ΣFy)', 'force'),
    ],
    solve: {
      R: { expr: '\\sqrt{#Fx^2 + #Fy^2}', fn: ({ Fx, Fy }) => Math.hypot(Fx, Fy) },
      Fx: { expr: '\\sqrt{#R^2 - #Fy^2}', fn: ({ R, Fy }) => Math.sqrt(R * R - Fy * Fy), note: 'magnitude (positive root)' },
      Fy: { expr: '\\sqrt{#R^2 - #Fx^2}', fn: ({ R, Fx }) => Math.sqrt(R * R - Fx * Fx), note: 'magnitude (positive root)' },
    },
    aliases: ['resultant', 'pythagoras', 'combined force', 'magnitude of resultant'],
    when: 'Combining ΣFx and ΣFy into a single resultant force.',
    sheet: 'derived',
    source: 'Engineering mechanics — statics',
    hsc: ['Resultant of concurrent coplanar forces', 'Reaction at a pin joint from its components'],
    example: { Fx: 3000, Fy: 4000 },
    checks: ({ R, Fx, Fy }) =>
      R + 1e-9 < Math.abs(Fx) || R + 1e-9 < Math.abs(Fy) ? [{ level: 'error', message: 'A component cannot be larger than the resultant.' }] : [],
    priority: 3,
  },
  {
    id: 'resultantAngle',
    name: 'Direction of a resultant',
    modules: [...MECH],
    topic: 'Force resolution',
    equation: '\\theta = \\tan^{-1}\\left(\\frac{F_y}{F_x}\\right)',
    vars: [
      v('thetaR', '\\theta', 'Direction of resultant from horizontal', 'angle'),
      v('Fx', 'F_x', 'ΣFx', 'force', { nonZero: true }),
      v('Fy', 'F_y', 'ΣFy', 'force'),
    ],
    solve: {
      thetaR: { expr: '\\tan^{-1}\\left(\\frac{#Fy}{#Fx}\\right)', fn: ({ Fx, Fy }) => Math.atan(Fy / Fx), note: 'check the quadrant from the signs of ΣFx and ΣFy' },
      Fy: { expr: '#Fx \\tan(#thetaR)', fn: ({ Fx, thetaR }) => Fx * Math.tan(thetaR) },
      Fx: { expr: '\\frac{#Fy}{\\tan(#thetaR)}', fn: ({ Fy, thetaR }) => Fy / Math.tan(thetaR) },
    },
    aliases: ['direction', 'angle of resultant', 'bearing of resultant'],
    when: 'Finding the line of action (angle) of a resultant or equilibrant.',
    sheet: 'derived',
    source: 'Engineering mechanics — statics',
    hsc: ['Direction of the reaction at a pinned support'],
    example: { Fx: 3000, Fy: 4000 },
    priority: 2,
  },
  {
    id: 'work',
    name: 'Work done',
    modules: [...MECH],
    topic: 'Work, energy & power',
    equation: 'W = Fs',
    vars: [
      v('W', 'W', 'Work done', 'energy', { concept: 'work' }),
      v('F', 'F', 'Force (in direction of motion)', 'force'),
      v('s', 's', 'Displacement', 'length'),
    ],
    solve: {
      W: { expr: '#F \\times #s', fn: ({ F, s }) => F * s },
      F: { expr: '\\frac{#W}{#s}', fn: ({ W, s }) => W / s },
      s: { expr: '\\frac{#W}{#F}', fn: ({ W, F }) => W / F },
    },
    aliases: ['work done', 'work', 'energy transferred by a force'],
    when: 'Energy transferred when a force moves through a distance along its line of action.',
    sheet: 'yes',
    source: 'Engineering mechanics — work, energy, power',
    hsc: ['Work done lifting a load with a crane', 'Work done by braking force'],
    example: { F: 2000, s: 15 },
    priority: 4,
  },
  {
    id: 'ke',
    name: 'Kinetic energy',
    modules: [...MECH],
    topic: 'Work, energy & power',
    equation: 'KE = \\tfrac{1}{2}mv^2',
    vars: [
      v('KE', 'KE', 'Kinetic energy', 'energy', { nonNegative: true }),
      v('m', 'm', 'Mass', 'mass', { positive: true }),
      v('v', 'v', 'Speed', 'velocity'),
    ],
    solve: {
      KE: { expr: '\\tfrac{1}{2} \\times #m \\times #v^2', fn: ({ m, v }) => 0.5 * m * v * v },
      m: { expr: '\\frac{2 #KE}{#v^2}', fn: ({ KE, v }) => (2 * KE) / (v * v) },
      v: { expr: '\\sqrt{\\frac{2 #KE}{#m}}', fn: ({ KE, m }) => Math.sqrt((2 * KE) / m), note: 'positive root (speed)' },
    },
    aliases: ['kinetic energy', 'KE', 'energy of motion', 'Ek'],
    when: 'Energy of a moving body — vehicles, braking energy, impact.',
    sheet: 'yes',
    source: 'Engineering mechanics — work, energy, power',
    hsc: ['Energy dissipated by brakes stopping a vehicle', 'Kinetic energy of a train'],
    example: { m: 1500, v: 20 },
    priority: 4,
  },
  {
    id: 'pe',
    name: 'Gravitational potential energy',
    modules: [...MECH],
    topic: 'Work, energy & power',
    equation: 'PE = mgh',
    vars: [
      v('PE', 'PE', 'Potential energy', 'energy'),
      v('m', 'm', 'Mass', 'mass', { positive: true }),
      gVar(),
      v('h', 'h', 'Height (vertical change)', 'length'),
    ],
    solve: {
      PE: { expr: '#m \\times #g \\times #h', fn: ({ m, g, h }) => m * g * h },
      m: { expr: '\\frac{#PE}{#g #h}', fn: ({ PE, g, h }) => PE / (g * h) },
      h: { expr: '\\frac{#PE}{#m #g}', fn: ({ PE, m, g }) => PE / (m * g) },
      g: { expr: '\\frac{#PE}{#m #h}', fn: ({ PE, m, h }) => PE / (m * h) },
    },
    aliases: ['potential energy', 'PE', 'gravitational energy', 'Ep'],
    when: 'Energy gained raising a mass through a vertical height (lifts, cranes, vehicles on hills).',
    sheet: 'yes',
    source: 'Engineering mechanics — work, energy, power',
    hsc: ['Energy to raise a lift car', 'Vehicle climbing a hill'],
    example: { m: 800, h: 12 },
    priority: 4,
  },
  {
    id: 'energyConservation',
    name: 'Energy conservation (no losses): KE = PE',
    modules: [...MECH],
    topic: 'Work, energy & power',
    equation: '\\tfrac{1}{2}mv^2 = mgh \\;\\Rightarrow\\; v = \\sqrt{2gh}',
    vars: [v('v', 'v', 'Speed at the bottom', 'velocity', { nonNegative: true }), gVar(), v('h', 'h', 'Height dropped', 'length', { nonNegative: true })],
    solve: {
      v: { expr: '\\sqrt{2 \\times #g \\times #h}', fn: ({ g, h }) => Math.sqrt(2 * g * h) },
      h: { expr: '\\frac{#v^2}{2 #g}', fn: ({ v, g }) => (v * v) / (2 * g) },
      g: { expr: '\\frac{#v^2}{2 #h}', fn: ({ v, h }) => (v * v) / (2 * h) },
    },
    aliases: ['energy conservation', 'free fall speed', 'falls from height', 'no losses'],
    when: 'PE converted fully to KE (friction ignored).',
    sheet: 'derived',
    source: 'Engineering mechanics — work, energy, power',
    hsc: ['Speed of a vehicle at the bottom of a slope with no friction'],
    example: { h: 20 },
    priority: 1,
  },
  {
    id: 'power',
    name: 'Power (rate of doing work)',
    modules: [...MECH],
    topic: 'Work, energy & power',
    equation: 'P = \\frac{W}{t}',
    vars: [
      v('P', 'P', 'Power', 'power'),
      v('W', 'W', 'Work done / energy transferred', 'energy', { concept: 'work' }),
      v('t', 't', 'Time', 'time', { positive: true }),
    ],
    solve: {
      P: { expr: '\\frac{#W}{#t}', fn: ({ W, t }) => W / t },
      W: { expr: '#P \\times #t', fn: ({ P, t }) => P * t },
      t: { expr: '\\frac{#W}{#P}', fn: ({ W, P }) => W / P },
    },
    aliases: ['power', 'rate of work', 'rate of energy'],
    when: 'Rate at which work is done or energy transferred.',
    sheet: 'yes',
    source: 'Engineering mechanics — work, energy, power',
    hsc: ['Power of a lift motor', 'Average braking power'],
    example: { W: 60000, t: 12 },
    priority: 4,
  },
  {
    id: 'energyTime',
    name: 'Energy from power and time',
    modules: [...ALL],
    topic: 'Work, energy & power',
    equation: 'E = Pt',
    vars: [v('E', 'E', 'Energy', 'energy', { concept: 'energy' }), v('P', 'P', 'Power', 'power'), v('t', 't', 'Time', 'time', { positive: true })],
    solve: {
      E: { expr: '#P \\times #t', fn: ({ P, t }) => P * t },
      P: { expr: '\\frac{#E}{#t}', fn: ({ E, t }) => E / t },
      t: { expr: '\\frac{#E}{#P}', fn: ({ E, P }) => E / P },
    },
    aliases: ['energy used', 'energy consumed', 'kWh', 'electrical energy'],
    when: 'Energy used by a machine or electrical device running at a given power for a time.',
    sheet: 'derived',
    source: 'Engineering mechanics / electricity',
    hsc: ['Energy (kWh) used by an electric train motor', 'Battery energy for an electric vehicle trip'],
    example: { P: 1500, t: 3600 },
    priority: 3,
  },
  {
    id: 'powerFv',
    name: 'Power from force and velocity',
    modules: [...MECH],
    topic: 'Work, energy & power',
    equation: 'P = Fv',
    vars: [v('P', 'P', 'Power', 'power'), v('F', 'F', 'Driving / tractive force', 'force'), v('v', 'v', 'Velocity (constant)', 'velocity')],
    solve: {
      P: { expr: '#F \\times #v', fn: ({ F, v }) => F * v },
      F: { expr: '\\frac{#P}{#v}', fn: ({ P, v }) => P / v },
      v: { expr: '\\frac{#P}{#F}', fn: ({ P, F }) => P / F },
    },
    aliases: ['tractive power', 'power at the wheels', 'thrust power', 'P=Fv'],
    when: 'Power needed to maintain a speed against a resisting force (vehicle, aircraft thrust power).',
    sheet: 'derived',
    source: 'Engineering mechanics — work, energy, power',
    hsc: ['Power to drive a car at constant speed against resistance', 'Thrust power of an aircraft'],
    example: { F: 800, v: 25 },
    priority: 4,
  },
  {
    id: 'rotPower',
    name: 'Rotational power',
    modules: ['transport', 'aero'],
    topic: 'Work, energy & power',
    equation: 'P = T\\omega = \\frac{2\\pi N T}{60}',
    vars: [
      v('P', 'P', 'Power', 'power'),
      v('T', 'T', 'Torque', 'torque', { concept: 'torque' }),
      v('omega', '\\omega', 'Angular speed (enter rpm to use N)', 'angularVelocity', { positive: true }),
    ],
    solve: {
      P: { expr: '#T \\times #omega', fn: ({ T, omega }) => T * omega },
      T: { expr: '\\frac{#P}{#omega}', fn: ({ P, omega }) => P / omega },
      omega: { expr: '\\frac{#P}{#T}', fn: ({ P, T }) => P / T },
    },
    aliases: ['rotational power', 'shaft power', 'engine power torque rpm', '2πNT/60', 'motor power'],
    when: 'Power transmitted by a rotating shaft, engine or motor. ω (rad/s) = 2πN/60 with N in rpm.',
    sheet: 'yes',
    source: 'Engineering mechanics — work, energy, power',
    hsc: ['Engine power from torque and rpm', 'Torque delivered by an electric motor'],
    example: { T: 250, omega: (3000 * 2 * Math.PI) / 60 },
  },
  {
    id: 'efficiency',
    name: 'Efficiency (power or energy)',
    modules: [...ALL],
    topic: 'Work, energy & power',
    equation: '\\eta = \\frac{P_{out}}{P_{in}} \\times 100\\%',
    vars: [
      v('eta', '\\eta', 'Efficiency', 'percent', { nonNegative: true, warnAbove: 1, warnText: 'Efficiency above 100% is physically impossible for a real machine.' }),
      v('Pout', 'P_{out}', 'Useful output power (or energy)', 'power', { nonNegative: true }),
      v('Pin', 'P_{in}', 'Input power (or energy)', 'power', { positive: true }),
    ],
    solve: {
      eta: { expr: '\\frac{#Pout}{#Pin}', fn: ({ Pout, Pin }) => Pout / Pin },
      Pout: { expr: '#eta \\times #Pin', fn: ({ eta, Pin }) => eta * Pin },
      Pin: { expr: '\\frac{#Pout}{#eta}', fn: ({ Pout, eta }) => Pout / eta },
    },
    aliases: ['efficiency', 'eta', 'output over input', 'motor efficiency'],
    when: 'Ratio of useful output to input — engines, motors, transformers, machines.',
    sheet: 'yes',
    source: 'Engineering mechanics / electricity',
    hsc: ['Efficiency of an electric motor from electrical input and mechanical output', 'Overall efficiency of a drive train'],
    example: { Pout: 850, Pin: 1000 },
    checks: ({ eta }) => (eta > 1 + 1e-9 ? [{ level: 'error', message: `Efficiency of ${(eta * 100).toFixed(1)}% exceeds 100% — output cannot exceed input. Check the data.` }] : []),
    priority: 4,
  },
  {
    id: 'efficiencyEnergy',
    name: 'Efficiency (energy)',
    modules: [...ALL],
    topic: 'Work, energy & power',
    equation: '\\eta = \\frac{E_{out}}{E_{in}} \\times 100\\%',
    vars: [
      v('eta', '\\eta', 'Efficiency', 'percent', { nonNegative: true, warnAbove: 1, warnText: 'Efficiency above 100% is physically impossible for a real machine.' }),
      v('Eout', 'E_{out}', 'Useful energy / work out', 'energy', { nonNegative: true }),
      v('Ein', 'E_{in}', 'Energy / work in', 'energy', { positive: true }),
    ],
    solve: {
      eta: { expr: '\\frac{#Eout}{#Ein}', fn: ({ Eout, Ein }) => Eout / Ein },
      Eout: { expr: '#eta \\times #Ein', fn: ({ eta, Ein }) => eta * Ein },
      Ein: { expr: '\\frac{#Eout}{#eta}', fn: ({ Eout, eta }) => Eout / eta },
    },
    aliases: ['efficiency', 'work output over work input', 'energy efficiency'],
    when: 'Efficiency from work/energy in and out (machines, hydraulic lifts).',
    sheet: 'yes',
    source: 'Engineering mechanics',
    hsc: ['Efficiency of a pulley system from work output and input'],
    example: { Eout: 4000, Ein: 5000 },
    checks: ({ eta }) => (eta > 1 + 1e-9 ? [{ level: 'error', message: 'Efficiency exceeds 100% — output energy cannot exceed input.' }] : []),
    priority: 3,
  },
  // ——— Kinematics ———
  {
    id: 'suvat1',
    name: 'Equation of motion: v = u + at',
    modules: [...MECH],
    topic: 'Kinematics',
    equation: 'v = u + at',
    vars: [
      v('v', 'v', 'Final velocity', 'velocity'),
      v('u', 'u', 'Initial velocity', 'velocity'),
      v('a', 'a', 'Acceleration', 'acceleration'),
      v('t', 't', 'Time', 'time', { nonNegative: true }),
    ],
    solve: {
      v: { expr: '#u + #a \\times #t', fn: ({ u, a, t }) => u + a * t },
      u: { expr: '#v - #a \\times #t', fn: ({ v, a, t }) => v - a * t },
      a: { expr: '\\frac{#v - #u}{#t}', fn: ({ v, u, t }) => (v - u) / t },
      t: { expr: '\\frac{#v - #u}{#a}', fn: ({ v, u, a }) => (v - u) / a },
    },
    aliases: ['v=u+at', 'uniform acceleration', 'deceleration time'],
    when: 'Uniformly accelerated motion without displacement.',
    sheet: 'yes',
    source: 'Engineering mechanics — kinematics',
    hsc: ['Deceleration of a braking vehicle', 'Time for an aircraft to reach take-off speed'],
    example: { u: 0, a: 3, t: 8 },
    checks: ({ t }) => (t < 0 ? [{ level: 'error', message: 'Negative time — check the signs of u, v and a (deceleration is negative).' }] : []),
    priority: 3,
  },
  {
    id: 'suvat2',
    name: 'Equation of motion: s = ut + ½at²',
    modules: [...MECH],
    topic: 'Kinematics',
    equation: 's = ut + \\tfrac{1}{2}at^2',
    vars: [
      v('s', 's', 'Displacement', 'length'),
      v('u', 'u', 'Initial velocity', 'velocity'),
      v('t', 't', 'Time', 'time', { nonNegative: true }),
      v('a', 'a', 'Acceleration', 'acceleration'),
    ],
    solve: {
      s: { expr: '#u #t + \\tfrac{1}{2} #a #t^2', fn: ({ u, t, a }) => u * t + 0.5 * a * t * t },
      u: { expr: '\\frac{#s - \\tfrac{1}{2} #a #t^2}{#t}', fn: ({ s, a, t }) => (s - 0.5 * a * t * t) / t },
      a: { expr: '\\frac{2(#s - #u #t)}{#t^2}', fn: ({ s, u, t }) => (2 * (s - u * t)) / (t * t) },
      t: {
        expr: '\\frac{-#u + \\sqrt{#u^2 + 2 #a #s}}{#a}',
        fn: ({ s, u, a }) => {
          if (Math.abs(a) < 1e-12) return s / u;
          const disc = u * u + 2 * a * s;
          if (disc < 0) return NaN;
          const r1 = (-u + Math.sqrt(disc)) / a;
          const r2 = (-u - Math.sqrt(disc)) / a;
          const pos = [r1, r2].filter((x) => x >= -1e-12).sort((x, y) => x - y);
          return pos.length ? pos[0] : NaN;
        },
        note: 'quadratic in t — smallest non-negative root',
      },
    },
    aliases: ['s=ut+1/2at^2', 'distance travelled while accelerating'],
    when: 'Displacement under uniform acceleration given time.',
    sheet: 'yes',
    source: 'Engineering mechanics — kinematics',
    hsc: ['Take-off run distance', 'Distance covered while accelerating'],
    example: { u: 5, t: 4, a: 2 },
    priority: 3,
  },
  {
    id: 'suvat3',
    name: 'Equation of motion: v² = u² + 2as',
    modules: [...MECH],
    topic: 'Kinematics',
    equation: 'v^2 = u^2 + 2as',
    vars: [
      v('v', 'v', 'Final velocity', 'velocity'),
      v('u', 'u', 'Initial velocity', 'velocity'),
      v('a', 'a', 'Acceleration', 'acceleration'),
      v('s', 's', 'Displacement', 'length'),
    ],
    solve: {
      v: { expr: '\\sqrt{#u^2 + 2 #a #s}', fn: ({ u, a, s }) => Math.sqrt(u * u + 2 * a * s), note: 'positive root' },
      u: { expr: '\\sqrt{#v^2 - 2 #a #s}', fn: ({ v, a, s }) => Math.sqrt(v * v - 2 * a * s), note: 'positive root' },
      a: { expr: '\\frac{#v^2 - #u^2}{2 #s}', fn: ({ v, u, s }) => (v * v - u * u) / (2 * s) },
      s: { expr: '\\frac{#v^2 - #u^2}{2 #a}', fn: ({ v, u, a }) => (v * v - u * u) / (2 * a) },
    },
    aliases: ['v^2=u^2+2as', 'stopping distance', 'braking distance'],
    when: 'Uniform acceleration without time — braking/stopping distances.',
    sheet: 'yes',
    source: 'Engineering mechanics — kinematics',
    hsc: ['Braking distance from speed and deceleration', 'Deceleration needed to stop within a distance'],
    example: { u: 0, a: 2.5, s: 80 },
    priority: 3,
  },
  {
    id: 'suvat4',
    name: 'Equation of motion: s = ½(u + v)t',
    modules: [...MECH],
    topic: 'Kinematics',
    equation: 's = \\tfrac{1}{2}(u + v)t',
    vars: [v('s', 's', 'Displacement', 'length'), v('u', 'u', 'Initial velocity', 'velocity'), v('v', 'v', 'Final velocity', 'velocity'), v('t', 't', 'Time', 'time', { nonNegative: true })],
    solve: {
      s: { expr: '\\tfrac{1}{2}(#u + #v) #t', fn: ({ u, v, t }) => 0.5 * (u + v) * t },
      u: { expr: '\\frac{2 #s}{#t} - #v', fn: ({ s, t, v }) => (2 * s) / t - v },
      v: { expr: '\\frac{2 #s}{#t} - #u', fn: ({ s, t, u }) => (2 * s) / t - u },
      t: { expr: '\\frac{2 #s}{#u + #v}', fn: ({ s, u, v }) => (2 * s) / (u + v) },
    },
    aliases: ['average velocity', 's=(u+v)t/2'],
    when: 'Uniform acceleration without the acceleration value.',
    sheet: 'yes',
    source: 'Engineering mechanics — kinematics',
    hsc: ['Distance travelled while braking in a known time'],
    example: { u: 20, v: 0, t: 5 },
    priority: 2,
  },
  {
    id: 'constSpeed',
    name: 'Constant speed: s = vt',
    modules: [...ALL],
    topic: 'Kinematics',
    equation: 's = vt',
    vars: [v('s', 's', 'Distance', 'length'), v('v', 'v', 'Speed (constant)', 'velocity'), v('t', 't', 'Time', 'time', { positive: true })],
    solve: {
      s: { expr: '#v \\times #t', fn: ({ v, t }) => v * t },
      v: { expr: '\\frac{#s}{#t}', fn: ({ s, t }) => s / t },
      t: { expr: '\\frac{#s}{#v}', fn: ({ s, v }) => s / v },
    },
    aliases: ['average speed', 'distance speed time'],
    when: 'Motion at constant speed (or average speed).',
    sheet: 'derived',
    source: 'Engineering mechanics — kinematics',
    hsc: ['Travel time of a train at constant speed'],
    example: { v: 25, t: 60 },
    priority: 1,
  },
  {
    id: 'workEnergy',
    name: 'Work–energy theorem (braking / accelerating)',
    modules: ['transport', 'aero', 'civil'],
    topic: 'Work, energy & power',
    equation: 'Fs = \\tfrac{1}{2}m(u^2 - v^2)',
    vars: [
      v('F', 'F', 'Braking (resisting) force', 'force'),
      v('s', 's', 'Distance over which force acts', 'length', { positive: true }),
      v('m', 'm', 'Mass', 'mass', { positive: true }),
      v('u', 'u', 'Initial speed', 'velocity', { nonNegative: true }),
      v('v', 'v', 'Final speed', 'velocity', { nonNegative: true }),
    ],
    solve: {
      F: { expr: '\\frac{#m (#u^2 - #v^2)}{2 #s}', fn: ({ m, u, v, s }) => (m * (u * u - v * v)) / (2 * s) },
      s: { expr: '\\frac{#m (#u^2 - #v^2)}{2 #F}', fn: ({ m, u, v, F }) => (m * (u * u - v * v)) / (2 * F) },
      m: { expr: '\\frac{2 #F #s}{#u^2 - #v^2}', fn: ({ F, s, u, v }) => (2 * F * s) / (u * u - v * v) },
      u: { expr: '\\sqrt{#v^2 + \\frac{2 #F #s}{#m}}', fn: ({ v, F, s, m }) => Math.sqrt(v * v + (2 * F * s) / m) },
      v: { expr: '\\sqrt{#u^2 - \\frac{2 #F #s}{#m}}', fn: ({ u, F, s, m }) => Math.sqrt(u * u - (2 * F * s) / m) },
    },
    aliases: ['braking force', 'work energy', 'change in kinetic energy', 'stopping force'],
    when: 'Work done by a braking force equals the loss of kinetic energy.',
    sheet: 'derived',
    source: 'Engineering mechanics — work, energy, power',
    hsc: ['Average braking force to stop a car in a given distance', 'Stopping distance from braking force'],
    example: { s: 40, m: 1200, u: 20, v: 0 },
    priority: 2,
  },
  {
    id: 'tractive',
    name: 'Net force on a vehicle',
    modules: ['transport', 'aero'],
    topic: 'Forces & motion',
    equation: 'F_t - F_r = ma',
    vars: [
      v('Ft', 'F_t', 'Tractive / driving force (or thrust)', 'force'),
      v('Fr', 'F_r', 'Total resistance (drag, rolling, friction)', 'force'),
      v('m', 'm', 'Mass', 'mass', { positive: true }),
      v('a', 'a', 'Acceleration', 'acceleration'),
    ],
    solve: {
      Ft: { expr: '#m #a + #Fr', fn: ({ m, a, Fr }) => m * a + Fr },
      Fr: { expr: '#Ft - #m #a', fn: ({ Ft, m, a }) => Ft - m * a },
      m: { expr: '\\frac{#Ft - #Fr}{#a}', fn: ({ Ft, Fr, a }) => (Ft - Fr) / a },
      a: { expr: '\\frac{#Ft - #Fr}{#m}', fn: ({ Ft, Fr, m }) => (Ft - Fr) / m },
    },
    aliases: ['tractive force', 'driving force minus resistance', 'thrust minus drag'],
    when: 'Vehicle or aircraft accelerating against resistance.',
    sheet: 'derived',
    source: 'Engineering mechanics — dynamics',
    hsc: ['Acceleration of a train given tractive effort and resistance', 'Take-off acceleration: (T − D)/m'],
    example: { Fr: 1500, m: 1000, a: 1.2 },
    priority: 2,
  },
  {
    id: 'momentum',
    name: 'Momentum',
    modules: ['transport', 'aero'],
    topic: 'Forces & motion',
    equation: 'p = mv',
    vars: [v('pm', 'p', 'Momentum', 'momentum'), v('m', 'm', 'Mass', 'mass', { positive: true }), v('v', 'v', 'Velocity', 'velocity')],
    solve: {
      pm: { expr: '#m \\times #v', fn: ({ m, v }) => m * v },
      m: { expr: '\\frac{#pm}{#v}', fn: ({ pm, v }) => pm / v },
      v: { expr: '\\frac{#pm}{#m}', fn: ({ pm, m }) => pm / m },
    },
    aliases: ['momentum'],
    when: 'Collisions and impact (vehicle safety).',
    sheet: 'no',
    source: 'Engineering mechanics — dynamics',
    hsc: ['Momentum of a vehicle before a collision'],
    example: { m: 1200, v: 15 },
    extension: true,
  },
  {
    id: 'impulse',
    name: 'Impulse–momentum',
    modules: ['transport', 'aero'],
    topic: 'Forces & motion',
    equation: 'F\\Delta t = m(v - u)',
    vars: [
      v('F', 'F', 'Average force', 'force'),
      v('t', '\\Delta t', 'Time of impact', 'time', { positive: true }),
      v('m', 'm', 'Mass', 'mass', { positive: true }),
      v('v', 'v', 'Final velocity', 'velocity'),
      v('u', 'u', 'Initial velocity', 'velocity'),
    ],
    solve: {
      F: { expr: '\\frac{#m (#v - #u)}{#t}', fn: ({ m, v, u, t }) => (m * (v - u)) / t },
      t: { expr: '\\frac{#m (#v - #u)}{#F}', fn: ({ m, v, u, F }) => (m * (v - u)) / F },
      m: { expr: '\\frac{#F #t}{#v - #u}', fn: ({ F, t, v, u }) => (F * t) / (v - u) },
      v: { expr: '#u + \\frac{#F #t}{#m}', fn: ({ u, F, t, m }) => u + (F * t) / m },
      u: { expr: '#v - \\frac{#F #t}{#m}', fn: ({ v, F, t, m }) => v - (F * t) / m },
    },
    aliases: ['impulse', 'impact force', 'crumple zone', 'airbag'],
    when: 'Average impact force — crumple zones and airbags increase Δt to reduce F.',
    sheet: 'no',
    source: 'Engineering mechanics — dynamics',
    hsc: ['Average force on an occupant during a collision'],
    example: { t: 0.1, m: 70, v: 0, u: 15 },
    extension: true,
    priority: 1,
  },
  {
    id: 'centripetal',
    name: 'Centripetal force (cornering)',
    modules: ['transport'],
    topic: 'Forces & motion',
    equation: 'F = \\frac{mv^2}{r}',
    vars: [
      v('F', 'F', 'Centripetal force', 'force'),
      v('m', 'm', 'Mass', 'mass', { positive: true }),
      v('v', 'v', 'Speed', 'velocity'),
      v('r', 'r', 'Radius of the curve', 'length', { positive: true, concept: 'radius' }),
    ],
    solve: {
      F: { expr: '\\frac{#m #v^2}{#r}', fn: ({ m, v, r }) => (m * v * v) / r },
      m: { expr: '\\frac{#F #r}{#v^2}', fn: ({ F, r, v }) => (F * r) / (v * v) },
      v: { expr: '\\sqrt{\\frac{#F #r}{#m}}', fn: ({ F, r, m }) => Math.sqrt((F * r) / m) },
      r: { expr: '\\frac{#m #v^2}{#F}', fn: ({ m, v, F }) => (m * v * v) / F },
    },
    aliases: ['cornering', 'centripetal', 'curve', 'roundabout'],
    when: 'Side friction needed for a vehicle to take a curve.',
    sheet: 'no',
    source: 'Engineering mechanics — dynamics',
    hsc: ['Friction force required for a car cornering'],
    example: { m: 1000, v: 15, r: 50 },
    extension: true,
    priority: 0,
  },
];
