/**
 * Telecommunications Engineering: electrical circuits, waves, antennas, decibels,
 * fibre optics, digital signals and data.
 */
import { cVar, FormulaDef, v } from './types';

const TEL = ['telecom'] as const;
const ELEC = ['telecom', 'transport'] as const;

export const telecomFormulas: FormulaDef[] = [
  {
    id: 'ohm',
    name: "Ohm's law",
    modules: [...ELEC],
    topic: 'Electrical circuits',
    equation: 'V = IR',
    vars: [v('V', 'V', 'Voltage (potential difference)', 'voltage'), v('I', 'I', 'Current', 'current'), v('R', 'R', 'Resistance', 'resistance', { positive: true })],
    solve: {
      V: { expr: '#I \\times #R', fn: ({ I, R }) => I * R },
      I: { expr: '\\frac{#V}{#R}', fn: ({ V, R }) => V / R },
      R: { expr: '\\frac{#V}{#I}', fn: ({ V, I }) => V / I },
    },
    aliases: ["ohm's law", 'ohms law', 'V=IR', 'potential difference', 'voltage drop'],
    when: 'Relationship between voltage, current and resistance in a conductor/resistor.',
    sheet: 'yes',
    source: 'Engineering electricity/electronics',
    hsc: ['Current drawn from a supply by a resistor network', 'Voltage drop across a resistor'],
    example: { I: 0.5, R: 24 },
    priority: 6,
  },
  {
    id: 'powerVI',
    name: 'Electrical power',
    modules: [...ELEC],
    topic: 'Electrical circuits',
    equation: 'P = VI',
    vars: [v('P', 'P', 'Power', 'power'), v('V', 'V', 'Voltage', 'voltage'), v('I', 'I', 'Current', 'current')],
    solve: {
      P: { expr: '#V \\times #I', fn: ({ V, I }) => V * I },
      V: { expr: '\\frac{#P}{#I}', fn: ({ P, I }) => P / I },
      I: { expr: '\\frac{#P}{#V}', fn: ({ P, V }) => P / V },
    },
    aliases: ['electrical power', 'P=VI', 'wattage', 'power rating'],
    when: 'Power delivered to/dissipated by a component or drawn from a supply.',
    sheet: 'yes',
    source: 'Engineering electricity/electronics',
    hsc: ['Power drawn by a traction motor', 'Current drawn by a 2 kW heater at 240 V'],
    example: { V: 240, I: 5 },
    priority: 6,
  },
  {
    id: 'powerI2R',
    name: 'Electrical power (I²R)',
    modules: [...ELEC],
    topic: 'Electrical circuits',
    equation: 'P = I^2 R',
    vars: [v('P', 'P', 'Power', 'power', { nonNegative: true }), v('I', 'I', 'Current', 'current'), v('R', 'R', 'Resistance', 'resistance', { positive: true })],
    solve: {
      P: { expr: '#I^2 \\times #R', fn: ({ I, R }) => I * I * R },
      I: { expr: '\\sqrt{\\frac{#P}{#R}}', fn: ({ P, R }) => Math.sqrt(P / R) },
      R: { expr: '\\frac{#P}{#I^2}', fn: ({ P, I }) => P / (I * I) },
    },
    aliases: ['I squared R', 'power loss', 'heating loss', 'transmission loss'],
    when: 'Power dissipated as heat in a resistance (transmission line losses).',
    sheet: 'yes',
    source: 'Engineering electricity/electronics',
    hsc: ['Power lost in transmission lines — why high voltage is used'],
    example: { I: 2, R: 10 },
    priority: 5,
  },
  {
    id: 'powerV2R',
    name: 'Electrical power (V²/R)',
    modules: [...ELEC],
    topic: 'Electrical circuits',
    equation: 'P = \\frac{V^2}{R}',
    vars: [v('P', 'P', 'Power', 'power', { nonNegative: true }), v('V', 'V', 'Voltage', 'voltage'), v('R', 'R', 'Resistance', 'resistance', { positive: true })],
    solve: {
      P: { expr: '\\frac{#V^2}{#R}', fn: ({ V, R }) => (V * V) / R },
      V: { expr: '\\sqrt{#P \\times #R}', fn: ({ P, R }) => Math.sqrt(P * R) },
      R: { expr: '\\frac{#V^2}{#P}', fn: ({ V, P }) => (V * V) / P },
    },
    aliases: ['V squared over R', 'heater resistance'],
    when: 'Power from voltage across a known resistance.',
    sheet: 'yes',
    source: 'Engineering electricity/electronics',
    hsc: ['Resistance of an element rated 1 kW at 240 V'],
    example: { V: 12, R: 6 },
    priority: 5,
  },
  {
    id: 'series2',
    name: 'Resistors in series (two)',
    modules: [...ELEC],
    topic: 'Electrical circuits',
    equation: 'R_T = R_1 + R_2',
    vars: [v('RT', 'R_T', 'Total resistance', 'resistance', { concept: 'R', positive: true }), v('R1', 'R_1', 'Resistor 1', 'resistance', { positive: true }), v('R2', 'R_2', 'Resistor 2', 'resistance', { positive: true })],
    solve: {
      RT: { expr: '#R1 + #R2', fn: ({ R1, R2 }) => R1 + R2 },
      R1: { expr: '#RT - #R2', fn: ({ RT, R2 }) => RT - R2 },
      R2: { expr: '#RT - #R1', fn: ({ RT, R1 }) => RT - R1 },
    },
    aliases: ['series', 'series resistance', 'total resistance series'],
    when: 'Series resistors (same current). For any network use the Circuit Analyser.',
    sheet: 'yes',
    source: 'Engineering electricity/electronics',
    hsc: ['Total resistance of series resistors'],
    example: { R1: 100, R2: 220 },
    checks: ({ R1, R2 }) => (R1 <= 0 || R2 <= 0 ? [{ level: 'error', message: 'A resistance must be positive — R_T must exceed each individual resistor.' }] : []),
    priority: 2,
  },
  {
    id: 'parallel2',
    name: 'Resistors in parallel (two)',
    modules: [...ELEC],
    topic: 'Electrical circuits',
    equation: '\\frac{1}{R_T} = \\frac{1}{R_1} + \\frac{1}{R_2}',
    vars: [v('RT', 'R_T', 'Total resistance', 'resistance', { concept: 'R', positive: true }), v('R1', 'R_1', 'Resistor 1', 'resistance', { positive: true }), v('R2', 'R_2', 'Resistor 2', 'resistance', { positive: true })],
    solve: {
      RT: { expr: '\\left(\\frac{1}{#R1} + \\frac{1}{#R2}\\right)^{-1}', fn: ({ R1, R2 }) => 1 / (1 / R1 + 1 / R2) },
      R1: { expr: '\\left(\\frac{1}{#RT} - \\frac{1}{#R2}\\right)^{-1}', fn: ({ RT, R2 }) => 1 / (1 / RT - 1 / R2) },
      R2: { expr: '\\left(\\frac{1}{#RT} - \\frac{1}{#R1}\\right)^{-1}', fn: ({ RT, R1 }) => 1 / (1 / RT - 1 / R1) },
    },
    aliases: ['parallel', 'parallel resistance', 'total resistance parallel', 'product over sum'],
    when: 'Parallel resistors (same voltage). R_T is always less than the smallest resistor.',
    sheet: 'yes',
    source: 'Engineering electricity/electronics',
    hsc: ['Equivalent resistance of parallel resistors'],
    example: { R1: 100, R2: 300 },
    checks: ({ RT, R1, R2 }) =>
      RT > Math.min(R1, R2) + 1e-9 || R1 <= 0 || R2 <= 0 ? [{ level: 'error', message: 'In parallel, R_T must be smaller than every branch resistance — inputs are inconsistent.' }] : [],
    priority: 2,
  },
  {
    id: 'wave',
    name: 'Wave equation',
    modules: [...TEL],
    topic: 'Waves & signals',
    equation: 'v = f\\lambda',
    vars: [
      v('c', 'v', 'Wave speed (3.00 × 10⁸ m/s for EM waves in vacuum/air)', 'velocity', { constant: 3e8, positive: true }),
      v('f', 'f', 'Frequency', 'frequency', { positive: true }),
      v('lambda', '\\lambda', 'Wavelength', 'length', { positive: true }),
    ],
    solve: {
      c: { expr: '#f \\times #lambda', fn: ({ f, lambda }) => f * lambda },
      f: { expr: '\\frac{#c}{#lambda}', fn: ({ c, lambda }) => c / lambda },
      lambda: { expr: '\\frac{#c}{#f}', fn: ({ c, f }) => c / f },
    },
    aliases: ['wavelength', 'frequency', 'c = fλ', 'v = fλ', 'radio wave', 'electromagnetic wave', 'microwave'],
    when: 'Relating frequency and wavelength of radio, microwave and light signals.',
    sheet: 'yes',
    source: 'Telecommunications — waves',
    hsc: ['Wavelength of an FM radio station', 'Frequency of a microwave link'],
    example: { f: 100e6, lambda: 3 },
    priority: 5,
  },
  {
    id: 'period',
    name: 'Period and frequency',
    modules: [...TEL],
    topic: 'Waves & signals',
    equation: 'T = \\frac{1}{f}',
    vars: [v('Tp', 'T', 'Period', 'time', { concept: 'period', positive: true }), v('f', 'f', 'Frequency', 'frequency', { positive: true })],
    solve: {
      Tp: { expr: '\\frac{1}{#f}', fn: ({ f }) => 1 / f },
      f: { expr: '\\frac{1}{#Tp}', fn: ({ Tp }) => 1 / Tp },
    },
    aliases: ['period', 'periodic time', 'cycle time'],
    when: 'Time for one cycle of a signal (reading an oscilloscope trace).',
    sheet: 'derived',
    source: 'Telecommunications — waves',
    hsc: ['Frequency of a signal from its period on a CRO'],
    example: { f: 50 },
    priority: 3,
  },
  {
    id: 'halfWave',
    name: 'Half-wave dipole antenna length',
    modules: [...TEL],
    topic: 'Antennas',
    equation: 'L = \\frac{\\lambda}{2}',
    vars: [v('La', 'L', 'Antenna length', 'length', { concept: 'antennaLength', positive: true }), v('lambda', '\\lambda', 'Wavelength', 'length', { positive: true })],
    solve: {
      La: { expr: '\\frac{#lambda}{2}', fn: ({ lambda }) => lambda / 2 },
      lambda: { expr: '2 \\times #La', fn: ({ La }) => 2 * La },
    },
    aliases: ['half wave dipole', 'dipole antenna', 'antenna length', 'aerial length'],
    when: 'Resonant dipole antenna length (ideal, ignoring end effects).',
    sheet: 'no',
    source: 'Telecommunications — antennas',
    hsc: ['Length of a dipole for a given broadcast frequency'],
    example: { lambda: 3 },
    priority: 2,
  },
  {
    id: 'quarterWave',
    name: 'Quarter-wave (monopole) antenna length',
    modules: [...TEL],
    topic: 'Antennas',
    equation: 'L = \\frac{\\lambda}{4}',
    vars: [v('La', 'L', 'Antenna length', 'length', { concept: 'antennaLength', positive: true }), v('lambda', '\\lambda', 'Wavelength', 'length', { positive: true })],
    solve: {
      La: { expr: '\\frac{#lambda}{4}', fn: ({ lambda }) => lambda / 4 },
      lambda: { expr: '4 \\times #La', fn: ({ La }) => 4 * La },
    },
    aliases: ['quarter wave', 'monopole', 'whip antenna', 'mobile phone antenna'],
    when: 'Quarter-wave whip/monopole antennas (vehicles, handsets).',
    sheet: 'no',
    source: 'Telecommunications — antennas',
    hsc: ['Length of a quarter-wave car radio antenna'],
    example: { lambda: 0.33 },
    priority: 1,
  },
  {
    id: 'dbPower',
    name: 'Power gain / loss in decibels',
    modules: [...TEL],
    topic: 'Decibels',
    equation: 'G_{dB} = 10\\log_{10}\\left(\\frac{P_{out}}{P_{in}}\\right)',
    vars: [
      v('G', 'G_{dB}', 'Gain (negative = loss/attenuation)', 'decibel', { concept: 'gainDb' }),
      v('P2', 'P_{out}', 'Output power', 'power', { concept: 'Pout', positive: true }),
      v('P1', 'P_{in}', 'Input power', 'power', { concept: 'Pin', positive: true }),
    ],
    solve: {
      G: { expr: '10\\log_{10}\\left(\\frac{#P2}{#P1}\\right)', fn: ({ P2, P1 }) => 10 * Math.log10(P2 / P1) },
      P2: { expr: '#P1 \\times 10^{#G/10}', fn: ({ P1, G }) => P1 * Math.pow(10, G / 10) },
      P1: { expr: '\\frac{#P2}{10^{#G/10}}', fn: ({ P2, G }) => P2 / Math.pow(10, G / 10) },
    },
    aliases: ['decibel', 'dB', 'gain', 'attenuation', 'amplifier gain', 'signal loss', 'power ratio'],
    when: 'Amplifier gain or cable/fibre attenuation as a logarithmic power ratio (3 dB ≈ ×2).',
    sheet: 'no',
    source: 'Telecommunications — signals',
    hsc: ['Output power of an amplifier with 20 dB gain', 'Signal remaining after a lossy cable'],
    example: { P2: 10, P1: 0.1 },
    priority: 3,
  },
  {
    id: 'dbVoltage',
    name: 'Voltage gain in decibels',
    modules: [...TEL],
    topic: 'Decibels',
    equation: 'G_{dB} = 20\\log_{10}\\left(\\frac{V_{out}}{V_{in}}\\right)',
    vars: [
      v('G', 'G_{dB}', 'Voltage gain', 'decibel', { concept: 'gainDb' }),
      v('V2', 'V_{out}', 'Output voltage', 'voltage', { concept: 'Vout', positive: true }),
      v('V1', 'V_{in}', 'Input voltage', 'voltage', { concept: 'Vin', positive: true }),
    ],
    solve: {
      G: { expr: '20\\log_{10}\\left(\\frac{#V2}{#V1}\\right)', fn: ({ V2, V1 }) => 20 * Math.log10(V2 / V1) },
      V2: { expr: '#V1 \\times 10^{#G/20}', fn: ({ V1, G }) => V1 * Math.pow(10, G / 20) },
      V1: { expr: '\\frac{#V2}{10^{#G/20}}', fn: ({ V2, G }) => V2 / Math.pow(10, G / 20) },
    },
    aliases: ['voltage gain', 'dB voltage'],
    when: 'Amplifier voltage gain (equal impedances).',
    sheet: 'no',
    source: 'Telecommunications — signals',
    hsc: ['Voltage gain of an amplifier stage'],
    example: { V2: 5, V1: 0.05 },
    priority: 2,
  },
  {
    id: 'fibreLoss',
    name: 'Total attenuation of a link',
    modules: [...TEL],
    topic: 'Fibre optics',
    equation: '\\text{Loss}_{dB} = \\alpha \\ell',
    vars: [
      v('loss', '\\text{Loss}', 'Total loss', 'decibel', { concept: 'lossDb', nonNegative: true }),
      v('alpha', '\\alpha', 'Attenuation per length', 'attenuation', { nonNegative: true }),
      v('len', '\\ell', 'Link length', 'length', { concept: 'linkLength', positive: true }),
    ],
    solve: {
      loss: { expr: '#alpha \\times #len', fn: ({ alpha, len }) => alpha * len },
      alpha: { expr: '\\frac{#loss}{#len}', fn: ({ loss, len }) => loss / len },
      len: { expr: '\\frac{#loss}{#alpha}', fn: ({ loss, alpha }) => loss / alpha },
    },
    aliases: ['attenuation', 'fibre loss', 'dB per km', 'cable loss', 'repeater spacing'],
    when: 'Attenuation of optical fibre or copper cable (dB/km × km).',
    sheet: 'no',
    source: 'Telecommunications — fibre optics',
    hsc: ['Maximum distance before a repeater is needed', 'Received power over a fibre link'],
    example: { alpha: 0.3e-3, len: 50000 },
    priority: 2,
  },
  {
    id: 'snell',
    name: "Snell's law (refraction)",
    modules: [...TEL],
    topic: 'Fibre optics',
    equation: 'n_1\\sin\\theta_1 = n_2\\sin\\theta_2',
    vars: [
      v('theta2', '\\theta_2', 'Angle of refraction (from normal)', 'angle', { min: 0, max: Math.PI / 2 }),
      v('n1', 'n_1', 'Refractive index of medium 1', 'ratio', { min: 1 }),
      v('theta1', '\\theta_1', 'Angle of incidence (from normal)', 'angle', { min: 0, max: Math.PI / 2 }),
      v('n2', 'n_2', 'Refractive index of medium 2', 'ratio', { min: 1 }),
    ],
    solve: {
      theta2: { expr: '\\sin^{-1}\\left(\\frac{#n1 \\sin(#theta1)}{#n2}\\right)', fn: ({ n1, theta1, n2 }) => Math.asin((n1 * Math.sin(theta1)) / n2) },
      n1: { expr: '\\frac{#n2 \\sin(#theta2)}{\\sin(#theta1)}', fn: ({ n2, theta2, theta1 }) => (n2 * Math.sin(theta2)) / Math.sin(theta1) },
      theta1: { expr: '\\sin^{-1}\\left(\\frac{#n2 \\sin(#theta2)}{#n1}\\right)', fn: ({ n2, theta2, n1 }) => Math.asin((n2 * Math.sin(theta2)) / n1) },
      n2: { expr: '\\frac{#n1 \\sin(#theta1)}{\\sin(#theta2)}', fn: ({ n1, theta1, theta2 }) => (n1 * Math.sin(theta1)) / Math.sin(theta2) },
    },
    aliases: ["snell's law", 'refraction', 'refractive index', 'angle of incidence', 'angle of refraction'],
    when: 'Refraction of light at the boundary between two media (angles from the normal). If no real answer, total internal reflection occurs.',
    sheet: 'no',
    source: 'Telecommunications — fibre optics',
    hsc: ['Angle of refraction entering a fibre core', 'Showing total internal reflection occurs'],
    example: { n1: 1.0, theta1: (30 * Math.PI) / 180, n2: 1.5 },
    priority: 3,
  },
  {
    id: 'criticalAngle',
    name: 'Critical angle (total internal reflection)',
    modules: [...TEL],
    topic: 'Fibre optics',
    equation: '\\sin\\theta_c = \\frac{n_2}{n_1}',
    vars: [
      v('thetaC', '\\theta_c', 'Critical angle (from normal)', 'angle', { min: 0, max: Math.PI / 2 }),
      v('n1', 'n_1', 'Core refractive index (denser)', 'ratio', { min: 1 }),
      v('n2', 'n_2', 'Cladding refractive index', 'ratio', { min: 1 }),
    ],
    solve: {
      thetaC: { expr: '\\sin^{-1}\\left(\\frac{#n2}{#n1}\\right)', fn: ({ n2, n1 }) => Math.asin(n2 / n1) },
      n1: { expr: '\\frac{#n2}{\\sin(#thetaC)}', fn: ({ n2, thetaC }) => n2 / Math.sin(thetaC) },
      n2: { expr: '#n1 \\sin(#thetaC)', fn: ({ n1, thetaC }) => n1 * Math.sin(thetaC) },
    },
    aliases: ['critical angle', 'total internal reflection', 'TIR', 'core', 'cladding', 'optical fibre'],
    when: 'Light in the core is totally internally reflected when it meets the cladding at more than θc. Requires n₁ > n₂.',
    sheet: 'no',
    source: 'Telecommunications — fibre optics',
    hsc: ['Critical angle at the core–cladding boundary'],
    example: { n1: 1.5, n2: 1.46 },
    checks: ({ n1, n2 }) => (n2 >= n1 ? [{ level: 'error', message: 'Total internal reflection requires n₁ (core) > n₂ (cladding).' }] : []),
    priority: 3,
  },
  {
    id: 'refractiveIndex',
    name: 'Refractive index',
    modules: [...TEL],
    topic: 'Fibre optics',
    equation: 'n = \\frac{c}{v}',
    vars: [v('n', 'n', 'Refractive index', 'ratio', { concept: 'n1', min: 1 }), cVar(), v('vm', 'v', 'Speed of light in the medium', 'velocity', { concept: 'vMedium', positive: true })],
    solve: {
      n: { expr: '\\frac{#c}{#vm}', fn: ({ c, vm }) => c / vm },
      vm: { expr: '\\frac{#c}{#n}', fn: ({ c, n }) => c / n },
      c: { expr: '#n \\times #vm', fn: ({ n, vm }) => n * vm },
    },
    aliases: ['refractive index', 'speed of light in glass', 'speed in fibre'],
    when: 'Speed of light in a fibre core (for transmission delay).',
    sheet: 'no',
    source: 'Telecommunications — fibre optics',
    hsc: ['Time for a pulse to travel along a fibre'],
    example: { vm: 2e8 },
    priority: 2,
  },
  {
    id: 'numericalAperture',
    name: 'Numerical aperture / acceptance angle',
    modules: [...TEL],
    topic: 'Fibre optics',
    equation: '\\sin\\theta_a = \\sqrt{n_1^2 - n_2^2}',
    vars: [
      v('thetaA', '\\theta_a', 'Acceptance (half) angle in air', 'angle', { min: 0, max: Math.PI / 2 }),
      v('n1', 'n_1', 'Core index', 'ratio', { min: 1 }),
      v('n2', 'n_2', 'Cladding index', 'ratio', { min: 1 }),
    ],
    solve: {
      thetaA: { expr: '\\sin^{-1}\\sqrt{#n1^2 - #n2^2}', fn: ({ n1, n2 }) => Math.asin(Math.sqrt(n1 * n1 - n2 * n2)) },
      n1: { expr: '\\sqrt{\\sin^2(#thetaA) + #n2^2}', fn: ({ thetaA, n2 }) => Math.sqrt(Math.sin(thetaA) ** 2 + n2 * n2) },
      n2: { expr: '\\sqrt{#n1^2 - \\sin^2(#thetaA)}', fn: ({ thetaA, n1 }) => Math.sqrt(n1 * n1 - Math.sin(thetaA) ** 2) },
    },
    aliases: ['numerical aperture', 'acceptance angle', 'acceptance cone', 'NA'],
    when: 'Maximum launch angle for light to be guided by a fibre.',
    sheet: 'no',
    source: 'Telecommunications — fibre optics',
    hsc: ['Acceptance angle of a step-index fibre'],
    example: { n1: 1.48, n2: 1.46 },
    extension: true,
    priority: 1,
  },
  {
    id: 'propDelay',
    name: 'Signal propagation delay',
    modules: [...TEL],
    topic: 'Waves & signals',
    equation: 't = \\frac{d}{v}',
    vars: [
      v('t', 't', 'Delay (travel time)', 'time', { nonNegative: true }),
      v('s', 'd', 'Distance travelled by the signal', 'length', { nonNegative: true }),
      v('c', 'v', 'Signal speed (3.00 × 10⁸ m/s for radio)', 'velocity', { constant: 3e8, positive: true }),
    ],
    solve: {
      t: { expr: '\\frac{#s}{#c}', fn: ({ s, c }) => s / c },
      s: { expr: '#c \\times #t', fn: ({ c, t }) => c * t },
      c: { expr: '\\frac{#s}{#t}', fn: ({ s, t }) => s / t },
    },
    aliases: ['delay', 'latency', 'geostationary satellite', 'travel time of signal', 'propagation'],
    when: 'Time for a radio/light signal to travel a distance (satellite latency: up and down = 2 × altitude).',
    sheet: 'derived',
    source: 'Telecommunications — satellite',
    hsc: ['Delay of a signal via a geostationary satellite (~35 786 km altitude)'],
    example: { s: 2 * 35786e3 },
    contextOnly: ['telecom'],
    priority: 3,
  },
  {
    id: 'dataTime',
    name: 'Data transfer time',
    modules: [...TEL],
    topic: 'Digital data',
    equation: 't = \\frac{\\text{data size}}{\\text{bit rate}}',
    vars: [
      v('t', 't', 'Transfer time', 'time', { positive: true }),
      v('D', 'D', 'Data size', 'data', { concept: 'dataSize', positive: true }),
      v('Rb', 'R_b', 'Bit rate', 'dataRate', { concept: 'bitRate', positive: true }),
    ],
    solve: {
      t: { expr: '\\frac{#D}{#Rb}', fn: ({ D, Rb }) => D / Rb },
      D: { expr: '#Rb \\times #t', fn: ({ Rb, t }) => Rb * t },
      Rb: { expr: '\\frac{#D}{#t}', fn: ({ D, t }) => D / t },
    },
    aliases: ['download time', 'bit rate', 'bandwidth', 'Mbps', 'data rate', 'transfer'],
    when: 'Time to transmit a file. 1 byte = 8 bits (MB ≠ Mb).',
    sheet: 'no',
    source: 'Telecommunications — digital',
    hsc: ['Time to download a file over an NBN link'],
    example: { D: 8e8, Rb: 50e6 },
    priority: 2,
  },
  {
    id: 'nyquist',
    name: 'Nyquist sampling rate',
    modules: [...TEL],
    topic: 'Digital data',
    equation: 'f_s = 2 f_{max}',
    vars: [v('fs', 'f_s', 'Minimum sampling frequency', 'frequency', { positive: true }), v('fmax', 'f_{max}', 'Highest signal frequency', 'frequency', { positive: true })],
    solve: {
      fs: { expr: '2 \\times #fmax', fn: ({ fmax }) => 2 * fmax },
      fmax: { expr: '\\frac{#fs}{2}', fn: ({ fs }) => fs / 2 },
    },
    aliases: ['nyquist', 'sampling rate', 'sampling frequency', 'analogue to digital', 'ADC', 'PCM'],
    when: 'Minimum sampling frequency to digitise an analogue signal without aliasing.',
    sheet: 'no',
    source: 'Telecommunications — digital',
    hsc: ['Sampling rate for telephone voice (4 kHz → 8 kHz)'],
    example: { fmax: 4000 },
    priority: 2,
  },
  {
    id: 'pcmBitRate',
    name: 'PCM bit rate',
    modules: [...TEL],
    topic: 'Digital data',
    equation: 'R_b = f_s \\times n \\times \\text{channels}',
    vars: [
      v('Rb', 'R_b', 'Bit rate', 'dataRate', { concept: 'bitRate', positive: true }),
      v('fs', 'f_s', 'Sampling frequency', 'frequency', { positive: true }),
      v('nb', 'n', 'Bits per sample', 'count', { concept: 'bitsPerSample', positive: true }),
      v('ch', 'N_{ch}', 'Number of channels', 'count', { concept: 'channels', positive: true, constant: 1 }),
    ],
    solve: {
      Rb: { expr: '#fs \\times #nb \\times #ch', fn: ({ fs, nb, ch }) => fs * nb * ch },
      fs: { expr: '\\frac{#Rb}{#nb #ch}', fn: ({ Rb, nb, ch }) => Rb / (nb * ch) },
      nb: { expr: '\\frac{#Rb}{#fs #ch}', fn: ({ Rb, fs, ch }) => Rb / (fs * ch) },
      ch: { expr: '\\frac{#Rb}{#fs #nb}', fn: ({ Rb, fs, nb }) => Rb / (fs * nb) },
    },
    aliases: ['PCM', 'bits per sample', 'CD audio', 'digital audio bit rate'],
    when: 'Bit rate produced by pulse-code modulation (e.g. CD audio 44.1 kHz × 16 bit × 2).',
    sheet: 'no',
    source: 'Telecommunications — digital',
    hsc: ['Bit rate of a digitised voice channel (8 kHz × 8 bit = 64 kbit/s)'],
    example: { fs: 44100, nb: 16, ch: 2 },
    priority: 2,
  },
  {
    id: 'quantLevels',
    name: 'Quantisation levels',
    modules: [...TEL],
    topic: 'Digital data',
    equation: 'N = 2^n',
    vars: [v('Nl', 'N', 'Number of levels', 'count', { concept: 'levels', positive: true }), v('nb', 'n', 'Number of bits', 'count', { concept: 'bitsPerSample', nonNegative: true })],
    solve: {
      Nl: { expr: '2^{#nb}', fn: ({ nb }) => Math.pow(2, nb) },
      nb: { expr: '\\log_2(#Nl)', fn: ({ Nl }) => Math.log2(Nl) },
    },
    aliases: ['quantisation levels', 'number of levels', 'resolution bits', '2^n'],
    when: 'Number of distinct values an n-bit binary word can represent.',
    sheet: 'no',
    source: 'Telecommunications — digital',
    hsc: ['Levels available from an 8-bit ADC (256)'],
    example: { nb: 8 },
    priority: 1,
  },
  {
    id: 'amIndex',
    name: 'AM modulation index',
    modules: [...TEL],
    topic: 'Modulation',
    equation: 'm = \\frac{V_m}{V_c}',
    vars: [
      v('mi', 'm', 'Modulation index (depth)', 'percent', { concept: 'modIndex', nonNegative: true, warnAbove: 1, warnText: 'm > 1 causes over-modulation and distortion.' }),
      v('Vm', 'V_m', 'Modulating (message) amplitude', 'voltage', { nonNegative: true }),
      v('Vc', 'V_c', 'Carrier amplitude', 'voltage', { positive: true }),
    ],
    solve: {
      mi: { expr: '\\frac{#Vm}{#Vc}', fn: ({ Vm, Vc }) => Vm / Vc },
      Vm: { expr: '#mi \\times #Vc', fn: ({ mi, Vc }) => mi * Vc },
      Vc: { expr: '\\frac{#Vm}{#mi}', fn: ({ Vm, mi }) => Vm / mi },
    },
    aliases: ['modulation index', 'modulation depth', 'amplitude modulation', 'AM'],
    when: 'Depth of amplitude modulation.',
    sheet: 'no',
    source: 'Telecommunications — modulation',
    hsc: ['Modulation depth from an AM waveform'],
    example: { Vm: 2, Vc: 5 },
    extension: true,
    priority: 1,
  },
  {
    id: 'amBandwidth',
    name: 'AM bandwidth',
    modules: [...TEL],
    topic: 'Modulation',
    equation: 'BW = 2 f_m',
    vars: [v('BW', 'BW', 'Bandwidth', 'frequency', { concept: 'bandwidth', positive: true }), v('fm', 'f_m', 'Highest modulating frequency', 'frequency', { concept: 'fmax', positive: true })],
    solve: {
      BW: { expr: '2 \\times #fm', fn: ({ fm }) => 2 * fm },
      fm: { expr: '\\frac{#BW}{2}', fn: ({ BW }) => BW / 2 },
    },
    aliases: ['AM bandwidth', 'sidebands', 'upper sideband', 'lower sideband'],
    when: 'AM produces upper and lower sidebands, doubling the message bandwidth.',
    sheet: 'no',
    source: 'Telecommunications — modulation',
    hsc: ['Bandwidth of an AM broadcast (5 kHz audio → 10 kHz)'],
    example: { fm: 5000 },
    extension: true,
    priority: 1,
  },
];
