/**
 * Personal & Public Transport: friction, simple machines, mechanisms, hydraulics,
 * electrical energy for transport systems.
 */
import { FormulaDef, v } from './types';

export const transportFormulas: FormulaDef[] = [
  {
    id: 'friction',
    name: 'Friction force',
    modules: ['transport', 'civil', 'aero'],
    topic: 'Friction',
    equation: 'F_f = \\mu N',
    vars: [
      v('Ff', 'F_f', 'Friction force (limiting)', 'force', { nonNegative: true }),
      v('mu', '\\mu', 'Coefficient of (static) friction', 'ratio', { nonNegative: true, warnAbove: 1.5, warnText: 'μ above 1.5 is unusual for engineering surfaces — check the data.' }),
      v('N', 'N', 'Normal reaction force', 'force', { concept: 'normal', nonNegative: true }),
    ],
    solve: {
      Ff: { expr: '#mu \\times #N', fn: ({ mu, N }) => mu * N },
      mu: { expr: '\\frac{#Ff}{#N}', fn: ({ Ff, N }) => Ff / N },
      N: { expr: '\\frac{#Ff}{#mu}', fn: ({ Ff, mu }) => Ff / mu },
    },
    aliases: ['friction', 'frictional force', 'coefficient of friction', 'limiting friction', 'F=μN', 'normal force'],
    when: 'Limiting (maximum) friction between surfaces — brakes, tyres, clutches, sliding loads.',
    sheet: 'yes',
    source: 'Engineering mechanics — friction',
    hsc: ['Force needed to start a crate sliding', 'Braking force available at the tyres', 'μ from a sliding test'],
    example: { mu: 0.3, N: 1000 },
    priority: 5,
  },
  {
    id: 'frictionAngle',
    name: 'Angle of friction / repose',
    modules: ['transport', 'civil'],
    topic: 'Friction',
    equation: '\\mu = \\tan\\phi',
    vars: [
      v('mu', '\\mu', 'Coefficient of friction', 'ratio', { nonNegative: true }),
      v('phi', '\\phi', 'Angle of friction (angle of repose)', 'angle', { min: 0, max: Math.PI / 2 }),
    ],
    solve: {
      mu: { expr: '\\tan(#phi)', fn: ({ phi }) => Math.tan(phi) },
      phi: { expr: '\\tan^{-1}(#mu)', fn: ({ mu }) => Math.atan(mu) },
    },
    aliases: ['angle of repose', 'angle of friction', 'μ = tan φ', 'tilting plane', 'about to slide'],
    when: 'A body on an incline is just about to slide when the incline angle equals φ.',
    sheet: 'yes',
    source: 'Engineering mechanics — friction',
    hsc: ['μ from the angle at which a block starts to slide'],
    example: { phi: 0.3 },
    priority: 4,
  },
  {
    id: 'inclineNormal',
    name: 'Normal force on an incline',
    modules: ['transport', 'civil'],
    topic: 'Friction',
    equation: 'N = W\\cos\\theta',
    vars: [
      v('N', 'N', 'Normal reaction', 'force', { concept: 'normal', nonNegative: true }),
      v('Wt', 'W', 'Weight (mg)', 'force', { positive: true }),
      v('theta', '\\theta', 'Incline angle', 'angle', { concept: 'incline', min: 0, max: Math.PI / 2 }),
    ],
    solve: {
      N: { expr: '#Wt \\cos(#theta)', fn: ({ Wt, theta }) => Wt * Math.cos(theta) },
      Wt: { expr: '\\frac{#N}{\\cos(#theta)}', fn: ({ N, theta }) => N / Math.cos(theta) },
      theta: { expr: '\\cos^{-1}\\left(\\frac{#N}{#Wt}\\right)', fn: ({ N, Wt }) => Math.acos(N / Wt) },
    },
    aliases: ['incline', 'inclined plane', 'ramp', 'slope', 'normal on slope'],
    when: 'Resolving weight perpendicular to an inclined surface.',
    sheet: 'derived',
    source: 'Engineering mechanics — friction',
    hsc: ['Friction on a vehicle parked on a hill'],
    example: { Wt: 1000, theta: (20 * Math.PI) / 180 },
    contextOnly: ['transport', 'civil'],
    priority: 3,
  },
  {
    id: 'inclineParallel',
    name: 'Weight component along an incline',
    modules: ['transport', 'civil'],
    topic: 'Friction',
    equation: 'F_{\\parallel} = W\\sin\\theta',
    vars: [
      v('Fpar', 'F_{\\parallel}', 'Component of weight down the slope', 'force'),
      v('Wt', 'W', 'Weight (mg)', 'force', { positive: true }),
      v('theta', '\\theta', 'Incline angle', 'angle', { concept: 'incline', min: 0, max: Math.PI / 2 }),
    ],
    solve: {
      Fpar: { expr: '#Wt \\sin(#theta)', fn: ({ Wt, theta }) => Wt * Math.sin(theta) },
      Wt: { expr: '\\frac{#Fpar}{\\sin(#theta)}', fn: ({ Fpar, theta }) => Fpar / Math.sin(theta) },
      theta: { expr: '\\sin^{-1}\\left(\\frac{#Fpar}{#Wt}\\right)', fn: ({ Fpar, Wt }) => Math.asin(Fpar / Wt) },
    },
    aliases: ['gradient resistance', 'down slope component', 'component of weight along slope'],
    when: 'Force tending to slide a body down a slope (gradient resistance of a vehicle).',
    sheet: 'derived',
    source: 'Engineering mechanics — friction',
    hsc: ['Extra tractive force for a vehicle climbing a hill'],
    example: { Wt: 1000, theta: (20 * Math.PI) / 180 },
    contextOnly: ['transport', 'civil'],
    priority: 3,
  },
  // ——— Simple machines ———
  {
    id: 'MA',
    name: 'Mechanical advantage',
    modules: ['transport', 'civil', 'aero'],
    topic: 'Simple machines',
    equation: 'MA = \\frac{L}{E}',
    vars: [
      v('MA', 'MA', 'Mechanical advantage', 'ratio', { positive: true }),
      v('Ld', 'L', 'Load (output force)', 'force', { concept: 'load', positive: true }),
      v('Ef', 'E', 'Effort (input force)', 'force', { concept: 'effort', positive: true }),
    ],
    solve: {
      MA: { expr: '\\frac{#Ld}{#Ef}', fn: ({ Ld, Ef }) => Ld / Ef },
      Ld: { expr: '#MA \\times #Ef', fn: ({ MA, Ef }) => MA * Ef },
      Ef: { expr: '\\frac{#Ld}{#MA}', fn: ({ Ld, MA }) => Ld / MA },
    },
    aliases: ['mechanical advantage', 'MA', 'load over effort', 'force ratio'],
    when: 'Force multiplication of a machine (lever, pulley, gear, hydraulic jack).',
    sheet: 'yes',
    source: 'Engineering mechanics — machines',
    hsc: ['MA of a pulley block', 'Effort required on a car jack'],
    example: { Ld: 2000, Ef: 500 },
    priority: 5,
  },
  {
    id: 'VR',
    name: 'Velocity ratio',
    modules: ['transport', 'civil', 'aero'],
    topic: 'Simple machines',
    equation: 'VR = \\frac{d_E}{d_L}',
    vars: [
      v('VR', 'VR', 'Velocity ratio', 'ratio', { positive: true }),
      v('dE', 'd_E', 'Distance moved by effort', 'length', { concept: 'distE', positive: true }),
      v('dLd', 'd_L', 'Distance moved by load', 'length', { concept: 'distL', positive: true }),
    ],
    solve: {
      VR: { expr: '\\frac{#dE}{#dLd}', fn: ({ dE, dLd }) => dE / dLd },
      dE: { expr: '#VR \\times #dLd', fn: ({ VR, dLd }) => VR * dLd },
      dLd: { expr: '\\frac{#dE}{#VR}', fn: ({ dE, VR }) => dE / VR },
    },
    aliases: ['velocity ratio', 'VR', 'movement ratio', 'distance ratio'],
    when: 'Ratio of distances moved (depends only on geometry, not friction).',
    sheet: 'yes',
    source: 'Engineering mechanics — machines',
    hsc: ['VR of a pulley system from rope pulled vs load raised'],
    example: { dE: 2, dLd: 0.5 },
    priority: 5,
  },
  {
    id: 'machineEff',
    name: 'Efficiency of a machine',
    modules: ['transport', 'civil', 'aero'],
    topic: 'Simple machines',
    equation: '\\eta = \\frac{MA}{VR} \\times 100\\%',
    vars: [
      v('eta', '\\eta', 'Efficiency', 'percent', { nonNegative: true, warnAbove: 1, warnText: 'Efficiency above 100% is impossible — MA cannot exceed VR.' }),
      v('MA', 'MA', 'Mechanical advantage', 'ratio', { positive: true }),
      v('VR', 'VR', 'Velocity ratio', 'ratio', { positive: true }),
    ],
    solve: {
      eta: { expr: '\\frac{#MA}{#VR}', fn: ({ MA, VR }) => MA / VR },
      MA: { expr: '#eta \\times #VR', fn: ({ eta, VR }) => eta * VR },
      VR: { expr: '\\frac{#MA}{#eta}', fn: ({ MA, eta }) => MA / eta },
    },
    aliases: ['efficiency of machine', 'MA/VR'],
    when: 'Efficiency of any simple machine.',
    sheet: 'yes',
    source: 'Engineering mechanics — machines',
    hsc: ['Efficiency of a block and tackle', 'Effort needed given efficiency and VR'],
    example: { MA: 3.2, VR: 4 },
    checks: ({ eta }) => (eta > 1 + 1e-9 ? [{ level: 'error', message: `η = ${(eta * 100).toFixed(1)}% > 100%: MA cannot exceed VR in a real machine. Check load, effort and distances.` }] : []),
    priority: 5,
  },
  {
    id: 'leverBalance',
    name: 'Lever balance (principle of moments)',
    modules: ['transport', 'civil'],
    topic: 'Simple machines',
    equation: 'E \\times a = L \\times b',
    vars: [
      v('Ef', 'E', 'Effort', 'force', { concept: 'effort', positive: true }),
      v('a', 'a', 'Effort arm (distance from fulcrum)', 'length', { concept: 'effortArm', positive: true }),
      v('Ld', 'L', 'Load', 'force', { concept: 'load', positive: true }),
      v('b', 'b', 'Load arm (distance from fulcrum)', 'length', { concept: 'loadArm', positive: true }),
    ],
    solve: {
      Ef: { expr: '\\frac{#Ld #b}{#a}', fn: ({ Ld, b, a }) => (Ld * b) / a },
      a: { expr: '\\frac{#Ld #b}{#Ef}', fn: ({ Ld, b, Ef }) => (Ld * b) / Ef },
      Ld: { expr: '\\frac{#Ef #a}{#b}', fn: ({ Ef, a, b }) => (Ef * a) / b },
      b: { expr: '\\frac{#Ef #a}{#Ld}', fn: ({ Ef, a, Ld }) => (Ef * a) / Ld },
    },
    aliases: ['lever', 'fulcrum', 'principle of moments', 'wheelbarrow', 'brake pedal'],
    when: 'Ideal (frictionless) lever: clockwise moments = anticlockwise moments about the fulcrum.',
    sheet: 'derived',
    source: 'Engineering mechanics — machines',
    hsc: ['Force at a brake pedal linkage', 'Effort on a wheelbarrow handle'],
    example: { a: 1.2, Ld: 600, b: 0.3 },
    priority: 3,
  },
  {
    id: 'leverVR',
    name: 'Velocity ratio of a lever',
    modules: ['transport'],
    topic: 'Simple machines',
    equation: 'VR = \\frac{a}{b}',
    vars: [
      v('VR', 'VR', 'Velocity ratio', 'ratio', { positive: true }),
      v('a', 'a', 'Effort arm', 'length', { concept: 'effortArm', positive: true }),
      v('b', 'b', 'Load arm', 'length', { concept: 'loadArm', positive: true }),
    ],
    solve: {
      VR: { expr: '\\frac{#a}{#b}', fn: ({ a, b }) => a / b },
      a: { expr: '#VR \\times #b', fn: ({ VR, b }) => VR * b },
      b: { expr: '\\frac{#a}{#VR}', fn: ({ a, VR }) => a / VR },
    },
    aliases: ['lever velocity ratio'],
    when: 'Geometry of a lever determines its VR.',
    sheet: 'derived',
    source: 'Engineering mechanics — machines',
    hsc: ['VR of a hand-brake lever'],
    example: { a: 0.4, b: 0.05 },
    priority: 2,
  },
  {
    id: 'pulleyVR',
    name: 'Velocity ratio of a pulley system',
    modules: ['transport', 'civil'],
    topic: 'Simple machines',
    equation: 'VR = n',
    vars: [v('VR', 'VR', 'Velocity ratio', 'ratio', { positive: true }), v('n', 'n', 'Number of rope segments supporting the load block', 'count', { concept: 'ropes', positive: true, integer: true })],
    solve: {
      VR: { expr: '#n', fn: ({ n }) => n },
      n: { expr: '#VR', fn: ({ VR }) => VR },
    },
    aliases: ['pulley', 'block and tackle', 'supporting ropes', 'sheaves'],
    when: 'Block and tackle: VR equals the number of rope falls supporting the moving block.',
    sheet: 'derived',
    source: 'Engineering mechanics — machines',
    hsc: ['VR and efficiency of a crane hoist'],
    example: { n: 4 },
    priority: 3,
  },
  {
    id: 'wheelAxle',
    name: 'Wheel and axle / belt drive VR',
    modules: ['transport'],
    topic: 'Mechanisms',
    equation: 'VR = \\frac{D}{d}',
    vars: [
      v('VR', 'VR', 'Velocity ratio', 'ratio', { positive: true }),
      v('Dw', 'D', 'Effort (wheel / driven pulley) diameter', 'length', { concept: 'Dwheel', positive: true }),
      v('da', 'd', 'Load (axle / driver pulley) diameter', 'length', { concept: 'daxle', positive: true }),
    ],
    solve: {
      VR: { expr: '\\frac{#Dw}{#da}', fn: ({ Dw, da }) => Dw / da },
      Dw: { expr: '#VR \\times #da', fn: ({ VR, da }) => VR * da },
      da: { expr: '\\frac{#Dw}{#VR}', fn: ({ Dw, VR }) => Dw / VR },
    },
    aliases: ['wheel and axle', 'belt drive', 'steering wheel', 'winch drum', 'pulley diameters'],
    when: 'Wheel-and-axle, winch or belt/chain drive ratio from diameters.',
    sheet: 'derived',
    source: 'Engineering mechanics — mechanisms',
    hsc: ['VR of a steering wheel on a shaft', 'Belt drive speed ratio'],
    example: { Dw: 0.4, da: 0.05 },
    priority: 2,
  },
  {
    id: 'screwJack',
    name: 'Screw jack VR',
    modules: ['transport'],
    topic: 'Mechanisms',
    equation: 'VR = \\frac{2\\pi R}{p}',
    vars: [
      v('VR', 'VR', 'Velocity ratio', 'ratio', { positive: true }),
      v('R', 'R', 'Handle (effort) radius', 'length', { concept: 'handleR', positive: true }),
      v('pt', 'p', 'Screw pitch (lead)', 'length', { concept: 'pitch', positive: true }),
    ],
    solve: {
      VR: { expr: '\\frac{2\\pi #R}{#pt}', fn: ({ R, pt }) => (2 * Math.PI * R) / pt },
      R: { expr: '\\frac{#VR #pt}{2\\pi}', fn: ({ VR, pt }) => (VR * pt) / (2 * Math.PI) },
      pt: { expr: '\\frac{2\\pi #R}{#VR}', fn: ({ R, VR }) => (2 * Math.PI * R) / VR },
    },
    aliases: ['screw jack', 'car jack', 'pitch of thread', 'lead screw'],
    when: 'One turn of the handle raises the load by one pitch.',
    sheet: 'no',
    source: 'Engineering mechanics — mechanisms',
    hsc: ['Effort required on a car screw jack'],
    example: { R: 0.3, pt: 0.005 },
    extension: true,
    priority: 1,
  },
  {
    id: 'gearRatio',
    name: 'Gear ratio (simple gear pair)',
    modules: ['transport', 'aero'],
    topic: 'Mechanisms',
    equation: 'GR = \\frac{T_{driven}}{T_{driver}} = \\frac{N_{driver}}{N_{driven}}',
    vars: [
      v('GR', 'GR', 'Gear ratio (= VR)', 'ratio', { concept: 'VR', positive: true }),
      v('tB', 'T_{driven}', 'Teeth on driven gear', 'count', { concept: 'teethDriven', positive: true, integer: true }),
      v('tA', 'T_{driver}', 'Teeth on driver gear', 'count', { concept: 'teethDriver', positive: true, integer: true }),
    ],
    solve: {
      GR: { expr: '\\frac{#tB}{#tA}', fn: ({ tB, tA }) => tB / tA },
      tB: { expr: '#GR \\times #tA', fn: ({ GR, tA }) => GR * tA },
      tA: { expr: '\\frac{#tB}{#GR}', fn: ({ tB, GR }) => tB / GR },
    },
    aliases: ['gear ratio', 'gears', 'teeth', 'driver gear', 'driven gear', 'gearbox', 'sprocket'],
    when: 'Speed reduction/torque increase of a gear pair (also chain sprockets). Use the Gear Train tool for compound trains.',
    sheet: 'derived',
    source: 'Engineering mechanics — mechanisms',
    hsc: ['Output speed of a gearbox', 'Bicycle chain-wheel and sprocket ratio'],
    example: { tB: 60, tA: 20 },
    priority: 3,
  },
  {
    id: 'gearSpeed',
    name: 'Gear speeds',
    modules: ['transport', 'aero'],
    topic: 'Mechanisms',
    equation: 'N_{driver} T_{driver} = N_{driven} T_{driven}',
    vars: [
      v('nB', 'N_{driven}', 'Speed of driven gear', 'angularVelocity', { concept: 'speedDriven', positive: true }),
      v('nA', 'N_{driver}', 'Speed of driver gear', 'angularVelocity', { concept: 'speedDriver', positive: true }),
      v('tA', 'T_{driver}', 'Teeth on driver', 'count', { concept: 'teethDriver', positive: true }),
      v('tB', 'T_{driven}', 'Teeth on driven', 'count', { concept: 'teethDriven', positive: true }),
    ],
    solve: {
      nB: { expr: '\\frac{#nA #tA}{#tB}', fn: ({ nA, tA, tB }) => (nA * tA) / tB },
      nA: { expr: '\\frac{#nB #tB}{#tA}', fn: ({ nB, tB, tA }) => (nB * tB) / tA },
      tA: { expr: '\\frac{#nB #tB}{#nA}', fn: ({ nB, tB, nA }) => (nB * tB) / nA },
      tB: { expr: '\\frac{#nA #tA}{#nB}', fn: ({ nA, tA, nB }) => (nA * tA) / nB },
    },
    aliases: ['output speed', 'rpm of gear', 'gear speed'],
    when: 'Relating rotational speeds of meshing gears.',
    sheet: 'derived',
    source: 'Engineering mechanics — mechanisms',
    hsc: ['Speed of the output shaft of a reduction gearbox'],
    example: { nA: (1200 * 2 * Math.PI) / 60, tA: 20, tB: 60 },
    priority: 3,
  },
  {
    id: 'gearTorque',
    name: 'Output torque through a gear train',
    modules: ['transport', 'aero'],
    topic: 'Mechanisms',
    equation: 'T_{out} = T_{in} \\times GR \\times \\eta',
    vars: [
      v('Tout', 'T_{out}', 'Output torque', 'torque'),
      v('Tin', 'T_{in}', 'Input torque', 'torque'),
      v('GR', 'GR', 'Gear ratio', 'ratio', { concept: 'VR', positive: true }),
      v('eta', '\\eta', 'Efficiency (1 if ideal)', 'percent', { positive: true, constant: 1, max: 1 }),
    ],
    solve: {
      Tout: { expr: '#Tin \\times #GR \\times #eta', fn: ({ Tin, GR, eta }) => Tin * GR * eta },
      Tin: { expr: '\\frac{#Tout}{#GR #eta}', fn: ({ Tout, GR, eta }) => Tout / (GR * eta) },
      GR: { expr: '\\frac{#Tout}{#Tin #eta}', fn: ({ Tout, Tin, eta }) => Tout / (Tin * eta) },
      eta: { expr: '\\frac{#Tout}{#Tin #GR}', fn: ({ Tout, Tin, GR }) => Tout / (Tin * GR) },
    },
    aliases: ['output torque', 'torque multiplication', 'final drive torque'],
    when: 'Gear reduction multiplies torque by the gear ratio (less losses).',
    sheet: 'derived',
    source: 'Engineering mechanics — mechanisms',
    hsc: ['Torque at the wheels after a final-drive reduction'],
    example: { Tin: 150, GR: 3.5, eta: 0.95 },
    contextOnly: ['transport', 'aero'],
    priority: 2,
  },
  // ——— Hydraulics ———
  {
    id: 'pascal',
    name: "Pascal's principle (hydraulic press/brakes)",
    modules: ['transport', 'aero', 'civil'],
    topic: 'Pressure & hydraulics',
    equation: '\\frac{F_1}{A_1} = \\frac{F_2}{A_2}',
    vars: [
      v('F2', 'F_2', 'Output force (large / slave piston)', 'force', { positive: true }),
      v('F1', 'F_1', 'Input force (small / master piston)', 'force', { positive: true }),
      v('A1', 'A_1', 'Input piston area', 'area', { positive: true }),
      v('A2', 'A_2', 'Output piston area', 'area', { positive: true }),
    ],
    solve: {
      F2: { expr: '\\frac{#F1 #A2}{#A1}', fn: ({ F1, A2, A1 }) => (F1 * A2) / A1 },
      F1: { expr: '\\frac{#F2 #A1}{#A2}', fn: ({ F2, A1, A2 }) => (F2 * A1) / A2 },
      A1: { expr: '\\frac{#F1 #A2}{#F2}', fn: ({ F1, A2, F2 }) => (F1 * A2) / F2 },
      A2: { expr: '\\frac{#F2 #A1}{#F1}', fn: ({ F2, A1, F1 }) => (F2 * A1) / F1 },
    },
    aliases: ["pascal's principle", 'hydraulic press', 'hydraulic brake', 'master cylinder', 'slave cylinder', 'hydraulic jack', 'piston'],
    when: 'Pressure applied to an enclosed fluid is transmitted equally: p = F₁/A₁ = F₂/A₂.',
    sheet: 'yes',
    source: 'Engineering mechanics — fluid mechanics',
    hsc: ['Force at a brake calliper from pedal force', 'Aircraft hydraulic actuator force', 'Hydraulic jack output force'],
    example: { F1: 200, A1: 3.14159e-4, A2: 7.85398e-3 },
    priority: 4,
  },
  {
    id: 'pistonArea1',
    name: 'Input piston area from diameter',
    modules: ['transport', 'aero', 'civil'],
    topic: 'Pressure & hydraulics',
    equation: 'A_1 = \\frac{\\pi d_1^2}{4}',
    vars: [v('A1', 'A_1', 'Input piston area', 'area', { positive: true }), v('d1', 'd_1', 'Input piston diameter', 'length', { positive: true })],
    solve: {
      A1: { expr: '\\frac{\\pi #d1^2}{4}', fn: ({ d1 }) => (Math.PI * d1 * d1) / 4 },
      d1: { expr: '\\sqrt{\\frac{4 #A1}{\\pi}}', fn: ({ A1 }) => Math.sqrt((4 * A1) / Math.PI) },
    },
    aliases: ['small piston diameter', 'master cylinder diameter'],
    when: 'Area of the input (small) piston.',
    sheet: 'no',
    source: 'Mathematics — mensuration',
    hsc: ['Hydraulic brake master cylinder'],
    example: { d1: 0.02 },
    priority: 7,
  },
  {
    id: 'pistonArea2',
    name: 'Output piston area from diameter',
    modules: ['transport', 'aero', 'civil'],
    topic: 'Pressure & hydraulics',
    equation: 'A_2 = \\frac{\\pi d_2^2}{4}',
    vars: [v('A2', 'A_2', 'Output piston area', 'area', { positive: true }), v('d2', 'd_2', 'Output piston diameter', 'length', { positive: true })],
    solve: {
      A2: { expr: '\\frac{\\pi #d2^2}{4}', fn: ({ d2 }) => (Math.PI * d2 * d2) / 4 },
      d2: { expr: '\\sqrt{\\frac{4 #A2}{\\pi}}', fn: ({ A2 }) => Math.sqrt((4 * A2) / Math.PI) },
    },
    aliases: ['large piston diameter', 'slave cylinder diameter', 'ram diameter'],
    when: 'Area of the output (large) piston.',
    sheet: 'no',
    source: 'Mathematics — mensuration',
    hsc: ['Hydraulic press ram'],
    example: { d2: 0.1 },
    priority: 7,
  },
  {
    id: 'hydraulicPressure',
    name: 'System pressure in a hydraulic circuit',
    modules: ['transport', 'aero', 'civil'],
    topic: 'Pressure & hydraulics',
    equation: 'P = \\frac{F_1}{A_1}',
    vars: [v('p', 'P', 'Fluid pressure', 'pressure', { positive: true }), v('F1', 'F_1', 'Input force', 'force', { positive: true }), v('A1', 'A_1', 'Input piston area', 'area', { positive: true })],
    solve: {
      p: { expr: '\\frac{#F1}{#A1}', fn: ({ F1, A1 }) => F1 / A1 },
      F1: { expr: '#p \\times #A1', fn: ({ p, A1 }) => p * A1 },
      A1: { expr: '\\frac{#F1}{#p}', fn: ({ F1, p }) => F1 / p },
    },
    aliases: ['line pressure', 'hydraulic pressure'],
    when: 'Pressure generated in the fluid by the input piston.',
    sheet: 'yes',
    source: 'Engineering mechanics — fluid mechanics',
    hsc: ['Brake line pressure'],
    example: { F1: 200, A1: 3.14159e-4 },
    priority: 3,
  },
  {
    id: 'hydraulicVolume',
    name: 'Hydraulic piston travel (volume conservation)',
    modules: ['transport', 'aero', 'civil'],
    topic: 'Pressure & hydraulics',
    equation: 'A_1 s_1 = A_2 s_2',
    vars: [
      v('s2', 's_2', 'Output piston travel', 'length', { positive: true }),
      v('A1', 'A_1', 'Input piston area', 'area', { positive: true }),
      v('s1', 's_1', 'Input piston travel', 'length', { positive: true }),
      v('A2', 'A_2', 'Output piston area', 'area', { positive: true }),
    ],
    solve: {
      s2: { expr: '\\frac{#A1 #s1}{#A2}', fn: ({ A1, s1, A2 }) => (A1 * s1) / A2 },
      s1: { expr: '\\frac{#A2 #s2}{#A1}', fn: ({ A2, s2, A1 }) => (A2 * s2) / A1 },
      A1: { expr: '\\frac{#A2 #s2}{#s1}', fn: ({ A2, s2, s1 }) => (A2 * s2) / s1 },
      A2: { expr: '\\frac{#A1 #s1}{#s2}', fn: ({ A1, s1, s2 }) => (A1 * s1) / s2 },
    },
    aliases: ['piston travel', 'distance moved by piston', 'volume displaced'],
    when: 'Incompressible fluid: volume displaced by the input piston equals that received by the output piston.',
    sheet: 'derived',
    source: 'Engineering mechanics — fluid mechanics',
    hsc: ['How far the small piston must move to lift a car 100 mm'],
    example: { A1: 3.14159e-4, s1: 0.1, A2: 7.85398e-3 },
    priority: 3,
  },
  {
    id: 'hydraulicVR',
    name: 'Velocity ratio of a hydraulic system',
    modules: ['transport', 'aero', 'civil'],
    topic: 'Pressure & hydraulics',
    equation: 'VR = \\frac{A_2}{A_1} = \\left(\\frac{d_2}{d_1}\\right)^2',
    vars: [v('VR', 'VR', 'Velocity ratio', 'ratio', { positive: true }), v('A2', 'A_2', 'Output piston area', 'area', { positive: true }), v('A1', 'A_1', 'Input piston area', 'area', { positive: true })],
    solve: {
      VR: { expr: '\\frac{#A2}{#A1}', fn: ({ A2, A1 }) => A2 / A1 },
      A2: { expr: '#VR \\times #A1', fn: ({ VR, A1 }) => VR * A1 },
      A1: { expr: '\\frac{#A2}{#VR}', fn: ({ A2, VR }) => A2 / VR },
    },
    aliases: ['hydraulic VR', 'hydraulic velocity ratio'],
    when: 'VR of a hydraulic jack/press (ideal MA equals VR).',
    sheet: 'derived',
    source: 'Engineering mechanics — fluid mechanics',
    hsc: ['Efficiency of a hydraulic jack'],
    example: { A2: 7.85398e-3, A1: 3.14159e-4 },
    contextOnly: ['transport', 'aero', 'civil'],
    priority: 2,
  },
  // ——— Electricity for transport ———
  {
    id: 'electricalEnergy',
    name: 'Electrical energy',
    modules: ['transport', 'telecom'],
    topic: 'Electricity',
    equation: 'E = VIt',
    vars: [
      v('E', 'E', 'Electrical energy', 'energy', { concept: 'energy' }),
      v('V', 'V', 'Voltage', 'voltage'),
      v('I', 'I', 'Current', 'current'),
      v('t', 't', 'Time', 'time', { positive: true }),
    ],
    solve: {
      E: { expr: '#V #I #t', fn: ({ V, I, t }) => V * I * t },
      V: { expr: '\\frac{#E}{#I #t}', fn: ({ E, I, t }) => E / (I * t) },
      I: { expr: '\\frac{#E}{#V #t}', fn: ({ E, V, t }) => E / (V * t) },
      t: { expr: '\\frac{#E}{#V #I}', fn: ({ E, V, I }) => E / (V * I) },
    },
    aliases: ['electrical energy', 'energy used by motor', 'VIt'],
    when: 'Energy drawn by an electric motor, lamp or heater over a time.',
    sheet: 'derived',
    source: 'Engineering electricity',
    hsc: ['Energy used by a tram motor during a trip'],
    example: { V: 600, I: 200, t: 120 },
    priority: 3,
  },
  {
    id: 'charge',
    name: 'Charge / battery capacity',
    modules: ['transport', 'telecom'],
    topic: 'Electricity',
    equation: 'Q = It',
    vars: [v('Q', 'Q', 'Charge (capacity)', 'charge'), v('I', 'I', 'Current', 'current'), v('t', 't', 'Time', 'time', { positive: true })],
    solve: {
      Q: { expr: '#I \\times #t', fn: ({ I, t }) => I * t },
      I: { expr: '\\frac{#Q}{#t}', fn: ({ Q, t }) => Q / t },
      t: { expr: '\\frac{#Q}{#I}', fn: ({ Q, I }) => Q / I },
    },
    aliases: ['charge', 'amp hours', 'Ah', 'battery capacity', 'battery life', 'run time'],
    when: 'Battery capacity (Ah) and run time at a given current.',
    sheet: 'no',
    source: 'Engineering electricity',
    hsc: ['How long an e-bike battery lasts at a given current'],
    example: { I: 10, t: 3600 },
    priority: 2,
  },
  {
    id: 'batteryEnergy',
    name: 'Battery energy',
    modules: ['transport', 'telecom'],
    topic: 'Electricity',
    equation: 'E = VQ',
    vars: [v('E', 'E', 'Stored energy', 'energy', { concept: 'energy' }), v('V', 'V', 'Battery voltage', 'voltage', { positive: true }), v('Q', 'Q', 'Capacity (charge)', 'charge', { positive: true })],
    solve: {
      E: { expr: '#V \\times #Q', fn: ({ V, Q }) => V * Q },
      V: { expr: '\\frac{#E}{#Q}', fn: ({ E, Q }) => E / Q },
      Q: { expr: '\\frac{#E}{#V}', fn: ({ E, V }) => E / V },
    },
    aliases: ['battery energy', 'kWh battery', 'Wh', 'energy stored in battery'],
    when: 'Energy stored in a battery pack (e.g. 400 V × 150 Ah = 60 kWh).',
    sheet: 'no',
    source: 'Engineering electricity',
    hsc: ['Electric vehicle battery pack energy'],
    example: { V: 400, Q: 150 * 3600 },
    priority: 2,
  },
  {
    id: 'transformer',
    name: 'Ideal transformer (voltage ratio)',
    modules: ['transport', 'telecom'],
    topic: 'Electricity',
    equation: '\\frac{V_p}{V_s} = \\frac{N_p}{N_s}',
    vars: [
      v('Vs', 'V_s', 'Secondary voltage', 'voltage'),
      v('Vp', 'V_p', 'Primary voltage', 'voltage'),
      v('Np', 'N_p', 'Primary turns', 'count', { positive: true }),
      v('Ns', 'N_s', 'Secondary turns', 'count', { positive: true }),
    ],
    solve: {
      Vs: { expr: '\\frac{#Vp #Ns}{#Np}', fn: ({ Vp, Ns, Np }) => (Vp * Ns) / Np },
      Vp: { expr: '\\frac{#Vs #Np}{#Ns}', fn: ({ Vs, Np, Ns }) => (Vs * Np) / Ns },
      Np: { expr: '\\frac{#Vp #Ns}{#Vs}', fn: ({ Vp, Ns, Vs }) => (Vp * Ns) / Vs },
      Ns: { expr: '\\frac{#Vs #Np}{#Vp}', fn: ({ Vs, Np, Vp }) => (Vs * Np) / Vp },
    },
    aliases: ['transformer', 'turns ratio', 'step down', 'step up', 'substation'],
    when: 'Step-up/step-down transformers in power distribution (railway traction supply).',
    sheet: 'no',
    source: 'Engineering electricity — power distribution',
    hsc: ['Turns ratio for a traction substation transformer'],
    example: { Vp: 11000, Np: 1000, Ns: 60 },
    extension: true,
    priority: 1,
  },
  {
    id: 'transformerCurrent',
    name: 'Ideal transformer (power balance)',
    modules: ['transport', 'telecom'],
    topic: 'Electricity',
    equation: 'V_p I_p = V_s I_s',
    vars: [
      v('Is', 'I_s', 'Secondary current', 'current'),
      v('Vp', 'V_p', 'Primary voltage', 'voltage', { positive: true }),
      v('Ip', 'I_p', 'Primary current', 'current'),
      v('Vs', 'V_s', 'Secondary voltage', 'voltage', { positive: true }),
    ],
    solve: {
      Is: { expr: '\\frac{#Vp #Ip}{#Vs}', fn: ({ Vp, Ip, Vs }) => (Vp * Ip) / Vs },
      Vp: { expr: '\\frac{#Vs #Is}{#Ip}', fn: ({ Vs, Is, Ip }) => (Vs * Is) / Ip },
      Ip: { expr: '\\frac{#Vs #Is}{#Vp}', fn: ({ Vs, Is, Vp }) => (Vs * Is) / Vp },
      Vs: { expr: '\\frac{#Vp #Ip}{#Is}', fn: ({ Vp, Ip, Is }) => (Vp * Ip) / Is },
    },
    aliases: ['transformer current'],
    when: 'An ideal transformer conserves power.',
    sheet: 'no',
    source: 'Engineering electricity — power distribution',
    hsc: ['Current in the primary winding'],
    example: { Vp: 240, Ip: 2, Vs: 12 },
    extension: true,
    priority: 1,
  },
];

